swiftlang/swift-driver

Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift
Update `jobFinished(job:result:pid:)` method to emit output to `stderr` instead of `stdout`.
This reflects the implementation of the current Driver as we can see [here](https://github.com/apple/swift/blob/d930599394b27fcac77a90b63e23372c6b31cd7a/lib/Driver/Compilation.cpp#L594)
=> [Driver] - jobFinished method now emits to stderr

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Addresses [this FIXME](https://github.com/apple/swift-driver/blob/1e1c30534eb6af42bf66763c5ed6d918e2f56a60/Sources/SwiftDriver/Driver/Driver.swift#L691). 
I created a new test for this as the assert didn't seem to fit into `testPrimaryOutputKinds`, but I'll of course change it if desired.
I'm not exactly sure if `DriverKind.usage` should be used here, but the values seem to correspond to [this code](https://github.com/apple/swift/blob/d930599394b27fcac77a90b63e23372c6b31cd7a/lib/Driver/Driver.cpp#L95) in the original driver.
=> Diagnose -i arg

Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
Hi, this is my first pull request to this repo, so I'm not 100 % sure what direction you guys want everything to go in. Let me know of any changes you want.
This change removes xcrunFind from Toolchain, and only keeps it on
DarwinToolchain. There is a special case on GenericUnixToolchain where
we check if we are on macOS, and if so we use xcrunFind. This change
solves that by initializing a new DarwinToolchain to return the correct
path.
=> Keep xcrunFind on DarwinToolchain only

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Utilities/StringAdditions.swift, Tests/SwiftDriverTests/StringAdditionsTests.swift
Stolen from [the Swift lexer](https://github.com/apple/swift/blob/1846a5957ee971979d86bf843a0e4885da2b5a46/lib/Parse/Lexer.cpp).
=> A proper implementation of String.isSwiftIdentifier

Sources/SwiftDriver/Utilities/VirtualPath.swift
Hi! 
Just a PR to fix a really simple `FIXME`. Not sure if the `FIXME` will finally apply or keeping the attribute `name` is the desired solution. Any comment or suggestion to finish the PR is more than welcome :)
=> Conform VirtualPath to CustomStringConvertible

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This PR tries to address the "Implement proper tokenization for response files" to-do item that is on the README.
**Now we can correctly parse:**
- Double slash comments.
- Quotes.
- Escaping characters.
- Espaces.
This matches the current behavior of the [LLVM tokenization method](https://llvm.org/doxygen/namespacellvm_1_1cl.html#ac14be339a38954dac57ac3352c948c1f) _(the Swift compiler is currently using the LLVM method)._
Also, after reading LLVM's [ExpandResponseFiles method](https://llvm.org/doxygen/namespacellvm_1_1cl.html#a80bb7b995361b8d2c104983f15cf06a0), I think our current implementation has all we need.
_Note:_ we need to update this implementation once we get Windows support. 
_For "documentation" purposes_
What are `Response files`? Files that contains a list of command line …
=> [Driver] - Tokenization for response files

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Addresses [this FIXME](https://github.com/sjavora/swift-driver/blob/2737f31ad7b598c8a3ed481cad3b96a0c778c5f3/Sources/SwiftDriver/Driver/Driver.swift#L739). Also adds tests for the `// Multithreading` extension.
=> Multithreading tests and diagnostics

Sources/SwiftDriver/Incremental Compilation/IncrementalCompilation.swift, Sources/SwiftDriver/Incremental Compilation/InputIInfoMap.swift, Sources/SwiftDriver/Utilities/Diagnostics.swift, Tests/SwiftDriverTests/AssertDiagnosticsTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Based on previous discussion, this makes all diagnostics declared in the project internal. Tests now compare the message strings directly.
Do we want to move the various extensions of `Diagnostic.Message` to `Diagnostics.swift`? Right now, they are sprinkled into various files based on relevance, but in `Driver.swift` there are now 5 separate extensions.
=> Internalize diagnostics

README.md
I'm not sure what policies you have regarding adding this type of information to your README, however using Docker for running my tests on Linux was very helpful for me, so I thought I'ld add it to the readme.
This commit adds a short paragraph explaining how to create a quick and
easy Docker for testing your changes in a Linux environment when you
don't have an easy access to a Linux device.
=> Add Linux docker for debugging info to README

README.md, Sources/SwiftDriver/Driver/CompilerMode.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Initial implémentation of whole-module optimization (WMO) mode.
=> Whole module optimization mode

Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Sources/SwiftDriver/Utilities/FileType.swift
`FileType.description` provides the "external" name for each file type,
which is used for parsable output and output file maps, among other
things. Fix the description for serialized diagnostics files... so now
diagnostics show up properly in Xcode.
=> [Parseable output] Use FileType's description for the file type.

Sources/SwiftDriver/Execution/ParsableOutput.swift, Sources/SwiftDriver/Execution/llbuild.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilation.swift, Sources/SwiftDriver/Incremental Compilation/InputIInfoMap.swift, Sources/SwiftDriver/Incremental Compilation/InputInfo.swift, Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift, Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/GenerateDSYMJob.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Sources/SwiftDriver/Options/OptionTable.swift, Sources/SwiftDriver/Utilities/DOTJobGraphSerializer.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/IntegrationTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift, Tests/SwiftDriverTests/TripleTests.swift
Found using SwiftLint's unused declaration and unused import rules.
I'm not sure how maintainers feel about keeping unused code or imports around if it's expected to be used at some point in the future.
I'm happy to close this if everything found here is ok to keep around.
I was looking for some low hanging fruit to contribute to this project and cleaning up unused stuff seemed like a good start.
=> [Lint] Remove unused declarations and imports

README.md
Adds links to existing driver docs in the docs directory.
I just found these docs by accident while looking something up in the old driver. I think it would be helpful to add them here so that new contributors can get a better idea about how the driver works. It certainly helped me.
=> [Docs] Add links to existing driver documentation

Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Sources/SwiftDriver/Execution/ParsableOutput.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift
Implements `SignalledMessage` as another kind of `ParsableMessage`.
=> [Parseable output] Implement SignalledMessage

Sources/SwiftDriver/Options/Options.swift, Sources/SwiftDriver/Utilities/PrefixTrie.swift, Sources/makeOptions/makeOptions.cpp
Add missing copyright headers in Options/Options.swift and Utilities/PrefixTrie.swift.
=> NFC: Add missing copyright headers.

Sources/SwiftDriver/Driver/DriverKind.swift, Sources/SwiftDriver/Options/Option.swift
This PR applies method naming conventions to `Option.isAcceptedBy(_:)`, move preposition "by" from the base name to the first argument label.
Also fixes some unfinished documentation comments.
=> Rename 'isAcceptedBy(_:)' to 'isAccepted(by:)'.

Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Sources/SwiftDriver/Execution/ParsableOutput.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift
This PR uses an initializer `init(name:kind:)` to unify multiple factory methods.
=> Replace 'ParsableMessage' factory methods with an initializer.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Sources/swift-driver/main.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This tries to implement the handling of subcommands based on the original driver. I must admit I'm a little out of my depth here so I'd appreciate some guidance:
- in the original driver, the subcommand check happens before the actual driver is even created ([here](https://github.com/apple/swift/blob/348fa2145e675ec4e396a1da54c2201a366a37da/tools/driver/driver.cpp#L234)) - I put the code in the init, because the FIXME was there, but should an init be invoking `exec`?
- related to the above, is `exec` the right function to use here?
- similarly, is `Process.findExecutable` the right method to use in place of `getExecutablePath`?
- there is a slight difference in behavior between `llvm::sys::path::stem` and `basenameWithoutExt` - namely `basenameWithoutExt` will return `.txt` for …
=> Handle subcommands

README.md, Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Utilities/FileType.swift
This replaces the specific properties in `Entry` with a dictionary keyed by `FileType` and adds a custom implementation of `Codable`.
Originally, I wanted to just use `FileType`'s `description` property, but some of the cases just return `rawValue`, which is not compatible in all cases ("o" vs "object", in particular). Instead I added the `name` property with values from [FileTypes.def](https://github.com/apple/swift/blob/master/include/swift/Basic/FileTypes.def). While there, I noticed that `FileType` doesn't currently have a case for `swiftsourceinfo`, so I added that as well.
=> Handle all FileTypes in OutputFileMap

Sources/SwiftDriver/Driver/CompilerMode.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/PredictableRandomNumberGenerator.swift, Tests/SwiftDriverTests/PredictableRandomNumberGeneratorTests.swift
Also, add a `PredictableRandomNumberGenerator` to ensure deterministic partitioning. `PredictableRandomNumberGenerator` should maybe move into tools-support-core at some point, but I think it's fine where it is for now. It's not a great random number generator, but it should work fine for the driver's use cases.
=> Shuffle batch mode partitions if a seed is provided

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Options/OptionParsing.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is an initial implementation of immediate mode. The big missing piece right now is setting [DY]LD_LIBRARY_PATH and DYLD_FRAMEWORK_PATH when needed. Before implementing that I think it's worth figuring out how the driver should run single job build plans for immediate mode and the REPL. I'm not sure if we should bypass the JobExecutor or not when executing in-place. If anyone has a strong opinion I could implement that in this PR or a follow up. I haven't made any changes yet so right now this just spawns a new process.
=> Add a bare-bones implementation of immediate mode

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Options/OptionParsing.swift, Sources/swift-driver/main.swift, Tests/SwiftDriverTests/Helpers/AssertDiagnostics.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
I changed error handling a little bit in the process. Now, any error caught at the top level will be emitted through the diagnostics engine if it conforms to `DiagnosticData`.
=> Diagnose unsupported options and add descriptions for option-parsing errors

Sources/SwiftDriver/Execution/JobExecutor.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Toolchain+InterpreterSupport.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
... and use it to set the right ones in immediate mode.
=> Allow specifying custom environment variables for jobs

Tests/SwiftDriverTests/SwiftDriverTests.swift
I looked for low-haning Linux tests to fix since I was already in that sphere, and I saw this test. It ran fine on my system. Better to have it run on Linux since it can! :)
=> Remove unnecessary linux skip for test

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/DriverKind.swift
This is enough to fix ~2/3 of the failures in the interpreter and stdlib lit test suites, making it easier to focus on the driver-related failures.
=> Fix direct invocation of non-compiler driver kinds

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/ReplJob.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Utilities/Diagnostics.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
The second commit also adds some special handling for single job build plans when in REPL or immediate mode.
=> Add REPL support

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
We're still not taking the file output map or primary outputs into consideration, but this is enough to get a few more integration tests up and running.
=> Infer module output path from '-o' where applicable

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/VerifyDebugInfoJob.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Tests/SwiftDriverTests/Helpers/AssertDiagnostics.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
The relevant lit tests don't pass yet, but they should once module name inference is fully implemented.
=> Implement -verify-debug-info

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/DriverKind.swift, Sources/SwiftDriver/Options/OptionTable.swift
- Add "See also" messages from the c++ driver on master
- Hide options not accepted by the current driver kind
- ~~update isAccepted(by:) to reject no-driver options in batch & interactive mode~~
=> Miscellaneous improvements to -help messages

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/GeneratePCHJob.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftDriver/Jobs/ReplJob.swift, Sources/SwiftDriver/Jobs/Toolchain+InterpreterSupport.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
A number of job-creation functions were asking the toolchain for the frontend path, rather than using the frontend path computed by the `Driver` instance. Fix them, and thread the Driver-computed Swift frontend path everywhere. We might want to change the way things are layered here in the future.
=> Respect -driver-use-frontend-path throughout job creation

Sources/SwiftDriver/Utilities/Triple.swift, Tests/SwiftDriverTests/TripleTests.swift
A couple of notes:
- thumb handling still isn't very good, I left a FIXME in the source
- there might be some opportunities to further improve the test coverage, I'm not very familiar with all of the different manufacturer variants
With this change, I was able to fix a few issues in the Driver integration test suite in addition to the newly enabled Triple tests.
=> Improved ARM arch parsing

Sources/SwiftDriver/Driver/Driver.swift
Currently we have the following for getting the compiler version. The issue with this is that I'm getting into a state where `getToolPath(.swiftCompiler)` is `/tmp/swift` my symlink to my `swift-driver`. This is causing an infinite loop because `swiftCompilerVersion` is called from `Driver.init`.
```
public func swiftCompilerVersion() throws -> String {
try Process.checkNonZeroExit(
args: getToolPath(.swiftCompiler).pathString, "-version",
environment: env
).split(separator: "\n").first.map(String.init) ?? ""
}
```
So taking a step back:
Should `getToolPath(.swiftCompiler)` ever point to my symlink?
If no, what am I doing wrong (was following the README).
If yes, then the implementation needs to change, the code below is in `Basic/Version.cpp`. Are these constants something we could have …
=> Handle -version argument

Sources/SwiftDriver/Driver/CompilerMode.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilation.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/GeneratePCHJob.swift, Sources/SwiftDriver/Jobs/GeneratePCMJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Teach the driver to emit Clang modules based on the with `-emit-pcm` command-line argument, where the input is the module map.
=> Add support for Clang module emission via -emit-pcm

Sources/SwiftDriver/Jobs/Planning.swift
This mirrors the batch partition calculation change in https://github.com/apple/swift/pull/28972. See below for an explanation.
---
While exploring how to optimize global build times, I noticed that the batch sizing logic wasn't producing multiple batches until a module had 50 files. Based on @graydon's [detailed batch calculation comment](https://github.com/apple/swift/blob/746b58e8e1c1ef1ac09d8031875fd2a08b65597c/lib/Driver/Compilation.cpp#L1269-L1362) (which says "cap the batch size ... at ... 25"), and based on the variable names ("`SizeLimit`"), I believe the batch calculation implementation is off.
The simple example is a module of 26 files. With the existing batch calculation, the result is a `26/25=1` batch. However this is larger than the `DefaultSizeLimit`. This calculation …
=> Adjust batch partition count calculation

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/swift-driver/main.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
The `-print-target-info` implementation itself is pretty straightforward. The refactor is a little more interesting, I pulled the `planBuild` call out of `Driver.run`. Now, all clients are expected to call `planBuild` for a list of jobs they can hand off to `Driver.run` or schedule themselves. I also pulled `-version` and `-print-target-info` handling out of `run` and into the build planning stage. This gives clients more control over executing them in case they want to do something like capture the output. It's not yet clear if we want to do something similar for printing help or forwarding to `swift-indent`/`swift-autolink-extract`, I've left that logic alone for now.
=> Forward -print-target-info to the frontend, begin refactoring planning for simple driver invocations

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Execution/JobExecutor.swift, Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/GeneratePCHJob.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftDriver/Utilities/StringAdditions.swift, Sources/SwiftDriver/Utilities/System.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Now, when a job is created, it can optionally indicate that it supports using a response file to pass its arguments. Then, `ArgsResolver` is responsible for checking the argument length and writing out a response file if needed. This ensures that if `ArgsResolver` lengthens the arguments, this is accounted for properly.
I'm fairly happy with this design, but there's one issue in how it interacts with LLBuild, which is why this is a WIP for now. A couple of the integration tests which pass 500k args run very slowly (~3-4 minutes each). It looks like most of the time is spent in JSONDecoder objc bridging (at least on macOS), which is used to serialize Jobs. This might need to be switched to a faster encoder/decoder.
This PR also makes a few changes to response file tokenization to more …
=> Use response files when running subcommands if needed

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Options/Options.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This mirrors this change https://github.com/apple/swift/pull/29362
=> Add -no-whole-module-optimization flag

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Addresses a minor fixme on getting default SDK Path only if triple is macosx.
cc @aciidb0mb3r
=> Search for the default SDK path only if triple is macOSX

Sources/SwiftDriver/Driver/CompilerMode.swift, Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is consistent with the c++ driver and fixes `Interpreter/availability_host_os.swift`
=> Don't use a bridging pch in immediate mode

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/DriverKind.swift, Sources/SwiftDriver/Execution/JobExecutor.swift, Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/GeneratePCHJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Sources/SwiftDriver/Options/Option.swift, Sources/SwiftDriver/Options/OptionTable.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Utilities/PredictableRandomNumberGenerator.swift, Sources/SwiftDriver/Utilities/RelativePathAdditions.swift, Sources/SwiftDriver/Utilities/Triple+Platforms.swift, Sources/SwiftDriver/Utilities/Triple.swift, Tests/SwiftDriverTests/AssertDiagnosticsTests.swift, Tests/SwiftDriverTests/Helpers/AssertDiagnostics.swift, Tests/SwiftDriverTests/IntegrationTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift, Tests/SwiftDriverTests/TripleTests.swift
Removed trailing whitespaces in Sources/ and Tests/ directories.
=> Remove trailing whitespaces

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Execution/JobExecutor.swift, Sources/SwiftDriver/Jobs/Job.swift, Tests/SwiftDriverTests/JobExecutorTests.swift
The condition is checked in both cases, but only single-job build plans emit a diagnostic right now, I left a fixme in the multi-job test. For that, I need to decide if the `JobExecutor` should propagate errors through the build graph, or if the `Context`should just include a `DiagnosticEngine`.
=> Diagnose when inputs are modified during the build

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Utilities/FileType.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
With this change, we're down to 6 interpreter and 3 stdlib lit tests still failing. I'm not all that happy with this solution, it feels kind of fragile. I haven't come up with anything better though so I thought I'd put this up in case anyone had a better solution in mind.
=> More accurate computation of compile job output paths

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This caused a surprising number of tests to fail which wrote something like `-o a.out.optimized`. The C++ driver uses `llvm::sys::path::stem` to remove extensions, which would result in `a.out`, which is an invalid module name, so the fallback of `main` would be used. `swift-driver` used to remove both extensions, and would name the module `a`. This behavior is clearly better, but I think it's too late to change considering how many tests broke...
=> Make module naming consistent with the integrated driver when the output filename has 2+ extensions

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/OutputFileMap.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This allows having relative paths on output file map json file. 
Also, I've made working directory to default to cwd if no `-working-directory` arg is supplied.
Also, there is small bug, if there is two identical inputs in output file map, driver would silently crash, as it uses `Dictionary(uniqueKeysWithValues:)` initializer, now it will choose last record (behaviour that usually seen in clang, for example), but is it better to have warning or error? There is some difficulty thought, as closure that handles duplicates doesn't have key as argument, so we need to find duplicates beforehand.
Also, it looks that there is a lot of dangling whitespaces, is it ok to remove them? May be e need some codestyle tool (swift-format?) that will make codestyle automated?
This is my first contribution …
=> Allow relative paths in output file map

Sources/SwiftDriver/Driver/Driver.swift, Sources/swift-driver/main.swift
Work in progress. I'd just like to see if I'm going in the right direction.
=> SR-12129: Diagnose lack of input files

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Utilities/Triple+Platforms.swift, Sources/SwiftDriver/Utilities/Triple.swift, Sources/SwiftOptions/Options.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift, Tests/SwiftDriverTests/TripleTests.swift
C++ implementation: https://github.com/apple/swift/pull/29017
Also fixes test/Driver/print_target_info.swift
=> Add support for catalyst

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilation.swift, Sources/SwiftDriver/Incremental Compilation/InputIInfoMap.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Add handling for relative paths in output file map path,
resonse file paths, recorded input modification dates.
=> Make swift driver friendlier to relative paths

CMakeLists.txt, Package.resolved, README.md, Sources/CMakeLists.txt, Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftOptions/CMakeLists.txt, Sources/swift-driver/CMakeLists.txt, Sources/swift-help/CMakeLists.txt, cmake/modules/FindLLBuild.cmake
The Swift driver is intended to be built fairly early in overall toolchain construction. Introduce a CMake build system that aligns with the CMake build for SwiftPM and other tools that need to be bootstrapped in this manner.
=> Add support for building with CMake

Package.swift
When bootstrapping SwiftPM, SwiftPM uses relative paths to find
its dependencies (e.g., llbuild) rather than repository URLs.
Do the same thing for the driver when `SWIFTCI_USE_LOCAL_DEPS` is set in
the environment. This allows us to use the Swift driver when
bootstrapping SwiftPM.
=> When bootstrapping SwiftPM, use relative paths for dependencies.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/ReplJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Now that it's been removed from the C++ driver, there's no reason to keep it around here.
=> Remove support for the integrated repl

Package.resolved, Sources/SwiftDriver/Execution/JobExecutor.swift
Revert the change to avoid calling LLBuild's `taskIsComplete` from a thread, which should improve the parallelism in the build.
=> Parallelize task build

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Utilities/FileType.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Fixes most of the issues with test `Driver/multi-threaded.swift`.
Future improvements required for all tests to pass:
1. Spacing of parseable-output json is different than c++ driver (use a regex in the test to allow optional space)
2. Support embed bitcode (I might look at this next)
=> Improve handling of multithreaded builds

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/Execution/JobExecutor.swift, Sources/SwiftDriver/Execution/llbuild.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilation.swift, Sources/SwiftDriver/Incremental Compilation/InputIInfoMap.swift, Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/swift-driver/main.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
The Swift driver library should never directly access the local file
system. Thread a file system parameter through the SwiftDriver library
so clients can provide an alternative file system if they want.
=> Thread a filesystem throughout the Swift driver.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Utilities/FileType.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Add support for the additional compiler mode added in: #28515.
=> Support invoking the Fast Dependency Scanner: `-scan-dependencies`

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Incremental Compilation/SourceFileDependencyGraph.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/Inputs/IncrementalCompilationInputs.swift, Tests/SwiftDriverTests/XCTestManifests.swift
This just ports over the parts of the source file fine-grained dependency graph the driver cares about. I just called it `SourceFileDependencyGraph` because I assume we don't intend to support the older dependency system. I'm still learning how all this works in the C++ driver, so I'm open to feedback on the API and approach!
=> Add support for reading fine-grained source file dependency graphs

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftOptions/DriverKind.swift, Sources/SwiftOptions/Option.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
`swift-indent` hasn't been included in toolchains for a while now, so remove all references to it.
`swift-autolink-extract` was removed from macOS toolchains fairly recently, so #if-out the linux linker tests that rely on it on macOS.
=> 5.2 Compatibility updates to reflect the toolchain symlink removals

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Execution/JobExecutor.swift, Tests/SwiftDriverTests/JobExecutorTests.swift
The JobExecutor's context now holds a diagnostic engine which can be used to emit errors encountered when running jobs.
=> Diagnose inputs modified during the build for multi-job plans

README.md, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Execution/JobExecutor.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Big change is:
> Remove job from build keys. Saves encoding and decoding the jobs
> 
> The runtime of the following (in release build) went from 2.27 minutes to 2.29 seconds (notice the change in units!!!)
> // RUN: %{python} -c 'for i in range(500001): print("-DTEST5_" + str(i))' > %t.5.resp
> // RUN: not %target-swiftc_driver %s @%t.5.resp -Xfrontend -debug-crash-immediately 2>&1
=> Driver performance improvements (profile test/Driver/response-file.swift)

README.md, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/BackendJob.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Sources/SwiftOptions/ParsedOptions.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
- The moduleNameIsFallback fix for the linker fixes `Driver/verify-debug-info.swift` (dysm at wrong name)
- embed-bitcode tests in `Driver/multi-threaded.swift` are fixed (Still some tests there "failing" because parsable output json is in different order)
- `Driver/embed-bitcode.swift` tests are fixed except one. Driver jobs are printed in different order.
```
// RUN: %target-swiftc_driver -embed-bitcode -Xcc -DDEBUG -Xllvm -fake-llvm-option -c -emit-module %s 2>&1 -### | %FileCheck %s -check-prefix=CHECK-MODULE
// CHECK-MODULE: -frontend
// CHECK-MODULE: -emit-bc
// CHECK-MODULE-DAG: -Xcc -DDEBUG
// CHECK-MODULE-DAG: -Xllvm -fake-llvm-option
// CHECK-MODULE-DAG: -emit-module-path
// CHECK-MODULE: -frontend
// CHECK-MODULE: -emit-module
// CHECK-MODULE: -frontend
// CHECK-MODULE: -c
// …
```
=> Support -embed-bitcode and -driver-print-bindings

Package.swift, Sources/SwiftDriver/Execution/llbuild.swift
This introduces a new environment variable `SWIFT_DRIVER_LLBUILD_FWK` which can be set to opt out of having a dependency on llbuild in the manifest. This allows linking with an existing llbuild.framework instead of building it, similar to SwiftPM's `SWIFTPM_LLBUILD_FWK` option.
=> Allow linking an existing llbuild.framework

Sources/SwiftDriver/CMakeLists.txt
https://github.com/apple/swift-driver/pull/101 added this file, but it wasn't added to the CMake build which I think is causing SwiftPM to fail on CI.
=> Add BackendJob.swift to cmake build

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Dependency Scanning/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Dependency Scanning/ModuleDependencyBuildGeneration.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ModuleDependencyScanning.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/FileType.swift, Sources/SwiftOptions/ExtraOptions.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/Inputs/ExplicitModuleDependencyBuildInputs.swift
This PR resurrects #47 and builds on top of it.
Adds new flag `-driver-print-module-dependencies-jobs` to instruct the driver to scan for dependencies and generate build jobs for each dependent Swift or C module.
At present, this WIP does the following:
- Invoke the Swift frontend Fast Dependency Scanner to prescan for dependencies.
- Construct a ModuleDependencyGraph from the dependency scanner's JSON output.
- Generate and print build jobs for each dependent module.
Next Steps:
- Actually have the driver schedule and execute the dependent module build jobs ahead of time, eliminating the need to re-build those modules when it tries to import them.
I am new to writing Swift so I encourage reviewers to nit-pick with extreme prejudice.
=> Print commands required to explicitly build module dependencies.

Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is the companion to https://github.com/apple/swift/pull/31970 in the C++ driver.
=> Propagate `-vfsoverlay` from driver to frontend.

Sources/SwiftOptions/OptionParsing.swift, Sources/SwiftOptions/PrefixTrie.swift, Tests/SwiftOptionsTests/PrefixTrieTests.swift, Tests/SwiftOptionsTests/XCTestManifests.swift
The previous prefix trie made a new `Node` for each character along the
input string. In addition to being wasteful, this would introduce many
more hops to match a given string.
Instead, store common `Substring`s in the `Node`s, and use a sorted
array/binary search through children to avoid extra time spend hashing
and storing in hashed collections.
Doing this reduces the number of nodes in the trie for the driver's
options by an order of magnitude -- from 6601 nodes to 660.
(This is actually a port of LLVM's Trie, but cleaned up and made more
idiomatic in Swift)
=> Significantly improve prefix trie performance and memory usage

Sources/SwiftDriver/Dependency Scanning/ModuleDependencyBuildGeneration.swift, Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift, Sources/SwiftDriver/Jobs/BackendJob.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/GenerateDSYMJob.swift, Sources/SwiftDriver/Jobs/GeneratePCHJob.swift, Sources/SwiftDriver/Jobs/GeneratePCMJob.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/ReplJob.swift, Sources/SwiftDriver/Jobs/VerifyDebugInfoJob.swift, Tests/SwiftDriverTests/JobExecutorTests.swift
Add two APIs for `Job` that are helpful in SwiftPM:
* `Job.Kind.isSwiftFrontend`: whether the job is executing the Swift frontend
* `Job.description`: simple description of what the job is doing
=> [Job] Add some convenient APIs for SwiftPM

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/Utilities/System.swift
Tested with Swift master natively on Android, also had to add the `swiftc` path below to my `PATH` for the tests to find it. Most tests pass with the following commands (the `_GNU_SOURCE` flag has to do with [building TSC on Android](https://github.com/apple/swift-package-manager/pull/2417#pullrequestreview-321705438)):
```
SWIFTCI_USE_LOCAL_DEPS=1 ../build/Ninja-Release/toolchain-android-aarch64/usr/bin/swift build -j 9 -Xswiftc -Xcc -Xswiftc -U_GNU_SOURCE
SWIFTCI_USE_LOCAL_DEPS=1 ../build/Ninja-Release/toolchain-android-aarch64/usr/bin/swift test -j 9 -Xswiftc -Xcc -Xswiftc -U_GNU_SOURCE
```
=> Port to Android

Tests/SwiftDriverTests/IntegrationTests.swift
I needed to make this change to successfully run the `driver/` integration tests inside Xcode, otherwise they would hang because the encoding was defaulting to ascii. It might be ok to just set LC_CTYPES instead, but I'm really not sure which is better.
=> Set LC_ALL=en_US.UTF-8 when running integration tests with lit.py

README.md
This matches the workflow I've been using to avoid the issue where `swift-driver` keeps invoking itself instead of the frontend. Maybe there's a better way?
=> Update README to avoid recursive lookups

README.md
Xcode already has an environment variable `TOOLCHAIN_DIR` that we can use to automatically find the toolchain path. `TOOLCHAIN_PATH` doesn't exist by default and it could be misleading in this case.
=> Simplify path to swiftc in toolchain in README

Tests/SwiftDriverTests/SwiftDriverTests.swift
=> Remove spurious print statements in the `-scan-dependencies` option test

Tests/SwiftDriverTests/SwiftDriverTests.swift
Having just switched CI to point to a specific (latest master snapshot) swift toolchain, instead of using the system toolchain (discussed in #113 ), a couple of test adjustments were required to get the test suite to pass:
- `testDOTFileEmission` to match latest toolchain's compiler executable name as `swiftc` vs `swift`. 
- `testToolchainClangPath` to skip the checking if the user overloaded swift executable path.
=> Fix tests to match behaviour when when using specific Swift toolchain.

Sources/SwiftDriver/Dependency Scanning/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Dependency Scanning/ModuleDependencyBuildGeneration.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ModuleDependencyScanning.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/GeneratePCHJob.swift, Sources/SwiftDriver/Jobs/GeneratePCMJob.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/ReplJob.swift, Sources/SwiftOptions/ExtraOptions.swift, TestInputs/ExplicitModuleBuilds/CHeaders/A.h, TestInputs/ExplicitModuleBuilds/CHeaders/B.h, TestInputs/ExplicitModuleBuilds/CHeaders/Bridging.h, TestInputs/ExplicitModuleBuilds/CHeaders/BridgingOther.h, TestInputs/ExplicitModuleBuilds/CHeaders/C.h, TestInputs/ExplicitModuleBuilds/CHeaders/D.h, TestInputs/ExplicitModuleBuilds/CHeaders/F.h, TestInputs/ExplicitModuleBuilds/CHeaders/G.h, TestInputs/ExplicitModuleBuilds/CHeaders/module.modulemap, TestInputs/ExplicitModuleBuilds/Swift/A.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/E.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/F.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/G.swiftinterface, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This PR adds the compile command argument interface for Explicit Module Builds, as specified in: https://github.com/apple/swift/pull/32125
- `-disable-implicit-swift-modules` and `-Xcc -Xclang -Xcc -fno-implicit-modules` are passed to all compile jobs to prevent the frontend from building any modules implicitly and diagnose if they have to.
- When building a module, the compile commands are passed paths to the module's direct dependencies with `-Xcc -Xclang -Xcc -fmodule-map-file=` and `-Xcc -Xclang -Xcc -fmodule-file=` and `-swift-module-file=`.
- Add `-experimental-explicit-module-build` option to request that the driver must attempt to perform a full explicit-module-build compile. 
For now, I include a test that verifies that the commands are generated as expected w.r.t. their …
=> Propagate Explicit Module Build command arguments to compile jobs.

Sources/SwiftDriver/Dependency Scanning/ModuleDependencyBuildGeneration.swift
As these files are already specified in the relevant dependency scanner JSON output field.
=> [Explicit Module Builds] Do not add the .modulemap file to the build command arguments

Sources/SwiftDriver/Driver/DebugInfo.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ModuleOutputInfo.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilation.swift, Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift, Sources/SwiftDriver/Jobs/BackendJob.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/GenerateDSYMJob.swift, Sources/SwiftDriver/Jobs/GeneratePCHJob.swift, Sources/SwiftDriver/Jobs/GeneratePCMJob.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/ReplJob.swift, Sources/SwiftDriver/Jobs/VerifyDebugInfoJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
I noticed that there were groups of properties in the driver that were returned as tuples and then assigned. It seemed natural to group these in structs.
=> Extract debug info and module output properties from Driver.swift

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Utilities/Diagnostics.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Previously only the values were passed through not the options as well.
This also adds the validation from Driver.cpp that they are correctly
formatted.
=> Fix -debug-prefix-map handling

Sources/SwiftDriver/Dependency Scanning/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Dependency Scanning/ModuleDependencyBuildGeneration.swift, Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
`@testable` may make eventual toolchain integration more difficult (because we'd have to build once for testing and again for integrating), so remove it from the one place it's currently used. This requires making the module dependency graph structures public, which IMO is an ok tradeoff.
=> Remove @testable import from explicit module builds test

Tests/SwiftDriverTests/SwiftDriverTests.swift
This is just an organizational change to keep all the tests for
`-num-threads` behavior in one place.
=> Move -num-threads tests to single function

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftOptions/Options.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is analogous to this change in Driver.cpp https://github.com/apple/swift/pull/32175
=> Add -coverage-prefix-map arg

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This also fixes Interpreter/objc_class_properties_runtime from the integration tests
=> Link runtime compatibility libs on darwin if needed

Utilities/build-script-helper.py
Allows building, testing, and installing swift-driver and swift-help
from Swift's build-script. Note that the installed swift-driver does
not yet replace `swift` or `swiftc`.
=> [Build] Add a helper for integration into Swift's build-script.

Sources/SwiftDriver/Jobs/Job.swift
It seems that Job's clients are under no obligation to supply any inputs here.
=> Do not force-unwrap Job displayInputs in Job description.

Sources/SwiftDriver/Execution/JobExecutor.swift, Sources/SwiftDriver/Explicit Module Builds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
I noticed the default argument was accidentally being used in a couple places and IMO it's not obvious the resolver holds a FileSystem, so this change drops it and passes the localFileSystem explicitly in tests.
=> Remove the localFileSystem default argument from ArgsResolver

Sources/SwiftDriver/Driver/Driver.swift
If the swiftmodule is the primary output, we need to use the exact path provided by `-o` to match the behavior of the c++ driver.
Fixes Interpreter/SDK/objc_bridge.swift
=> More module output path fixes

Sources/SwiftDriver/Driver/Driver.swift, Sources/swift-driver/main.swift
- Add an error message matching the c++ driver for missing/malformed output file maps
- add a missing exit(EXIT_FAILURE) to main.swift (pretty sure it's my fault that was missing)
Fixes: Driver/warnings_control and Driver/missing-ofm
=> Add missing output file map error

Sources/SwiftDriver/Toolchains/Toolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Some of Swift-related executables (like swift-help) have hyphens in the
name, which does not translate well into an environment name for overriding
executables (e.g., `SWIFT_DRIVER_SWIFT-HELP_EXEC`). Replace hyphens
with underscores to make the names usable.
=> Replace "-" into "_" when figuring out SWIFT_DRIVER_*_EXEC names.

Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift
Look for the swift-frontend executable for the Swift frontend, rather
than the "swift" executable. If there is no swift-frontend, fall back
to "swift".
The Swift compiler recently changed to make the primary (non-symlink)
executable "swift-frontend", although it contains both the driver and
the frontend logic. In this new scheme, "swift" and "swiftc" are
symlinks to swift-frontend (to use the existing C++ driver), but can
be replaced with symlinks to "swift-driver" to use this new driver.
This allows a much simpler drop-in replacement strategy.
=> Use swift-frontend as the Swift frontend executable.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Utilities/Triple.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Introduce a utility function to invoke the Swift frontend with
its `-print-target-info` option and parse the resulting JSON, which
provides information about the target of the compile that will be
useful to the driver.
For now, use this to retrieve the host target triple when no triple
was supplied. This is more consistent than going through Clang to
retrieve this information, and we'll be using more of this info soon.
=> Use the Swift frontend to determine the host target triple.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Utilities/Triple+Platforms.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
The Swift frontend provides a wealth of information about target triples, runtime compatibility, paths, and so on via its `-print-target-info`. Query `-print-target-info` and use it for several things:
* Canonicalizing target triples
* Determining the version of the Swift runtime that's guaranteed to be available for a given target triple
* Determining when to link against the OS-provided Swift standard library via rpaths.
=> Use the frontend's -print-target-info more often

Sources/SwiftDriver/Driver/Driver.swift
This fixes a small regression introduced by #143  (stdlib/FloatingPointIR was failing)
=> Make sure single job plans are executed in place by the DriverExecutor

README.md, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Newest toolchains contain the swift --> swift-frontend rename so a couple of tests needed fixing up.
=> Fix tests to match behaviour expected with newest toolchain

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Explicit Module Builds/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Explicit Module Builds/ModuleArtifacts.swift, Sources/SwiftDriver/Explicit Module Builds/SwiftModuleArtifacts.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/FileType.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This PR implements the interface expected by the frontend, as built by @nkcsgexi in:
https://github.com/apple/swift/pull/32355
https://github.com/apple/swift/pull/32450 
Swift module's explicit Swift module dependencies are now encoded in a JSON file, passed with `-explicit-swift-module-map-file`. The key benefit is that now the frontend doesn't need to deserialize the .swiftmodule file just to collect the module's name.
Resolves rdar://problem/64533451
=> [Explicit Module Builds] Emit a JSON file that specifies details of explicit Swift module dependencies

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
@DougGregor @artemcm 
Pulled from #144
=> Fixup module source info output

Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Explicit Module Builds/InterModuleDependencyGraph.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
As of https://github.com/apple/swift/pull/32633 when the scanner finds an up-to-date, already-compiled module next to the interface or cached, it reports a compiledModulePath in lieu of the usual dependency info. Instead of trying to generate a job, we should use this path directly.
I think this should fix the recent CI failures
=> [Explicit Modules] Handle compiledModulePaths output by the dependency scanner

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Execution/DriverExecutor.swift, Sources/SwiftDriver/Jobs/Planning.swift
This gets rid of the last two ArgsResolvers outside of the executor
=> Delegate job printing to the DriverExecutor since it involves argument resolution

Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
This enables a tiny cleanup when choosing which compatibility libs to link
=> Make SwiftVersion struct Comparable

Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Job.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This will be useful for SwiftPM (and other build systems) to distinguish intermediate dependency artifacts versus the main module build, in order to correctly pass in cross-target dependencies.
=> [Explicit Modules] Provide an API for querying whether a job is a main module job.

Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftOptions/Options.swift
Companion to https://github.com/apple/swift/pull/32777.
=> Stop passing -sil-merge-partial-modules

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift, Tests/SwiftDriverTests/XCTestManifests.swift
Adopt improvements to `-print-target-info` from https://github.com/apple/swift/pull/32758:
* Use the compiler version provided by `-print-target-info` rather than invoking a second time with `-version`
* Use the compatibility libraries provided by `-print-target-info` rather than hard-coding the known set.
=> Gather more information from -print-target-info

Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Utilities/Triple+Platforms.swift, Sources/SwiftDriver/Utilities/Triple.swift, Tests/SwiftDriverTests/TripleTests.swift
A couple of minor changes on top of https://github.com/apple/swift-driver/pull/165:
* Sink some macOS-specific APIs down into tests; I kept thinking they needed generalization, but really they needed not to be APIs at all
* Lookup "clang" via the normal approach, rather than only using the one from the Xcode default toolchain
* Stop inferring simulator-ness based on architecture.
=> [Darwin] Miscellaneous toolchain cleanups and modernizations

Utilities/build-script-helper.py
This reflects the new `swift-frontend` executable the driver will look for.
Gearing up for: https://github.com/apple/swift/pull/32851
=> [Build Script Helper] Fix frontend executable search environment variable.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftOptions/DriverKind.swift, Sources/SwiftOptions/Option.swift, Sources/SwiftOptions/OptionTable.swift, Sources/swift-driver/main.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This eliminates the last case where the driver was launching processes directly. IMO it makes sense to treat these flags as subcommands since they're direct frontend tool invocations that don't involve any coordination by the driver. I also dropped references to swift-autolink-extract because it's now a direct symlink to swift-frontend alongside swift-symbolgraph-extract.
=> Treat -frontend and -modulewrap invocations as subcommands

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Explicit Module Builds/InterModuleDependencyGraph.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
These types are only public for testing, so use @_spi to hide them.
=> [Explicit Modules] Use @_spi for types exposed only for testing

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/Helpers/DriverExtensions.swift
We shouldn't merge this until SPM stops relying on it (https://github.com/apple/swift-package-manager/pull/2798).
=> Drop the executor default argument value in Driver's init

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Utilities/Sanitizer.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is enough to get all of sanitize_scudo.swift passing except for the Windows test cases, and one that relies on the sanitizer ordering. Rather than fix the ordering here, I'm going to change the integrated driver to match swift-driver.
=> Add -sanitize=scudo support

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Utilities/FileType.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift
- -save-optimization-record= is distinct from -save-optimization-record and has some unusual behavior to support different record types
- -save-optimization-record-passes just needs to be added to compile jobs
This change fixes Driver/opt-record.swift and Driver/opt-record-options.swift
=> Add support for remaining optimization record options

Tests/SwiftDriverTests/SwiftDriverTests.swift
This test runs extremely slowly on Linux CI (~12 min.). Shrink the input size while the performance regression is investigated (I'm guessing it's a JSONEncoder issue or a missed optimization on `(1...500_000).map { "-DTEST_\($0)" }`).
=> Shrink response file test input size

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Tests/SwiftDriverTests/IntegrationTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This fixes Driver/os-deployment.swift and slightly improves Driver/macabi-environment.swift. There's some remaining Darwin-specific argument validation left to be implemented, which I'll create a starter bug for
=> Validate Darwin deployment targets and target variants

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This commit  validates the following arguments to driver:
1. link-objc-runtime by checkin arc path,
2. experimentalCxxStdlib flag to limit it to libc++
3. -static-stdlib to flag that its not supported.
This commit is for SR-13255 https://bugs.swift.org/browse/SR-13255
=> Validate C++ and ObjC related args for Darwin toolchain

Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Explicit Module Builds/InterModuleDependencyGraph.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/Inputs/ExplicitModuleDependencyBuildInputs.swift
`-scan-dependencies` now emits ready-to-use binary module candidates that can be imported by the compiler, e.g. modules adjacent to .swiftinterface files or in prebuilt module dirs. 
When invoking `-compile-module-from-interface`, pass down these module candidates so the compiler can emit forwarding modules to them, saving the effort of type-checking/serializing binary modules at all.
Resolves rdar://problem/66243229
=> [Explicit Module Builds] Pass down pre-built module candidates to the -compile-module-from-interface jobs

Package.swift
Required for PR [Support for Netrc for Downloader](https://github.com/apple/swift-tools-support-core/pull/88)  & [SPM mirror](https://github.com/apple/swift-package-manager/pull/2833).
Discussed: [SPM support basic auth for non-git binary dependency hosts](https://forums.swift.org/t/spm-support-basic-auth-for-non-git-binary-dependency-hosts/37878/10?u=sstadelman).
=> Bumped minimum platform version to 10.13 

Package.swift
It was merged prematurely and is causing breaks in other projects (SwiftPM and, cascadingly, everything that relies on it).
=> Revert #185: Bump minimum platform version to 10.13

TestInputs/ExplicitModuleBuilds/Swift/A.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/E.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/F.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/G.swiftinterface, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift
- Explicit Module Build test input .swiftinterface files to explicitly bring in SwiftONoneSupport
- Triple test to function when the toolchain uses fallback from `swift-driver` to `swift`
=> Update tests to match latest toolchain expectations.

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Explicit Module Builds/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Explicit Module Builds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Explicit Module Builds/PlaceholderDependencyResolution.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/Inputs/ExplicitModuleDependencyBuildInputs.swift
This change introduces support for external dependencies in Explicit Module Build compilation mode.
Building a Swift module in Explicit Module Build mode requires passing all of its module dependencies as explicit arguments to the build command.
When the driver's clients (build systems, e.g. SwiftPM) are planning a build that involves multiple Swift modules, planning for each individual module may take place before its dependencies have been built. This means that the dependency scanning action will not be able to discover such modules. In such cases, the clients must provide the driver with information about such external dependencies, including the path to where their compiled `.swiftmodule` will be located, once built, and a full inter-module dependency graph for each such dependence. …
=> [Explicit Module Builds] Support explicit module builds with external dependencies.

Utilities/build-script-helper.py
If a toolchain is specified, set the search environment variable for each tool executable the driver cares about to ensure that the specified toolchain's specific version is used.
=> [Build Script Helper] Setup environment variables for the specified toolchain's executables

Sources/SwiftDriver/Utilities/Triple.swift, Tests/SwiftDriverTests/TripleTests.swift
This is a direct port of some of the updates to clang/llvm. I didn't port over canonicalization of the fake "macOS 10.16" triples because it looks like that's already been mostly removed elsewhere.
=> Improve support for macOS 11/darwin 20 triple versioning

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This should help make it a bit clearer what's going on when using the driver with an incompatible toolchain or configuring SWIFT_DRIVER_SWIFT_FRONTEND_EXEC incorrectly
=> Report a better error message when retrieving target info from the frontend fails

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This fixes the remaining source info integration test (Driver/sourceinfo_file.swift)
=> Fix .swiftsourceinfo output path when the build system provides a Project/ dir

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/ModuleWrapJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift, Tests/SwiftDriverTests/XCTestManifests.swift
In addition to the added tests, this fixes Driver/modulewrap.swift. I did also find a bug while working on this where we aren't always planning an autolinking job when we should. I'm pretty sure that's an unrelated issue with how we're setting the object file format of triples though.
=> Support module wrapping for debugging on Linux

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/ModuleWrapJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/Triple.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift, Tests/SwiftDriverTests/TripleTests.swift, Tests/SwiftDriverTests/XCTestManifests.swift
Builds on https://github.com/apple/swift-driver/pull/199, only the second commit is new.
This PR infers a triple's object format if the environment is successfully parsed but the format can't be determined from that environment. This can happen with triples like `x86_64-unknown-linux-gnu` and caused autolink-extract jobs not to be generated sometimes because the object format wasn't correctly inferred as ELF. Unfortunately I had to ifdef out some tests on macOS as a result since `swift-autolink-extract` isn't available there.
=>  Infer object format when it can't be determined from a triple's successfully parsed environment

Sources/SwiftDriver/Utilities/Triple.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift, Tests/SwiftDriverTests/TripleTests.swift
Reverts apple/swift-driver#201
Linux CI builds with this change are failing with "unableToFind(tool: "swift-autolink-extract")" during SMP tests. I've been unable to find the cause, so reverting for now.
=> Revert " Infer object format when it can't be determined from a triple's successfully parsed environment"

Utilities/build-script-helper.py
Sorry for the back and forth, this seems to have been a bit of a chicken-and-egg between macOS and Linux.
=> [Build Script Helper] Only export toolchain executable paths when the executable exist and bring back wrongly-removed tools.

Tests/SwiftDriverTests/SwiftDriverTests.swift
=> [Gardening] Remove a print statement from VFS overlay tests

Sources/SwiftDriver/Jobs/Job.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
We generate such jobs on a per-module basis anyways.
This will give slightly nicer status commands in SwiftPM.
=> Describe generatePCM jobs with the module name, not the first display input.

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Utilities/VersionExtensions.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This fixes the Driver/sdk-version.swift integration test, and it's also a prerequisite to begin modernizing linker deployment targets to use -platform_version instead of the old flags.
Unfortunately, SDKSettings.json doesn't work very well with Codable synthesis and the implementation of Codable for `Version` in TSC, so there's a lot of manual decoding. Also, this implementation sometimes includes a minor version of `0` where the integrated driver would not (for example -target-sdk-version 13.4.0 instead of 13.4); as far as I know this won't break anything, and it makes the version remapping much simpler.
=> Attempt to use SDKSettings.json on Darwin platforms to set -target-sdk-version

Tests/SwiftDriverTests/SwiftDriverTests.swift
We have build bots that build `swift` but do not build `lldb`, this ensures that this test does not fail in that environment. 
Example of such build bot:
https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_04-long-test/6634/console
=> Disable the REPL test when no LLDB is found in the toolchain.

Utilities/build-script-helper.py
Instead of doing it automatically every time.
This will allow callers (mostly `swift` `build-script`) decide/override whether or not cleanup should be done.
https://github.com/apple/swift/pull/33563 shows the use of this action in the compiler's `build-script`.
=> [Build Script Helper] Make cleaning up build directory a separate "clean" action.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Explicit Module Builds/ClangVersionedDependencyResolution.swift, Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Explicit Module Builds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Explicit Module Builds/PlaceholderDependencyResolution.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/FileType.swift, Sources/SwiftOptions/Options.swift, TestInputs/ExplicitModuleBuilds/CHeaders/C.h, TestInputs/ExplicitModuleBuilds/CHeaders/G.h, TestInputs/ExplicitModuleBuilds/CHeaders/X.h, TestInputs/ExplicitModuleBuilds/CHeaders/module.modulemap, TestInputs/ExplicitModuleBuilds/Swift/A.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/E.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/F.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/G.swiftinterface, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/Inputs/ExplicitModuleDependencyBuildInputs.swift
- Factor out placeholder dependency resolution out of the ExplicitModuleHandler into the Driver
- Generate and post-process the dependency graph before passing it on to the ExplicitModuleHandler:
- Run the Swift Fast Dependency Scanner.
- Resolve placeholder dependencies, if any.
- Re-scan and update Clang modules with a super-set of their dependencies against all compilation targets.
**Some background on this issue:**
When building a Swift module at a fixed target version, the module may have dependencies which specify a different target version. It is possible that in this case, multiple swift modules, with different targets, have a dependency on the same Clang module. There is a hard requirement that the target version of the Clang module compilation match exactly the target version of …
=> [Explicit Module Builds] Re-scan all clang modules against all targets against which they will be built.

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Utilities/Triple+Platforms.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Builds on #209, only the second commit is new.
This fixes Driver/macabi-environment.swift and begins revolving some of the failures in Driver/linker.swift. It replaces the older deployment target linking flags with `-platform_version`.
=> Use platform_version to pass deployment target information to the linker

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Utilities/Triple+Platforms.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
I haven't been able to reproduce the issue that caused this to be reverted locally, so running on Swift CI to try and diagnose the problem
=> Reapply "Use platform_version to pass deployment target info to the linker"

Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Explicit Module Builds/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Explicit Module Builds/ModuleArtifacts.swift, Sources/SwiftDriver/Explicit Module Builds/PlaceholderDependencyResolution.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Ensure the flag is propagated from a given swift module's dependency graph details to its swift module info passed in as an explicit module map to frontend jobs.
This is a companion PR to: 
https://github.com/apple/swift/pull/33430
=> [Explicit Module Builds] Add `isFramework` flag to the dependency graph and swift module info.

Sources/SwiftDriver/CMakeLists.txt
Add missing file.
It seems that when I re-based https://github.com/apple/swift-driver/pull/217, I somehow managed to silently undo the CMakeLists change it meant to contain...
=> Fix the swift-driver build using CMake

Sources/SwiftDriver/Execution/ArgsResolver.swift, Sources/SwiftDriver/Jobs/CommandLineArguments.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/Job.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Previously, .autolink files were passed as flags throughout the driver so that they could be prefixed by "@". This PR adds a new Job.ArgTemplateKind, `responseFilePath` to make sure we resolve the underlying path properly. This fixes most of the Driver/tools_directory integration test (there's at least one other remaining unrelated issue preventing it from passing)
=> Properly resolve paths to temporary response files when autolinking

Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
The compiler computes the resource folder based on its own executable path when it is not explicitly set, but it used to always pick the shared resource folder, because it did not have information about whether the binary will be statically or dynamically linked. This has been changed in https://github.com/apple/swift/pull/33168 and this PR adjusts the behavior to match that of the C++ implementation.
=> Pass -use-static-resource-dir to frontend when linking statically

Package.swift
In certain build contexts, it can be necessary to align the swift-driver deployment target with the one specified for SwiftPM via this environment variable.
=> Align with `SWIFTPM_MACOS_DEPLOYMENT_TARGET` if set

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This fixes the Driver/no-inputs.swift integration test, and by moving the check to the start of build planning, it also eliminates a couple of crashes where when we were creating compile jobs we assumed there was at least 1 input file.
=> Update the no inputs error to allow invocations like 'swiftc -v'

Sources/SwiftDriver/Execution/ArgsResolver.swift, Sources/SwiftDriver/Jobs/CommandLineArguments.swift, Sources/SwiftDriver/Jobs/Job.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Previously, appending a parsed option like '-I=/some/path' to a job's command line was unimplemented. This change represents these internally as a new Job.ArgTemplate case, joinedOptionAndPath.
I noticed this when running the full swift integration test suite with swift-driver. It turns out this was the only thing keeping all of the PlaygroundTransform tests from passing.
=> Support adding a "joined" option with a path argument to a command line

Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
This corresponds to this fix from January in the C++ driver: https://github.com/apple/swift/pull/29183
=> Add -require-explicit-availability and -require-explicit-availability-target to common frontend opts

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
While debugging why the TypeDecoder tests were all failing when run with swift-driver, I discovered that for invocations like `swiftc -emit-executable foo.swift -g -emit-module`, we weren't prefixing the swiftmodule file with -add_ast_path in the linker job. This PR fixes ~20 assorted integration test failures, and makes some minor cleanups to linker input handling on Linux as well.
=> Fixup linker input handling and use -add_ast_path when needed

Sources/SwiftOptions/ParsedOptions.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Another small bugfix: according to https://github.com/apple/swift/pull/8134, the relative ordering of "-F" and "-Fsystem" search paths needs to be preserved in frontend invocations. Instead of introducing a special case, I just changed the behavior of ParsedOptions.arguments(for options:) since it shouldn't be that expensive to always sort the options and I'm guessing this isn't the only case where it could end up mattering for correctness.
=> Preserve relative ordering in ParsedOptions.arguments(for options:)

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Execution/DriverExecutor.swift, Sources/SwiftDriver/Explicit Module Builds/ClangVersionedDependencyResolution.swift, Sources/SwiftDriver/Explicit Module Builds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Explicit Module Builds/SerializableModuleArtifacts.swift
https://github.com/apple/swift/pull/33569 introduced a batch dependency scanning mode to save up on the overhead of clang instance creation.
This patch switches `swift-driver` over to using the new batch mode instead of generating individual `-scan-clang-dependencies` jobs for each re-scan.
=> [Explicit Module Builds] Use the new batch scanning mode for versioned PCM clang modele re-scan

Sources/SwiftDriver/CMakeLists.txt
Correct missing quote mark in Sources/SwiftDriver/CMakeLists.txt.
Just as I was working on preventing this kind of thing...
=> Fix CMake Build

Sources/SwiftDriver/Utilities/Diagnostics.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This slightly updates the message to `values for '-debug-prefix-map' must be in the format 'original=remapped', not 'foo'`, and makes it consistent with the c++ driver after https://github.com/apple/swift/pull/33706. Once both are merged, Driver/debug-prefix-map.swift and Driver/coverage-prefix-map.swift should pass.
=> Reword *-prefix-map diagnostic messages

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftOptions/ExtraOptions.swift, Sources/SwiftOptions/ParsedOptions.swift
This has been pretty useful for debugging some of the integration tests failures, so I think it makes sense to include, at least as an internal debugging option. Putting the check at the end of `Driver.run` seemed like the best way to avoid false positives, but I can move it somewhere else if anyone has a better idea.
=> Add a -driver-warn-unused-options flag for debugging

Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Jobs/Planning.swift
Preprocess the dependency graph, setting module paths to be relative to the module cache path, if one is present.
Only do so for modules that do not already specify a path.
=> [Explicit Module Builds] Point module dependency modules to be put into the module cache

README.md
A 5.3 snapshot is able to build the driver, but will fail most of the tests, which can be confusing for anyone who doesn't follow the development closely.
=> Add trunk snapshot requirement to the README

Sources/SwiftDriver/Jobs/CompileJob.swift
Previously, -track-system-dependencies and -cross-module-optimization weren't being forwarded to the frontend. This fixes up a couple miscellaneous integration tests.
=> Add missing flags to compile jobs

Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
Fixes DebugInfo/compiler-flags-macosx.swift
With these updates, swift-driver should now match the behavior of the integrated driver and clang by passing -debug-info-store-invocation only when it's passed to the driver or RC_DEBUG_OPTIONS is set.
=> Fix -debug-info-store-invocation logic on Darwin

Sources/SwiftDriver/CMakeLists.txt
Because Yams is used with `@_implementationOnly`, the clients of
`SwiftDriver` do not need to link against `Yams` or `CYaml`.  This was
uncovered when building SourceKit-LSP.
=> build: link Yams privately

README.md
This PR updates `DriverInternals` and `DriverParseableOutput` from `.rst` to `.md` in the `README`.
The files were updated a couple months ago in the following commits:
https://github.com/apple/swift/commit/d2c3a78c5db3d7e9a730d24708c8c336552996ba
https://github.com/apple/swift/commit/229352318935734850fafd45a24b4621490aff29
=> FIX - broken DriverInternals and DriverParseableOutput rst urls

Sources/SwiftDriver/Driver/Driver.swift, Sources/swift-driver/main.swift, Tests/SwiftDriverTests/Helpers/AssertDiagnostics.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This PR adds validation for:
- conditional compilation arguments
- `-profile-generate` and `-profile-use`
- `-F` and `-Fsystem`
Additionally, if a validation step fails when initializing the driver, don't fail immediately. Instead, record any other validation failures and then exit before planning.
=> Implement additional argument validation steps and record multiple failures before exiting

CMakeLists.txt, Package.resolved, Package.swift, README.md, Sources/swift-help/CMakeLists.txt, Sources/swift-help/main.swift
swift-argument-parser needs some CMake fixes before this can land
=> Add a swift-argument-parser dependency and use it in swift-help

Package.resolved, Package.swift
The issue with `swift-argument-parser` version 0.3.1 is being resolved in https://github.com/apple/swift-package-manager/pull/2919, so we need to coordinate the dependency update here as well.
=> Update swift-argument-parser dependency

Sources/SwiftDriver/Utilities/Triple+Platforms.swift, Tests/SwiftDriverTests/TripleTests.swift
Looking at the `Triple.FeatureAvailability` initializers, I came across this comment:
```swift
/// Each version parameter is `Optional`; a `nil` value means the feature is		
/// not supported on any version of that platform. Use `Triple.Version.zero`		
/// for a feature that is available in all versions.
```
It stuck out to me because Swift is a very expressive language and can model this better than with a convention described in a comment (which was repeated in both initializers). So I did:
```swift
public enum Availability {
case unavailable
case available(since: Version)
case availableInAllVersions
}
```
I'm not thrilled about `availableInAllVersions`, but it is explicit. Also, nesting `Availability` in `FeatureAvailability` is probably not great, but I couldn't think of a better …
=> Make `FeatureAvailability` more explicit

Sources/SwiftDriver/Jobs/CompileJob.swift
- canonical sib, raw sib, imported modules, and index data are always top level (as far as I know)
- bitcode is top-level if it's the compiler output type (in other words, it's not being embedded)
This fixes:
- Frontend/sil-primary-file-with-sib.swift
- reproducible-builds/swiftc-emit-bc.swift
- reproducible-builds/swiftc-emit-sib.swift
- reproducible-builds/swiftc-emit-sibgen.swift
=> Update isTopLevelOutput predicate

Tests/SwiftDriverTests/IntegrationTests.swift
Matching the directory structure created by the `update-checkout` script.
With this change, we can run integration tests according to the instructions in the README.
=> [Integration Tests] Fixup the path to llvm's lit.py to reflect the monorepo structure

Tests/SwiftDriverTests/IntegrationTests.swift
Counterpart to https://github.com/apple/swift/pull/33961 which has the context.
This PR passes the swift_driver parameter to lit so that it disables the integrated_driver feature.
=> Add a lit feature for the c++ driver

Sources/SwiftDriver/Jobs/CommandLineArguments.swift
This is a tiny change so that I can merge this, then update SPM to use its own executor instead of `SwiftDriverExecutor`, and then land https://github.com/apple/swift-driver/pull/263 without a cross-repository merge.
=> Make joinedArguments helper public so it can be used by SPM

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Execution/DriverExecutor.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
When the driver fails to get the target info from the frontend, print out more detailed information
=> Better output from a decoding error

README.md
I had to pass -DCMAKE_OSX_ARCHITECTURES=x86_64 today to get the build to work, the error was pretty vague but I think it must be related to macOS on arm64
=> Update llbuild CMake directions

Sources/SwiftDriver/Execution/ArgsResolver.swift
The default "preferred line-width" setting appears to be `80` characters. At that setting, encoding a filesystem path that is longer than `80` characters long and contains a whitespace at an index `> 80`, a line-break will be inserted at that index, which then results in serializing a malformed `outputFileMap` that contains invalid paths the frontend will not be able to read.
=> Set the line-width parameter on the Yams `serialize` routine to unlimited.

Sources/SwiftDriver/Driver/Driver.swift
No functional changes, but it eliminates an unnecessary frontend invocation
=> [NFC] Use frontend target info to print compiler version in -v mode

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Since the docs for this aren't open source, I'm not sure my test cases are all that great, but all the relevant integration tests are passing now and the implementation wasn't as complicated as I expected. The use of a "claimed" bit on `Driver.loadedModuleTracePath` is definitely a bit of a hack though.
Fixes:
Driver/loaded_module_trace.swift
Driver/loaded_module_trace_append.swift
Driver/loaded_module_trace_env.swift
Driver/loaded_module_trace_foundation.swift
Driver/loaded_module_trace_header.swift
Driver/loaded_module_trace_multifile.swift
Driver/loaded_module_trace_spi.swift
=> Add support for loaded module trace emission

Utilities/build-script-helper.py
Previously only the x86 `swift-driver` and `swift-help` executables were copied over to the specified toolchain's `bin` directory.
With this change, `libSwiftDriver` shared library is also packaged and installed into the toolchain, as well as `libSwiftOptions`.
To do so, we build the driver and all of its dependencies using CMake for `arm64` and `x86_64` and create universal binaries, as documented [here](https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary).
Because the driver's dependencies need to come along for the ride, the installed artifacts are as follows, within the specified toolchain:
```
bin/swift-driver
bin/swift-help
```
```
lib/swift/macosx/libTSCBasic.dylib
lib/swift/macosx/libTSCLibc.dylib
lib/swift/macosx/libTSCUtility.dylib …
```
=> [Build Script Helper] On macOS make install action use CMake and install libSwiftDriver

Sources/SwiftDriver/Explicit Module Builds/ClangVersionedDependencyResolution.swift, Sources/SwiftDriver/Explicit Module Builds/InterModuleDependencyGraph.swift
- Add a new `InterModuleDependencyGraph` field in `ClangModuleDetails` to capture against which targets this module has been scanned. The `directDependencies` of this module then represent the super-set of dependencies at all of the specified targets. 
- When performing a batched, versioned-PCM re-scan, only perform the re-scan at sets of PCMArgs that are "new" to this module to potentially discover additional dependencies. 
On its own, this change will not yield much improvement, but it is a necessary piece of the puzzle for a follow-up change that will build on top of this to drastically reduce the amount of redundant re-scanning that is currently happening in multi-module build contexts.
=> [Explicit Module Builds] Keep track of PCMArgs at which clang modules have been scanned

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Explicit Module Builds/ClangVersionedDependencyResolution.swift, Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Explicit Module Builds/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Explicit Module Builds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Explicit Module Builds/PlaceholderDependencyResolution.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Instead of SwiftPM passing in a set of external targets along with their dependency graphs, SwiftPM will now pass in:
- A set of external targets along with the location of their resulting `.swiftmodule` files, as before 
- a collection of *all* modules seen so far across all targets already planned in this build.
The second point replaces previous behaviour, where SwiftPM only passed in the dependency graphs of targets which are dependencies of the target swift-driver is currently planning the build for. Having access to *all* previously-seen modules will allow us to be more intelligent with knowing what modules do not need scanning as well as what clang modules require a re-scan, as each re-scan updates Clang module's details with the set of PCMArgs their dependencies currently capture …
=> [Explicit Module Builds] Change interface used by SwiftPM to communicate external dependencies.

Sources/SwiftDriver/Driver/Driver.swift
Now that https://github.com/apple/swift-package-manager/pull/2959 has been merged, this is no longer needed.
=> Remove temporary backwards-compatible SwiftPM interface

Sources/SwiftDriver/Explicit Module Builds/PlaceholderDependencyResolution.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/Inputs/ExplicitModuleDependencyBuildInputs.swift
It will be much better for SwiftPM to not have to know how to mutate the graph in this way when it has to, and to have this code be common across other clients.
=> [Explicit Module Builds] Provide API for a common dependency graph operation performed by SwiftPM

Sources/SwiftDriver/Utilities/VirtualPath.swift
This PR adds new public computed properties `relativePath` and `temporaryFileName` to `VirtualPath`. The goal is to use these in SPM's ManifestBuilder to avoid switching over all of the VirtualPath cases. This should unblock https://github.com/apple/swift-driver/pull/250 which adds a new enum case, and might help avoid some issues once SwiftDriver is being built with library evolution enabled in some contexts but not others.
=> Add API so SPM doesn't need to switch over VirtualPath cases

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift
This change decodes the paths in `-print-target-info` as `VirtualPath`s to simplify their use throughout the driver. This initial change is pretty small, but I think it'll make it easier to use the runtime library and resource dir paths reported by the frontend throughout the rest of the driver. 
I thought about modifying the frontend so it always resolves these paths to absolute, but I think that would just create problems for distributed build systems in the future.
=> Decode paths as VirtualPaths from -print-target-info output

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Explicit Module Builds/ClangVersionedDependencyResolution.swift, Sources/SwiftDriver/Explicit Module Builds/CommonDependencyGraphOperations.swift, Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Explicit Module Builds/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Explicit Module Builds/PlaceholderDependencyResolution.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/Inputs/ExplicitModuleDependencyBuildInputs.swift
This is a refactoring change intended to reduce ambiguity in what nodes in the dependency graph can represent. As dependency graph structure and individual modules are being communicated and merged among different components, such ambiguities in the graph introduce additional, unnecessary complexity to graph operations.
- Introduce a new module kind: `.swiftPrebuiltExternalDependency`.
This node kind is to be used for external target dependencies built by build system clients. Previously we were using `.swift` modules to represent both pre-compiled external targets and Swift module dependencies that require a build job to be created by the driver. This new structure means that every `.swift` module dependency must have a build job constructed for it, and every `.swiftPrebuiltExternal` …
=> [Explicit Module Builds] Refactor the InterModuleDependencyGraph to distinguish prebuilt external dependencies.

Tests/SwiftDriverTests/JobExecutorTests.swift
Clear CI while we investigate the cause. 
Example failure:
https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_04-long-test/6931/console
=> Disable intermittently-failing testStubProcessProtocol on Linux

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/Job.swift
The C++ driver uses -driver-print-actions in several tests. We should implement the same
action in the Swift driver so we can run the compiler-side tests by using the Swift driver.
Printing the exactly same results is difficult but they should be semantically equivalent.
=> Implement -driver-print-actions for testing purposes

Sources/SwiftDriver/Jobs/CompileJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
`-index-file` uses single compiles, but the `-index-file-path` needs to be passed as a `-primary-file` input. It looks like all the other indexing flags were already being handled correctly.
This fixes the remaining index store tests:
Index/Store/driver-index-with-auxiliary-outputs.swift
Index/Store/driver-index.swift
Index/Store/driver-multiple-inputs.swift
Index/Store/unit-one-file-multi-file-invocation.swift
=> Pass -index-file-path as a primary file input

Sources/SwiftDriver/Driver/Driver.swift
`uint` is a typedef that is made available on Darwin targets.  The Swift
spelling for this type is `UInt`.  Adjust it to repair the build on
Windows.
=> SwiftDriver: repair the build on non-Darwin after #295

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Sources/SwiftDriver/Jobs/Toolchain+InterpreterSupport.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
In addition to the added tests, this also fixes Driver/linker-rpath.swift. It was kind of tricky to keep the scope of this change small, so this PR includes a few related changes.
- computeResourceDirPath now returns a VirtualPath and handles the case where the user overrides it to be relative. As a result, all the places we were computing paths based on the resource directory required minor, hopefully uncontroversial updates. We're still not using the resource dir from the frontend target info yet because it looks like there might be a few minor issues that need to be resolved first.
- Before this change, `-working-directory` was applied to arguments after frontend target info was fetched, now it is applied beforehand so that the combination of `-working-directory` and a relative …
=> Return the compiler resource directory as a VirtualPath and fixup clients

Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftOptions/ExtraOptions.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Just using `-driver-print-jobs` works fine, if needed for debugging purposes.
=> Remove extra option to print explicit dependency build jobs.

Utilities/build-script-helper.py
In incremental builds of the driver, these commands will fail, which is okay.
Failing to remove specified Rpaths means they are already missing, and failure to add specified Rpaths means they are already present. So we should ignore these failures and proceed with the installation, which we already do. Always outputting these errors pollutes build logs and leads people to mistakenly blame these errors for unrelated failures.
=> [Build Script Helper] Avoid outputting install_name_tool failures

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Execution/ArgsResolver.swift, Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift, Sources/SwiftDriver/Explicit Module Builds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift
I forgot to change the base branch on this so I had to reopen it to fix a merge conflict. Once https://github.com/apple/swift-package-manager/pull/2962 is merged I should be able to merge this without breaking the build.
This commit introduces a new VirtualPath case, temporaryFileWithKnownContents.
This allows the ExplicitModuleBuildHandler to indirectly delegate writing artifact info
temporary files to the ArgsResolver.
=> Remove the fileSystem in ExplicitModuleBuildHandler

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Utilities/Diagnostics.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
The frontend takes care of the actual inference, so here I just check if we're in a situation where the explicit triple does not have the simulator environment but the frontend target info one does.
=> Warn when a target environment is inferred to be a simulator

Sources/SwiftDriver/Jobs/VerifyModuleInterfaceJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This fixes the ModuleInterface/verify-module-interfaces.swift test. Previously, the module interface was correctly being added as a job input, but it wasn't added to the command line.
=> Add the module interface input to the command line of a verification job

Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift
There is nothing that requires the use of `MSVCRT` (i.e. `stderr`,
`stdout`, or the overloaded math routines).  This eases the removal of
the `visualc` module from the Swift standard library.
=> SwiftDriver: use `ucrt` instead of `MSVCRT`

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Sources/SwiftDriver/Incremental Compilation/BuildRecordInfo.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/Tracer.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
1. Centralize the `parsedOptions` interrogation for `-driver-show-job-lifecycle`
2. Use diagnostic remarks for `-driver-show-job-lifecycle` and `-driver-show-incremental`
Why? Much easier to test, may not mess up Xcode's reading of the compiler's output.
Why not? We'll have to fix some integration tests, as it differs from legacy front end.
3. Add tests for these outputs
4. Call back into `BuildRecordInfo` and `IncrementalCompilationState` when jobs finish.
Robert floated, and I like the idea of mimicking the legacy driver's messages. However, since we don't have the same sort of task queue (at the present), I'm not sure it's feasible.
=> [Incremental] Testable debugging outputs & tests

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift, Sources/SwiftDriver/Utilities/Triple+Platforms.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is an initial implementation of a WebAssembly toolchain. It shares a lot of similarities with the GenericUnixToolchain, but it doesn't support dynamic libraries and other features like sanitizers, profiling, etc. Overall, there are enough differences that trying to subclass GenericUnixToolchain seemed potentially error-prone.
The functionality in this PR goes a bit beyond the current Wasm support in the main Swift repo. I tested this change by installing swift-driver into a toolchain snapshot from the SwiftWasm fork and then verifying I could compile a basic working program.
=> Add initial WebAssembly toolchain implementation

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Utilities/Diagnostics.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This fixes the Driver/ast_dump_with_WMO.swift test, and expands the override to cover -index-file as well based on a FIXME in the C++ source. If both are specified, a warning is emitted: `ignoring '-wmo' because '-dump-ast' was also specified`
=> -dump-ast overrides -wmo and -index-file

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
- Move printing of the output map to the `run()` stage and exit after.
- Adjust the kind of inputs printed in `printBindings` to print `displayInputs`.
- Add `displayInputs` to the link job.
This change makes `test/Driver/basic_output_file_map.swift` pass.
=> Make print-output-map and print-bindings behaviour match the C++ driver.

Sources/SwiftDriver/Jobs/Planning.swift
This allows us to compare the output with that of the C++ driver
=> BatchMode: log batch configurations when -driver-show-job-lifecycle is set. NFC

Utilities/build-script-helper.py
While not required for `libSwiftDriver` clients, this is necessary in order to use the toolchain-installed `swift-driver` executable, since we separated the driver's targets in https://github.com/apple/swift-driver/pull/263.
=> [Build Script Helper] Install libSwiftDriverExecution into the toolchain

Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This allows the -merge-module action to find and import those partial entities.
rdar://70494813
=> Infer .swiftdoc and .swiftsourceinfo paths from .swiftmodule path in a given outputFileMap

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
=> Teach swift-driver to emit private interfaces

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
=> Derive supplementary output paths using the full basename of .swiftmodule

Utilities/build-script-helper.py
=> [Build Script Helper] install llbuild and ArgumentParser

Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Fixes:
ClangImporter/pch-bridging-header-unittest-ok.swift
ClangImporter/pch-bridging-header-unittest-warn.swift
ClangImporter/pch-bridging-header-with-another-bridging-header.swift
The c++ driver uses the original header when creating module merging jobs, and trying to use a pch causes weird failures in the test suite. I really don't understand why some frontend actions support precompiled headers and others don't, so it's possible there's a better solution to be found.
=> Don't pass a precompiled header to module merging jobs

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftOptions/ExtraOptions.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Incremental compilation currently relies on a merge-module phase. A typical
build plan for a module App composed of two source files (`A.swift` and `B.swift`)
involves four main jobs:
1. Compile `A.swift`, output `A.o` and `A~partial.swiftmodule`.
2. Compile `B.swift`, output `B.o` and `B~partial.swiftmodule`.
3. Link `A.o` and `B.o` in the final executable.
4. Merge-module: merging `A~partial.swiftmodule` and `B~partial.swiftmodule` to form
the final `App.swiftmodule`.
Jobs 3 and 4 must run after jobs 1 and 2 to use their outputs.
The flag `-experimental-emit-module-separately` replaces the merge-module job but
the emit-module job that can run in parallel to the other jobs and doesn’t need
the partial swiftmodules.
1. Compile `A.swift`, output `A.o`.
2. Compile `B.swift`, output `B.o`. …
=> Intro incremental build alternative to emit module files separately

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
This, along with https://github.com/apple/swift/pull/34405 will let us see real failures in the incremental dependency lit tests. Without these changes, nearly all the tests fail immediately because they rely on fake frontends and the -print-target-info decoding fails.
=> Include prefix args from -driver-use-frontend-path in -print-target-info jobs

Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Object files and other linker inputs specified on the command line should be included in the linker job. Additionally, if a loaded module trace is emitted, it should be associated with the first input to a compile job, which isn't necessarily the first input.
I added a couple of regression tests, and this also fixes a large number of lit tests (it took me awhile to notice the regression because it didn't affect anything in the Driver folder, I'm not sure exactly when it happened)
=> Fix a regression affecting command line linker inputs

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Need the `#if os(Linux)` tests to run in CI to verify they are correct because I wasn't able to run them. The swift docker images only seem to be for releases, and we require print-target-info changes from main.
=> Fix for simulator and linux -profile-generate linker args

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/DriverVersion.swift
When swift-driver is releases separately from the compiler, an independent version number could help.
=> Add a version number indicating swift-driver's source version

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
Fixes the darwin part of Driver/static-archive.swift. This test didn't check for this specifically, but it was testing for `libtool -static` and libclang_rt was in between that. Looked further and found c++ driver only includes libclang_rt when linking dynamically.
=> Only link compiler_rt when dynamic linking

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Explicit Module Builds/CommonDependencyGraphOperations.swift, Sources/SwiftDriver/Explicit Module Builds/ExplicitDependencyBuildPlanner.swift, Sources/SwiftDriver/Explicit Module Builds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Explicit Module Builds/PlaceholderDependencyResolution.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/Inputs/ExplicitModuleDependencyBuildInputs.swift
In contexts where SwiftDriver is used to plan a multi-module build (e.g. SwiftPM), use the `ModuleInfoMap` containing results of prior scans to avoid further redundant re-scanning.
_All_ previously-seen Swift modules are treated as potential placeholder dependencies during subsequent dependency-scanning actions. This causes the dependency scanner, upon encountering an `import` of such module, to not: search for its interface, parse it, and build a full dependency tree yet again.
The dependency scanner output, on subsequent re-scans, is therefore a much shallower graph with many placeholders, which get _resolved_ in the client (SwiftDriver) using the external `ModuleInfoMap` provided by the build system.
For planning the build of SwiftPM with _Explicit Modules_, this change reduces the …
=> [Explicit Module Builds] Re-use external build artifacts to avoid redundant Swift moduel re-scan

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/InterpretJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift, Sources/SwiftDriver/Jobs/Toolchain+InterpreterSupport.swift, Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
In theory this is NFC, but I'll run full CI just in case (Edit: looks like it passed). In addition to replacing all uses of the old method with reference to the target info's `runtimeResourcePath`, I had to update the -print-target-info job in toolchain computation to ensure it returned the static resource directory when needed. I tried replacing all uses of runtime library paths with the -print-target-info version too but ran into some issues where the macosx paths weren't included for catalyst targets, I'll need to look into that more.
=> Remove `computeResourceDirPath` and rely on the one reported by `-print-target-info`

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Sources/SwiftDriver/Execution/DriverExecutor.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift, Sources/SwiftDriverExecution/SwiftDriverExecutor.swift, Sources/SwiftDriverExecution/llbuild.swift, Tests/SwiftDriverTests/Helpers/AssertDiagnostics.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift, Tests/SwiftDriverTests/XCTestManifests.swift
Redo the interaction between `llbuild` and `IncrementalBuildState` in order to allow 2nd wave compilations to interleave with first wave compilations. As each first wave job finishes, add rules for discovered 2nd wave jobs.
=> [Incremental] Interleave waves by adding llbuild rules dynamically

Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Following the legacy driver, put the output of the autolink step in the same place as the .o files, instead of in a temp directory. That way, we could possibly omit this step in the future in an incremental build.
rdar://70961296
=> Put the output of the (Linux) autolink step in the same place as the .o files

Sources/SwiftDriver/Jobs/EmitModuleJob.swift
Use the new frontend flag `-experimental-skip-non-inlinable-function-bodies-without-types` in emit-module jobs in order to preserve all type information that LLDB relies on.
Depends on https://github.com/apple/swift/pull/34612
=> Preserve nested type info in swiftmodule files generated by the emit-module job

Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/XCTestManifests.swift
For some reason, the test that checks incremental diagnostics is failing on Linux.
Temporarily disable it; I'll look at it tomorrow.
Also, I had forgotten to regenerate the Linux test list, so this adds in the test for the autolink output path.
=> Disable a linux test temporarily

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Incremental Compilation/BuildRecord.swift, Sources/SwiftDriver/Incremental Compilation/BuildRecordInfo.swift, Sources/SwiftDriver/Incremental Compilation/DependencyKey.swift, Sources/SwiftDriver/Incremental Compilation/DictionaryOfDictionaries.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift, Sources/SwiftDriver/Incremental Compilation/InputInfo.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/Integrator.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/Node.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/NodeFinder.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/SwiftDeps.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/Tracer.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/Incremental Compilation/Multidictionary.swift, Sources/SwiftDriver/Incremental Compilation/SourceFileDependencyGraph.swift, Sources/SwiftDriver/Incremental Compilation/TwoDMap.swift, Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift, Tests/SwiftDriverTests/TwoDMapTests.swift
The latest Swift compiler is less tolerant of @_spi's than before. Remove the offenders.
rdar://71381579
=> Remove @_spi's that were preventing compilation

Sources/SwiftOptions/OptionParsing.swift, Tests/SwiftOptionsTests/OptionParsingTests.swift
1. If a flag has an unexpected suffix and is not supported by the current driver mode, diagnose it as an unsupported option instead of being available in another mode
2. Reject 'separate' options if they have an unexpected suffix
=> Option parsing fixes when args have unexpected suffixes

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftOptions/Option.swift, Sources/SwiftOptions/OptionParsing.swift, Sources/SwiftOptions/OptionTable.swift, Tests/SwiftDriverTests/IntegrationTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Fixes: Driver/help.swift
Also replaces deprecated `createSymlink` calls with `localFileSystem.createSymbolicLink`
=> Install swift-help for integration tests. Suppress .noDriver options from being emitted by swift-help.

Sources/SwiftDriver/Explicit Module Builds/ExplicitDependencyBuildPlanner.swift, Sources/SwiftDriver/Explicit Module Builds/PlaceholderDependencyResolution.swift, Sources/SwiftDriver/Incremental Compilation/BuildRecordInfo.swift
When generating build jobs for explicit module dependencies, we must distinguish multiple versions of the same Clang module/pcm by encoding the arguments used to build it (e.g. target triple) into the pcm filename.
So far, we have been using an unstable hash, which means that these filenames were not stable across invocations and were being needlessly re-built in some scenarios (e.g. many-target builds).
Switching to a stable hash (SHA256) ensures that the same Clang module, built with the same command line, will produce the same .pcm filename. This will allow the client build system (e.g. SwiftPM) to deduplicate identical compilation jobs because their output filenames will now also match.
=> [Explicit Module Builds] Use a stable hash to encode build arguments into PCM filenames

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Adds -repl warning
Rewords warning_incremental_requires_build_record_entry
Fix error_i_mode using potentially wrong driver kind
Fix error_argument_not_allowed_with not using '-debug-info-format='
Fixes Driver/options.swift (except for swift-driver doesn't allow integrated repl)
=> Update option diagnostics to match c++ driver

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/Planning.swift
Fixes:
Driver/actions.swift
Driver/actions-dsym.swift
Driver/bridging-pch.swift now fails on the output not having -* at the end.
Also fix issue where linker was being passed swiftmoduledoc and swiftsourceinfo files. (As far as I can tell they were ignored)
=> Rework printActions to be more like how the actions are created

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Best theory to explain a mysterious test failure on CI Linux. Land it and if test starts failing, disable the test again.
=> Ensure temp dir is different between testIncremental and testIncrementalDiagnostics to see if that fixes the test breakage in CI

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Reverts apple/swift-driver#374
This change caused failures in `swift` PR testing.
e.g. https://ci.swift.org/job/swift-PR-Linux-smoke-test/25956/console
=> Revert "Ensure temp dir is different between testIncremental and testIncrementalDiagnostics to see if that fixes the test breakage in CI"

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
This doesn't change any functionality, but there are several tests that rely on this ordering. Seemed easier to do it this way.
Fixes:
Driver/tools_directory.swift
Driver/sdk.swift - Now failing on windows support
=> Reorder darwin dynamic linker args to match c++ driver

Sources/SwiftDriver/Driver/Driver.swift
This allows us to see the compiler version with the driver version in the same line.
=> Don't print new line after the driver version

Sources/SwiftDriver/Incremental Compilation/BuildRecordInfo.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Make disabling incremental build message same as in legacy driver.
Towards getting legacy driver lit tests to run.
=> Make disabling incremental build message same as in legacy driver.

CMakeLists.txt, Package.swift, Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/_CSwiftDriver/CMakeLists.txt, Sources/_CSwiftDriver/_CSwiftDriverImpl.c, Sources/_CSwiftDriver/include/_CSwiftDriver.h, Sources/_CSwiftDriver/include/module.modulemap
We could use functions like dlopen and dlsym in this client-side library to talk with
compiler-side C APIs.
=> Set up a client-side C library to talk with C APIs exposed from the compiler

Sources/SwiftDriver/Driver/Driver.swift
Since the constructor uses a local `outputFileMap` that is different from `self.outputFileMap`, wrap the local in a block so later uses in this long method cannot accidentally use the wrong one.
=> [NFC] Encapsulate local outputFileMap to forestall bugs

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/Incremental Compilation/BuildRecordInfo.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift
Allow build record to reside at a relative path on the way to making legacy lit tests work.
=> [Incremental] Allow build record to reside at a relative path

Sources/SwiftDriver/Driver/Driver.swift
For the sake of compatibility with legacy driver, and better incremental builds, write the build record even if there was an error.
=> [Incremental] Write build record even if error.

Sources/SwiftDriver/Incremental Compilation/BuildRecord.swift, Sources/SwiftDriver/Incremental Compilation/InputInfo.swift
Handle relative paths when writing build record. (and a typo fix). Needed for legacy lit tests.
=> [Incremental] Handle relative paths when writing build record. (and a typo fix)

Sources/SwiftDriver/Incremental Compilation/DependencyKey.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/Tracer.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Move print code for dependency keys that was only used for trace printing, to `DependencyKey.description`.
Include the containing file when printing out a node.
=> [Incremental] Refactor & enhance dependency trace printing.

Sources/SwiftDriver/Incremental Compilation/DependencyKey.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/NodeFinder.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/Tracer.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Dependency graphs contain an implicit link from a given interface to its implementation. Take that into account when tracing uses of defs.
=> [Incremental] When tracing uses, include the implicit use of implementation when interface changes

Sources/SwiftDriver/Driver/CompilerMode.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Execution/DriverExecutor.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Without being aware of @cltnschlosser 's similar PR ( https://github.com/apple/swift-driver/pull/371/files ), I wrote this code last week. I suspect the two PRs do the same thing. So, not being sure how to proceed, I thought I would put this up and we might review each other's work and come up with a nice synthesis, (hence the "DNM").
Rather than disturb the interface that goes across to swiftpm, I included the extra parameter in the workload structure.
BTW, some version of this functionality is needed for the legacy lit tests.
Have incorporated several great ideas from @cltnschlosser  's PR.
=> [Incremental] stop if no -driver-continue-building-after-errors

Sources/SwiftDriver/Incremental Compilation/SourceFileDependencyGraph.swift
Allow relative paths when reading swiftdeps files. Required for using legacy tests.
=> [Incremental] Allow relative paths when reading swiftdeps files

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift, Sources/SwiftDriver/Utilities/Triple.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift
In order to use legacy lit dependency tests, the driver must honor `-driver-use-fronttend-path`. In that use-case, there is no point in querying the frontend for target info, so add a computation for dummy values for this.
=> [Incremental] Honor -driver-use-frontend-path

CMakeLists.txt
Swap the toolchain search order.  This ensures that the correct linker setup is done on WIndows.  For some reason, the Swift search first will potentially pick up MinGW if the tools are in the path.
=> build: swap compiler search

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Enable testBatchModeContinueAfterErrors & skip frontend query even if no extra arguments to -driver-use-frontend-path.
This test uncovered a bug, so add the test and and the fix.
Could not enable the test earlier because it depended on another PR.
=> [Incremental] Enable testBatchModeContinueAfterErrors & skip frontend query even if no extra arguments to -driver-use-frontend-path

Sources/SwiftDriver/Incremental Compilation/BuildRecord.swift, Sources/SwiftDriver/Incremental Compilation/BuildRecordInfo.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Utilities/FileType.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This issue happens in B&I and only reproduces in release builds. It suggests that we should set up testing swift-driver with ASAN turned on.
rdar://71942829
=> Walk-around a dangling pointer issue

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#393
This change causes a failure in SwiftPM unit-tests:
```
Test Case '-[BuildTests.BuildPlanTests testExplicitSwiftPackageBuild]' started.
/Volumes/Data/GHWorkspace1/swift-driver/Sources/SwiftDriver/Execution/DriverExecutor.swift:91: error: -[BuildTests.BuildPlanTests testExplicitSwiftPackageBuild] : failed: caught error: "jobFailedWithNonzeroExitCode(1, "<unknown>:0: error: unsupported target architecture: \'\'\n<unknown>:0: error: unsupported target OS: \'\'\n")"
Test Case '-[BuildTests.BuildPlanTests testExplicitSwiftPackageBuild]' failed (0.208 seconds).
```
=> Revert "[Incremental] Enable testBatchModeContinueAfterErrors & skip frontend query even if no extra arguments to -driver-use-frontend-path"

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Required because legacy driver does an exact check of input mod time vs time reconstructed from build record.
=> Add test for date accuracy.

Sources/SwiftDriver/Incremental Compilation/DependencyKey.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/Node.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/NodeFinder.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/SwiftDeps.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/Tracer.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
In order to pass legacy tests, honor -driver-always-rebuild-dependents
=> [Incremental] Honor -driver-always-rebuild-dependents

Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift
Legacy driver insists that dates match exactly.  So do that here for compatibility. Required for some lit tests.
=> [Incremental] Use same up-to-date test as legacy driver

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Utilities/FileType.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This one only subverts the frontend target check if the new frontend path is a Python script. That way, the option still should work with swiftpm. Don't merge until the swiftpm unit tests pass with this.
=> [Incremental] Another attempt to get the driver to honor -driver-use-frontend-path

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Utilities/FileType.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Turns out the tests invoke `Python` as the command, so test for that. No need to add .py to file types.
=> [Incremental] Properly detect the testing case when honoring -driver-use-frontend-path

Sources/SwiftDriver/Incremental Compilation/BuildRecord.swift, Sources/SwiftDriver/Incremental Compilation/DependencyKey.swift, Sources/SwiftDriver/Incremental Compilation/DictionaryOfDictionaries.swift, Sources/SwiftDriver/Incremental Compilation/InputInfo.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/Integrator.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/Node.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph Parts/SwiftDeps.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/Incremental Compilation/SourceFileDependencyGraph.swift, Sources/SwiftDriver/Incremental Compilation/TwoDMap.swift, Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift, Tests/SwiftDriverTests/TwoDMapTests.swift, Utilities/build-script-helper.py
For now, comment out testable and _spi, which makes it easier to try the driver out with various versions of the compiler.
Someday, we can either uncomment the @spi's, or we can move components into sub-modules. What do you think?
=> Comment out `@testable` and `@_spi`

Sources/SwiftDriver/Incremental Compilation/BuildRecord.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift, Sources/SwiftDriver/Incremental Compilation/ModuleDependencyGraph.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift
With the changes in the title, follows legacy behavior and passes `Driver/Dependencies/crash-added-fine.swift`
=> [Incremental] Don't read swiftdeps of a new input or of a crashed compile.

Sources/SwiftDriver/Incremental Compilation/BuildRecord.swift, Sources/SwiftDriver/Incremental Compilation/BuildRecordInfo.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/Inputs/IncrementalCompilationInputs.swift
Legacy test driver-show-incremental-arguments-fine.swift requires this.
Same applies to build date.
=> [Incremental] Mimic legacy for testing, can omit argsHash from build record and it still matches.

Sources/SwiftDriver/Incremental Compilation/BuildRecordInfo.swift
Pull over a feature from the legacy driver: Preserve old build record in order to pass dependencies-preservation-file.swift.
=> [Incremental] Preserve old build record in order to pass dependencies-preservation-file.swift

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Explicit Module Builds/ClangVersionedDependencyResolution.swift, Sources/SwiftDriver/Explicit Module Builds/ExplicitDependencyBuildPlanner.swift, Sources/SwiftDriver/Explicit Module Builds/Inter Module Dependencies/CommonDependencyOperations.swift, Sources/SwiftDriver/Explicit Module Builds/Inter Module Dependencies/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Explicit Module Builds/Inter Module Dependencies/InterModuleDependencyOracle.swift, Sources/SwiftDriver/Explicit Module Builds/PlaceholderDependencyResolution.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This PR refactors the handling of inter-module dependencies to centralize their handling in a new, reference-type, oracle.
`InterModuleDependencyOracle` will now be responsible for responding to queries about dependencies of a given module.
The intent behind it is to abstract the actual mechanism used for tracking/computing/caching inter-module dependencies. A single oracle reference is intended to be passed around to multiple Driver invocations, corresponding to different targets, by build-system clients (e.g. SwiftPM), replacing today's use of `ModuleInfoMap`-based API, to communicate already-computed dependency-scan results.
As implemented, it is a simple store of `ModuleInfo` value objects, which a `Driver` invocation populates by invoking a `-scan-dependencies` job; not unlike …
=> [Explicit Module Builds] Introduce an InterModuleDependencyOracle abstraction for tracking and sharing dependency scanning results

Package.resolved, Sources/SwiftDriver/Utilities/RelativePathAdditions.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift
This PR just resolves a couple of FIXMEs after I added some AbsolutePath/RelativePath utilities to TSC in https://github.com/apple/swift-tools-support-core/pull/173
=> Migrate to TSC versions of some Absolute/RelativePath APIs

Sources/SwiftDriver/Execution/ArgsResolver.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
- Adjust the supplementary output file map calculation to better match the C++ driver's WMO behavior
- Always include either primary inputs or the first input in the supplementary output file map, even if there aren't any corresponding outputs
Fixes Driver/supplementary-filelist-empty.swift and Driver/modulewrap.swift
=> Match the legacy driver's output file map behavior when there are no outputs

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Sources/SwiftDriver/Execution/DriverExecutor.swift, Sources/SwiftDriver/Execution/ParsableOutput.swift, Sources/SwiftDriver/Incremental Compilation/BuildRecordInfo.swift, Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift, Sources/SwiftDriver/Utilities/Triple.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
With these changes, all 50 test in `Driver/Dependencies` run (assuming https://github.com/apple/swift/pull/35171 ).
See the individual commits for the details.
rdar://71869951
rdar://71870416
rdar://72508507
=> [Incremental] Bring swift-driver into correspondence with legacy driver.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
For example, `swift -experimental-explicit-module-build hello.swift` will now prebuild module dependencies, and then run the interpret job in-place at the end. On its own this isn't that useful, but I'm using it to explore the idea of `@package` imports in scripts a bit more, and I think the generalization here is pretty harmless
=> [Explicit Modules] Support using -experimental-explicit-module-build with immediate mode

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Utilities/Diagnostics.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This doesn't pass the corresponding lit test yet because the flags are in a different order, but everything else seems to match.
It's worth pointing out that I deleted the `-update-code` check in `determinePrimaryOutputs` because the condition would never be met (-update-code isn't in the modes option group and the same problem occurs in the old driver). This seems consistent with the intent of the original driver's implementation which treats the migration as a parallel output to the compile, but might be worth double checking for correctness because I don't think the migrator is used much outside of Xcode.
Also, please feel free to ignore this until after the holidays! I'm just posting it early to run CI tests
=> Add support for the -update-code flag used to run the migrator

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/swift-driver/main.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
We need this to enable explicit modules in the driver-as-executable mode. For instance,
we have two Swift targets A and B, where A depends on X.pcm which in turn depends on Y.pcm, and
B only depends on Y.pcm. In the driver-as-executable mode, the build system isn't aware
of the shared dependency of Y.pcm so it will be generated multiple times. If all these Y.pcm
share the same name, X.pcm may fail to be loaded because its dependency Y.pcm could have a changed mod time.
We only differentiate these PCM names in the non-integrated mode due to the lacking of
inter-module planning.
rdar://72830153
=> [ExplicitModule] when using driver as an executable, differentiate PCM dependency names for each target

Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
This is a port of the change to the C++ Driver from apple/swift#34978 to Swift.
All the tests in this repo passed with this pull when run on linux x86_64. I don't know if this Driver is periodically run against the upstream testsuite, in which case the upstream pull will have to be merged first.
@cltnschlosser, this pull invalidates much of #370, maybe you can repurpose that by reworking the tests and adding the Android sanitizer change.
=> Remove redundant clang '-target' flag from Unix Toolchain

Package.resolved, Package.swift
In the `release/5.4` branch, also switch the branch-based dependencies to the `release/5.4` branch.
=> [5.4] Switch branch-based dependencies from `main` to `release/5.4`.

Utilities/build-script-helper.py
Not all toolchains assume that we're also targeting arm64 on macOS (e.g. S4TF). 
Building for the host platform only will also match what we do in some other, similar components.
Previous behavior of building universal binaries on Darwin is still available using:
`--cross-compile-hosts x86_64-apple-macosx10.15 arm64-apple-macosx10.15`
=> [Build Script Helper] Build for host platform only, by default.

Sources/SwiftDriver/Driver/OutputFileMap.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
The build system always uses .swift file for all output kinds. This causes an issue when we are using
the .bc file path as the key to get the .o file path.
rdar://73358362
=> OutputFileMap: use .swift file path as the key for .o file when .bc file is an intermeidate output

Package.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftOptions/DriverKind.swift, Sources/SwiftOptions/OptionTable.swift, Sources/swift-help/CMakeLists.txt, Sources/swift-help/main.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This PR has a couple of changes to the help tool:
- The subcommand listings are reformatted a bit, and I added a note to "Use "swift help subcommand" for more information about a subcommand". This is inspired by Go's help page, which also supports more general help topics. I think we could do something similar in a follow-up to add the kind of driver documentation requested in https://bugs.swift.org/browse/SR-7704.
- "swift help build/test/package/run" now forward to the help pages for each subcommand
=> Improve support for subcommands help in swift-help

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Unlike the old driver, all of the temporaries are created in a subdirectory, so we can just delete that instead of tracking each temporary file individually. We should also save temps if any of the jobs signals - I left that as a todo in this PR because it will require a bit more refactoring to make that information available to the driver.
=> Delete temporaries after running unless -save-temps is passed

Sources/SwiftOptions/OptionTable.swift
In the spirit of https://bugs.swift.org/browse/SR-7704, the legacy driver prints out a list of `MODES:` when invoked in "batch-mode": `swiftc --help`.
This PR adds the same behaviour here.
=> Display a list of driver modes in batch mode driver help.

Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Sources/SwiftDriver/ExplicitModuleBuilds/PlaceholderDependencyResolution.swift, Sources/SwiftDriver/ExplicitModuleBuilds/SerializableModuleArtifacts.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
In the process of generating explicit dependency jobs, we end up spending a lot of time constructing `VirtualPath` objects from strings contained in the dependency graph, (It involves querying whether or not this string constitutes an absolute path, and breaking it down into components) which all add up to a large amount of string manipulation.
Instead, decode these strings into `VirtualPath` values directly, using the `TextualVirtualPath` wrapper.
=> Decode path fields in `InterModuleDependencyGraph` as VirtualPaths

Sources/swift-driver/main.swift
The build system may interrupt swift-driver invocation if some errors are hit in other targets.
If these interrupted swift-driver processes return a non-zero value, the build
log will show a bunch of red-herring error-messages.
rdar://73456559
=> Exit with 0 when swift-driver invocation is interrupted

Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
Scrap the ad-hoc implementation of confinement queue concurrency for an explicit serial dispatch queue.
=> [NFC] Swap a Semaphore for Synchronous DispatchQueue

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
Fix assertion failure by moving subtraction of already-compiled inputs to the calling function so that if job compiling x.swift requires y.swift be compiled, and job compiling y.swift requires x.swift be compiled, x.swift and y.swift are subtracted out from jobs needing to be compiled. The bug shows up when testing with -j1.
=> [Incremental] Move subtraction to outer function to cope with multiple input jobs.

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/InputInfo.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/NodeFinder.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift, Sources/SwiftDriver/IncrementalCompilation/Multidictionary.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
- Add a new type representing changed inputs
- Break down the `forEach`-style APIs into explicit sequences and clean up their call sites.
- Break down the karnaugh map in `computeSpeculativeInputs`
=> [NFC] Simplify Parts of the Change Computation's Interface

Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Match the legacy driver and propagate this flag to the merge-modules job so embedded incremental information winds up in swift modules.
-------
Cross Module Incremental Builds Tasks
=> Propagate Experimental Cross Module Incremental Build Flag

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
@CodaFi Introduced a nice new type, but it doesn't need to be mutable, so use `let`s.
=> [NFC, Incremental] Use let's instead of var's for the ChangedInput struct.

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Tests/SwiftDriverTests/Helpers/Fixture.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
This should make tests that build virtual file systems easier to write in the future. While I'm here, sequester some hacks for computing paths into the test fixtures directory.
=> [NFC] Plumb Through Explicit FileSystem to the Integrator

Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
=> [Incremental] Accept VirtualPath for reading a SourceFileDependencyGraph so the lit tests work.

Package.resolved, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/NodeFinder.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Use bitstream to read and write ModuleDependencyGraph instances out to
disk. The idea is that eventually the Driver can emit its dependency
graph as a supplemental output (possibly adjacent to the build record)
and recover the state it was last in by reading that file. This is as
opposed to the status quo where O(N) swiftdeps files are read and
integrated at startup. Whether this is a net win has yet to be seen.
Also, we're using bitstream because it's convenient. It would be prudent
to explore alternative serialization formats at some point.
rdar://73517080
=> Add Round-Trip Serialization For ModuleDependencyGraph

Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
- Squash Fingerprint data into the end of a node record as a trailing blob.
- Restore the immutable `fingerprint` member
- Document, clean up, and formalize more serialization infrastructure.
=> Clean Up The Module Dependency Graph Format A Bit

Sources/SwiftDriver/IncrementalCompilation/BidirectionalMap.swift, Sources/SwiftDriver/IncrementalCompilation/DictionaryOfDictionaries.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift, Sources/SwiftDriver/IncrementalCompilation/Multidictionary.swift, Sources/SwiftDriver/IncrementalCompilation/TwoDMap.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift
- Serialize external dependencies
- Serialize uses-by-defs
=> Finish Up Driver Dependency Graph Serialization

Tests/SwiftDriverTests/Helpers/DriverExtensions.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
The latest Swift makes tests fail because it cannot load libraries. Point the frontend to the sdk for the incremental tests. Add an affordance to do so. More tests will probably need to use this affordance in the future.
=> [Incremental] Add sdk arguments to incremental tests

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/NodeFinder.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
In order to implement cross-module incrementality, the SwiftDeps type needs to also represent a swiftSourceFile file, so the name is how wrong.
=> [Incremental] Rename "SwiftDeps" etc. to "DependencySource"

Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Integrates incrementalExternalDependencies.
Unimplemented/Broken:
Does not write ModuleDepGraph or try to read it instead of swiftDeps. Probably doesn't do the right thing if it did read ModuleDepGraph.
- For instance: how to handle deleted imports
Does not do the right thing when importing a module with incrementalExternalDependencies when running with -enable-incremental-cross-module-etc turned off.
Implemented:
Reads incrementalExternalDependencies and integrates the contents of the swiftmodule files, running to a fixpoint.
Causes anything depended upon them to be marked as dirty, since right now there is no prior ModuleDepGraph.
=> [DNM Incremental] Start of cross-module incrementality

Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
The test being skipped is an unfortunate necessity given the delay in producing nightly toolchains. Once apple/swift#35741 lands we can turn this back on.
=> Fold Incremental External Dependency Nodes Into External Dependency Nodes

Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift
Now that external dependencies and incremental external dependencies are
one and the same, we need to serialize the fingerprints that may or may
not be attached to them.
=> Serialize Fingerprint Blobs For External Dependencies

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Straight-forward adaptation of:
https://github.com/apple/swift/pull/35026
=> -c with LTO should still emit bitcode

Sources/SwiftDriver/Execution/ArgsResolver.swift, Sources/SwiftDriver/Jobs/CommandLineArguments.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/ReplJob.swift, Sources/SwiftDriverExecution/SwiftDriverExecutor.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Introduce a new Job.ArgTemplate case which represents "squashed" arguments, so we can represent the structure of LLDB's --repl= argument and resolve the args which will be used to configure the frontend before concatenating them. The old behavior wasn't causing too many problems in practice, but this should make it easier to eventually launch the REPL as the last step in a multi-job build plan.
Also, this PR shell escapes arguments when printing jobs with -###, matching the behavior of the old driver
=> Ensure REPL arguments are processed by the ArgsResolver

Sources/SwiftDriver/Execution/ArgsResolver.swift, Sources/SwiftDriver/Jobs/CommandLineArguments.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/ReplJob.swift, Sources/SwiftDriverExecution/SwiftDriverExecutor.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#451
This breaks SwiftPM:
https://ci.swift.org/job/swift-package-manager-self-hosted-Linux-smoke-test/1489/
=> Revert "Ensure REPL arguments are processed by the ArgsResolver"

Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/KeyAndFingerprintEnforcer.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/NodeFinder.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Lots of restructuring; passes the lit tests.
=> [Incremental] Next step towards cross-module incremental dependencies

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift
The refactoring of the incremental compilation state class is in three pieces:
1) Formalize the type of the InitialState computed by the initializer
2) Internalize computeModuleDependencyGraph and instead make a unified computeInitialState entrypoint (we'll need this for testing later)
3) Divide the status quo and cross-module initial state computations. There is no change to the status quo outside of the breakup of Driver.getBuildInfo
The cross-module path is slightly different than the status quo. For one, the incremental build need not fail entirely when either the build record or dependency graph cannot be read. In fact, it is a requirement that the incremental build proceed but schedule every single input file to rebuild, otherwise we won't have a module dependency graph to …
=> Read and Write The Driver's Dependency Graph For Cross-Module Builds

Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift, Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
There are going to be a lot of them, and they are not currently used much in the driver and creating this many `VirtualPath` objects is very expensive.
https://github.com/apple/swift-driver/pull/437 got a bit overzealous.
=> [Dependency Scanning] Do not decode `sourceFiles` fileds of the inter-module dependency graph into VirtualPaths

Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Otherwise, this test crashes when it calls `getDependencies`. With this change I can run the whole test suite using the frontend fallback.
=> XCTFail a dependency scanner test which relies on libSwiftScan if it can't be found

Sources/SwiftDriver/Execution/ArgsResolver.swift, Sources/SwiftDriver/Jobs/CommandLineArguments.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/ReplJob.swift, Sources/SwiftDriverExecution/SwiftDriverExecutor.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This reverts commit e807fdcbd5add1ba41b8e6d9800da248d7556f69.
It also brings back `[Job.ArgTemplate].joinedArguments` as a deprecated property forwarding to the renamed `joinedUnresolvedArguments`, to avoid breaking SwiftPM.
=> Reapply "Ensure REPL arguments are processed by the ArgsResolver"

Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
These .PCM filenames are computed as `moduleName` + `hash(PCMArgs)`, using SHA256, in `targetEncodedClangModuleName`.
Avoid re-computing this filename for every direct and transitive depending module by caching the computed hashed names.
=> [Explciti Module Builds] Cache the computation of Clang module dependency PCM names.

Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is the behavior of the C++ driver and we should preserve it.
rdar://74127445
=> Indexing: include index file entry in supplementary output file map

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
- include swiftDeps without output file map
- diagnose multiple files with same name
TODO
=> Fix Driver/driver-compile.swift

Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/NodeFinder.swift, Sources/SwiftDriver/IncrementalCompilation/Multidictionary.swift
- Clean up subscripting so accessing one-past-the-end indices is no longer possible
- Make the interface for Multidictionary more closely align to either Dictionary or Set
- Document everything
This PR should be NFC, but we'll see if anything was relying on the old subscript order.
=> Clean Up the MultiDictionary Interface

Sources/SwiftDriver/IncrementalCompilation/KeyAndFingerprintEnforcer.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Also correct a bogus assert that was firing when external dependency nodes didn't have fingerprints.
=> Re-enable Embedded Dependencies Test

Sources/CSwiftScan/include/swiftscan_header.h, Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift, Sources/SwiftDriver/SwiftScan/SwiftScan.swift, Sources/SwiftDriver/Utilities/FileType.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Building on https://github.com/apple/swift/pull/35882, make the driver aware of which swift-frontend flags its toolchain's compiler supports. 
- Add `supportedFrontendFlags` property to the Driver
- This property is computed using either:
- A `libSwiftScan` query if an instance of the library is available and supports executing such query
- A fallback mechanism that invokes `swift-frontend -emit-supported-features` 
For `libSwiftDriver`, this is critical for multiplexing library instances, and for the library's compatibility with different versions of the compiler.
Resolves rdar://73631930
=> Make the driver aware of all the flags the selected toolchain's `swift-frontend` supports.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift
And fix the `FrontendOverride::setUpForTargetInfo` to clear the overridden compiler.
This should get the compiler tests in `Driver/Dependencies` running again.
=> Use the FrontendOverride when querying the `hostTriple`.

Sources/SwiftDriver/SwiftScan/SwiftScan.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Keep `SwiftScan` internal becuase using `@spi public` combined with using an `implementationOnly` property type does not work when building with 5.3 (as SwiftPM self-hosted PR testing does).
Doing this instead of https://github.com/apple/swift-driver/pull/485.
=> Workaround a compiler error with SPI public type using `implementationOnly` properties.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift
When using swift-driver as a library, we cannot assume compiler is adjacent to the
build system executable.
=> Allow libSwiftDriver client passing down a compiler executable directory

Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Deal with erroneous file types a bit better.
=> [Incremental] Improve the interface to DependencySource

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Otherwise they deposit various build products into the package root (e.g. `main.o`, `other.o`, etc.).
=> Add -working-directory argument to incremental tests' `runDriver` routine.

Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift
A small change to keep `printPath` from crashes when nodes are integrated from swiftmodules, when we start doing cross-module dependencies.
=> [Incremental] Handle nodes imported from swiftmodules

Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift, Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Add `inputDependencySourceMap` to `ModuleDependencyGraph` serialization.
Also add map entries in `getChangesForSimulatedLoad` so that the round-trip test is testing map serialization.
=> [Incremental] Add `inputDependencySourceMap` to `ModuleDependencyGraph` serialization

Sources/swift-driver/main.swift
The underlying swift compiler isn't ready to be safely canceled yet and
interrupting them may cause red-herring build failures that pollute the build log.
rdar://74292387
=> Ignore interruption signal sent from the build system

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/IncrementalCompilation/BidirectionalMap.swift, Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/InitialStateComputer.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/NodeFinder.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift, Sources/SwiftDriver/IncrementalCompilation/Multidictionary.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift, Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
After thinking about strategies, here is a rough cut, unfinished. It passes the XC tests locally, and I want to see if it will pass on CI.
I have yet to test it with the legacy lit tests, nor test how it works for incremental, cross-module builds.
And there are #warnings, where it needs more work.
EDIT: Now passes lit tests
EDIT: I think it might be ready for landing, modulo what is found by a review.
=> [Incremental] Support reading priors and incremental external dependencies.

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
=> [Incremental, NFC] use reduce(into:) {} where reasonable

Sources/SwiftDriver/IncrementalCompilation/BidirectionalMap.swift, Sources/SwiftDriver/IncrementalCompilation/InitialStateComputer.swift
In some cases, some versions of the compiler cannot cope with `if let foo = foo`. So just rename the variables in the problematic cases.
=> [NFC] Workaround compiler issue by renaming some optionals

Sources/swift-driver/main.swift
This should help distinguish cases where the driver invocation was interrupted by the client (e.g. a build system) vs. exited with a failure on its own.
=> Emit a remark on interrupt of the driver

Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftOptions/Options.swift, Sources/makeOptions/makeOptions.cpp
This commit adds support for the `-access-notes-path`, `-emit-symbol-graph`, and `-emit-symbol-graph-dir` flags to the new driver.
I have also updated Options.swift; I *think* I've handled all of the new options that can be passed into the driver, but I'd like a second pair of eyes to confirm that.
Note that the symbol graph tests still don't pass because of an issue with the frontend's handling of the `-emit-symbol-graph-dir` flag; I've filed rdar://74418885 about that.
No new tests because I couldn't find anywhere that similar passthrough flags were being tested in the driver. If I've missed something, please let me know.
=> Add support for symbol graphs and access notes

Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
This library is unavailable in some contexts and on some architectures. For now, let's have the `swift-frontend -emit-supported-features` flow be the default.
=> Default to swift-frontend for querying supported frontend flags

Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/NodeFinder.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
When integrating a node where the only change is its fingerprint, it's critical to set the fingerprint of the integrated-to node on the module dependency graph to match the node being integrated. That way, if its fingerprint changes back and it gets integrated again, the change will be noticed. 
The above was not happening. This PR adds a test case, fixes the bug, adds a nice `description` to source file dependency nodes (to aid in debugging), and also adds a check to ensure that a graph is serializable.
=> [Incremental] Fix fingerprint integration bug, add a test, and add debugging affordances.

Sources/SwiftDriverExecution/MultiJobExecutor.swift, Sources/swift-driver/main.swift
We need to ensure that we terminate (SIGINT) the running compiler processes without emitting an error that those processes got terminated, and allow the driver to continue execution so that it is able to emit parseable-output which communicates that the terminated compiler jobs were interrupted. 
Resolves rdar://74527749
=> Interrupt handler: terminate (SIGINT) running compiler processes and allow the driver to exit gracefully.

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Sources/SwiftDriver/IncrementalCompilation/DependencyGraphDotFileWriter.swift, Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/InitialStateComputer.swift, Sources/SwiftDriver/IncrementalCompilation/KeyAndFingerprintHolder.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Add capability to write dot files for source file- and module- dependency graphs. It's a debugging facility for the incremental work. (`-driver-emit-fine-grained-dependency-dot-file-after-every-import`)
=> [Incremental] Add writing dependency dot files

Sources/SwiftDriver/IncrementalCompilation/DependencyGraphDotFileWriter.swift, Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift
When printing out swiftdeps and swiftmodules for the debugging remarks and in the dot graphs, just use the basename of the swiftdeps and the parent-directory of the swiftmodules. (Because every swiftmodule has the same basename, the parent carries the info.)
Also, get the source name for a `SourceFileDependencyGraph` from its `DependencySource`, which is statically guaranteed to be present.
=> [Incremental] Improve printing for debugging

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/IncrementalCompilation/DirectAndTransitiveCollections.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/InitialStateComputer.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Suggest reviewing commit-by-commit:
1. Adds a test
2. Simplifies integration logic by using a `phase` variable in the `ModuleDependencyGraph`
3. Introduces wrappers for sets and arrays in order to use the type system to enforce the transitive closing where needed.
Your feedback is sought!
=> [Incremental] Simplify integration logic using a phase concept & Use wrapper types

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
=> Incremental: ensure we add post-compile jobs if no new compile jobs are found

Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Fix two issue observed with early adopters of `-experimental-emit-module-separately`:
- Pass on the `-parse-as-library` flag to the frontend avoiding considering single file target as a script. rdar://74713625
- Ignore the flag in whole-module builds leaving it to the single job to generate the module files.
=> Emit-module separately: fix use with -emit-library and -whole-module-optimization

Tests/SwiftDriverTests/IntegrationTests.swift
The lit tests in the integration suite aren't run by default—this marks all of the failing ones as skipped so that it will be safe to make integration testing default for CI.
=> [Integration Tests] Skip currently-failing lit tests

Utilities/build-script-helper.py
This will enable the swift build-script test runs to get a more complete run—"enable integration tests" seems in-line with the scope of other projects test runs.
=> Enable integration tests in build-script-helper.py

Sources/SwiftDriverExecution/MultiJobExecutor.swift
`executeJob` itself runs in a concurrent context.
Adding further asynchrony in emitting parseable-output here isn't worth the trouble it can cause because the performance implications of waiting for these messages to be emitted are likely negligible.
Blocking on calls to `jobStarted` and `jobFinished` defines away various possibilities for error states, for example - the executor concluding its workload and returning before all parseable-output messages have been emitted, potentially confusing the build system in the process.
Resolves rdar://74058113
=> Block on emitting parseable-output messages in `executeJob`.

Tests/SwiftDriverTests/Helpers/OutputFileMapCreator.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
In preparation for adding new incremental import tests, pull out `OutputFileMapCreator`. Also some reordering of `IncrementalCompilationTests`.
=> [Incremental] Reorder IncrementalCompilationTests and extract OutputFileMapCreator

Tests/SwiftDriverTests/IntegrationTests.swift
Previously the swiftRootDir would be calculated by taking `swiftBuildDir/../../..`, which is accurate on most developer machines, but it is not accurate for some CI bots that use one fewer layer of directories. We already know the `swiftRootDir` more accurately, we're using it for calculating relative paths, just use that one.
=> [Integration Tests] Calculate the swiftRootDir more accurately

TestInputs/ExplicitModuleBuilds/CHeaders/G.h, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
There is an intermittent failure of this test where the order of batch scanning entries affects scanning result.
Temporarily make this test not need this behavior, while we address the issue in the dependency scanner.
=> Tweak test relying on versioned clang module re-scanning to not need it.

Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftOptions/Options.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Now that cross-module incremental builds are controlled by -{enable,disable}-incremental-imports, resync the options and teach merge-modules to propagate the disable flag.
rdar://74363450
=> Re-Sync Options Flags

Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Utilities/FileType.swift, Sources/SwiftOptions/Options.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
The frontend supports this via new options -index-unit-output-path and -index-unit-output-path-filelist that mirror -o and -output-filelist. These are intended to allow sharing index data across builds in separate directories (so different -o values) that are otherwise equivalent as far as the index data is concerned (e.g. an ASAN build and a non-ASAN build) by supplying the same -index-unit-output-path for both.
This change updates the driver to add these new options to the frontend invocation 1) when a new "index-unit-output-path" entry is specified for one or more input files in the -output-file-map json or 2) when -index-file is specified (guaranteeing a single primary input) and a new -index-unit-output-path driver option is passed.
Equivalent change for the old driver here: …
=> Add driver support to specify an overriding output path to record in the index data

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/Job.swift
"Display inputs" are used to convey to the user/client the set of input files that a given compile job will build, e.g. in parseable-output.
The driver is relying on the presence of the bridging PCH in `displayInputs` because the `printActions` code relies on `displayInputs`, when they are present. Unlike parseable-output, action printing is used for compiler debugging purposes only, and given that `printActions` is a best-effort emulation of the legacy driver behavior that doesn't really exist in the new driver, we can just as well get away with using `primaryInputs` and ensure `compile` job actions refer to the corresponding precompiled header, to keep the C++ tests passing (`test/Driver/actions.swift` & `test/Driver/actions-dsym.swift`).
=> Do not add precompiled bridging header to a Compile job's display inputs

TestInputs/ExplicitModuleBuilds/CHeaders/G.h, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This reverts commit b2ac19551894dbd905fd0c68ea2b3dd429ea8977.
The underlying Dependency Scanner is fixed in: https://github.com/apple/swift/pull/36294
We will need to wait for that PR to make it to a toolchain snapshot before merging this.
=> Revert "Tweak test relying on versioned clang module re-scanning to not need it."

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Its usage was removed in the SwiftPM Client a while back:
https://github.com/apple/swift-package-manager/pull/3042
=> Remove deprecated `externalBuildArtifacts` API.

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Reverts apple/swift-driver#529
This seems to have caused failures in SwiftPM Linux CI, 
e.g.: https://github.com/apple/swift-package-manager/pull/3338
=> Revert "Remove deprecated `externalBuildArtifacts` API."

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift
After this change, we now have three rules: (a) ExecuteJobRule, (b) ExecuteAllJobsRule and (c) ExecuteAllCompilationJobsRule. The start callback of (c) requests all mandatory compilations via (a). The provideInput callback of (c) synchronously requests additional incremental build jobs by requesting more (a) as inputs. (b) requests (c) as the only input and runs post-compilation jobs after the only input is ready.
This refactoring allows us to (1) avoid requesting new inputs asynchronously, which may lead to race condition; and (2) avoid keeping track of a LLTaskBuildEngine instance in the context.
=> llbuild: refactor llbuild rules in MultiJobExecutor

Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
Playing a hunch to fix a performance issue. 
rdar://75351845
=> [Incremental] Try a cache for external dependency mod times

Tests/IncrementalImportTests/AddFuncInImportedExtensionTest.swift, Tests/IncrementalImportTests/HideAndShowFuncInStructAndExtensionTest.swift, Tests/IncrementalImportTests/RenameMemberOfImportedStructTest.swift, Tests/IncrementalImportTests/SpecificFuncAdditionInExtensionWithinModuleTest.swift, Tests/IncrementalTestFramework/AddOn.swift, Tests/IncrementalTestFramework/Context.swift, Tests/IncrementalTestFramework/Expectation.swift, Tests/IncrementalTestFramework/ExpectedCompilations.swift, Tests/IncrementalTestFramework/ExpectedProcessResult.swift, Tests/IncrementalTestFramework/IncrementalTest.swift, Tests/IncrementalTestFramework/Module.swift, Tests/IncrementalTestFramework/Source.swift, Tests/IncrementalTestFramework/Step.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Allow a test to specify an expectation for the stdout, stderr, and error codes. Add such a check to two of the tests.
=> [Incremental] Add a check of the result of running the built app to the `IncrementalTestFramework`

Tests/IncrementalImportTests/Antisymmetry.swift, Tests/IncrementalImportTests/Transitivity.swift, Tests/IncrementalTestFramework/Context.swift, Tests/IncrementalTestFramework/IncrementalTest.swift, Tests/IncrementalTestFramework/Module.swift, Tests/TestUtilities/OutputFileMapCreator.swift
Add some more tests, and touch up some of the internals of the test framework.
=> Some Improvements to Cross-Module Incremental Build Testing

Utilities/build-script-helper.py
[Change analagous to: https://github.com/apple/swift-package-manager/pull/3363]
With the version-bump of Yams in apple/swift#36366, Yams 4.0.2 now actually expresses the dependency on Dispatch in its CMake config.
With the current behavior of passing `-Ddispatch_DIR` to its CMake build, we have the following problem on Linux:
- swift's `build-script` installs Dispatch into a just-built toolchain which we use to build swift-driver, which will contain, among other things, the Dispatch `.swiftmodule`.
- The compiler workspace checkout of swift-corelibs-libdispatch also contains a copy of the Dispatch `.swiftmodule`.
Both of these will be found, leading to build failures like:
```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-nightly-install/usr/lib/swift/dispatch/module.m …
```
=> [Build Script Helper] Do not pass `-Ddispatch_DIR` to the Yams CMake build

Sources/SwiftDriver/Jobs/CompileJob.swift
Unfortunately, (Typed)VirtualPath's Hashable conformance is wildly expensive to the point that constructing and searching a hashed collection is much more expensive than a linear scan. Preliminary tests show a factor of 4 improvement here by switching to a linear scan for large workloads.
While I'm here, avoid materializing the filtered collection of input files and just use a loop condition. This saves an enormous amount of transient memory during the planning step.
=> Use an Array When Computing Primary Inputs

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Utilities/System.swift
These are not compile blockers, but it makes sense to set these anyway.
=> Add some directives to enable OpenBSD support.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift
The overhead from Foundation is around 10x due to the fact that it has
to do the syscall, allocate a dictionary, convert all the entries, then
bridge the whole enchilada back to Swift.
For a 1000 file incremental build, 40 seconds of overhead was removed from build
execution.
=> Use Our Own Stat for Mod Times

Sources/SwiftDriver/IncrementalCompilation/DependencyGraphDotFileWriter.swift, Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Delay converting external dependency file names to paths as an optimization. For example, on a clean build, the external dependency names might never have to be used as paths; but this PR may not go quite that far. Still more than doubles the speed I measured in a no-priors build.
=> [Incremental] Delay converting external dependency file names to paths as an optimization.

Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift
Creating in-memory collections that are derived from the set of input files is potentially expensive for large compilations.
=> [Perf] Drop Some Places We Re-Materialize Input Files

Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/NodeFinder.swift
What should have always been an assertion is now an assertion.
=> [Incremental, Optimization] Only verifyUseIsOK in a debug build.

Sources/SwiftDriver/IncrementalCompilation/InitialStateComputer.swift
If the prior graph gets corrupted, or we change the format, the driver needs to recover from reading a malformed one by writing a good one. By remaining in incremental mode, this change will do that.
=> [Incremental] Recover better from malformed prior ModuleDependencyGraph

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
Public API was changed in edd0ee6 but needs to be maintained for compatibility.
ProcessResult will not be used in function body.
rdar://75650542
=> Maintain previously changed public API

Sources/SwiftDriver/Utilities/VirtualPath.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift, Tests/SwiftDriverTests/JobExecutorTests.swift
Also deduplicate them while we're at it. We don't need to ask each job for its input set, we just need to check the same set of files we recorded mod times for in the first place. This saves a quadratic amount of disk I/O and syscalls in the incremental and non-batch builds, which can be a huge wall time savings for large compiles.
In the incremental stress test, 15 seconds are just gone from total wall time. Total user time spent in stating files went from 7 seconds to 20 milliseconds!
=> Perform Input Modification Checks At the End of the Build

TestInputs/ExplicitModuleBuilds/Swift/G.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/Swift.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/SwiftOnoneSupport.swiftinterface, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Make sure we always find the stdlib on Darwin, and use custom "fake" interfaces for stdlib and OnoneSupport in the dependency scanning test.
=> [Test] Harden Explicit Module Build test

Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Port of this PR: https://github.com/apple/swift/pull/36356
=> Use library search group when linking statically

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftOptions/ExtraOptions.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift
=> Add an option that causes individual `swift-frontend` invocations to emit parseable output, instead of the driver.

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/IntegrationTests.swift
Also provides an escape hatch to invoke with the system default (just launching `lit.py` as a standalone script executable)
LLVM is transitioning its script infrastructure to python3 and we may run into issues if we continue using the system-default python2 on some platforms.
Resolves rdar://75848017
=> [Integrated Tests] Invoke `lit.py` using python3

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Sources/SwiftDriver/Execution/ParsableOutput.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Job.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift
We have, historically, treated batch mode as an implementation detail of the compiler. As a consequence, we have been lying to clients of parsable-output by emitting multiple `began`, `finished`, `signalled` messages for each batch job - one message per primary input. The time has come to teach swift-driver to tell the same old lies. 
Emulating existing C++ driver behavior:
- Cargo-cult the concept of a `quasiPID`
(https://github.com/apple/swift/blob/main/include/swift/Basic/ParseableOutput.h#L36)
- Break up one compile job with multiple primaries into multiple `[Began|Finished|Signalled]Message` messages
- Collect `((job, primaryInput) -> quasiPID)` information to generate correct `Finished` messages
- Fixup individual command lines of each `Began` message (w.r.t. `-o` and …
=> [Parsable Output] Break down batch compile jobs into constituent messages

Sources/SwiftDriver/SwiftScan/SwiftScan.swift
Otherwise some building compilers will see errors:
```
error: value of optional type 'UnsafeMutablePointer<CChar>?' (aka 'Optional<UnsafeMutablePointer<Int8>>') must be unwrapped to a value of type 'UnsafeMutablePointer<CChar>' (aka 'UnsafeMutablePointer<Int8>')
for ptr in cstrings { free(ptr) }
```
=> Add `free()` workaround that causes error when built with some compiler versions.

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
This class is serendipitously used only from the main queue for the
Driver's usual use cases. But we have no reason to expect clients of
libSwiftDriver to manipulate this class in the same manner. Provide a serial
confinement queue and protect the mutable members of
IncrementalCompilationState with it.
In the future, we ought to drop the queue and use actors.
rdar://75744005
=> Use a Confinement Queue to Protect IncrementalCompilationState

Sources/SwiftDriver/Jobs/GenerateDSYMJob.swift, Sources/SwiftDriver/Jobs/LinkJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Instead of taking the input file and replacing its extension with `.dSYM`.
This change causes the behavior to match what the C++ driver does and what LLDB expects.
Resolves rdar://76073797
=> Set dsym-job's output to be the primary output file + `.dSYM`

Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
And said input matches the expected output path.
Otherwise both the `.compile` and the `.mergeModule` jobs have an identical output:
`.temporary(<module_name>.swiftmodule)` which will trigger a fatal error in the MultiJobExecutor because it may cause LLBuild cycles downstream.
=> [Merge Modules] Omit merge-modules job when only one input is given.

Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#577
Because we are relying on the presence of merge-modules job for emitting interface files in various contexts (only -emit-module jobs are capable of that).
=> Revert "[Merge Modules] Omit merge-modules job when only one input is given."

Sources/SwiftDriver/IncrementalCompilation/BuildRecord.swift, Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/InitialStateComputer.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift, Tests/SwiftDriverTests/Helpers/AssertDiagnostics.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/Inputs/IncrementalCompilationInputs.swift
If the merge-modules step fails or is cancelled, all the compile steps may be skipped, yet the post-compile jobs still must run.
Improve the logic that was skipping the post-compile jobs whenever there are no compile jobs.
When the compile jobs would otherwise be skipped, check their outputs against the time the previous build finished.
In order to perform the check, enhance the build record to store the end time as well as the start time of the prior build.
rdar://76127929
=> [Incremental] Skip post-compile jobs only if no compiles ran, and all the outputs are up-to-date.

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Instead of locating it in the current toolchain that the driver belongs to.
This will match the behaviour in the legacy driver:
https://github.com/apple/swift/blob/main/lib/Driver/DarwinToolChains.cpp#L287
Resolves rdar://76035286
=> Locate "arclite" library relative to the Clang in the active Xcode

Utilities/build-script-helper.py
When used, we mostly just need to be aware that the build is in a single-target mode and to simplify where the build products are placed, so that they are easier to find from the compiler's `build-script`.
This will be used from swift's `build-script` to always build an instance of `swift-driver` using a host toolchain, in order to patch the `swift` build directory with the new driver.
=> [Build Script Helper] Add an option that indicates the driver is being built for use with a local just-built frontend

Sources/SwiftDriver/Jobs/VerifyModuleInterfaceJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Otherwise, today, we are always emitting these serialized diagnostic files incorrectly.
We use either:
- `ModuleName` + `.dia` for both plain and private module interfaces (which is wrong because we have multiple producers of an identical file).
- `InterfaceFileBasename` + `.dia` for both plain and private module interfaces (which is wrong for the plain interface, for example, because it may conflict with a compile job emitting an identically-named `.dia` file).
Looking at the legacy driver, we don't actually emit these most of the time, even when `-serialize-diagnostics` is specified on the invocation, because that refers to the overall build, not the verification. Which leads me to believe there aren't any consumers for these specific serialized diagnostics.
Resolves rdar://76122268
=> Only output serialized diagnostics for verify jobs if explicitly requested in the output file map

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift, Sources/SwiftDriver/Jobs/BackendJob.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/GeneratePCHJob.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift, Tests/TestUtilities/Fixture.swift, Tests/TestUtilities/TemporaryFileMatching.swift
This PR augments `VirtualPath` with an ability to create a temporary file that is unique a given driver execution context: `createUniqueTemporaryFile`. i.e. if a temporary file with the same filename as one being requested has been created before, using this API, then the newly-created file will have a suffix appended to the base name to distinguish it.
This brings swift-driver closer to the legacy driver's behavior, which generates unique temporary files by-default, using LLVM's `llvm::sys::fs::createTemporaryFile`.
Doing so is necessary to resolve several kinds of problems, for example: 
Compiling a module `Foo` consisting of two source files `Foo.swift` and `Bar.swift` will result in a temporary partial module `Foo.swiftmodule` being produced from building `Foo.swift` and a full …
=> Use unique temporary file names

Package.swift, Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Utilities/Triple.swift, Sources/swift-build-sdk-interfaces/main.swift, TestInputs/mock-sdk.sdk/SDKSettings.json, TestInputs/mock-sdk.sdk/usr/lib/swift/A.swiftmodule/arm64e-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/A.swiftmodule/x86_64-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/E.swiftmodule/arm64e-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/E.swiftmodule/x86_64-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/F.swiftmodule/arm64e-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/F.swiftmodule/x86_64-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/G.swiftmodule/arm64e-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/G.swiftmodule/x86_64-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/H.swiftmodule/arm64e-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/H.swiftmodule/x86_64-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/Swift.swiftmodule/arm64e-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/Swift.swiftmodule/x86_64-apple-macos.swiftinterface, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This PR is an implementation of swift_build_sdk_interfaces.py using
libSwiftDriver. The tool is used to traverse an entire SDK to find
Swift interface files and to generate prebuilt module cache for each one
of them. Comparing to the python implementation, this implementation generates
the prebuilt modules in the dependency order so that:
(1) It's more performant than the python counterpart. Several preliminary
experiments showed an average of 40% less CPU time spent on generating modules in an SDK.
(2) It fails fast. If an interface is broken in the SDK, this new implementation
won't schedule jobs for building other modules depending on this interface. It should help us avoid
issues like rdar://76201633
=> Implement swift_build_sdk_interfaces.py using libSwiftDriver

Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift, Sources/swift-build-sdk-interfaces/main.swift, TestInputs/mock-sdk.sdk/usr/lib/swift/F.swiftmodule/arm64-apple-macos.swiftinterface, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Prebuit modules of arm64e interfaces can be loaded to help building arm64 interfaces.
=> PrebuiltModuleGen: Allow arm64 interfaces to depend on arm64e interfaces

Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/IntegrationTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift
The following tests currently fail on Apple Silicon:
```
testDarwinBasic
testSaveTemps
testPrebuiltModuleGenerationJobs
testLitDriverDependenciesTests
```
e.g. https://ci.swift.org/job/oss-swift-incremental-RA-macos-apple-silicon/433/consoleText
For the most part, the test code just does not account for the fact that macOS can run on anything other than x86. 
These tests are going to be disabled on Apple Silicon for the time being to unblock CI, while we go and fix the test code.
=> Temporarily disable tests that fail on Apple Silicon CI.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift
A mitigation to rdar://76359678.
If the write fails, import incrementality is lost, but it is not a fatal error.
@CodaFi , what do you think?
=> [Incremental] Only warn if cannot write prior module dependencies, and print more error info

Package.resolved, Sources/SwiftDriver/Execution/ProcessProtocol.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift, Sources/SwiftDriverExecution/SwiftDriverExecutor.swift, Tests/SwiftDriverTests/JobExecutorTests.swift
This change uses `Process` input handling added in https://github.com/apple/swift-tools-support-core/pull/208 to allow forwarding of the driver's Standard Input to a frontend job.
Resolves rdar://76454784
=> Add support for compile jobs that read source input from standard input.

Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift, Sources/swift-build-sdk-interfaces/main.swift
Foundation failures can lead to noticeable slowness in compilation, so we should
consider them critical.
=> PrebuiltModuleGen: consider failures of Foundation and anything below critical

Sources/SwiftDriver/Driver/Driver.swift
SwiftPM needs this to check what compiler flags are available.
Currently it is possible to use a version of SwiftPM, `5.5`, that attempts to use flags that do not currently exist on any publicly available version of `swiftc`
=> Expose supportedFrontendFlags

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift, Sources/SwiftDriver/Utilities/Diagnostics.swift, Sources/SwiftDriver/Utilities/Triple+Platforms.swift, TestInputs/SDKChecks/MacOSX10.10.sdk/SDKSettings.json, TestInputs/SDKChecks/MacOSX10.11.sdk/SDKSettings.json, TestInputs/SDKChecks/MacOSX10.14.Internal.sdk/SDKSettings.json, TestInputs/SDKChecks/MacOSX10.15.4.sdk/SDKSettings.json, TestInputs/SDKChecks/MacOSX10.15.Internal.sdk/SDKSettings.json, TestInputs/SDKChecks/MacOSX10.15.sdk/SDKSettings.json, TestInputs/SDKChecks/MacOSX10.8.sdk/SDKSettings.json, TestInputs/SDKChecks/MacOSX10.9.sdk/SDKSettings.json, TestInputs/SDKChecks/MacOSX7.17.sdk/SDKSettings.json, TestInputs/SDKChecks/iPhoneOS.sdk/SDKSettings.json, TestInputs/SDKChecks/iPhoneOS12.99.sdk/SDKSettings.json, TestInputs/SDKChecks/iPhoneOS13.0.sdk/SDKSettings.json, TestInputs/SDKChecks/iPhoneOS7.sdk/SDKSettings.json, TestInputs/SDKChecks/tvOS.sdk/SDKSettings.json, TestInputs/SDKChecks/tvOS13.0.sdk/SDKSettings.json, TestInputs/SDKChecks/tvOS8.0.sdk/SDKSettings.json, TestInputs/SDKChecks/watchOS.sdk/SDKSettings.json, TestInputs/SDKChecks/watchOS2.0.sdk/SDKSettings.json, TestInputs/SDKChecks/watchOS3.0.Internal.sdk/SDKSettings.json, TestInputs/SDKChecks/watchOS3.0.sdk/SDKSettings.json, TestInputs/SDKChecks/watchOS6.0.sdk/SDKSettings.json, Tests/SwiftDriverTests/SwiftDriverTests.swift
=> Attempt to diagnose arguments to `-sdk` that point to unsupported SDKs

TestInputs/ExplicitModuleBuilds/Swift/G.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/Swift.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/SwiftOnoneSupport.swiftinterface
This explicit specifier causes these modules to get built for `x86_64` even on `Apple Silicon` hosts:
e.g. https://ci.swift.org/job/oss-swift-incremental-RA-macos-apple-silicon/490/console
=> Remove target `x86_64` specialization from `testExplicitModuleBuildEndToEnd`

Sources/SwiftDriver/Driver/Driver.swift
5.3 and ealier compilers may hit:
```
swift-driver/Sources/SwiftDriver/Driver/Driver.swift:2044:15: error: definition conflicts with previous value
guard let sdkInfo = sdkInfo else {
```
e.g.
https://ci.swift.org/job/swift-PR-toolchain-osx/949/console
=> Update `isSDKTooOld` to be compatible with older compilers.

Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Verify interfaces generated by single compile jobs and emit-module jobs. The verify job was previously only added after merge-module jobs which is more prone to generate broken swift interfaces.
=> Verify module interfaces generated from emit-module jobs

Sources/SwiftDriver/Jobs/Planning.swift
SwiftCI is using a 5.3 compiler and errors out on trying to build this code with:
```
swift-driver/Sources/SwiftDriver/Jobs/Planning.swift:188:31: error: variable used within its own initial value
let emitModuleJob = try emitModuleJob()
```
=> Small fix to `emitModuleJob` for compatibility with <=5.3 compilers.

TestInputs/mock-sdk.sdk/usr/lib/swift/A.swiftmodule/arm64-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/E.swiftmodule/arm64-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/G.swiftmodule/arm64-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/H.swiftmodule/arm64-apple-macos.swiftinterface, TestInputs/mock-sdk.sdk/usr/lib/swift/Swift.swiftmodule/arm64-apple-macos.swiftinterface, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift
https://github.com/apple/swift-driver/pull/599 and https://github.com/apple/swift-driver/pull/602 disabled the following tests:
- `testDarwinBasic`
- `testSaveTemps`
- `testInputForwarding`
- `testPrebuiltModuleGenerationJobs`
This PR generalizes those tests to be agnostic to the macOS architecture and re-enables them on Apple Silicon. 
The only remaining Apple Silicon-disabled test after this is:
- `testLitDriverDependenciesTests `
=> Generalize disabled tests to also work on Apple Silicon 

Tests/SwiftDriverTests/IntegrationTests.swift
This test was previously failing in `swift` CI.
I cannot trigger the failure locally so re-enabling here to test with cross-repository PR testing.
=> Re-enable `testLitDriverDependenciesTests` when run on Apple Silicon

Tests/SwiftDriverTests/IntegrationTests.swift
As part of rdar://76815547, i want to make sure the symbol-graph's integration into the frontend is properly flexed with both the old driver and the new driver.
=> test SymbolGraph/EmitWhileBuilding when a lit dir is available

CMakeLists.txt
There are several key livability fixes in 3.17 for building Swift code.
This should prevent scenarios like this:
https://github.com/apple/swift/pull/37114
Where CMake `<3.17` missed setting up rpaths on the `swift-driver` executable.
=> Bump required CMake version to 3.17

CMakeLists.txt
Reverts apple/swift-driver#624
This is breaking many Linux bots as they only have CMake 3.16.5. Reverting until the bots are updated.
rdar://77440032
=> Revert "Bump required CMake version to 3.17"

Package.resolved, Package.swift
Will open corresponding PRs for SwiftPM and SourceKit-LSP.
=> Bump swift-argument-parser to 0.4.1

Package.swift
This switches the branch dependencies for `swift-tools-support-core` and `swift-llbuild`, as we do for every release branch.  This is needed in order for SwiftPM to make the switch (since it has a dependency on `swift-driver`).
=> [5.5] Change branch dependencies on TSC and LLBuild from `main` to `release/5.5`

Sources/swift-help/main.swift
Currently, running `swift help package` (when the `swift-help` from this package is installed) prints the help screen for the `swift package` command. However, subcommands and sub-subcommands are not accessible:
```
$ swift help package clean
Error: Unexpected argument 'clean'
Usage: swift-help [<topic>] [-show-hidden]
See 'swift-help --help' for more information.
```
This adds an array that captures additional subcommands and passes them along to the matched command:
```
$ swift help package clean
OVERVIEW: Delete build artifacts
USAGE: swift package clean [<options>] --enable-index-store
OPTIONS:
-Xcc <Xcc>              Pass flag through to all C compiler invocations 
-Xswiftc <Xswiftc>      Pass flag through to all Swift compiler invocations 
-Xlinker <Xlinker>      Pass flag through …
```
=> Support subcommands when querying for help

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Normally the inputDependencySourceMap bidirectionally maps .swift files to .swiftdeps files. However, we have seen failures when no .swift file can be found, from issues reading the prior module dependency graph. Instead of crashing, fall back to a non-incremental build.
Also adds a test to ensure that after such a fall-back, the next build will work incrementally.
=> [Incremental] Gracefully recover from when an input cannot be found in the inputDependencySourceMap.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/InitialStateComputer.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
rdar://76284047
1. Recover from a missing inputSourceDependency map entry with a clean build.
2. Add a test for this.
=> [5.5][Incremental Imports] Recover from input map failure

Sources/swift-driver/CMakeLists.txt, Sources/swift-help/CMakeLists.txt
Some time between CMake 3.16 and 3.17 the default behaviour seems to have changed as follows:
For a project which will build an executable, e.g.:
```
add_executable(exe_target
main.swift)
target_link_libraries(exe_target PUBLIC
libA
libB)
```
In 3.17, the invocation command to create the `exe_target` executable includes `-Xlinker -rpath -Xlinkier <libA_path/lib>` and so forth for the linked libraries and their dependencies.
In 3.16, the linker is not passed the rpath flags, so the executable ends up without the `LC_RPATH` required for it to run.
This affects executable targets only, libraries do still have rpaths propagated correctly.
The correct solution (which will hopefully happen soon) is to bump the compiler's minimum CMake version to 3.18.
This is under discussion now here: …
=> Add workaround for building executables with older CMake versions.

Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Otherwise using it on Darwin does not error out early and results in really confusing errors downstream in compilation. 
Resolves rdar://77631444
=> Validate that `-static-executable` is not supported on Darwin.

Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
When trying to figure out why an incremental build is taking too long, one needs information about compilation resulting from external dependencies. This PR adds that information to what is shown when `-driver-show-incremental` set.
Otherwise, there is no functional change.
=> [5.5][Incremental Imports] Print more info about externals when setting -driver-show-incremental

Sources/swift-driver/CMakeLists.txt, Sources/swift-help/CMakeLists.txt
The `-rpath` linker options are not portable and persist into
installation providing an attack vector.  This uses CMake to control the
RPATH for testing and ensures that the paths are erased at install time.
This is more secure and portable.
=> use `BUILD_RPATH` to make the build more portable

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/IntegrationTests.swift
Fixes the issues I was running into: https://forums.swift.org/t/lots-of-errors-running-swift-driver-integration-tests/47986
Still 90 failing tests, which is more than the 50 from March 27: https://github.com/apple/swift-driver/pull/365/commits/dadb0a3707f979dedd72d984bbd6b21dea33829d
A lot of Dependencies tests failing with similar looking errors, but first step is actually being able to run the tests :)
This is an example error snippet if anyone is curious:
```
8: Failed to read dependency file
check:12'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
9: Traceback (most recent call last):
check:12'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10:  File "SOURCE_DIR/test/Driver/Dependencies/Inputs/update-dependencies.py", line 53, in <module>
check:12'0 …
```
=> Provide swift-frontend path when running integration tests

Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Passing them in without a `-Xlinker` prefix argument is not valid when invoking the linker using the clang executable as `clang -fuse-ld=gold`. We still need to use the prefix to make sure clang forwards them to the underlying linker invocation.
=> Pass down `-Xlinker` flags to the underlying clang linker call using `-Xlinker`

Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is a cherry-pick of the change merged in: https://github.com/apple/swift-driver/pull/635 on `main`. 
Resolves rdar://77631444
=> [5.5] Validate that `-static-executable` is not supported on Darwin.

Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Passing them in as-is is not valid when invoking the linker using the clang executable as `clang -fuse-ld=gold`.
This is a 5.5 cherry-pick of a change merged on `main` in: https://github.com/apple/swift-driver/pull/644
=> [5.5] Pass down `-Xlinker` flags to the underlying clang linker call using `-Xlinker` prefix

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
port validation for `-sanitize-recover` over from the c swift driver
rdar://77619051
=> [rdar://77619051] implement sanitize-recover validation

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
port over validation from c swift driver instead of relying on frontend
rdar://77619161
=> implmement validation for -sanitize-address-use-odr-indicator

Sources/SwiftDriver/IncrementalCompilation/DictionaryOfDictionaries.swift, Sources/SwiftDriver/IncrementalCompilation/TwoDMap.swift
Cherry pick #654 
----------------
DictioanryOfDictionaries implemented its subscript in terms of updateValue
and removeValue, both of which keep track of and return the old value, and then
threw away the old value.
Instead, flip it so removeValue and updateValue are implemented in terms of the
subscript, and make the subscript modify the dictionary in-place.
This ended up being a 700x speedup on an Intel Mac and a 180x speedup on an M1.
Fixes rdar://77882768
=> Fix quadratic COW copies in DictionaryOfDictionaries

Sources/SwiftDriver/Jobs/Planning.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/617
---------------------------------------------------
Some SwiftCI bots are using a 5.3 compiler and errors out on this code with:
```
swift-driver/Sources/SwiftDriver/Jobs/Planning.swift:188:31: error: variable used within its own initial value
let emitModuleJob = try emitModuleJob()
```
=> [5.5] [NFC] Small fix to `emitModuleJob` for compatibility with <=5.3 compilers.

Sources/SwiftDriver/IncrementalCompilation/TwoLevelMap.swift
Using `startIndex` of the outerDict is wrong. We go to the trouble of
searching for the first non-empty inner dictionary for a reason. We need
to use *that* index as the start instead.
=> Fix startIndex Calculation

Sources/SwiftDriver/IncrementalCompilation/BidirectionalMap.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/BidirectionalMapTests.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
The setters here were both implemented in such a way that the map would
lose the invariant that it was truly bidirectional. In particular, one
must ensure that previous mappings from keys to values were struck from
the bidirectional map before emplacing a new mapping, else the mirror
image of the mapping would retain extra entries.
In addition, document the misuse of this data structure in the driver.
The mapping from swiftdeps to swift files is a not a bijection. There
are three sources of data that can all give conflicting mappings from
swiftdeps files to swift files in particular:
1) The output file map
2) The priors
3) Swiftdeps files after the frontends have run
This means we can have at most three conflicting maps from some
swiftdeps files to some swift file. Currently, the driver …
=> Fixup Bidirectional Map

Utilities/build-script-helper.py
For now, allow `x86_64` and `arm64` fat builds, mimicking how SwiftPM builds:
https://github.com/apple/swift-package-manager/blob/main/Utilities/bootstrap#L808
Other cross-compilation flows will require more testing.
=> [Build Script Helper] Restrict cross-compilation to producing fat macOS build products

Sources/SwiftDriver/IncrementalCompilation/BidirectionalMap.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/BidirectionalMapTests.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Cherry pick #662 
------------
The setters here were both implemented in such a way that the map would
lose the invariant that it was truly bidirectional. In particular, one
must ensure that previous mappings from keys to values were struck from
the bidirectional map before emplacing a new mapping, else the mirror
image of the mapping would retain extra entries.
In addition, document the misuse of this data structure in the driver.
The mapping from swiftdeps to swift files is a not a bijection. There
are three sources of data that can all give conflicting mappings from
swiftdeps files to swift files in particular:
1) The output file map
2) The priors
3) Swiftdeps files after the frontends have run
This means we can have at most three conflicting maps from some
swiftdeps files to some …
=> [5.5] Fixup Bidirectional Map

Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftOptions/ExtraOptions.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
We want to make emit-module-separately the default incremental build mode soon. Let's first add a flag to disable it to be safe. Once emit-module-separately is the default, passing this flag will force the driver to revert to using the merge-module incremental build mode.
=> Intro a flag to disable emit-module-separately

Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Creation of a dSYM bundle for a static library is not supported.  Do not
create a job to create a dSYM bundle for a static library.
=> Driver: do not create a dSYM bundle for static archives

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
We no longer need the simulated failure path since we can reproduce this
as of #662
=> Drop the Failure Simulation Paths from the Incremental Build

Sources/SwiftDriver/Jobs/CompileJob.swift
Otherwise these jobs today have input-less parsable-output:
```
"command_executable" : "\/usr\/bin\/swift-frontend",
"inputs" : [
],
"kind" : "began",
```
Resolves rdar://78321174
=> In WMO, treat all inputs as `displayInputs` for parsable-output

Sources/SwiftOptions/Options.swift, Sources/makeOptions/makeOptions.cpp
It looks like the Swift frontend added a couple new `SwiftFlags`, which is breaking the `makeOptions` product: https://github.com/apple/swift/blob/93eae81b0485507ea982440cc6968a4d94252999/include/swift/Option/Options.h#L42-L43. This matches those in this project.
=> Add two new SwiftFlags in makeOptions

Sources/SwiftDriver/Jobs/CompileJob.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/671
------------------------------
Otherwise these jobs today have input-less parsable-output:
```
"command_executable" : "\/usr\/bin\/swift-frontend",
"inputs" : [
],
"kind" : "began",
```
Resolves rdar://78321174
=> [5.5] In WMO, treat all inputs as `displayInputs` for parsable-output

Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is the new driver version of apple/swift#37539.
rdar://78334766
----
Explanation: When emitting a static library, the driver attempts to run dsymutil on it. dsymutil is not supposed to be run on archives so it fails. As a result, one cannot compile static libraries with debug info at all. This patch just fixes the behavior by checking when adding the dsymutil job if we are emitting a static library and in such a case, do not add the dsymutil job.
Scope: Small. Just ensures that if we are compiling a static library we do not add a dsymutil job in the driver.
Risk: Low.
Testing: Adding a compiler test that validates the behavior.
Issue: rdar://78271443
=> [5.5] New Driver: do not generate a dSYM bundle for static archives

Sources/SwiftDriver/Driver/Driver.swift
Forgot to do this earlier when I added `-emit-irgen`.
=> Note file type for -emit-irgen.

Sources/SwiftOptions/Options.swift, Sources/makeOptions/makeOptions.cpp
A new `ModuleInterfaceOptionIgnorable` as added to `Options.inc`, so `makeOptions.cpp` needed to be updated.
=> Update makeOptions and SwiftOptions.

Tests/SwiftDriverTests/CrossModuleIncrementalBuildTests.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/NonincrementalCompilationTests.swift
The file `IncrementalCompilationTests.swift` has grown over time and accreted other test classes, encumbering navigation and clarity. Give `CrossModuleIncrementalBuildTests` and `NonincrementalCompilationTests` their own files, and reorder the contents of `IncrementalCompilationTests.swift` to group related tests and their helpers together. Opportunistically, make the helpers `private`.
This change will facilitate the addition of tests in the future.
=> [NFC] Reorganize the tests in IncrementalCompilationTests.swift

Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift
A refactoring of `inputDependencySourceMap` prior to really fixing the below:
See https://github.com/apple/swift-driver/pull/662
> There is a remaining lurking bug here that involves an extra step.
Suppose you build in a normal way with foo.swift/foo.c setup. Then you
rebuild and cancel it after a frontend has emitted a new swiftdeps file,
finally, you crash the driver by exploiting this bug. The driver is now
in a state where swiftdeps disagree with the priors which disagree with
the output file map.
> All this to say, we should take the earliest opportunity to remove
BidirectionalMap and its uses. But this commit is not the one to make
such a structural change to the driver.
Start on that.
rdar://77998890
=> [NFC, Incremental] Refactoring to facilitate replacing the inputDependencySourceMap with the right thing

Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Add some documentation and clarify the construction of a few APIs.
Break up and rename ExternalDependency.Why into
ExternalDependency.InvalidationReason. Then, re-introduce the methods
that compute those invalidation reasons into the module dependency
graph. This unblocks a small amount of cleanup as we no longer need to
retrieve the reason we're going to invalidate nodes more than once.
=> [NFC] Refactor External Integration A Bit

Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift
A recent PR, https://github.com/apple/swift-driver/pull/666, nicely cleaned up some of the external dependency code by reifying the notion of a known vs unknown external dependency. 
Fix a couple of typos from that PR.
Add some clarity to that PR for the sake of those to come who are not as familiar with this, somewhat tricky, code:
- Add a named local variable, `isNew`, in order to make the meaning result of a call to `record` more salient, and
- Restore the intension-revealing function, `recordUsesOfSomeExternal` to make the intention, i.e. the remembering of *uses* of an external dependency salient.
=> [NFC: Incremental] Clarifications and typo fixes

Sources/SwiftDriver/Driver/CompilerMode.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/GeneratePCMJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This gets lowered into a `-dump-pcm` `swift-frontend` job that outputs a bunch of information about the module to standard output.
Resolves rdar://78739383
=> Add support for `-dump-pcm` compiler mode

Sources/SwiftDriver/Driver/CompilerMode.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/GeneratePCMJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/691
-----------------------------------------------------------------------
This gets lowered into a `-dump-pcm` `swift-frontend` job that outputs a bunch of information about the module to standard output.
Resolves rdar://78739383
=> [5.5] Add support for `-dump-pcm` compiler mode

Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftOptions/Options.swift
This reverts commit 0acbbbd001887bf8be842065928df037b457f88c.
Using this flag caused breakage when trying to use upstream LLVM
as well as Clang/LLVM from Xcode 12.5. See SR-14714.
=> Revert "Conditionally pass musttail checking flag to frontend."

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Adds a bunch of removal test options
- A facility for testing all combinations of them
- The first, most basic removal test,
- A fix for that test, that removes priors if incremental setup fails
=> [Incremental] Add first file removal test

Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Using `lstat` here will do the wrong thing when the input path is a symlink since it's going to give us mod time info on the symlink instead of the file it references. Since mod time updates are intentionally not propagated across links, this has the potential to cause us to miscompile if a file's contents change on disk but the symlink passed as input hasn't actually changed. It also has the potential to defeat the incremental build when build systems that generate symlinks on every build interact with the driver.
On Darwin (and, technically, other UNIX-likes) the fix is simple: use stat instead of lstat which will resolve symlinks for us. On Windows the answer is... complicated. Instead, on the fallback path, resolve symlinks before retrieving the modification time of the file. …
=> Use `stat` Instead of `lstat`

Package.resolved, Sources/SwiftDriver/Utilities/VirtualPath.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Cherry pick of #697 
---------
Using `lstat` here will do the wrong thing when the input path is a symlink since it's going to give us mod time info on the symlink instead of the file it references. Since mod time updates are intentionally not propagated across links, this has the potential to cause us to miscompile if a file's contents change on disk but the symlink passed as input hasn't actually changed. It also has the potential to defeat the incremental build when build systems that generate symlinks on every build interact with the driver.
On Darwin (and, technically, other UNIX-likes) the fix is simple: use stat instead of lstat which will resolve symlinks for us. On Windows the answer is... complicated. Instead, on the fallback path, resolve symlinks before retrieving the …
=> [5.5] Use `stat` Instead of `lstat`

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
As more tests are added (including removal tests to come), the lists of expected diagnostics becomes ever-more unwieldy.
Encode sequences of these diagnostics.
=> [NFC, Incremental testing] Encode sequences of diagnostics

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Instead of passing them as inputs to the `swift-frontend` invocations, which does not make sense.
Part of rdar://78881502
=> Pass `.tbd` inputs down to the linker invocation.

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Tests all combinations of `removeInputFromInvocation`,  `removeSwiftDepsFile`, & `restoreBadPriors`.
The last condition simulates a case where a file is removed but somehow the driver does not get to remove the priors, which has entries for the removed file.
For that condition, the test passes but prints out a warning.
A subsequent PR will fix this issue.
=> [Incremental, Testing] Implement 7 more removal tests.

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/701 for the `release/5.5` branch.
--------------------------------------
Instead of passing them as inputs to the `swift-frontend` invocations, which does not make sense as they are not source-code.
Part of rdar://78881502
=> [5.5] Pass `.tbd` inputs down to the linker invocation.

Package.resolved, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This change ensures that explicit swift module dependencies are built into binary modules with filenames that encode their context hash (as reported by the dependency scanner). e.g. `A.swiftinterface` --> `A-<CONTEXT_HASH>.swiftmodule`.
This is required because in some situations builds of the same module for different contexts (e.g. target architectures) otherwise overlap and cause chaos.
Resolves rdar://78820404
=> [Explicit Module Builds] Use context hash in Swift dependency module file names

Sources/SwiftDriver/IncrementalCompilation/BidirectionalMap.swift, Sources/SwiftDriver/IncrementalCompilation/DirectAndTransitiveCollections.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift, Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Make the `inputDependencyMap` immutable, solely reflecting the `OutputFileMap`.
Do not include it in the priors.
In a previous PR, @CodaFi uncovered and explained issues with the `inputDependencySourceMap:
```
// FIXME: The map between swiftdeps and swift files is absolutely *not*`
// a bijection. In particular, more than one swiftdeps file can be encountered
// in the course of deserializing priors *and* reading the output file map
// *and* re-reading swiftdeps files after frontends complete
// that correspond to the same swift file. These cause two problems:
// - overwrites in this data structure that lose data and
// - cache misses in `getInput(for:)` that cause the incremental build to
// turn over when e.g. entries in the output file map change. This should be
// replaced by a …
```
=> [Incremental] Harness immutability to make `inputDependencySourceMap` robust

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Causing the behavior to be analagous to the Legacy driver's here:
https://github.com/apple/swift/blob/main/lib/Driver/Driver.cpp#L2415
Otherwise, this isn't a supported flow and leads to driver crashes downstream.
Also ensure that we do not perform the check that ensures the same output is not produced more than once for standard-out outputs. This allows things like `-emit-ir` to actually function with `-wmo -num-threads` and be output correctly.
=> Verify usage of `-o` arguments in multi-threading mode.

Package.resolved, Sources/CSwiftScan/include/swiftscan_header.h, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/SwiftScan/SwiftScan.swift, Sources/SwiftDriver/Utilities/FileType.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
https://github.com/apple/swift/pull/37723 added API to libSwiftScan to save and restore the dependency scanner's state on the filesystem.
This PR adds this API to the corresponding client code in the driver.
=> [Explicit Module Builds] Add libSwiftScan API for scanner cache serialization/deserialization

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
1. Use a result builder for the expected diagnostics, and
2. Add another condition to the file removal test in which the removed file depends on a file that changes
=> [Incremental, Testing] Result builder & dependent removal test

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/IntegrationTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/715
------------------------------------------------
For compiles which fall under our "in-place execution" flow, ensure that we print the in-place job before executing it if `-v` was specified.
Resolves rdar://79295614
=> [5.5] Ensure that verbose (`-v`) mode applies to in-place execution.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
5.5 Cherry-pick of https://github.com/apple/swift-driver/pull/711
-----------------------------------------
Causing the behavior to be analagous to the Legacy driver's here:
https://github.com/apple/swift/blob/main/lib/Driver/Driver.cpp#L2415
Otherwise, this isn't a supported flow and leads to driver crashes downstream.
Resolves rdar://79171618
=> [5.5] Produce an error when multiple `-o` options are specified in multi-threading mode

Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift, Sources/SwiftDriver/SwiftScan/SwiftScan.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
An ability to do a simple import pre-scan was added to the dependency scanner in https://github.com/apple/swift/pull/34028, with a corresponding libSwiftScan API added later. It parses input files looking for `import` statements and outputs an array of module names imported in the provided input source files.
This PR adds the ability to invoke this import pre-scan from the driver.
=> [Dependency Scanning] Add ability to use the dependency scanner's import-prescan mode

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Now that all cases of the removal test work, there is no need for separate tests.
Also, add some more information.
=> Clean up testRemoval

Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift
It's failing in CI for some as-yet-undetermined reason.
rdar://79594631
=> Disable explicit module builds test

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Sources/SwiftDriver/Utilities/Triple+Platforms.swift
These are needed for the swift-driver to work correctly on this
platform.
OpenBSD has the lld linker in the base system, so just default to using
it over bfd, as suggested by the comments.
=> Add some additional directives for OpenBSD.

Sources/SwiftDriver/IncrementalCompilation/BidirectionalMap.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift, Sources/SwiftDriver/IncrementalCompilation/TwoDMap.swift, Tests/SwiftDriverTests/BidirectionalMapTests.swift
Shuffle the docs around on some decls, drop some unused decls, and prettify the interface to BidirectionalMap with some new docs.
=> Clean Up Some Data Structures a Bit

Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Recent changes that introduced `-clang-target` have introduced a conflict with how explicit module builds work. We need to address this, but in the meantime, re-enable the test with `-disable-clang-target`.
Resolves rdar://79594631
=> Revert "Disable explicit module builds test #725" and fix the test.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift, Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Test effect of a minor version number change on the priors, and also add the needed affordances.
Also increment the minor version to reflect the omission of the no-longer-needed serialized inputDependencySourceMap.
Required before landing https://github.com/apple/swift-driver/pull/728
=> [NFC, Incremental] Test effect of a minor version number change on the priors

Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
This warning is mostly useful for debugging the driver, so let's hide it when `libSwiftDriver` is used, instead of a `swift-driver `executable.
There are also valid scenarios where the scanning action can succeed just-as-well using the fallback path where this warning is extraneous and may confuse users because it is not actionable.
=> Do not emit a dependency-scanner fallback warning when in integrated-driver mode

Package.resolved, Sources/SwiftDriver/Jobs/Toolchain+InterpreterSupport.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This has not been a good idea since Swift started shipping in the OS. 
The OS runtime is the one we would like Swift scripts to use. Using the installed toolchain can potentially cause sync issues.
Continue setting this variable in other UNIX toolchains, because there is no runtime shipped in the OS there. 
Resolves rdar://78951185
=> Do not set `DYLD_LIBRARY_PATH` to point the installed toolchain/sdk on macOS.

Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift
As-is, these tests are sensitive to the environment and are currently failing with:
```
ld: library not found for -lobjc
```
Passing in the sdk path explicitly should make them pass and be more resilient.
Resolves rdar://79934188
=> [5.5][NFC] Fix executable tests by passing in the SDK path explicitly.

Sources/SwiftDriver/Jobs/Toolchain+InterpreterSupport.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of #733.
-------------------------------------------
This has not been a good idea since Swift started shipping in the OS. The OS runtime is the one we would like Swift scripts to use. Using the installed toolchain can potentially cause sync issues.
Resolves rdar://78951185
=> [5.5] Do not set `DYLD_LIBRARY_PATH` to point the installed toolchain/sdk.

Sources/SwiftOptions/Options.swift
The `-gsil` is deprecated in favor of `-sil-based-debuginfo`.
This PR is a synergy with https://github.com/apple/swift/pull/38167.
=> [SIL] Deprecating the '-gsil' frontend flag

Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift
Consume the new non-owning bitstream deserialization in apple/swift-tools-support-core#236 to provide a 3-5x boost to deserialization performance for source and module dependency graph files. Also, undo a cached hash optimization that was only really necessary because of the quadratic COW issue resolved in #654. Otherwise, the hash was being eagerly computed during deserialization which forced an extra half-second of wall time.
=> Improve Deserialization Performance

Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Utilities/build-script-helper.py
This [matches the upstream driver](https://github.com/apple/swift/blob/0149ccd0ca69a8e97a4d13d172c8ce67f5498a60/lib/Driver/UnixToolChains.cpp#L134) and removes the build toolchain's rpath for this shipping swift-driver executable itself on ELF platforms, as I've done before for SPM, apple/swift-package-manager#2703, and other repos:
```
> readelf -d swift-DEVELOPMENT-SNAPSHOT-2021-06-12-a-centos8/usr/bin/swift-driver | ag runpath
0x000000000000001d (RUNPATH)            Library runpath: [/home/build-user/swift-nightly-install/usr/lib/swift/linux:$ORIGIN:$ORIGIN/../lib/swift/linux]
```
I ran the following command twice to test this pull with a prebuilt trunk snapshot, because the swift-driver used the first time didn't have this Swift addition:
```
./swift/utils/build-script -R …
```
=> Enable checking for -no-toolchain-stdlib-rpath and use it on this repo's binaries before installing

TestInputs/ExplicitModuleBuilds/Swift/Swift.swiftinterface, TestInputs/ExplicitModuleBuilds/Swift/SwiftOnoneSupport.swiftinterface, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
- Pass down SDK paths to explicit module tests
- Remove "fake" stdlib files, making sure dependency scanning tests rely on the real ones
- Gate a couple of tests on frontend flag availability
Package bots are currently failing on a few SwiftDriver tests:
https://ci.swift.org/job/oss-swift-package-macos/5970/console
=> Unblock package bots by making tests more resilient to environment changes.

Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is the only remaining Android difference with the C++ driver. The new test was tested natively on Android with my Swift 5.4.1 toolchain package in [the Termux app](https://termux.com/), all tests passed.
=> Get Android to parity with upstream driver and enable remaining tests

Package.resolved, Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/Jobs/APIDigesterJobs.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift, Sources/SwiftDriver/Utilities/FileType.swift, Sources/SwiftOptions/ExtraOptions.swift, Tests/SwiftDriverTests/APIDigesterTests.swift
The goal here is to add support to the driver for generating an API/ABI baseline or comparing to one immediately after emitting a module. This means higher-level build systems like SwiftPM can share the implementation and each won't need to have their own support for generating swift-api-digester command lines to add breaking-change detection.
A few notes on the implementation:
- Right now, all the flags related to this functionality have separate API and ABI variants. The makes it possible to generate or compare both types of baseline in a single driver invocation, but I'm not entirely sure it's worth the trouble
- The baselines are treated as 'auxilary' outputs, similar to swiftsourceinfo files, so if an output path isn't specified they'll look for a Project/ directory if one is …
=> Add an integration with swift-api-digester

Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
It is currently failing on Apple Silicon CI:
https://ci.swift.org/job/oss-swift-incremental-RA-macos-apple-silicon/1010/console
=> Disable `testDependencyScanning` on Apple Silicon

Utilities/build-script-helper.py
Add a flag, `--cross-compile-config`, to pass in a SPM cross-compilation file and cross-compile with that instead of CMake. Also, fix non-Darwin installs to use the `--prefix` list passed in, rather than simply installing into the build toolchain.
I tested this with the latest trunk source snapshot from June 12. The `build-script` side of this pull was just added to apple/swift#36917. This pull is the equivalent of apple/swift-package-manager#3403. I plan to use this pull to build and install this swift-driver as part of [my upcoming Swift 5.5 toolchain for Android](https://github.com/buttaface/termux-packages/tree/swift55/packages/swift).
=> [Build Script Helper] Add support for non-Darwin cross-compilation hosts, starting with Android

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/IntegrationTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
For compiles which fall under our "in-place execution" flow, ensure that we print the in-place job before executing it if `-v` was specified.
Resolves rdar://79295614
=> Ensure that verbose (`-v`) mode applies to in-place execution.

Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift, Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
If priors contain nodes from input files that have been removed, do not add those nodes to the `ModuleDependencyGraph` when deserializing priors.
I have measured driver time on a 1000+ source-file project, and the extra time for this check was about 1 ms according to instruments, out of 2.8 secs spent reading the priors. Total driver time was 26 secs.
=> [Incremental] When reading priors, don't use nodes for removed inputs.

Package.resolved, Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/OutputFileMap.swift, Sources/SwiftDriver/Jobs/APIDigesterJobs.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift, Sources/SwiftDriver/Utilities/FileType.swift, Sources/SwiftOptions/ExtraOptions.swift, Tests/SwiftDriverTests/APIDigesterTests.swift, Utilities/build-script-helper.py
This reapplies the patch that caused failure on the package bots, then updates build-script-helper to include swift-api-digester in the list of tools whose lookup is override by the --toolchain flag
=> Reapply swift-api-digester integration

Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift, Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Tests/IncrementalTestFramework/CompiledSourceCollector.swift, Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
The status quo reads every `swiftmodule` file for every input file. This PR fixes that. It is trickier than it seems because, when incremental imports are disabled, every time an initial `swiftdeps` file is processed, invalidation must happen for every (changed) `swiftmodule` referenced. So, this fix involves a larger reorganization that it would seem at first blush.
I've tried to include enough comments, etc., so that this code should be understandable.
=> [Incremental] Fix clean build quadratic performance bug

Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Ensure that saved priors actually comes from the prior build. Guards against reading stale priors.
=> [Incremental] Compare modification time of priors to build times in build record

Package.resolved, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift, Tests/TestUtilities/DriverExtensions.swift
When the integrated driver is being used, the individual job output should be tracked by the library client, instead of the driver forwarding it into stderr.
Resolves rdar://80520371
=> Add `.silent` mode to the ToolExecutionDelegate to be used in integrated driver mode

Package.resolved, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift, Tests/TestUtilities/DriverExtensions.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/752
-----------------------------------------------
When the integrated driver is being used, the individual job output should be tracked by the library client, instead of the driver outputting it into stderr.
Resolves rdar://80520371
=> [5.5] Add `.silent` mode to the ToolExecutionDelegate to be used in integrated driver mode

Package.swift, Package@swift-5.4.swift, Sources/SwiftDriver/Execution/DriverExecutor.swift, Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift, Sources/SwiftDriver/SwiftDriver.docc/ExplicitModuleBuilds.md, Sources/SwiftDriver/SwiftDriver.docc/IncrementalBuilds.md, Sources/SwiftDriver/SwiftDriver.docc/Info.plist, Sources/SwiftDriver/SwiftDriver.docc/SwiftDriver.md, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift
This provides a model for what integrating Docc documentation would look like for the Swift driver. A few articles are included to get a feel for the basics of what we can provide here.
=> Add Docc Support and Some Preliminary Articles

Package.swift, Package@swift-5.5.swift
SwiftPM doesn't appear to respect the legacy files. So, make 5.5 the
outlier and restore the 5.1-compatible manifest as the default.
The diff is atrocious, but these two files have just been swapped
Package@swift-5.1.swift -> Package.swift
Package.swift -> Package@swift-5.5.swift
=> Swap Package Manifest Files

Package@swift-5.5.swift
The inverse of #754 when building in Swift-CI because the local package
URL is lowercase...
=> Alias the Local yams Package to Yams

Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Some lit tests are failing on CI, but they won't fail locally. Based on the output, I suspect the priors currency test is failing and it shouldn't. So let's try relaxing the test: using the build-record mod time instead of the build-start time, and don't do the build end time test, since the build record had better be from the previous run anyway.
=> [Incremental] Relax currency test to fix ci errors

Package@swift-5.5.swift
The name of the local package is just "llbuild" in 5.5 when building
with local deps enabled. We need to propagate that dependency
explicitly.
=> Fixup LLBuild Package Reference in SWIFT_CI Local Build

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftOptions/Options.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Allow users to specify a particular LTO library on Darwin.
=> Add support for -lto_library linker flag

Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
The CI mod times seem to be very coarse, so relax the priors currency test a bit more.
=> [Incremental] Relax the priors currency test by what ought to be enough to get through CI

Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
We should turn clang target on for implicit module after we are confident that the feature works nicely in explicit module builds.
=> Specify -clang-target only when explicit module is on

Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
I got overzealous when deleting code in https://github.com/apple/swift-driver/pull/749 and removed one piece of functionality that we still rely on.
Although the external target map is no longer necessary when scanning dependencies using libSwiftScan, we still use it for resolution of `canImport` statements during the scan.
We need to figure out a better way to deal with `canImport` statements in the scanner, but in the meantime this will restore functionality.
=> [Dependency Scanning] Restore passing external target map as inputs to the scanning action.

Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
Reverts apple/swift-driver#763
Possibly causing SwiftPM failure on Linux, when combined with a recent compiler change.
https://ci.swift.org/job/oss-swift-pr-test/18142/
=> Revert "[Dependency Scanning] Restore passing external target map as inputs to the scanning action."

Package.swift, Package@swift-5.5.swift
Exclude the CMakeLists.txt files explicitly so that swiftpm does not issue warnings about them.
I still see a warning about `Sources/SwiftDriver/SwiftDriver.docc`, but I wasn't sure if it's correct to exclude it or if that might interfere with using it from Xcode or not.
=> Fix swiftpm warnings about CMakeLists.txt files

Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Matching behavior of this flag in the legacy driver.
Resolves rdar://80925867
=> Propagate `-warn-concurrency` to frontend invocations.

Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/770
------------------------------------
Resolves rdar://80925867
=> [5.5] Propagate `-warn-concurrency` to frontend invocations.

Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Verifying swiftinterface files after they are emitted will detect framework breaking issues much earlier. It can be turned off in offending projects with `-no-verify-emitted-module-interface`.
Only swiftinterfaces emitted from non-merge-module builds at verified by default. Merge-module builds are more likely to generate broken swiftinterfaces even when a whole-module or emit-module-separately build generates a valid one.
rdar://77534863
=> Verify emitted module interfaces by default (Take 2)

Tests/SwiftDriverTests/SwiftDriverTests.swift
To investigate CI failures, e.g.:
https://ci.swift.org/job/oss-swift-incremental-RA-macos-apple-silicon//1135/console
Related to rdar://80558898
=> Disable `testVerboseImmediate` test on Apple Silicon

Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift, Utilities/build-script-helper.py
Cherry-pick of #732 and #767
- Explanation: This [matches the upstream driver](https://github.com/apple/swift/blob/0149ccd0ca69a8e97a4d13d172c8ce67f5498a60/lib/Driver/UnixToolChains.cpp#L134) and removes the build toolchain's rpath for this shipping swift-driver executable itself on ELF platforms.
- Scope: Adds behavior to match upstream and remove an extraneous rpath from the swift-driver and other executables from this repo. 
- Risk: None
- Testing: Passes all tests, as indicated in the upstream pull, and should now pass more tests from the compiler test suite.
- Reviewer: @artemcm
=> [5.5] Enable checking for -no-toolchain-stdlib-rpath and use it on this repo's binaries before installing

Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
It has been observed that a static library may sometimes contain the
autolink extracted rules.  This causes autolink-extract to not be able
to process the archive as a dependency, causing a build failure.
=> Jobs: do not inject the swiftautolink file into archives

Package.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift, Tests/SwiftDriverTests/Inputs/ExplicitModuleDependencyBuildInputs.swift
Specifically, whether an external target moduel is a framework. This is required to pass this information down to the compiler in order to generate correct auto-linking directives.
Part of rdar://81177797
=> [Explicit Module Builds] Add API to specify richer external target module details

Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
The dependency scanner specifies which exact modulemaps must be used, we do not need Clang to also search for modulemaps.
=> [Explicit Module Builds] Pass in `-fno-implicit-module-maps` for pre-building Clang explicit dependencies

Package.swift
Fix build breakage introduced in #779 
rdar://81367644
=> swift-driver package fails to compile due to missing quotes around string

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is a regression from [the C++ Driver](https://github.com/apple/swift/blob/35735e7d0c57b57953623eb069d3812cd95d25e6/lib/Driver/Driver.cpp#L1776), ~will add a test later today and this should be~ ready to go.
=> SR-14796: Don't lose '-sdk /' when dropping the trailing slash

Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
`libSwiftDriver` clients need to be able to instantiate values of this type.
=> Change `ExternalTargetModuleDetails.init` to be public

Tests/SwiftDriverTests/CleanBuildPerformanceTests.swift
This test is failing on Linux, e.g.:
https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_04-long-test/8571/
rdar://81411914
=> Disable `testCleanBuildSwiftDepsPerformance` on non-macOS hosts to investigate failure.

Sources/SwiftDriver/SwiftDriver.docc/ExplicitModuleBuilds.md
Update the formatting for the link to the incremental builds page for clarity.
=> Reformat link in ExplicitModuleBuilds.md

Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Not doing so can lead to dangerous collisions if a build system uses a cetral cache across different targets that have a common dependency that is found in different places in the filesystem. For example, when building targets `A` and `B`, both of which depend on Clang module `C`, but have different search paths, finding `C` in two different locations, we should produce two distinct PCMs. With today's hashing scheme, the second will overwrite the first.
=> [Explicit Module Builds] Include source modulemap path into PCM filename hash.

Sources/swift-build-sdk-interfaces/main.swift
Introduced in https://github.com/apple/swift-driver/pull/796, this passed CI because swift-driver CI uses a recent compiler.
This broke SwiftPM CI because it uses a 5.3 compiler which contains a bug which makes such patterns fail to build.
=> Fix `guard let sdkPath = sdkPath` pattern for compatiblity with older compilers

Sources/SwiftDriver/Driver/Driver.swift
Forgot to cherry-pick this earlier when I landed it in https://github.com/apple/swift-driver/pull/676. Without this, trying to pass `-emit-irgen` to the new driver will crash (can be worked around by `-disallow-use-new-driver`).
(cherry picked from commit 9a85a8268c731bdd549b0237388b42e9a512efc9)
Fixes rdar://81971182.
=> [5.5] Note file type for -emit-irgen.

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/IncrementalCompilation/DirectAndTransitiveCollections.swift, Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift, Sources/SwiftDriver/IncrementalCompilation/SwiftSourceFile.swift, Sources/SwiftDriver/Jobs/Job.swift, Sources/SwiftDriver/Jobs/Planning.swift, Tests/SwiftDriverTests/CleanBuildPerformanceTests.swift, Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Add a distinguished wrapper type for `SwiftSourceFile` in order to clarify where the incremental code is dealing with any sort of input file, or exactly a Swift source file.
In service of rdar://79790907
=> [Incremental] Add SwiftSourceFile type

Package.resolved, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Utilities/VersionExtensions.swift
This PR replaces the Version(potentiallyIncompleteVersionString:) extension with the new Version(versionString:, usesLenientParsing:) from TSC
=> Replace lenient version parsing implementation with the one in TSC

Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift, Sources/swift-build-sdk-interfaces/main.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
These cherry-picks from `main` complete the `swift-build-sdk-interfaces` tool to be functionally equivalent to the legacy implementation of `swift_build_sdk_interfaces.py`, so we could replace the legacy mechanism with the new one for better efficiency.
related to: rdar://81848232
=> [5.5] PrebuiltModuleGen: cherry-pick recent changes

Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
To unblock updating CI Xcode which is currently failing in:
https://ci.swift.org/job/swift-PR-macOS-new-xcode/117/console
The proper test fix is included in https://github.com/apple/swift-driver/pull/781, which will re-enable this test.
(cherry picked from commit 4997eb66e3cf143163cdaf4d0726ec490ea7de54)
=> Temporarily disable `testDependencyScanning`

Tests/SwiftDriverTests/APIDigesterTests.swift, Tests/SwiftDriverTests/CrossModuleIncrementalBuildTests.swift, Tests/SwiftDriverTests/NonincrementalCompilationTests.swift
=> test: temporarily skip testBaselineGenerationEndToEnd to unblock CI

Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftOptions/Options.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
=> Make `-library-level` a driver argument and pass it to the frontend

Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This is more robust than just relying on a hand-written command, and unblocks this test passing on Apple Silicon.
=> [Test Change] Use `Driver` to generate scanner invocation in dependency scanning test

Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/814
----------------------------------------------------------------------------------
This is more robust than just relying on a hand-written command, and unblocks this test passing on Apple Silicon.
=> [5.5][Test Change] Use `Driver` to generate scanner invocation in dependency scanning test

Tests/SwiftDriverTests/APIDigesterTests.swift
=> test: skip testAPIComparisonEndToEnd() while investigating

Sources/SwiftDriver/IncrementalCompilation/DependencyGraphDotFileWriter.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
Since the dot file writer contains a sequence number, it gets mutated whenever a dot file is written.
Make this a struct to pass that info upwards in preparation for making thread-safety for the incremental state clearer.
=> [Incremental] Make dot file writer a struct

Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
https://github.com/apple/swift-driver/pull/816 moved some things around in the incremental compilation state that may be relied on by clients as public API.
This PR restores the removed API surface. Sorry I missed these during review.
=> Fix small API break in the incremental build state

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Previously it was always using `yaml` type even if the format requested was bitstream.
=> [SwiftDriver] Make sure the proper file type is used for the optimization record file in a supplementary output file map

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/TestUtilities/OutputFileMapCreator.swift
This re-implements this logic https://github.com/apple/swift/blob/3116eed2e465a2688f070b3b87adc106cbbaf09f/lib/Driver/Driver.cpp#L414-L417 to not warn when output file maps don't have a main entry when using WMO
=> Disable output file map diagnostic for non-incremental mode

Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
It is a more-robust way of ensuring different instances of the same module will never end up overlapping.
Ever since we removed the `-target` argument from `PCMArgs`, previous method of using `PCMArgs` and `.modulemap` path could not, for example, distinguish building the same Clang module, from the same `.modulemap`, with different `-target` triples.
=> [Explicit Module Builds] Use Clang dependencies' `contextHash` as partof its filename-encoded hash

Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Making emit-module-separately the default build mode will improve the reliability of incremental builds. This mode builds the module files in a distinct job which only parses the module API and doesn't use the merge-module phase.
In support, this PR fixes a few issues and update a lot of tests expecting the precise behavior of merge-module.
rdar://77225764
=> Make emit-module-separately the default incremental build mode 

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
I realized this test would pass even if the WMO arg was removed, which
would negate the positive case. Now if that happens we fall back to
-incremental and get the expected warning.
=> Improve testFileMapMissingMainEntryWMO

Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
All prebuilt modules are emitted into SDK-versioned subdirs. When targeting at macCatalyst,
the value from -target-sdk-version doesn't match the actual SDK version because the SDK under
used is a macosx SDK. This patch computes the prebuilt module cache path and passes it down directly
to the compiler invocation.
rdar://82464316
=> Pass-down -prebuilt-module-cache-dir when targeting at macCatalyst

Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/825
----------------------------------------------------------------
- **Explanation**: It is a more-robust way of ensuring different instances of the same module will never end up overlapping.
Ever since we removed the -target argument from PCMArgs, previous method of using PCMArgs and .modulemap path could not, for example, distinguish building the same Clang module, from the same .modulemap, with different -target triples.
- **Risk**: Low
- **Reviewed by**: @nkcsgexi 
- **Testing**: Automated tests modified to reflect new behavior
=> [5.5][Explicit Module Builds] Use Clang dependencies' `contextHash` as part of its filename-encoded hash

Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
These jobs do not require handling of the module's PCH.
If we do emit these flags, the underlying Clang invocation will have expectations that may not be met (such as going looking for existing PCH files, etc.).
=> [Dependency Scanning] Do not include PCH-handling command-line flags on the scanning jobs

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/CompilerMode.swift, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/SwiftHelpIntroJob.swift, Sources/swift-help/main.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
> Note: This PR is for a pitch discussion and building a test toolchain. Please don't merge this – thanks!
Add an "intro" topic to swift-help, printing the version, welcome message, and
available subcommands.
When running `swift` by itself, show the intro before entering the REPL.
When running `swift-help` directly or via `swift --help`, show all of the
available flags as previously.
rdar://78280423
More context: https://forums.swift.org/t/command-line-ux-enhancements-for-swift/50670
=> Add help intro

Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/841
------------------------------------------------------------------
Explanation: These jobs do not require handling of the module's PCH. If we do emit these flags, the underlying Clang invocation will have expectations that may not be met (such as going looking for existing PCH files, etc.), leading to errors/crashes.
Risk: Low
Reviewed by: @nkcsgexi
Testing: Automated tests modified to capture the new behavior restriction
=> [5.5][Dependency Scanning] Do not include PCH-handling command-line flags on the scanning jobs

Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/843
-------------------------------------------------------------------
- **Explanation**: This form causes Swift's underlying Clang invocation to take different code-paths when loading pre-built PCM dependencies, which is not affected on whether the compiler is in emit-pre-built-header mode.
- **Risk**: Low
- **Reviewed by**: @nkcsgexi
- **Testing**: Automated tests modified to capture the new behavior
Workaround for rdar://83309762
=> [5.5][Explicit Module Builds] Use new form of `-fmodule-file` to work around Clang issue with explicit builds and emit-PCH

Sources/CSwiftScan/include/swiftscan_header.h, Sources/SwiftDriver/ExplicitModuleBuilds/ClangVersionedDependencyResolution.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift, Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift, Sources/SwiftDriver/SwiftScan/SwiftScan.swift
The graph coming out of the scanner will already contain an initial set of captured PCM arguments as defined by the initial scanner invocation. This will allow us to skip the batch re-scan at argument sets that are redundant because they were already captured via the initial scan.
=> [Dependency Scanning] Adapt to changes in dependenncy scanner to capture initial PCM arguments

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Explanation: This change asks the compiler to emit ABI descriptors while generating module files if this feature (emitting ABI while emitting module) is supported by the compiler. To check whether the feature is supported by the compiler, this change also added support for the feature list file installed in the toolchain.
Risk: Low
Reviewed by: @artemcm 
Testing: Automated tests added
This is a cherry-pick of https://github.com/apple/swift-driver/pull/845
=> [5.5] Emit ABI descriptor while emitting the final module

Sources/CSwiftScan/include/swiftscan_header.h, Sources/SwiftDriver/ExplicitModuleBuilds/ClangVersionedDependencyResolution.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift, Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift, Sources/SwiftDriver/SwiftScan/SwiftScan.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/848
-----------------------------------------------
- Explanation: The graph coming out of the scanner will already contain an initial set of captured PCM arguments as defined by the initial scanner invocation. This will allow us to skip the batch re-scan at argument sets that are redundant because they were already captured via the initial scan.
- Risk: Low
=> [5.5][Dependency Scanning] Adapt to changes in dependency scanner to capture initial PCM arguments

Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Previously, we were using the file name to infer whether an interface is for macabi.
However, this seems to be inaccurate because some macabi interfaces don't have "-macabi" in
the file names. This patch teaches the driver to open interface files and check
module targets specifically.
=> PrebuiltModuleGen: check if an interface is for macabi by reading interface contents

Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Explanation: Previously, we were using the file name to infer whether an interface is for macabi.
However, this seems to be inaccurate because some macabi interfaces don't have "-macabi" in
the file names. This patch teaches the driver to open interface files and check
module target specifically.
Scope: Swift prebuilt module generation
Risk: Very low
Testing: regression test added
Reviewed by: @xymus 
Cherry-pick of: https://github.com/apple/swift-driver/pull/855
=> [5.5] PrebuiltModuleGen: check if an interface is for macabi by reading interface contents

Sources/SwiftDriver/Jobs/CompileJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Currently, when combining -c + -lto + -o, the driver will produce a ".bc" file on disk, even if the -o argument said ".o". This PR fixes that and matches the behavior of the C++ driver in the swift repo.
=> Building object files using -c with -lto should respect the output file path (-o) if present

Package@swift-5.5.swift
The `SwiftDriverTests` target should not depend on the `swift-driver`
target.  The latter is the executable binary.  This was noticed when
trying to port the swift-driver project to Windows.  The Windows linker
caught the fact that the `main` entry point was multiply defined, once
from the test binary, and once from the `swift-driver` executable.  Do
not add the `swift-driver` to the dependency set as that will cause a
link dependency, which results in the multiply defined symbols.
=> build: remove bogus dependency on `swift-driver`

Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
When building an archive, permit the LLVM bitcode content into the
archive as the LTO path will add those.  This should ensure that we can
continue to experiment with the LTO optimizations.
=> Jobs: permit bitcode items when building with LTO

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/TestUtilities/OutputFileMapCreator.swift
This re-implements this logic https://github.com/apple/swift/blob/3116eed2e465a2688f070b3b87adc106cbbaf09f/lib/Driver/Driver.cpp#L414-L417 to not warn when output file maps don't have a main entry when using WMO
This cherry picks https://github.com/apple/swift-driver/pull/707 with some significant compatibility changes to the tests
=> [5.5] Disable output file map diagnostic for non-incremental mode

Sources/SwiftDriver/Driver/Driver.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This makes swift-driver's behavior consistent with the old driver, which supports relative paths (both on the command line and in other response files). The LLVM response file parsing behavior used by the legacy driver is such that
-   Response file equivalence to prevent recursion is based on the file's device/inode pair, not its path.
-   Relative paths are resolved based on the current working directory of the process, even when the relative path is in another response file. (LLVM's parser has an option to make relative paths resolve based on the containing response file's path, but this is not enabled by the legacy driver.)
-   After resolving, the path is tested to ensure that it resolves to an actual file; this ensures that special linker paths like `@loader_path` fall back to …
=> Support response files with relative paths.

Tests/TestUtilities/PathExtensions.swift
The path handling in the tests needs to account for the fact that path
representation is currently hardcoded and the representation differs on
different platforms.  These are intended to help convert the
representation.
=> TestUtilities: add path utilities

Package.resolved
https://github.com/apple/swift-driver/commit/c94045879f487c3a3d21d54181d64a898e2cfb4e included an update to `Package.resolved` using recent ToT SPM format, which we should not use because of risk of breaking external clients here.
=> Revert `Package.resolved` back to stable release format.

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Utilities/FileType.swift, Sources/SwiftOptions/ExtraOptions.swift, Sources/SwiftOptions/Options.swift
Reverts apple/swift-driver#872
=> Revert "Pass-down -emit-module-semantic-info-path when swift compiler supports this flag"

Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This adjusts the tests for Windows.  With this set of changes, the
ExplicitModuleBuildTests all pass on Windows (except those which use a
macOS target triple).
=> SwiftDriverTests: adjust for Windows

Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
=> PrebuiltModuleGen: only use -err in log file names that contain fatal errors

Sources/SwiftDriver/CMakeLists.txt, Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/WindowsExtensions.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Sources/SwiftDriver/Jobs/Toolchain+InterpreterSupport.swift, Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/Toolchain.swift, Sources/SwiftDriver/Toolchains/WindowsToolchain.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift
This is sufficient to build on Windows, and the resulting driver is able
to somewhat function.  The tests are still not usable due to assumptions
about path which do not hold and the insufficiency of the path
representation in tools-support-core.  This is likely best approached by
replacing the use of `Path` from t-s-c with the representation in
system.  However, this allows some attempt to validate the swift-driver
which is increasingly becoming required for s-p-m, and thus unblocks
further work.
=> SwiftDriver: initial (incomplete) windows port

Sources/SwiftDriver/Jobs/CompileJob.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/MergeModuleJob.swift, Sources/SwiftOptions/Options.swift
As part of https://github.com/apple/swift/pull/39865, this updates swift-driver to include the new `-symbol-graph-minimum-access-level` flag.
I also updated the job CLI flag code to bring it up to speed with the symbol-graph flags that are added during the old driver's job planning process.
=> update symbol graph emission flags

Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Set the env var `ENABLE_RESTRICT_SWIFTMODULE_SDK` to enable passing down the SDK name to the compiler for it to ensure that swiftmodule are only loaded with the SDK used to build them.
=> Move the check for the swiftmodule SDK behind an env var

Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
This is just bringing over [the one C++ Driver change from a larger compiler pull](https://github.com/apple/swift/pull/39921/files#diff-55fd9483c4660c88c6c3e942cdc38a2cae2647839c581e322c7bf292775e5c43), so I don't have to [change the linker manually all the time](https://github.com/buttaface/swift-android-sdk/blob/main/swift-android-trunk.patch#L112).
=> Android: make lld the default linker, since the Android NDK just removed all other linkers

Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
This reverts commit 095cdac250314895c6b77146d78595c3fa2599b5, restoring the reverted functionality.
=> Revert "Revert "[Dependency Scanning] Restore passing external target map as inputs to the scanning action.""

Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
If we have both individual source files and the emit-module file emit .d files, we
are risking collisions in output filenames.
In cases where other compile jobs exist, they will produce dependency outputs already.
There are currently no cases where this is the only job because even an `-emit-module`
driver invocation currently still involves partial compilation jobs.
When partial compilation jobs are removed for the `compilerOutputType == .swiftModule`
case, this will need to be changed here.
Workaround for rdar://85253406
=> Ensure that the separate emit-module job does not emit `.d.` outputs.

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
These tests should be skipped with ObjC as a heuristic that the ObjC
runtime enabled Foundation is available.  This is working around a
Foundation issue, and that should be fixed.  This simply makes the
workaround more portable and precise.
=> Tests: adjust condition for skipped tests

Sources/SwiftDriver/Jobs/Planning.swift, Sources/SwiftDriver/Jobs/VerifyModuleInterfaceJob.swift
The interface verification phase should downgrade errors to warnings as an
intermediate step to stage it in. This won't fail the build if interface errors
occur but it should help users verify project-side fixes.
=> Pass-down -downgrade-typecheck-interface-error to interface verification job

Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
I just added this to a larger pull, apple/swift#39921, that updates the compiler repo to use Android NDK 23, which got rid of binutils, so updating the archiver here too. Not too important when cross-compiling, as you can still use the system `ar` just fine, but when natively compiling in the Termux app on Android, `llvm-ar` is now the default archiver there.
I also had to [patch llbuild to get SPM to use `llvm-ar`](https://github.com/termux/termux-packages/commit/a21ea2ad06d702b8ae59e9e9530cd5cf1857609c#diff-efe86a3fbe5cd2f773ba4c774b09efbbf5a2c6099fe15a6ab44212ac55f7d5b4R9), otherwise it just uses the first `ar` it finds in the system `PATH`. @neonichu, this means SPM doesn't use the `--toolchain` or `-Xswiftc -tools-directory` paths passed in for static library products that call the …
=> Android: switch the archiver for static libraries over to llvm-ar

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Driver/ModuleOutputInfo.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Sources/SwiftDriver/Utilities/Diagnostics.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Support -module-alias in driver 
Parse input and store aliases in ModuleOutputInfo
Validate input aliases and emit diagnostics 
Resolves rdar://85523248
=> Introduce module aliasing to Driver

Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Otherwise, for example, when using the `emit-module-separately` mode, the `emit-module` job is *always* mandatory, even on a null build.
Resolves rdar://85554508
=> [Incremental Builds] Skip `jobsBeforeCompiles` if no compilation jobs are to be run.

Tests/IncrementalImportTests/HideAndShowFuncInStructAndExtensionTest.swift
Windows uses a different EOL marker (CR+LF) compared to Unix (LF).  This
accounts for that in the output enabling the
HideAndShowFuncInStrucAndExtensionTest to now pass on Windows.
=> Tests: account for EOL marker differences

Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift, Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift, Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift, Sources/SwiftDriver/SwiftScan/SwiftScan.swift, Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Use real module names during dependency scan / construct deps graph and imports
Add tests using driver dependency scanner and fallback frontend scanner
Make isFramework optional in SwiftModuleDetails and SwiftPrebuiltExternalModuleDetails (else throws JSON Decoding error)
Resolves rdar://85525296
=> Module aliasing: use real module names to resolve graph during dependency scan

Sources/SwiftDriver/Toolchains/Toolchain.swift
Avoid injecting a `_EXE` into environment variables for tool
replacements on Windows.  This allows us to use the same variable across
all the platforms.
=> Toolchains: adjust environment variable generation on Windows

Sources/SwiftDriver/Driver/WindowsExtensions.swift
We would previously try to strip the extension without care about the
length.  This can potentially cause an out-of-bounds access (which
fortunately an assert helped caught this!).  Add a guard to avoid an
invalid access.  This is important to enable a subsequent change that
makes finding tools more flexible for cross-platform testing.
=> Driver: be more careful about extension handling

Sources/SwiftDriver/Toolchains/Toolchain.swift
Slightly older compilers may error out here with:
```
error: cannot infer contextual base in reference to member 'replacingOccurrences'
.replacingOccurrences(of: "-", with: "_")
~^~~~~~~~~~~~~~~~~~~~
```
Resolves rdar://86127658
=> Fix build break with an ambiguous contextual base on older compilers

Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
The motivation is that I'm trying to fix a linker/LTO warning that shows up when LTO-ing together C and Swift code:
```
ld: warning: linking module flags 'SDK Version': IDs have conflicting values ('[2 x i32] [i32 11, i32 0]' from clang.o with '[3 x i32] [i32 11, i32 0, i32 0]' from ld-temp.o)
```
Apparently, Clang passes -target-sdk-version 11.0, and the *old* Swift driver does as well, but the new Swift driver uses 11.0.0. Let's fix that.
=> Format SDK versions in -target-sdk-version as major.minor when patch number is zero

Sources/SwiftDriver/Toolchains/Toolchain.swift
This more aggressively adds the `.exe` extension to the tools on
Windows.  This allows a greater number of tools to be found on Windows
as the proper name is now used.
=> Toolchain: be more aggressive about adding extensions

CMakeLists.txt, Utilities/build-script-helper.py
motivation: SwiftSystem provides infra that can replace some bespoke implementations in TSC and, improving the cross-platform support. as such we are adding it as a dependency to TSC
changes: add SwiftSystem to CMake setup so it can be included in CMake based builds
=> begin to integrate SwiftSystem

Sources/SwiftDriver/IncrementalCompilation/Multidictionary.swift, Tests/SwiftDriverTests/MultidictionaryTests.swift
Add a reverse index to Multidictionary to make value removal more efficient in large dictionaries.
In a module with several tens of thousands of definitions in the dependency graph, disappearing nodes from the graph becomes very expensive as removeOccurences(of:) is an O(number_of_keys) operation. This change makes removeOccurrences(of:) O(number_of_keys_containing_the_value), which can be tens of thousands of times faster.
The cost of this change is that insertValue(:forKey:) and removeValue(:forKey:) are approximately twice as expensive, and the dictionary will use about twice as much memory. For small graphs, this difference should be trivial. For my several-tens-of-thousands-of-definitions graph, it takes about four seconds to load rather than two. The driver doesn't seem to use …
=> Add a reverse index to Multidictionary

Sources/SwiftDriver/Driver/Driver.swift
The deserialisation process may fail for reasons other than unable to
load the file.  This was occurring on Windows and was giving an
erroneous error message that the file could not be loaded when the issue
was the contents of the file.  This threads that error through the
wrapped error type rather than just dropping the error on the floor.
=> Driver: wire through the actual error from OFM loading

Sources/SwiftDriver/Driver/Driver.swift
This allows finding the driver properly on Windows for testing purposes.
=> Driver: support extension-less lookup of swift

Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Utilities/Triple+Platforms.swift
Since this feature flag reflects the inverse of the check in the legacy driver,
clarify what the new meaning is and clean up its usages.
=> Clean Up Native ARC Feature Flag

Tests/SwiftDriverTests/CrossModuleIncrementalBuildTests.swift
This adjusts the output file map emission to ensure that the path is
properly escaped.  This was causing problems on Windows, where the path
separator (`\`) was not escaped and would therefore generate invalid
JSON.  This allows the CrossModuleIncrementalBuildTests to now pass on
Windows.
=> Tests: properly emit the output file map

Tests/SwiftDriverTests/SwiftDriverTests.swift
`dynamicLinker` is an entirely inappropriate name for this variable.
This is not the "dynamic linker" (a synonym for the loader), but rather
the "static linker" (aka linker) on Darwin or the linker driver on
non-Darwin targets.  `linkerOrLinkerDriver` seems overly verbose, and
since the linker is rarely meant to be invoked directly by the user (as
traditional Unix linking semantics imply meaning to the order of
arguments), name the variable `linkerDriver`.  This is purely an
aesthetic change, but one that caused me significant amount of
discomfort.
=> Tests: rename variable (NFC)

Tests/SwiftDriverTests/SwiftDriverTests.swift
This makes it easier to diagnose issues as we can immediately tell what
the two values are.
=> Tests: prefer `XCAssertEqual` over `XCAssertTrue(... = ...)`

Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
This adds handling for passing along link library requests from the
driver to the linker driver.  This was detected by running the test
suite on Windows.  We now pass the
SwiftDriverTests.SwiftDriverTests/testLinking test on Windows.
=> SwiftDriver: pass along link library requests on Windows

Tests/SwiftDriverTests/SwiftDriverTests.swift
When targeting ELF, we use the `swift-autolink-extract` tool to extract
extra arguments for autolinking as ELF does not have a blessed universal
mechanism for doing so.  This adjusts the tests to account for that.
=> Tests: generalise the handling for ELF vs non-ELF targets

Tests/SwiftDriverTests/SwiftDriverTests.swift
Rather than hardcoding the paths and the path separator, we now compute
the actual locations to ensure that we can correctly represent the path
representation natively on the target.  This enables the correct
representation on Windows.
=> Tests: improve native path representation

Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Sources/SwiftDriver/Execution/DriverExecutor.swift, Sources/SwiftDriver/Execution/ParsableOutput.swift, Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift
This adds the handling for abnormal process termination on Windows.
With this, we can now track processes which exit abnormally, indicating
failure.  This was identified by the saveTemps test which now passes on
Windows.  Add an additional test case for the new message type to
differentiate the abnormal exit due to an exception from a signalled
exit which is limited to Unixish platforms.
=> SwiftDriver: address TODO about abnormal process termination

Tests/SwiftDriverTests/SwiftDriverTests.swift
This is based on #940; only the last commit is relevant.
=> Tests: compute the `TestInputs` path more robustly

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift, Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift, Sources/SwiftDriver/Toolchains/DarwinToolchain.swift, Sources/SwiftDriver/Utilities/System.swift, Sources/SwiftDriver/Utilities/VirtualPath.swift
They should reflect the semantics of what they intend to represent,
which is "Darwin-based platform".
rdar://85918430
=> Don't unnecessarily constrain ifdefs to macOS

Sources/SwiftDriver/Driver/Driver.swift, Sources/SwiftDriver/Jobs/EmitModuleJob.swift, Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Scheduling a separate emit-module job for whole-module builds, combined with the integrated driver in the build system, will allow to parallelize what used to be essentially sequential builds. This mode unblocks building dependents early by duplicating some work in two processes, it requires more cpu work for a faster wall clock build time. Another advantage of this mode is the resulting swiftmodule is lighter from a classic whole-module build.
rdar://85976762
=> Turn on emit-module-separately for whole-module builds by default

Tests/SwiftDriverTests/APIDigesterTests.swift, Tests/SwiftDriverTests/IncrementalBuildPerformanceTests.swift, Tests/SwiftDriverTests/IncrementalCompilationTests.swift, Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
Process away the body of the tests on Windows to avoid the warning
during the build.  This is hopefully temporary as the tests should
not be skipped, but require further investigation and skipping the
tests enables running the test suite completely on Windows.
=> Tests: avoid some warnings on Windows (NFCI)

Tests/SwiftDriverTests/JobExecutorTests.swift, Tests/SwiftOptionsTests/OptionParsingTests.swift
Windows does not use the same quoting strategy at Unix platforms.
Adjust the expectations on Windows to match.
=> Tests: handle differences in quoting on Windows

Tests/SwiftDriverTests/JobExecutorTests.swift
A copy-paste error was accidentally introduced in the attempt to get the
full test suite running on Windows (even though it did not pass).  This
corrects that mistake.
=> Tests: correct `-sdk` parameter for Windows

Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
Reverts apple/swift-driver#910
To check if this caused the failure in the ASAN bot
https://ci.swift.org/job/oss-swift-incremental-ASAN-RA-macos/6155/
=> Revert "Query compiler supported features from `libSwiftScan`, when one is present"

Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
Correct the handling for non-`-l` linker options on Windows.  We now
correctly forward the user-specified linker search paths to the linker
through the linker driver.
=> SwiftDriver: pass along linker options to the linker driver

Tests/SwiftDriverTests/SwiftDriverTests.swift
The immediate mode execution will not set an environment variable (i.e.
`DYLD_LIBRARY_PATH` or `LD_LIBRARY_PATH`) as the runtime components are
searched for by `Path` or by the explicit path that a manifest may
provide for a UWP application.
=> Tests: correct environment testing for Windows

Utilities/build-script-helper.py
https://github.com/apple/swift-driver/pull/915 added a CMake dependency on swift-system.
Since then, the CMake build of the driver builds swift-system, but when the `install` action is triggered, the dependency's module and shared library are not installed into the toolchain. As a result, built toolchains are unable to invoke swift-driver due to the missing dylib.
This ensures that much like other driver dependencies (TSC, ArgumentParser), we also install SwiftSystem.
Resolves rdar://86754758
=> Install `swift-system` into the toolchain during CMake build's `install` action

Tests/SwiftDriverTests/SwiftDriverTests.swift
This explicitly passes a SDK to the driver invocation as on Windows, the
default SDK does have a SDKSettings.json which does not match the macOS
one.  This results in a spurious warning which causes the test to fail.
Pass the SDKChecks SDK root as the SDK for test.  This allows
SwiftDriverTests.SwiftDriverTests/testEnvironmentInferenceWarning to
pass on Windows.
=> Tests: explicitly pass a SDK for environment inference tests

Tests/TestUtilities/OutputFileMapCreator.swift
Correct the path separator for the output file map entries.  This
has no impact on the test coverage but does make it easier to copy-paste
values and to work with the values on Windows.
=> Tests: correct output file map entries

Tests/SwiftDriverTests/SwiftDriverTests.swift
The difference between the work graph is due to the use of the autolink
extract step which is ELF specific, not host specific.  This configures
the path to check the output format instead.
=> Tests: remove an unnecessary target host check

Tests/IncrementalImportTests/HideAndShowFuncInStructAndExtensionTest.swift
This removes a stray space which was noticed while working on the
windows test suite coverage.
=> Tests: remove stray space (NFC)

Package.swift
Update `swift-llbuild` and `swift-tools-support-core` dependencies to use the 'release/5.6' branch instead of `main`.  This is needed before we can switch over SwiftPM to depend on 'release/5.6'.
=> [5.6] Update package dependencies to use the 'release/5.6' branch

Package.resolved, Package@swift-5.5.swift
This brings `Package@swift-5.5.swift` up to parity with recent change in https://github.com/apple/swift-driver/pull/929
=> [5.6] Update `5.5`-specific manifest dependencies to `5.6`

Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift, Sources/SwiftDriver/Execution/DriverExecutor.swift, Sources/SwiftDriver/Execution/ParsableOutput.swift, Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift, Sources/SwiftDriverExecution/MultiJobExecutor.swift, Tests/SwiftDriverTests/ParsableMessageTests.swift
This adds the handling for abnormal process termination on Windows.
With this, we can now track processes which exit abnormally, indicating
failure.  This was identified by the saveTemps test which now passes on
Windows.  Add an additional test case for the new message type to
differentiate the abnormal exit due to an exception from a signalled
exit which is limited to Unixish platforms.
=> [5.6] SwiftDriver: address TODO about abnormal process termination

Utilities/build-script-helper.py
This is now a dependency of the main `libArgumentParser.dylib` and not having it installed casuses `Library not loaded` errors when using the toolchain.
Resolves rdar://86859779
=> [Build Script Helper] Install `libArgumentParserToolInfo.dylib` into the toolchain

Sources/SwiftDriverExecution/MultiJobExecutor.swift, Tests/SwiftDriverTests/SwiftDriverTests.swift
When a compile job fails, remove all outputs except the diagnostics file.
rdar://19945961
=> Clean up stale compiler outputs

Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This adjusts the driver invocation to add in additional module search
paths for the tests which seem to be required on Windows.  It is
unclear why this is needed for the swift-driver, as the search paths
should be derived from `-sdk`.  Ensuring that the tests pass is the
first step towards making swift-driver viable for Windows though.
=> Tests: make ExplicitModuleBuildTests pass on Windows

Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Introduce a sleep in the "touch" operation - a portable implementation
which rewrites contents to alter the mtime - though it can appear to
fail due to granularity of the time stamp.  The alteration would appear
as if it did not occur.  This sleep *before* the operation ensures that
enough time has passed between the writing of the file originally and
the rewrite which will adjust the mtime.  This may impact other
platforms (e.g. Linux) where file system mtimes can be truncated.
Darwin remains immune to this with the increased resolution for file
times with the APFS transition.
This enables a subset of the tests to now pass on Windows.  Although not
explored, it is possible that this also allows more stability for tests
which previously failed on Linux.
Special thanks to Artem Chikin for …
=> SwiftDriverTests: introduce a `sleep` for file modification

Sources/SwiftDriver/IncrementalCompilation/DependencyGraphDotFileWriter.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/NodeFinder.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift, Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Clarify what it means to have a nil `dependencySource` by replacing the optional with an enumeration.
=> Refactor, representing no source via an enum

Sources/SwiftDriver/IncrementalCompilation/DependencyGraphDotFileWriter.swift, Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift, Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift, Tests/SwiftDriverTests/CrossModuleIncrementalBuildTests.swift, Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift, Tests/SwiftDriverTests/NonincrementalCompilationTests.swift
For the sake of clarity, try an enum instead of a boolean for `isProvides`.
=> [NFC] Replace isProvides Bool with an enum

Tests/SwiftDriverTests/JobExecutorTests.swift
This allows the source modification during build tests to pass on
Windows where nanosecond precision is not available for file
modification times.
=> Tests: inject a sleep for test modifications

Sources/SwiftDriver/Utilities/System.swift
Escape the quote in the string rather than use the literal support as
the behaviour differs across versions:
```
error: multi-line string literal content must begin on a new line
```
=> Utilities: avoid use of raw string literals

Sources/swift-driver/main.swift
This is identical behavior on bash but when spawning the process using posix_spawn (like llbuild does) the exit code of (SIGINT | 0x80) == 130 gets encoded as an exit code rather than the uncaught signal.
rdar://77055430
=> Kill the process after cleanup on interrupt

Sources/SwiftDriver/Driver/Driver.swift
This allows `libSwiftDriver` clients to ask the driver to serialize its incremental state all at once: the module dependency graph and the build record.
=> Make `writeIncrementalBuildInformation` a public method.

Sources/SwiftDriver/Driver/Driver.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/979
----------------------------------
• Explanation: Build systems can use libSwiftDriver for planning target builds, instead of shelling out to `swiftc`. Incremental builds in such cases have to be managed by the build system by exercising a relevant API surface of libSwiftDriver's incremental machinery. In order to get correct incremental builds, the driver must serialize its incremental state after compilation, to ensure that successive incremental builds can do the right thing with up-to-date records of previous compilation. Today, this serialization is done automatically by the driver in its `run` method, but build systems may not use this method at all and instead have its own methods of job execution. As such, they require …
=> [5.6] Make `writeIncrementalBuildInformation` a public method.

Sources/swift-driver/main.swift
`kill` is a non-portable function from the Unix C library.  Replace the
functionality with Windows SDK's `TerminateProcess`.  Encode `SIGINT` as
a NT error for the process termination code.
=> swift-driver: repair the build after #980
