swiftlang/swift-driver

- Sources/SwiftDriver/Options/ParsedOptions.swift
This was breaking the batch-mode tests.
> Fix hasFlag computation.

- README.md
After a day without getting anything done, needed something to "lift" myself... so, here it is @harlanhaskins xD
Sorry!
> [Docs] - mark as done tokenization in response files.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Jobs/GeneratePCHJob.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/InterpretJob.swift
- Sources/SwiftDriver/Jobs/LinkJob.swift
- Sources/SwiftDriver/Jobs/MergeModuleJob.swift
- Sources/SwiftDriver/Jobs/ReplJob.swift
- Sources/SwiftDriver/Jobs/Toolchain+InterpreterSupport.swift
- Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Also cache tool paths after they have been looked up.
> Add Toolchain.overrideToolPath (and remove passing swiftCompiler path everywhere).

- README.md
REPL mode implemented in https://github.com/apple/swift-driver/pull/43
Immediate mode implemented in https://github.com/apple/swift-driver/pull/36
PCH generation implemented by @cltnschlosser in https://github.com/apple/swift-driver/pull/21
> Update README todo list

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Previously it would make n jobs (where n is number of inputs).
> Fix batch mode one partition.

- Package.swift
- Sources/SwiftDriver/Execution/ParsableOutput.swift
- Tests/SwiftDriverTests/AssertDiagnosticsTests.swift
- Tests/SwiftDriverTests/Helpers/AssertDiagnostics.swift
To match SwiftPM, set the macOS minimum deployment target to 10.10.
> Set macOS minimum deployment target to 10.10.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Driver/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Driver/OutputFileMap.swift
- Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift
- Sources/SwiftDriver/Incremental Compilation/IncrementalCompilation.swift
- Sources/SwiftDriver/Incremental Compilation/InputIInfoMap.swift
- Sources/SwiftDriver/Incremental Compilation/SourceFileDependencyGraph.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/InterpretJob.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Utilities/PredictableRandomNumberGenerator.swift
- Sources/SwiftDriver/Utilities/System.swift
- Sources/SwiftDriver/Utilities/Triple.swift
- Sources/SwiftDriver/Utilities/VirtualPath.swift
> Improve formatting

- Sources/SwiftDriver/Execution/JobExecutor.swift
- Sources/SwiftDriver/Explicit Module Builds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/Job.swift
- Tests/SwiftDriverTests/IntegrationTests.swift
- Tests/SwiftDriverTests/JobExecutorTests.swift
Fixes test/Driver/assert.swift
Fixes test/Driver/crash.swift
> Add diagnostics for failing/signalling jobs

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
The test invokes the driver using `-experimental-explicit-module-build` and ensures an executable is produced without errors. 
The test runs for a long time because it must compile the `Swift` module, currently just testing how much overhead it will be with CI's toolchain.
> [Explicit Module Builds] Add end-to-end explicit module build compile test

- Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift
When traversing transitive dependencies of some module, there may be many paths that encountered the same module.
We currently ensure we only generate a compile job for each module once, but do not ensure each dependency gets
added as an input to the build command once. This PR fixes that.
> [Explicit Module Builds] Avoid adding duplicate module dependency options to compile commands.

- Sources/SwiftDriver/Explicit Module Builds/ExplicitModuleBuildHandler.swift
Post-merge review feedback for #154
> Tidy up addedDependenciesSet query/insertion.

- Tests/SwiftDriverTests/AssertDiagnosticsTests.swift
- Tests/SwiftDriverTests/Helpers/AssertDiagnostics.swift
> [Gardening] Fix a couple of warnings in tests

- Sources/SwiftDriver/Explicit Module Builds/InterModuleDependencyGraph.swift
To match outputted structure from: https://github.com/apple/swift/pull/32956
Actual logic support to come.
> [Explicit Module Build] Add compiledModuleCandidates to the module dependency graph.

- Sources/SwiftDriver/Utilities/Triple.swift
We can re-structure this properly later, but for now this should unblock things.
> Allow for major macOS version 11.

- Sources/SwiftDriver/CMakeLists.txt
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift
Looked over the FIXME comments. Decided to start with a simple task like renaming the IncrementalCompilation class to IncrementalCompilationTests. 
Ran the tests and everything looks good on my side.
> Refactor IncrementalCompilation to IncrementalCompilationState

- Utilities/build-script-helper.py
- Only set environment variables for executables built by `swift` `build-script` as a part of a toolchain.
- Export `SDKROOT` on Darwin to ensure tests always have an SDK if one is not specified explicitly. (this mimics how SwiftPM sets up its environment for a bootstrap)
> [Build Script Helper] Improvements to build with a specified toolchain

- Sources/SwiftDriver/CMakeLists.txt
Add missing extension to new file.
> build: repair #221

- Sources/SwiftDriver/CMakeLists.txt
- Sources/SwiftDriver/Execution/DriverExecutor.swift
- Sources/SwiftDriver/Explicit Module Builds/ClangVersionedDependencyResolution.swift
- Sources/SwiftDriver/Explicit Module Builds/ModuleArtifacts.swift
- Sources/SwiftDriver/Explicit Module Builds/ModuleDependencyScanning.swift
They seem to have test-breaking interactions with `swift` trunk, causing CI failures.
> Revert #225 and #234

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Nothing exciting, just some minor cleanups I noticed.
> Update doc comments and mark additional Driver APIs as @_spi(Testing)

- Tests/SwiftDriverTests/SwiftDriverTests.swift
I'm pretty sure this was just a copy-paste error on my part 🤦
> Delete an incorrect FIXME

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
[Incremental] Add the .swiftdeps output to a compile job.
> add swiftdeps output to compile job

- Sources/SwiftDriverExecution/MultiJobExecutor.swift
As I dive into swift-driver & llbuild for incremental compilation, a bit of intention-revealing refactoring helps.
> [Incremental, NFC] Small refactoring w/ intention-revealing function names

- Utilities/build-script-helper.py
This allows us to decouple building swift-driver inside `swift`'s `build-script` from relying on SwiftPM.
This applies to both Darwin and Linux platforms.
The `Install` action is still different across Darwin and Linux, generalizing that will be followup work, once I resurrect my Linux environment. 
Resolves rdar://70060523
> [Build Script Helper] Make the 'build' action use the CMake build flow

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Consider all inputs when deciding whether supplementary output file map will be used

- Sources/SwiftOptions/OptionParsing.swift
- Sources/SwiftOptions/ParsedOptions.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Properly handle input file names after DashDash

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/LinkJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Honor working directory setting for implicit output paths

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Teach swift-driver to find tools in -tools-directory dir

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Properly set up jobs when -lto is set

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> CompileJob should take precompiled bridging header as input

- Utilities/build-script-helper.py
In particular skip tests.
Addresses rdar://70450674
> [Build Script Helper] build only the needed subset of llbuild

- Utilities/build-script-helper.py
> [Build Script Helper] clean up more LC_RPATH

- Tests/SwiftDriverTests/SwiftDriverTests.swift
And use it to also skip a part of `testNoInput`.
The driver very well may be built and tested in environments that do not have LLDB.
We should skip tests that rely on LLDB being present in such environments.
Although we've had `testNoInput` for some time, we have not been updating the set of tests that run on Linux (adding tests does not automatically make them run on linux, that requires the additional step of running: `swift test --generate-linuxmain`, which we have been forgetting to do for a while (And I wasn't aware of 😬)). Now, some recent PR updated this list so we've noticed it failing on some Linux build bots where there is no LLDB. 
e.g. https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_04/14947/
> Common out utility to check if LLDB is present, to skip tests that rely on LLDB

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
A few related fixes for static linking on macOS:
- Don't pass options like -platform_version, -force_load, etc. to the static linker
- Don't use .swiftmodule files as static linker inputs
- Don't pass -lto_library to the static linker, and only pass it to the dynamic linker if we're actually performing LTO
> Static linking fixes on Darwin

- Sources/SwiftDriver/Incremental Compilation/IncrementalCompilationState.swift
In preparation for wave integration.
> [Incremental] Minor cleanups to `IncrementalCompilationState`

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This fixes Driver/sanitize_coverage.swift
> Add validation for -sanitize-coverage=

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Accept none as the value for -runtime-compatibility-version

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Input file list itself should be part of inputs of the compilation job

- Sources/SwiftDriver/Incremental Compilation/InputInfo.swift
Be clearer how running incrementally interacts with job status, and how unfinished jobs are handled.
> [Incremental] Clean up build-record status computation.

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Honor -emit-module-path for installAPI tasks

- Sources/SwiftDriver/Incremental Compilation/BuildRecord.swift
- Sources/SwiftDriver/Incremental Compilation/BuildRecordInfo.swift
> [NFC Incremental] Tiny cleanups

- Sources/swift-driver/main.swift
> ExplicitModules: use explicit modules when SWIFT_ENABLE_EXPLICIT_MODULE is set

- Sources/SwiftDriverExecution/MultiJobExecutor.swift
Otherwise the build system may complain about malformed output.
rdar://72830153
> Inform finished job only when the job has been started

- Sources/SwiftDriver/Execution/DriverExecutor.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecord.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift
- Reflow and redocument a few abstractions in the Incremental subdirectory
- Correct the style and whitespace used in a few places along the way.
> [NFC] Miscellaneous Formatting and Convention Cleanups

- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift
- Sources/SwiftOptions/ParsedOptions.swift
- Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
Untangle the nest of callbacks into a single type.
> [NFC] Sequester Incremental Build Reporting Into a Type

- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
Fix broken main resulting from two PRs with a merge race, AFAICT.
> Fix the breaks

- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift
Workaround a change in the compiler. 
rdar://problem/73984428
> [Incremental] Fix var in guard not usable

- Sources/SwiftDriver/IncrementalCompilation/BidirectionalMap.swift
- Tests/SwiftDriverTests/BidirectionalMapTests.swift
These will be needed in an upcoming PR.
> [Incremental] Add functions and tests to BidirectionalMap

- Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/NodeFinder.swift
- Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift
Move the mocking affordances out of the main line code.
> [Incremental, NFC] Move mocking functions to the testing directory

- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift
- Sources/SwiftDriverExecution/MultiJobExecutor.swift
- Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
I'll be rebasing onto master as soon as the "move mocking" PR lands.
EDIT: has been rebased.
> [NFC, Incremental] Renaming things in preparation for cross-module

- Tests/SwiftDriverTests/BidirectionalMapTests.swift
It's the latest approved version of Xcode in apple/swift, so makes sense that swift-driver should build when using it.
> Fix compile when using Xcode 12.4

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift
Both of these outputs will be printed to stderr. Without a queue, interleaving them can
lead to malformed parsable output.
rdar://75370288
> Use a global DispatchQueue to synchronize parseable outputs and driver error messages

- Package.swift
- Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift
- Sources/SwiftDriver/IncrementalCompilation/InitialStateComputer.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
- Tests/IncrementalImportTests/AddFuncInImportedExtensionTest.swift
- Tests/IncrementalImportTests/HideAndShowFuncInStructAndExtensionTest.swift
- Tests/IncrementalImportTests/RenameMemberOfImportedStructTest.swift
- Tests/IncrementalImportTests/SpecificFuncAdditionInExtensionWithinModuleTest.swift
- Tests/IncrementalTestFramework/AddOn.swift
- Tests/IncrementalTestFramework/CompiledSourceCollector.swift
- Tests/IncrementalTestFramework/Context.swift
- Tests/IncrementalTestFramework/ExpectedCompilations.swift
- Tests/IncrementalTestFramework/IncrementalTest.swift
- Tests/IncrementalTestFramework/Module.swift
- Tests/IncrementalTestFramework/Source.swift
- Tests/IncrementalTestFramework/Step.swift
- Tests/SwiftDriverTests/Helpers/AssertDiagnostics.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
- Tests/TestUtilities/DriverExtensions.swift
- Tests/TestUtilities/Fixture.swift
- Tests/TestUtilities/OutputFileMapCreator.swift
A framework based on creating structures to specify a test, with fairly minimal boilerplate and maximal flexibility.
Can represent file additions, removes, module additions, removals.
> [NFC, Incremental Imports]: A framework for multi-module incremental tests with minimal ceremony

- Package.swift
Best to be explicit about these things
rdar://75455829
> Explicitly link XCTest

- Package.swift
Xcode 12.3 and 12.4 require macOS 10.15.4.
> Bump Default Package Version to 10.15

- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Integrator.swift
Skip an unnecessary set addition.
> [Incremental] Small performance optimization

- Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
On top of @CodaFi  's intern fix (to come), seems to be worth another 10%
> [Incremental Optimization] Cache hashes for DependencyKey and ModuleDependencyGraph.Node

- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
When deserializing a `ModuleDependencyGraph`, don't record uses in a dictionary twice. Just save in an array while reading. On a project with 1,000 files, when rebuilding after just adding a newline to one file, swift-driver-new time in Instruments was reduced from 5.3 secs to 4.7.
> [Incremental, Optimization] Defer use hashing when reading a ModuleDependencyGraph

- Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
`-driver-show-incremental` doesn't show enough information when an external dependency causes recompilation. Fix that.
> [Incremental Imports] Explain more about invalidation from externals.

- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Remove a never-used stub function.
> [NFC] Remove unused test function.

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
Matching Swift PR: apple/swift#36805, rdar://76370561
> Conditionally pass musttail checking flag to frontend.

- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> [NFC] Fix typo

- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
The behavior-neutral changes that will be wanted when more tests are added:
1. Add an `inputPath` method and use it where needed.
2. Add a `write` method to factor out future input writing.
3. Eliminate many cases where the tests would just crash. Raise exceptions instead. Add 'try's.
4. Rewrite `doABuild` and return a non-optional.
> [NFC] Refactor some incremental compilation tests, prior to adding more tests

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
This PR adds a test to test input additions and fixes a bug that can manifest in nondeterministic outputs from `-driver-show-incremental`.
> [Incremental] Add input addition test and fix nondeterminism bug

- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
Minor fixes to two incremental messages.
> [NFC] Remove double-spaces and add clarification to two incremental diagnostics

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
Thanks to @CodaFi for pointing out the opportunity and the fix!
> [Incremental] More efficient sorting

- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Rename some functions to reveal intentions
- Add some Doxygen comments to clarify parameters
- Reorder some functions to ease navigation
- Reformat some function declarations
- Misc other renaming and streamlining
> [NFC, Incremental] Clean up `IncrementalCompilationTests` prior to adding more tests

- Package.resolved
- Package.swift
5.5 cherry pick of https://github.com/apple/swift-driver/pull/534
> [5.5] Bump swift-argument-parser to 0.4.1

- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
An aid to understanding the ci issue.
> [Incremental] Print the priors time delta

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> [5.5] cherry-pick -clang-target support

- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Add a test for wiring up '-no-toolchain-stdlib-rpath' in #732

- Tests/SwiftDriverTests/ParsableMessageTests.swift
This adjusts the test suite to account for the differences on Windows.
We must construct the absolute path to the working directory, which
includes the drive letter.  Furthermore, construct the paths for the
checks as relative to the working directory.  This makes the test more
explicit about it's expectations and makes it support Windows.
Windows does not support signals, even for unexpected termination.
Instead the process exits with a particular error code which encodes the
"exception".  This adjusts the test expectation accordingly.
Adjust the diagnostic expectations which do not match due to the EOL
specifier (CR+LF vs LF).
The ParsableMessageTests now pass on Windows.
> Tests: make ParsableMessageTests pass on Windows

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Some platforms expect an executable to have a certain suffix.  This
allows a hook for decorating the name accordingly.  This allows a number
of additional asserts to now pass on Windows.
> Tests: be more careful about executable names

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Specify the working directory on driver invocations to avoid test artifacts in the package root.
- Skip running tests if frontend does not support `-module-alias`
- Remove `-clang-target` on explicit module build test
> [NFC] Module Aliasing Test Cleanup

- Sources/SwiftDriver/Utilities/System.swift
This adds an initial pass for computing the command line length for the
purposes of response file triggering.  This is complicated as the
computation requires constructing the quoted string parameter to be
passed and proper command line quoting in Windows is odd.
> SwiftDriver: implement response file handling for Windows

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Use the TSC path types to compute the path strings for the output file
map resolution as `/foo_root` is not an absolute path on all platforms.
This adjustment now allows this test to pass on Windows.
> Tests: adjust the paths for output map resolution

- Tests/SwiftDriverTests/SwiftDriverTests.swift
The previous emission did not take into account separator escaping
(Windows uses `\` which must be escaped when emitted).  This corrects
the emission of the JSON content.
Once we do so, the loading of the JSON succeeds, but the tests fail as
the paths are now the Windows native paths and must be adjusted
accordingly.
> Tests: correct output file map JSON emission

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
> Test fix: import a swiftinterface that does not have objc dependency

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This adds support for handling Windows style response files.  These are
important to get correct as they are consumed by both swift and clang.
The differences will result in the `\` path separator getting discarded,
yielding invalid paths.
> Driver: add support for tokenizing a Windows-style rsp

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/APIDigesterTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Where Library Evolution is enabled
> Only emit ABI descriptors on Darwin platforms

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Driver/LinkKind.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This now surfaces the options in the error
> Improve error message for invalid LTOKind

- Sources/SwiftOptions/Options.swift
This is a follow-up of https://github.com/apple/swift-driver/pull/1019.
The related change in the swift-repo: https://github.com/apple/swift/pull/41540
> re-generate Options.swift

- Utilities/build-script-helper.py
Reverts apple/swift-driver#1021
> Revert "Update build-script-helper.py to use python3"

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Add support for `-enable-regex-literals` flag

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1047
> Revert "Revert "Add support for `-enable-regex-literals` flag""

- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
1. missing `-enable-library-evolution`
2. missing a library level flag
3. wrong library level flag
> AdopterAnalysis: diagnose several issues within .swiftinterface

- Tests/SwiftDriverTests/SwiftDriverTests.swift
This just reflows the text to make the guard pattern more canonical.
> Tests: reflow some text (NFC)

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Sources/SwiftOptions/ExtraOptions.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This PR brings rdar://83110325 and rdar://91574616 to `release/5.7`.
Original PRs:
https://github.com/apple/swift-driver/pull/1046
https://github.com/apple/swift-driver/pull/1056
> 91574616 emit module dependencies & diagnostics

- Sources/SwiftDriver/Jobs/Job.swift
- Tests/IncrementalTestFramework/CompiledSourceCollector.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Tests/SwiftDriverTests/NonincrementalCompilationTests.swift
This aligns better to what other tools show in the build log.
rdar://91820791
> Change description for lifecycle

- Sources/SwiftDriver/Jobs/Job.swift
- Tests/IncrementalTestFramework/CompiledSourceCollector.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Tests/SwiftDriverTests/NonincrementalCompilationTests.swift
Reverts apple/swift-driver#1065
> Revert "Change description for lifecycle"

- Utilities/build-script-helper.py
This was just a run of 2to3 on this script.
Fixes https://github.com/apple/swift/issues/58528
> Update build-script-helper to python3

- Utilities/build-script-helper.py
This came from the python2 -> python3 conversion and https://github.com/apple/swift-driver/pull/1087
> Always run tests in parallel

- Utilities/build-script-helper.py
Reverts apple/swift-driver#1092
> Revert "Always run tests in parallel"

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Swift-driver support for the flag being added in https://github.com/apple/swift/pull/42394
> Add support for `-file-prefix-map`

- Utilities/build-script-helper.py
Cherry-pick of https://github.com/apple/swift-driver/pull/1087
----------------------------------------------------------------
This was just a run of 2to3 on this script.
Fixes https://github.com/apple/swift/issues/58528
> [5.7] Update build-script-helper to python3

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This reverts commit 3294e33f4a5d358b9053bf82a494333d8246feaa, reversing
changes made to 80873b0623b31101ec4fe5ee32ad70b543f0587e.
This is blocking pull request testing
> Revert pull request #1147

- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Relands apple/swift-driver#991, and fixes related test regression.
cc @artemcm @compnerd
> Revert "Revert "Disfavor current working directory when looking up executables""

- Sources/SwiftDriver/Utilities/Version.swift
Add a file copyright header to a newly minted file.
> Utilities: add missing file header

- Sources/swift-build-sdk-interfaces/main.swift
> PrebuiltModuleGen: create absent module cache directory

- Sources/swift-help/main.swift
> Remove package-collection and package-registry from top-level command help

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Refs https://github.com/apple/swift/pull/64088
> [cxx-interop] Re-run `makeOptions` to generate `-cxx-compatibility-mode`.

- .gitignore
This file is automatically generated by VS Code, so there's little sense in tracking its addition. If one would like to add customized launch configurations, those can still be added with `git add -f`.
> Add `.vscode/launch.json` to `.gitignore`

- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/swift-build-sdk-interfaces/main.swift
> Prebuilt-module-generation: support a mode that aggregates broken interfaces as a JSON output for easy comparision

- Sources/SwiftDriver/Driver/DebugInfo.swift
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1473
> Revert "Revert "Make the DWARF version configurable.""

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
Update for https://github.com/apple/swift/pull/70046
Updated by 'makeOptions'
> Update Options.swift for '-disable-sandbox'

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/SwiftScan/SwiftScanCAS.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
> [Caching] Add CAS size management APIs

- Sources/swift-driver/main.swift
Resolves https://github.com/apple/swift/issues/70932
> Resolve main executable symlink when looking up driver-adjacent subcommand binaries

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
For https://github.com/apple/swift/pull/73725
> Add In-process plugin server path

- Package.resolved
- Package.swift
> Bump `swift-argument-parser` to 1.4.0

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This is a complementary change to the change in https://github.com/swiftlang/swift/pull/76363
> Add -print-diagnostic-groups

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Also fix 'testDOTFileEmission' to correctly escape strings in the Linux code-path
> [Test] Fixup tests requiring `.removingAutolinkExtractJobs`

- Sources/SwiftDriver/Toolchains/Toolchain.swift
Shortcut the `xcrun` based finding of tools to immediately fail on non-macOS platforms, returning `nil`. This should help non-macOS platforms by avoiding the unnecessary search paths and failing to execute the command which is not found.
> Toolchains: disable `xcrun` commands on non-Darwin platforms

- Sources/SwiftDriver/Utilities/System.swift
Fix building on FreeBSD. Tested on x86_64 FreeBSD-14.1-RELEASE-p6
> [FreeBSD] Fix FreeBSD build

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
Pass -nostdlibimport through in the same manner as -nostdimport.
rdar://147966272
> Pass -nostdlibimport through

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Reverts swiftlang/swift-driver#1877
> Revert "[Explicit Module Builds] Adopt new direct-import field for Swift source modules"

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Reverts swiftlang/swift-driver#1886
> Revert "[6.2 🍒][Explicit Module Builds] Adopt new direct-import field for Swift source modules"

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
The absolute path for the output modules are used by LLDB to look up modules on disk. Revert before LLDB can understand CAS.
This reverts commit 90c6ece2360730a19baed7d6c5797310945bea32.
rdar://150334469
> Revert "[SwiftCaching] Don't leak output path in the explicit modulemap JSON"

- Sources/SwiftDriver/Jobs/APIDigesterJobs.swift
- Sources/SwiftOptions/Options.swift
Sync the options to add support for `-module-import-from-cas`..
> [Options] Sync Options.swift with compiler
