- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
This adds a couple more strategic `sleep` invocations to ensure that
filesystems without nanosecond precision on file timestamps can be
accommodated.  This allows the incremental compilation tests to now pass
on Windows.
> Tests: add some sleeps for file system modifications

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
TSAN is not supported on Windows at the current time.  This excludes the
tests on Windows as they cannot be supported.
> Tests: disable TSAN tests on Windows

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
The Windows toolchain is setup with a split SDK/toolchain and relies on
being able to compose the two.  For some reason, this requires
additional include paths to be passed to the swift-driver implementation
(`-sdk` is sufficient with the C++ driver).  For now, add the additional
include paths to allow the tests to pass.
> Tests: add shims and stdlib search paths to driver

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Jobs/SwiftHelpIntroJob.swift
- Sources/swift-help/main.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Now that there is a more user-friendly help intro that shows by
default, stop launching the REPL when there are no input files.
Launch the REPL explicitly with the `repl` subcommand.
> Stop launching REPL when there aren't inputs

- Tests/IncrementalTestFramework/Module.swift
Add a sleep before re-creating the files for the incremental tests.
For filesystems where the timestamp granularity is insufficient, we
would previously fail to re-compile sources as the timestamps would
be identical.  This allows the last of the incremental testsuite to
now pass on Windows.  There are some stability issues remaining for
investigation, a handful of skipped tests due to tools-support-core
and one concern - include path testing.  Once those have been given
a chance for investigation, it will likely be sufficient completion
for enabling swift-driver on Windows with SPM as well as the driver
binary in the installed image.
> IncrementalTestFramework: add filesystem workarounds

- Sources/SwiftOptions/OptionParsing.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/SwiftOptionsTests/OptionParsingTests.swift
Previously `swiftc --invalid foo.swift` would be interpreted as
`swiftc -- foo.swift`. Now we fail in this case since `--invalid` is
likely to be a typo regardless of whether you meant to do `-- invalid`
or `--something-valid`.
> Throw error for invalid double dash argument

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Un-hardcode the explicit target triple for the test.  This allows the
test to run on Windows where there is no `ld` (nor `ld.exe`).  This then
uncovers the fact that the windows toolchain did not honour
`-tools-directory`.  Fixing that uncovers the fact that the lookup for
the tool will fail as the empty file does not get identified as a
binary.  To work around that, we now emit a 97-byte PE binary that is
correctly identified as a binary as the contents.  This will never be
executed and so should be fine to emit on all platforms.  Note that the
identified linker is different between Darwin and non-Darwin as the
behaviour of the driver is different - non-Darwin uses clang, while
Darwin uses `ld` (ld64) directly.
Thanks to @artemcm for the discussion on how to fix this properly.
> Windows: support `-tools-directory`

- Tests/SwiftDriverTests/SwiftDriverTests.swift
This is based on #946 and transitively on #940.  Only the last commit is relevant.
> Tests: explicitly pass a ld for Darwin targets

- Sources/swift-build-sdk-interfaces/CMakeLists.txt
- Sources/swift-driver/CMakeLists.txt
- Sources/swift-help/CMakeLists.txt
This is the first and last step towards enabling swift-driver on
Windows.  The current swift-driver test suite passes on Windows, and
with the changes now merged, `swift build --use-integrated-swift-driver`
works.  This change will extract the tools so that we can package them
up.  This sets the stage for the last change needed in SPM and allows
experimenting with packaging now.
> build: install the executable targets

- Sources/swift-help/main.swift
Users know what they're doing by using `swiftc` instead of `swift`. Subcommand info is useless for `swiftc` users and should be eliminated.
> Hide intro for `swiftc --help`

- Sources/SwiftDriver/Utilities/Triple+Platforms.swift
Remove a convenience initializer - it's better to be absolutely clear about platform bounds when describing
feature availability.
> [NFC] Be Explicit About tvOS Feature Availability

- CMakeLists.txt
- Sources/CSwiftScan/CMakeLists.txt
- Utilities/build-script-helper.py
This will allow us to not install shared libraries of TSC, ArgumentParser, etc. into the toolchain when installing the driver.
This would also help avoid having to do things like:
https://github.com/apple/swift-driver/pull/963
https://github.com/apple/swift-driver/pull/953
> [CMake Build] Build and link driver dependencies as static libraries

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This test does not fail with recent toolchain snapshots, but seems to fail when using older (shipping) toolchains.
> Skip currently-failing `testModuleAliasingPrebuiltWithScanDeps`.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This patch loosens the restriction for building deprecated iOS targets
to only when the user attempts to compile a binary or emit IR.
This allows the compiler to continue building swift modules and
interfaces for newer deployment targets.
The error message is also slightly modified to allow the same message to
apply to different platforms.
resolves: <rdar://87898177>
> Loosen restriction for building deprecated iOS targets

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This PR adds support to the flag `-file-compilation-dir`, which simply forwards the flag to frontend.
There is another [PR](https://github.com/apple/swift/pull/40735) for old driver.
Need both PR to keep all implementations in sync.
> Support `-file-compilation-dir`

- Sources/SwiftDriver/Jobs/LinkJob.swift
The non-Darwin targets use clang as the linker driver.  As a result, the
non-Darwin targets implicitly support response files (clang will expand
it if the linker does not support response files or file lists).
Unfortunately, the Darwin target manually invokes ld, which requires
re-implementing the handling there.  To complicate things further, older
ld64 does not support response files, but does support linker file
lists, while newer ld64 supports both.  Ideally, Darwin would also use
clang as the linker driver to homogenise the paths.
This is required for Windows support as the command line limit is much
lower on Windows than on Linux - nearing 4k which is possible to exceed
when building a larger project (e.g. swift-driver).
> SwiftDriver: enable response files on LinkJobs

- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This adjusts the response file emission to follow the clang behaviour.
Doing so allows the use of response files on Windows to be passed to
clang, which will default to POSIX style response files unless
explicitly passed `--rsp-quoting=windows`.  This allows for a single
path for the emission across platforms, and avoids having to deal with
the dynamic switching of the response file formats.  With this change,
ignoring the serialization issue, it is now possible to build
swift-driver with swift-driver.
> SwiftDriver: change the response file emission

- README.md
The Windows path is mature enough to support building swift-driver with swift-driver as the driver.  There is one remaining issue is a clang issue that was uncovered by the new driver.
> README: update platform status

- Sources/swift-build-sdk-interfaces/main.swift
- Sources/swift-driver/main.swift
These modules did not use any of the `TSCLibc` interfaces but relied on
the module's re-exported libc import.  Simply inline that and remove the
dependency on `TSCLibc`.  On Linux and Apple platforms, this does not
have much impact, however, Windows does not support static linking of
Swift content yet.  As a result, this avoids an unnecessary dynamic
library being linked and increasing the dirty memory of the process.
> remove unnecessary `TSCLibc` dependency

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The origin [PR](https://github.com/apple/swift-driver/pull/968) is merge into main. 
In short, this flag gives us identical debug info paths regardless of what location we compiled the file from.
It's a small but useful feature, and hope it can happen on Swift 5.6.
The PR to merge into Swift 5.6 in Swift is [here](https://github.com/apple/swift/pull/41062)
Resolves [SR-5694](https://bugs.swift.org/browse/SR-5694).
> Support -file-compilation-dir

- CMakeLists.txt
- Sources/CSwiftScan/CMakeLists.txt
- Utilities/build-script-helper.py
Reverts apple/swift-driver#965
Resulting toolchains with this change seem to be unable to find `libllbuild.dylib`.
> Revert "[CMake Build] Build and link driver dependencies as static libraries"

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationProtectedState.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift
- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/GeneratePCHJob.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Utilities/VersionExtensions.swift
- Sources/swift-build-sdk-interfaces/main.swift
- Sources/swift-driver/main.swift
- Tests/SwiftDriverTests/APIDigesterTests.swift
- Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift
- Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift
- Tests/SwiftDriverTests/IncrementalBuildPerformanceTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Tests/SwiftDriverTests/JobExecutorTests.swift
- Tests/SwiftDriverTests/ParsableMessageTests.swift
This explicitly identifies the TSCUtility interfaces that SwiftDriver
depends on.  This helps identify a "burn down list" of interfaces that
remain in TSC(Utility) which are in use.  As these interfaces are
replaced, we can easily monitor the remaining interfaces that are in
use.
> SwiftDriver: explicitly indicate the TSCUtility interfaces

- Tests/SwiftDriverTests/CrossModuleIncrementalBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/JobExecutorTests.swift
- Tests/SwiftDriverTests/ParsableMessageTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/OutputFileMapCreator.swift
- Tests/TestUtilities/PathExtensions.swift
This adds a new helper function to create the native path string and
escape it in a single operation.  This reduces some of the verbosity
at the call sites.  The desire is to eventually remove the extension
on `String` and be able to simplify all the call sites.
> Tests: introduce `AbsolutePath.nativePathString(escaped:)`

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This replaces some of the early string conversion of paths to allow the
use of the newer `nativePathString(escaped:)` functions.
> Tests: remove some early stringification of paths

- Tests/SwiftDriverTests/CrossModuleIncrementalBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/PathExtensions.swift
This cleans up the remaining instances of the
`String.nativePathString()` and `String.escaped()` which were overly
broad extensions and poorly named in favour of the new
`AbsolutePath.nativePathString(escaped:)` and
`VirtualPath.nativePathString(escaped:)`.
> Tests: clean up remnants of the old string extensions

- Sources/SwiftDriver/CMakeLists.txt
- Sources/SwiftDriver/SwiftScan/Loader.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
This migrates the TSCUtility helpers for the loader to swift-driver in
order to enable deprecating the utility functions in tools-support-core.
This family of functions interacts with the dynamic linker (aka loader)
to loader and unload modules and lookup symbols by name.  The migration
takes the opportunity to adjust the API surface a small amount to read
more naturally in Swift rather than being a wrapper layer over the Unix
C APIs.
> SwiftDriver: migrate and alter TSCUtility.dl*

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
This adds in the special case handling for static linking on Windows.
clang is unable to drive the static linking process and we must
replicate the C++ driver behaviour here.  Unfortunately, the librarian
is invoked as a modified linker invocation, and we have two different
implementations that we support (as well as the opportunity to use an
alternative).  This wires up `-use-ld=lld`, `-use-ld=lld.exe` and
`-use-ld=lld-link`, `-use-lld=lld-link.exe` to behave identically and
use lld.  The default linker remains the MSVC linker (link.exe), both of
which are invoked as the librarian by the second argument being `/LIB`.
This allows building static libraries with the swift-driver.  This was
not caught in previous testing due to the swift-package-manager not
actually generating a static …
> SwiftDriver: repair the static linking support for Windows

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This patch adds a new Darwin Swift driver environment variable in the spirit of
RC_DEBUG_OPTIONS, called RC_DEBUG_PREFIX_MAP, which allows a meta build tool to
add one additional -fdebug-prefix-map entry without the knowledge of the build
system.
See also https://reviews.llvm.org/D119850
rdar://85224717
> Darwin: introduce a global override for debug prefix map entries 

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The driver splits the compile job into two jobs: one for creating the object file, one for emitting the swiftmodule.
For the swiftmodule-job the driver adds -experimental-skip-non-inlinable-function-bodies-without-types.
This breaks CMO, because in CMO, the inlinable-decision is not derived from the AST but done in the optimizer.
As a quick hack we could disable -experimental-skip-non-inlinable-function-bodies-without-types.
But for CMO, the two-job approach is highly problematic, because it risks the two compile jobs to get out of sync, e.g. by different command line options, indeterministic behavior, etc. This can result in unresolved symbol errors, which are very hard to debug.
This change also adds a new option `-disable-cmo` to disable cross-module-optimization. It can be used to go …
> fix cross-module-optimization builds and add the option `-disable-cmo`

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
This introduces a new `clangxx` tool which maps to `clang++`.  This is
required to ensure that we are able to support linking against the C++
runtime with C++ interop is enabled.
> Toolchains: introduce `clangxx` tool (NFC)

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This adjusts the linker job construction to switch the linker driver to
the C++ compiler driver as the linker driver when C++ interop is
enabled.  This allows us to ensure that we properly link against the C++
runtime which should be assumed to be needed with C++ interop.  This is
required for further exploration of C++ interop.
> SwiftDriver: use `clang++` as linker driver with C++ Interop

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This addresses a TODO to resolve the swift registrar via evaluation of
`SDKROT` environment variable.  The path is computed through an order
preference of:
1. `-resource-dir`
2. `-sdk`
3. `SDKROOT`
4. toolchain relative resource directory
This should enable the use of the swift driver to compile Swift code
without needing to explicitly pass the `-sdk` parameter on Windows.
> SwiftDriver: add support for resolving the registrar via SDKROOT

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Existing check decides to skip all compilation if there are no compile jobs and no post-compile job depends on before-compile jobs' outputs. This change refines the check to also ensure we do not run before-compile jobs whose only dependents are interface verification jobs. Otherwise, we would have an emit-module job, followed by verify-module-interface jobs on a null incremental build.
Resolves rdar://89913538
> [Incremental Builds] Produce an empty first wave if only job to run is verify module interface job.

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
We should also be able to emit ABI descriptors for modules without evolution. However, doing so leads us to deserialize more contents from binary modules, exposing more deserialization issues as a result.
> Pass-down -empty-abi-descriptor if evolution is disabled

- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
- Sources/swift-build-sdk-interfaces/main.swift
- Tests/SwiftDriverTests/IntegrationTests.swift
- Tests/SwiftDriverTests/JobExecutorTests.swift
Replace instances of `AbsolutePath.appending(RelativePath(_:))` with
`AbsolutePath(_:relativeTo:)` in light of the deprecation of the old
spelling.  This is particularly important for Windows which will now
properly normalize and canonicalize the path when constructed in the
new spelling.
> Replace `AbsolutePath.appending(_:)` for deprecations

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
With the introduction of features like @_spi_available, we may print public and private interfaces differently even from the same codebase without @_spi. For this reason, we should always print private interfaces so that we don’t mix the public interfaces with private Clang modules.
rdar://91061334
> Always emitting private swift interfaces if public interfaces are emitted

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1045 due to failures on several bots. (It looks like the test needs to be more flexible to accommodate non-Darwin platforms.)
Workaround for rdar://91190206.
> Revert "Add support for `-enable-regex-literals` flag"

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Sources/SwiftOptions/ExtraOptions.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
When serialized diagnostics are requested by the build system, it is expected to provide an output-file-map to specify per-file diagnostic output paths. The build system may also request serialized diagnostics module-wide in WMO compilation by specifying an output-file-map entry of module scope (`""`).
Emit-module jobs are always run at module scope, which means that if we want to get serialized diagnostics from the emit-module job, in WMO we do not know which path to use, because the module-scope path is specified for the WMO compilation job.
This change introduces a separate output path for the emit-module serialized diagnostics to be specified either:
- On the command-line with `-emit-module-serialize-diagnostics-path`
- In the output file-map using key `"emit-module-diagnostics": …
> Track serialized diagnostics of emit-module jobs separately.

- Tests/SwiftDriverTests/SwiftDriverTests.swift
These tests specified the Darwin triple unconditionally, resulting in
the test always being run in Darwin mode.  However, the ABI output is
not emitted on all platforms, which resulted in an out-of-bounds access
in the output.  Remove the explicit target triple, repairing the tests
on Windows.
> Tests: correct invalid tests

- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
- Tests/TestUtilities/DriverExtensions.swift
The toolchain should not really consult `DEVELOPER_DIR`.  While this was
initially useful, as the toolchain distribution grows and matures, it is
desirable to restore the ability to have disjoint and re-rooted installs
on Windows.  As a result, `DEVELOPER_DIR` would no longer be as valuable
for identifying the locations as the toolchain may be installed separate
from the SDKs.  This is inline with swift-package-manager which now also
has unlearnt this variable. `SDKROOT` remains as a means for the user to
specify the SDK implicitly through the environment.
> SwiftDriver: unlearn about `DEVELOPER_DIR`

- Tests/TestUtilities/Fixture.swift
The `AbsolutePath.appending(_:RelativePath)` interface was deprecated in
favour of `AbsolutePath(_:relativeTo:)` which allows us to anchor the
relative path which is needed to properly form relative paths on
Windows.  This updates the API usage in swift-driver accordingly.
> TestUtilities: silence warning from updated swift-tools-support-core

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Previous spelling could easily be mistaken for gating the entire feature.
Part of rdar://91119995
> Rename flag for enabling forward slash literals to be less ambiguous.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Sources/SwiftOptions/ExtraOptions.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Emit-module jobs might have different discovered dependencies and run in a different context where they need to get invalidated separately from the compile jobs.
With the new key "emit-module-dependencies" in the output file map the build system can specify that it expects a makefile-style dependency file at the given path.
rdar://91574616
> Create discovered dependencies file for emit-module jobs

- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Swiftinterface verification is incompatible with modules using generated headers. Let's disable the by default verification in such a case.
---
Also fix some indentation issues and clarify the many conditions for the verification to be active.
> swiftinterface verification: disable verification for modules with generated headers

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1049
---------------------------------------------
Previous spelling could easily be mistaken for gating the entire feature.
Part of rdar://91119995
> [5.7] Rename flag for enabling forward slash literals to be less ambiguous.

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Rather than iterating over all the jobs (even if there are only two) to
find a matching job, extract the module emission job and verify that the
assertions hold over the job.
> Tests: simplify test condition (NFCI)

- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Swiftinterface verification is incompatible with modules using generated headers. Let's disable the by default verification in such a case.
Cherry-pick of #1060
rdar://91711963
> [5.7] swiftinterface verification: disable verification for modules with generated headers

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Now that the frontend properly consults the architecture independent
path for the Swift modules, we can address the TODO that was left to
be addressed.  This requires apple/swift#42419 and
apple/swift-installer-scripts#119
> Tests: address TODO for Windows

- Sources/SwiftDriver/Driver/Driver.swift
We would tokenise the entire file as a single line rather than
tokenising each line.  Match the semantics of the function.
> Driver: correct tokenisation on Windows

- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Calling the driver from the `/usr/bin` directory of a toolchain will use that toolchain even if the called driver is from another toolchain. I thought this should be regarded as a bug?
> Disfavor current working directory when looking up executables

- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This PR is causing a Windows build failure. 
Reverts apple/swift-driver#991
> Revert "Disfavor current working directory when looking up executables"

- Tests/SwiftDriverTests/ParsableMessageTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Simply construct he path relative to the root.  Previous changes had
caused divergences as the null coalesced value would never be used in
any case.  Furthermore, this cleanup will work better with the new path
canonicalization for relative paths on Windows.
> Tests: simplify, homogenise path computation

- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Instead of embedding a block list of module names to disable a certain feature, we should set up an externally installed config file for that purpose. Therefore, we don't need to rebuild swift-driver when the block list needs an update.
rdar://92407381
> [5.7] Set up an externally installed config file to specify block list for certain driver features

- Package.resolved
This re-resolves the package, which updates the unpinned
swift-tools-support-core and swift-llbuild repositories.  This should
have no impact on other platforms, but enables building on Windows
without the need to explicitly re-resolve the package.
> build: re-resolve dependencies

- Tests/SwiftDriverTests/JobExecutorTests.swift
- Tests/SwiftDriverTests/NonincrementalCompilationTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
When building with apple/swift-tools-support-core#310, we normalize more
paths which results in test failures.  Update the tests to accommodate
the new behaviour.
> Tests: adjust tests for improvements to path normalization in TSC

- Tests/SwiftDriverTests/SwiftDriverTests.swift
There is no guarantee that the path between the temporary directory and
current working directory can be represented with a relative path.  This
is particularly important on Windows where the paths may reside on
different volumes, which have separate roots.  Alter the two instances
in the test to use the current directory for the temporary storage, and
ensure that we clean up afterwards as we are likely in the source tree.
> Tests: ensure that the path will be relative

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/swift-driver/main.swift
`fatalError` is more akin to an assertion rather than a "condition
failed, please exit".  The improper use here would, upon a typo on
Windows, induce the Doctor to try to categorise the fault and then
emit a minidump.  This is both frustrating and unnecessary.  Add a
new error case and use it to emit the message and exit gracefully.
> Driver: use a proper error rather than `fatalError`

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
So far, the swift-frontend decided by itself if CMO can be enabled. This caused problems when used with an old driver, which doesn't consider CMO.
Now, the driver decides when to use default CMO.
Depends on the swift changes https://github.com/apple/swift/pull/58529
> Explicitly tell the frontend to enable default cross-module-optimization

- Sources/SwiftDriver/Driver/Driver.swift
Provide a fallback default for the `emit-module.d` file.  It has been
observed on Windows and Android that builds subsequent to #1056 would
emit files into the root of the source tree (specifically, `pwd`). If
there is no explicit location specified for the new output, and given
that there is no primary output associated with the command, the path
that defaults is simply a singular file name component, emitting that
file into the location that the driver was executed from (which comes
out to the root of the package for commandline invocations), dirtying
the source tree.
Rather than sinking the knowledge for the default into
`existingOutputForSingleInput`, where we have no access to the module
name, emit the logic inline and derive a name based on the Swift module
and place it as a peer. …
> Driver: provide a more suitable default for `emit-module.d`

- Sources/SwiftDriver/Driver/Driver.swift
Provide a fallback default for the `emit-module.d` file.  It has been
observed on Windows and Android that builds subsequent to #1056 would
emit files into the root of the source tree (specifically, `pwd`). If
there is no explicit location specified for the new output, and given
that there is no primary output associated with the command, the path
that defaults is simply a singular file name component, emitting that
file into the location that the driver was executed from (which comes
out to the root of the package for commandline invocations), dirtying
the source tree.
Rather than sinking the knowledge for the default into
`existingOutputForSingleInput`, where we have no access to the module
name, emit the logic inline and derive a name based on the Swift module
and place it as a peer. …
> [5.7] Driver: provide a more suitable default for `emit-module.d`

- Tests/SwiftDriverTests/SwiftDriverTests.swift
This adjusts the tests for the updated behaviour in
swift-tools-support-core to correct relative path handling.
Additionally, enable tests that can now be supported.
> Tests: adjust tests for swift-tools-support-core#312

- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Instead of embedding a block list of module names to disable a certain feature, we should set up an externally installed config file for that purpose. Therefore, we don't need to rebuild swift-driver when the block list needs an update.
rdar://92407381
> [5.7 Sooner] Set up an externally installed config file to specify block list for certain driver features

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/swift-driver/main.swift
`fatalError` is more akin to an assertion rather than a "condition
failed, please exit".  The improper use here would, upon a typo on
Windows, induce the Doctor to try to categorise the fault and then
emit a minidump.  This is both frustrating and unnecessary.  Add a
new error case and use it to emit the message and exit gracefully.
> [5.7] Driver: use a proper error rather than `fatalError`

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/OptionParsing.swift
- Sources/SwiftOptions/ParsedOptions.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This is to prevent driver being lagging behind swift-frontend. For any unknown
driver flags that are recognizable to the swift compiler, we should save these flags
and pass them down to the compiler because the compiler is ready to take them.
> ParsedOptions: save unknown driver flags that are recognizable for swift-frontend

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/OptionParsing.swift
- Sources/SwiftOptions/ParsedOptions.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This is to prevent driver being lagging behind swift-frontend. For any unknown
driver flags that are recognizable to the swift compiler, we should save these flags
and pass them down to the compiler because the compiler is ready to take them.
> [5.7] ParsedOptions: save unknown driver flags that are recognizable for swift-frontend

- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
This remark is basically tripped by every swiftmodule in the SDK for
most projects. As it doesn't appear in tests anywhere and it provides
very little signal, best to strike it for now. If we discover it has
some diagnostic utility we can always revert this and add some tests.
> Remove Noisy Remark

- Sources/SwiftDriver/Driver/Driver.swift
It seems that a similar problem has impacted the generation of
serialised diagnostics for modules.  Follow the adage of CS inherently
having 3 numbers: 0, 1, N and generalise the path to a penultimate
fallback.  We should always have the swift dependency information on
hand to locate the build directory as that is the "master dependency".
This should hopefully prevent accidental cases of files leaking into the
current directory.
> Driver: further generalise #1088

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry pick https://github.com/apple/swift-driver/pull/1076 to 5.7 branch, support in Swift (C++ driver) was already merged in https://github.com/apple/swift/pull/58946 for 5.7.
Add support for the newly introduced `-file-prefix-map` flag.
> [5.7] Add support for -file-prefix-map

- Sources/SwiftDriver/Driver/Driver.swift
It seems that a similar problem has impacted the generation of
serialised diagnostics for modules.  Follow the adage of CS inherently
having 3 numbers: 0, 1, N and generalise the path to a penultimate
fallback.  We should always have the swift dependency information on
hand to locate the build directory as that is the "master dependency".
This should hopefully prevent accidental cases of files leaking into the
current directory.
> [5.7] Driver: further generalise #1088

- Sources/SwiftDriver/Driver/Driver.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1088 & https://github.com/apple/swift-driver/pull/1093
----------------------------------------------------------------------
- Explanation: Provide a fallback default for the `emit-module.d` and `emit-module.dia` files. If there is no explicit location specified for the new output, and given that there is no primary output associated with the command, the path that defaults is simply a singular file name component, emitting that file into the location that the driver was executed from (which comes out to the root of the package for commandline invocations), dirtying the source tree. Rather than sinking the knowledge for the default into `existingOutputForSingleInput`, where we have no access to the module name, emit the logic …
> [5.7-04182022] Provide a more-suitable default for emit-module auxiliary files

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftOptions/Options.swift
This flag was recently added in https://github.com/apple/swift/pull/58932.
> Add support for the new `-index-ignore-clang-modules` flag

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This flag was recently added and merged into 5.7 in https://github.com/apple/swift/pull/59254 and is a cherry-pick of https://github.com/apple/swift-driver/pull/1109.
Resolves rdar://95618415.
> [5.7] Add support for the new `-index-ignore-clang-modules` flag

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
watchOS 9 doesn't support 32bit architectures, however we should still
allow the compiler to generate swift modules for these target triples
for back deployment support.
> Prohibit IR Generation for 32bit watchos when deployment target > 9.0

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Utilities/Triple+Platforms.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Fixes "off by one" type error in watchOS validation - 32-bit archs should be blocked for watchOS >= 9.0, not >= 8.7. Fixes an incorrect fallthrough where invalid tvOS archs would issue errors about 32-bit iOS archs not being supported on iOS 11 and later. Fixes labeling of "macOS" as "OS X" in an error. Fixes an issue where arm64_32 would incorrectly be blocked for watchOS >= 8.7. Generally simplifies the validation code. Improves the test coverage to cover all of these scenarios.
> Fix some correctness issues in target triple validation and improve test coverage

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift
- Tests/SwiftDriverTests/ParsableMessageTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1121
---------------------------------------------------------
The incremental state is never used/referenced from this delegate and the existence of this reference may complicate things with respect to the incremental state's lifetime.
rdar://95990331
> [5.7] Remove `incrementalCompilationState` from `ToolExecutionDelegate`.

- Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift
Previously, the removeAll call below the initializer would trigger CoW. If the scratch buffer was larger than the count, this would result in an unnecessarily large allocation. In a very large source file, the source-file-provides-implementation node may have multiple orders of magnitude more edges compared to any other node in the graph, which could lead to excessive memory usage and a large slowdown deallocating the array storage when tearing down the graph.
I tested this using the swiftdeps from an artificially generated swiftdeps with 50k empty struct declarations. Before this change, it took 31s to load and destroy, after this change it only took 0.25s.
rdar://95648282
> Explicitly copy defsIDependUpon into an appropriately sized array when initializing SourceFileDependencyGraph.Node

- Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift
Reverts apple/swift-driver#1119
> Revert "Explicitly copy defsIDependUpon into an appropriately sized array when initializing SourceFileDependencyGraph.Node"

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift
- Tests/SwiftDriverTests/ParsableMessageTests.swift
The incremental state is never used/referenced from this delegate and the existence of this reference may complicate things with respect to the incremental state's lifetime.
rdar://95990331
> Remove `incrementalCompilationState` from `ToolExecutionDelegate`.

- Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift
Reapplying the reverted PR with an extra type annotation which will hopefully allow it to compile with hosttools.
Previously, the removeAll call below the initializer would trigger CoW. If the scratch buffer was larger than the count, this would result in an unnecessarily large allocation. In a very large source file, the source-file-provides-implementation node may have multiple orders of magnitude more edges compared to any other node in the graph, which could lead to excessive memory usage and a large slowdown deallocating the array storage when tearing down the graph.
I tested this using the swiftdeps from an artificially generated swiftdeps with 50k empty struct declarations. Before this change, it took 31s to load and destroy, after this change it only took 0.25s.
rdar://95648282
> Reapply "Explicitly copy defsIDependUpon into an appropriately sized array when initializing SourceFileDependencyGraph.Node"

- Sources/swift-driver/main.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1120
-----------------------------------------------------
motivation: fix regression where SIGINT would not terminate frontend processes
changes:
* call DispatchSourceSignal::resume
* call signal(SIGINT, SIG_IGN)
rdar://95862616
> [5.7] Fix SIGINT handler in swift-frontend

- Package.swift
This allows packages depending on SwiftPM (and transitively on Swift Driver) to correctly resolve dependencies.
> 5.7: set `swift-llbuild` branch to `release/5.7`

- Package.swift
- Package@swift-5.5.swift
Looks like a few references to `main` where missed in #1104 which breaks the 5.7 branch of SwiftPM.
> Fix 5.7 dependencies

- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Otherwise, changing the argument to an option which affects incremental builds, or the relative ordering of multiple options affecting incremental builds won't correctly rebuild all of the sources.
rdar://96556787
> Update incremental build hash to encode option arguments and ordering

- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Otherwise, changing the argument to an option which affects incremental builds, or the relative ordering of multiple options affecting incremental builds won't correctly rebuild all of the sources.
rdar://96556787
> [5.7]Update incremental build hash to encode option arguments and ordering

- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Reverts apple/swift-driver#1130
This was merged into the release branch prematurely
> Revert "[5.7]Update incremental build hash to encode option arguments and ordering"

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This flag is added to the frontend in https://github.com/apple/swift/pull/60000.
> Add support for `-index-include-locals`.

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This change adds the relevant API entry-points to `SwiftScan`.
It does not yet transition the driver's current use-sites where we shell out a `swift-frontend` process, but should make it easy to do so.
The library itself is gaining these entry-points here:
https://github.com/apple/swift/pull/40160
> Add `-print-target-info` libSwiftScan entry-points

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Putting up a revert in case this is the culprit behind failures like:
https://ci.swift.org/job/swift-PR-Linux-smoke-test/2536/
Reverts apple/swift-driver#911
> Revert "Add `-print-target-info` libSwiftScan entry-points"

- Tests/SwiftDriverTests/SwiftDriverTests.swift
The `testToolsDirectory()` test is failing in PR testing, and I think this is why.
> Fix testToolsDirectory test in environments with SWIFT_DRIVER_CLANG_EXEC set

- Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift
5.7 cherry pick of https://github.com/apple/swift-driver/pull/1119
> [5.7] Explicitly copy defsIDependUpon into an appropriately sized array when initializing SourceFileDependencyGraph.Node

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Driver equivalent to the compiler change in https://github.com/apple/swift/pull/60139.
> Add supplementary output path handling for extracted compile-time-known values

- Tests/SwiftDriverTests/SwiftDriverTests.swift
In Linux testing (e.g. in our CI) these currently generate non-fatal 'error:' messages. This makes human scanning of CI logs more difficult than it should be
> Remove non-fatal test error conditions in Linux testing

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
There's been a few PRs mentioning that running `makeOptions` results in
more churn than the one option they were expecting. Run separately to
sync up again.
> Re-run makeOptions to sync up Swift and C++ driver

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This ensures the compiler flags specified in the interface are ignored because they are already captured in the dependency scanner output.
> [Explicit Modules] Pass '-ignore-interface-provided-options' to interface build jobs.

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
A recent refactoring for Windows increased the module count for the
system modules and this resulted in the test suite failing due to the
difference.  This is technically backwards incompatible and expects that
the most recent toolchain is in use but it seems unclear how to account
for that easily.
> SwiftDriverTests: adjust module count on Windows

- Package.resolved
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftOptions/Options.swift
Companion change to https://github.com/apple/swift/pull/60556. 
This allows us to gather all the required flags for compilation of a given interface during the dependency scan, and then use those flags directly during the build, instead of once again reading out flags from the interface file and instantiating a new compiler subInstance when building said interface.
> [Explicit Modules] Pass '-explicit-interface-module-build' to interface build jobs.

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/Jobs/Job.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
`.emitModule` is re-used for two kinds of jobs:
- Build all sources of a target into a binary module
- In Explicit Module Builds, compile a dependency module interface into a binary module
It is worthwhile to treat these separate kinds of jobs separately.
Resolves rdar://98842129
> Separate two kinds of emit-module jobs into different categories: source emit-module and explicit dependency interface build

- Sources/swift-driver/main.swift
Otherwise after https://github.com/apple/swift-driver/pull/1120 we are now falling through to `fatalError` on interrupt.  
Resolves rdar://98584872
> On interrupt, after handling the compilation process set termination, restore the SIGINT default action.

- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- SwiftScan use of it seems not needed anymore
- ArgsResolver use can use 'NSLock' directly
> Remove use of deprecated STSC 'Lock'

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherrypick of #1153
__Explanation:__ [lld 13 changed how `--gc-sections` works last year](https://reviews.llvm.org/D96914), which was then [flipped on by default](https://reviews.llvm.org/rG6d2d3bd0a61f5fc7fd9f61f48bc30e9ca77cc619), and causes all Swift code on ELF platforms not to link with lld 13 and 14 anymore if stripping is enabled.
__Scope:__ Only affects lld for these ELF platforms
__SR Issue:__ apple/swift#60406
__Risk:__ low, since it only affects ELF platforms for this one linker
__Testing:__ I [just built the last August 2 source snapshot of the 5.7 toolchain for Android AArch64](https://github.com/buttaface/termux-packages/actions/runs/2886129294), where lld 14 is the default linker, with [this patch](https://github.com/buttaface/termux-packages/blob/swift-devel/packages/swift/ …
> [5.7] Work around lld 13+ issue with --gc-sections for ELF by adding -z nostart-stop-gc

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftOptions/ExtraOptions.swift
Add '-print-explicit-dependency-graph' to output the final dependency graph as JSON and '-print-preprocessed-explicit-dependency-graph' to output the initial dependency graph before external (placeholder) dependencies are resolved.
> Add options for debug printing of the explicit module dependency graph.

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
Since we are passing in the command-line to the scanner library with individual flags and paths as separate strings, this should not be necessary.
Depends on https://github.com/apple/swift/pull/60712
Part of rdar://98985453
> [Dependency Scanning] Do not quote paths in the dependency scanner invocation command

- Sources/SwiftDriver/Jobs/Job.swift
This way it is more similar to GeneratePCM's "Compiling Clang module...".
> Change phrasing of '.compileModuleFromInterface' to be more consistent

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The compiler uses the -target-sdk-name flag information to restrict which swiftmodules can be loaded and which should be ignored. This avoids preventable crash when swiftmodules are copied between mismatching SDKs.
rdar://83104265
> Pass down SDK name to the compiler by default

- Sources/SwiftOptions/CMakeLists.txt
`ExtraOptions.swift` was recently removed.
> Repair CMake build

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriverExecution/MultiJobExecutor.swift
- Sources/SwiftDriverExecution/SwiftDriverExecutor.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/ParsableMessageTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This change deprecates `ArgsResolver` API that takes a boolean `forceResponseFiles` in favor of a new API that takes an `ResponseFileHandling` enum. This enum allows the previous behaviors of `.forced` and `.heuristic` (`true` and `false`, respectively of `forceResponseFiles`), and adds an option to override disable use of response files completely (`.disabled`).
This is useful in the example of dependency scanning when it is done via a C interface to a compiler library: even for exceedingly-long command-line argument lists, using response files is not necessary since we just pass in an address of an already-allocated memory buffer containing the argument list, directly.
Resolves rdar://99296444
> Add ability to override/disable response file use in ArgsResolver

- Utilities/build-script-helper.py
This would be needed to compile on Apple Silicon, so that CMake does not
infer the wrong architecture when we want to build for Intel (see
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5291)
Addresses rdar://99587478
> Set explicitly the desired Darwin architecture for all CMake builds

- Utilities/build-script-helper.py
Script `Utilities/build-script-helper.py` doesn't clean `swift_flags` array while iterating on different targets, which results in the wrong `-target` flag passed on the second iteration.
Same with `base_cmake_flags` array, it should not be shared between different targets.
This bug currently blocks swift toolchain cross-compiling on M1 macs.
> Clean `swift_flags` array between targets in build-script-helper.py

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Execution/DriverExecutor.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecord.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Sources/SwiftDriver/IncrementalCompilation/InputInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Sources/SwiftDriver/Jobs/Job.swift
- Sources/SwiftDriver/Utilities/DateAdditions.swift
- Sources/SwiftDriver/Utilities/VirtualPath.swift
- Sources/SwiftDriverExecution/MultiJobExecutor.swift
- Sources/SwiftDriverExecution/SwiftDriverExecutor.swift
- Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Tests/SwiftDriverTests/NonincrementalCompilationTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
A TimePoint functions like a Duration, but for products that cannot yet use the niceties in Swift 5.7 like the Swift driver. This type carries a 64-bit second value and a 32-bit nanosecond value. Like Duration, it does not represent any one OS clock value, but is rather just a "point in time".
Using this type, we can simplify and clean up quite a few places that were trafficking in Foundation.Date and prepare for a future world where we have Duration too. The driver uses time point values to compare file modification times to each other - hence why we can get away with ignoring the epoch. The one oddity is the build record, which serializes time point values. But build records, like the rest of the incremental state, are not actually meant to leave a given user's machine.
> Replace Foundation.Date with TimePoint

- Sources/SwiftDriver/CMakeLists.txt
- Sources/SwiftDriver/Utilities/DOTModuleDependencyGraphSerializer.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
It can be nice to be able to visualize all of a module's dependencies.
A followup change will wire it up to a driver flag to allow an arbitrary driver invocation to emit this to a specified path. 
(Such flags must first be added in the main `swift` repo)
> Add a Dot serializer for the inter-module dependency graph.

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- TestInputs/ExplicitModuleBuilds/Swift/I.swiftinterface
- TestInputs/ExplicitModuleBuilds/Swift/S.swiftinterface
- TestInputs/ExplicitModuleBuilds/Swift/W.swiftinterface
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
The driver invokes the scanning action via a `libSwiftScan` API call. This PR adds the diagnostic query API which the driver uses to get the scanner's diagnostics after a scan and emits them for its clients.
The API entry-points added in https://github.com/apple/swift/pull/60999
> [Explicit Modules] Query and then emit diagnostics from the dependency scanner

- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
There was a race between #1174 and #1176 which removed an import.
> Fix build break by adding missing Import

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/ParsableMessageTests.swift
This flag allows printing of the inter-module dependency graph using either JSON (default) or DOT formats. 
Added in https://github.com/apple/swift/pull/61056.
> Add support for '-explicit-dependency-graph-format=' flag

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
These do not actually have much to do with the test. If dependency scanner produces an error or a warning, for example, all this test needs to make sure the right data is emitted to the output. Other tests verify the actual integrity of the scanning action's output.
Resolves rdar://99977956
> Remove extra checks for no emitted diagnostics in 'testPrintingExplicitDependencyGraph'

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
The explicit triple sets an OS, which then requires that the value for `-sdk` match.  Because Windows uses a `-sdk` parameter, this will fail on Windows due to a mismatch for the SDKs.  By excluding the triple, a host specific value is used which allows this to match and pass.
> SwiftDriverTests: exclude explicit triple

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftOptions/OptionParsing.swift
- Sources/SwiftOptions/Options.swift
- Sources/SwiftOptions/ParsedOptions.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
“swift -e” can be used to run code specified directly on the command line rather than passed through stdin or a source file. The values of the “-e” switches are each treated as one line of source code, which are concatenated together into a temporary main.swift file and passed to the frontend jobs.
Fixes rdar://17258540.
> Add “swift -e” support

- Sources/SwiftDriver/Driver/Driver.swift
The change in #1188 accidentally used a 5.7 feature (multi-statement closure result type inference), but it needs to support at least 5.6 for the earlyswiftdriver pass. Add an explicit type to avoid this problem.
> Fix accidental use of new feature in -e

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
Additionally, clarify that `lookup(executable:)` expects the argument without executable suffix.
Fixes #1186
> Remove the use of hard-coded `.exe` suffix

- Sources/SwiftDriver/CMakeLists.txt
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ToolingInterface/SimpleExecutor.swift
- Sources/SwiftDriver/ToolingInterface/ToolingUtil.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
- Sources/SwiftOptions/ParsedOptions.swift
- Tests/SwiftDriverTests/SwiftDriverToolingInterfaceTests.swift
This function currently exists in the legacy C++-based Swift Driver. This is a re-implementation of the same functionality which will eventually replace it.
A follow-up change will begin wiring up how to use this API from the C++ entry-point. 
Part of rdar://75851402
> Implement 'getSingleFrontendInvocationFromDriverArguments' utility API

- Tests/SwiftDriverTests/ParsableMessageTests.swift
The hijacked error stream needs to account for string normalization of the line ending on Windows to ensure that the `.contains` match passes there.  This addresses the remaining test regressions on Windows.
> SwiftDriverTests: account for windows line endings

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
They were waiting for the dependency scanner to learn how to query Clang dependency scanner without relying on Objective-C. This is now possible.
> Enable Explicit Module Build tests on Linux

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/Inputs/ExplicitModuleDependencyBuildInputs.swift
https://github.com/apple/swift/pull/60882 adds functionality to the Clang scan-deps invocation that produces placeholder paths as '<replace-me>'s in the generated command-line. The first step to adapting to these changes is to teach the driver to substitute the expected file paths.
Once the scanner changes land, we will revisit the driver specifying these paths in favour of having the scanning action being able to determine the correct output location from the get-go.
> [Dependency Scanning] Adapt to upcoming dependency scanner API change s with the output path.

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
As of https://github.com/apple/swift/pull/60882 and https://github.com/apple/swift/pull/61303, emit-pcm will accept clang frontend arguments with '-Xcc', instead of clang driver arguments.
> [Explicit Module Builds] Adapt to Clang dependency scanner changes

- Sources/SwiftDriver/Utilities/DateAdditions.swift
else it breaks when compiling for 32-bit armv7 with large inputs.
I [recently hit this when cross-compiling trunk SPM for Android armv7 on my daily CI](https://github.com/buttaface/swift-android-sdk/runs/8302044832?check_suite_focus=true#step:6:7000), as `distantFuture` overflows `Int` on 32-bit platforms. I had to add this patch to get it to build again, buttaface/swift-android-sdk@043df19.
@CodaFi, you added `TimePoint`, let me know what you think of this tweak.
> Make the new TimePoint.seconds() input explicitly Int64

- Sources/SwiftDriver/Jobs/Job.swift
This new diagnostic should distinguish between the verification of the public and the private swiftinterface. It should look like this:
```
Verifying emitted module interface MyFramework.private.swiftinterface
```
When building for two archs at a time, the same message will still appear twice (down from 4 times the same message). This appears to be common to all jobs named from the driver side, I'm not sure if we could improve this from the driver side or if it should be from the driver client side.
I didn't see tests for these so please let me know if I missed a testing opportunity.
> Update the name of the swiftinterface verification job to name the target file

- Sources/SwiftDriver/CMakeLists.txt
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/Bitcode.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/BitcodeElement.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/Bits.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/Bitstream.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/BitstreamReader.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/BitstreamVisitor.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/BitstreamWriter.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/BlockInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Sources/SwiftDriver/IncrementalCompilation/SourceFileDependencyGraph.swift
The swift-driver is the only consumer of the bitcode implementation in TSCUtility.  Migrate the code to the single user to allow us to deprecate the API in tools-support-core.  While there are no practical changes to the implementation, this does take the opportunity to split up the bitcode implementation into multiple files.
> SwiftDriver: migrate LLVM bitcode support from tools-support-core

- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Lift the workaround that disabled scheduling the swiftinterface verification task when a compatibility header is generated. This is an issue only when the header is also installed, we now expect the build system to disable the verification when it installs the header.
For more context, this issue lead to errors on missing headers and failures to build the underlying clang module at verification.
rdar://100989723
> Re-enable swiftinterface verification with compatibility headers

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
Clients should have transitioned to 'externalTargetModuleDetailsMap'.
> Remove deprecated 'externalTargetModulePathMap'

- Sources/swift-driver/main.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1157
-----------------------------------------
Resolves rdar://98584872
> [5.7] On interrupt, after handling the compilation process set termination, restore the SIGINT default action.

- Package.resolved
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Driver/OutputFileMap.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/DependencySource.swift
- Sources/SwiftDriver/Jobs/BackendJob.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/GenerateDSYMJob.swift
- Sources/SwiftDriver/Jobs/GeneratePCHJob.swift
- Sources/SwiftDriver/Jobs/LinkJob.swift
- Sources/SwiftDriver/Jobs/MergeModuleJob.swift
- Sources/SwiftDriver/Jobs/ModuleWrapJob.swift
- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/VerifyModuleInterfaceJob.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
- Sources/SwiftDriver/Utilities/VirtualPath.swift
Follow up to #1204 that adopts to the new API.
> Update to new path APIs

- README.md
This was introduced as a dependency in #915, so mention it.
> swift-system is now a dependency.

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This is equivalent to passing `-use-ld=lld` to the driver.
> SwiftDriver: on FreeBSD, use lld, not gold

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
The driver previously implemented a scheme where it computed an output path for the PCMs of clang module dependencies by hashing the command-line used to build the PCM plus a set of special arguments determined by the depending Swift module that made the PCM unique to the depending Swift module in the build graph. This was previously done first and foremost to accomodate the fact that we used to have Clang modules built against different target triples in the build graph.
The driver would previously execute a dependency scan, and follow it up with a re-scan of relevant clang modules which we require to have dependency info about at a target triple that is different from the main module's target triple. With the introduction of '-clang-target', we are aiming to ensure that '-target' triple …
> [Explicit Module Builds] Rely on Clang dependencies' ContextHash to determine the PCM output filename

- Sources/swift-help/main.swift
Tis PR fixes the issue that`swift --help` did not list the subcommand `swift package-collection`.
> Add package-collection subcommand to swift help

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/Jobs/Planning.swift
This change adapts to the `modulePath` of Clang modules in the dependency scanner output being *the* output path for such PCMs. Implemented in https://github.com/apple/swift/pull/62067.
The change temporarily handles the previous case to ensure the driver CI can work with both kinds of compilers/scanners.
> Adapt to dependency scanner outputting canonical Clang PCM output paths

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Otherwise, every single compiled program will end up linking it, and Foundation on top of it.
> Only add '-fobjc-link-runtime' to the linker invocation when the driver is invoked with '-link-objc-runtime'

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1224
> Revert "Only add '-fobjc-link-runtime' to the linker invocation when the driver is invoked with '-link-objc-runtime'"

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftOptions/Options.swift
`-emit-syntax` and `-verify-syntax-tree` are not supported anymore.
See: https://github.com/apple/swift/pull/62132
> Remove legacy libSyntax related options

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
Instead allow the dependency scanning oracle to be configured such that the scanning actions use placeholders.
In contexts where the driver's client can guarantee that all module dependencies have been built prior to planning of the dependee, placeholders are not necessary in the scanner, becuase the binary modules will simply be discovered on the filesystem.
Resolves rdar://102339586
> [Dependency Scanning] Do not specify placeholder modules by default as inputs to scanning actions

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ClangVersionedDependencyResolution.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationProtectedState.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Utilities/VirtualPath.swift
- TestInputs/ExplicitModuleBuilds/Swift/E.swiftinterface
- Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Building on top of https://github.com/apple/swift-driver/pull/621, on an incremental build, load a prior dependency graph, check if it is still valid:
1. import set of the current module has not changed
2. input files of every module in the prior graph are older than the output and if it is, re-use it, skipping invoking the dependency scanner again.
More concretely, computation of the initial incremental state in `computeIncrementalStateForPlanning` will attempt to read out and validate a prior serialized inter-module dependency graph. If validated, such graph will become a part of the initial incremental state itself.
During build planning, at the stage of computing inter-module dependencies, the dependency scanning action will be skipped if the initial incremental state contains a …
> [Explicit Module Builds] Serialize and re-use the inter-module dependency graph as incremental build state

- Sources/SwiftDriver/Jobs/Planning.swift
'guard let X else {}' works with latest Swift compilers (such as one used in swift-driver CI) but isn't supported in some older compilres used in CI and other bots.
> Rephrase use of 'guard let' not supported by older compilers.

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Jobs/MergeModuleJob.swift
- Sources/SwiftOptions/Options.swift
This PR adds support for the flags added in apple/swift#59047 and apple/swift#61637.
The PR should be merged before/with apple/swift#61637.
> Add support for -emit-extension-block-symbols and -omit-extension-block-symbols flags

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Otherwise we give the scanner object files, and whatever else, and it gets confused.
> [Dependency Scanning] Only specify Swift source-file inputs as inputs to the dependency scanning action.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ClangVersionedDependencyResolution.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationProtectedState.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Utilities/VirtualPath.swift
- TestInputs/ExplicitModuleBuilds/Swift/E.swiftinterface
- Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Second attempt at landing https://github.com/apple/swift-driver/pull/1230
Which previously caused compiler lit test regressions in main CI. 
-------------------------------
Building on top of https://github.com/apple/swift-driver/pull/621, on an incremental build, load a prior dependency graph, check if it is still valid:
- import set of the current module has not changed
- input files of every module in the prior graph are older than the output and if it is, re-use it, skipping invoking the dependency scanner again.
More concretely, computation of the initial incremental state in `computeIncrementalStateForPlanning` will attempt to read out and validate a prior serialized inter-module dependency graph. If validated, such graph will become a part of the initial incremental state itself. …
> Bring back [Explicit Module Builds] Serialize and re-use the inter-module dependency graph as incremental build state

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This reverts commit 2dbaf861ac9cfc0f3affe8d5d13f5f34c931a499.
> Revert "Revert "Only add '-fobjc-link-runtime' to the linker invocation when the driver is invoked with '-link-objc-runtime'""

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
In an all-or-nothing coarse-grained fashion, for now.
> [Explicit Module Builds] On an incremental build, skip re-building module dependencies when they are up-to-date

- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Update `Options.swift` to bring in a change to make `-e` 'separate', instead of 'joinedOrSeparate'.
From: https://github.com/apple/swift/pull/62526
> Make `-e` flag 'separate', instead of 'joinedOrSeparate'

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This info is required so that it can be specified as input to compilation that uses such module as a dependency, in order to decide whether or not to insert an auto-linking directive for it.
Companion change to https://github.com/apple/swift/pull/62540
Part of rdar://102824777
> [Dependency Scanning] Query scanner whether discovered binary Swift modules are frameworks

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecord.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationProtectedState.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Sources/SwiftDriver/IncrementalCompilation/InputInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Tests/SwiftDriverTests/CrossModuleIncrementalBuildTests.swift
- Tests/SwiftDriverTests/DependencyGraphSerializationTests.swift
- Tests/SwiftDriverTests/Helpers/MockingIncrementalCompilation.swift
- Tests/SwiftDriverTests/IncrementalBuildPerformanceTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Tests/SwiftDriverTests/NonincrementalCompilationTests.swift
This PR fixes a pretty harrowing set of Linux bugs we've observed on and off over the years with the incremental build.
The build record and the module dependency graph are currently emitted by "cross-module incremental builds" alongside a "swiftdeps" YAML file that summarizes the compilation session that occurred before this one. This has a number of downsides
- We have a hard dependency on a YAML library for just this one thing
- With two input files comes a quad-state of cases to handle (if priors desyncs from build record and vice versa... bad things happen)
- Moreover, we have observed that mod times returned to us on ext4 on older Ubuntus have a pretty high (probably << 1/100) chance of telling us that the priors file was somehow emitted _before_ the compilation session ended. …
> Consign the YAML Build Record to the Legacy Incremental Build Path

- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/swift-build-sdk-interfaces/main.swift
Now users will see a diagnostic like this:
```
error: value of SWIFT_EXEC is not a valid absolute path: ../build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swiftc
```
Also, fix a diagnostic typo.
> PrebuiltModuleGen: Print an error instead of crashing when `SWIFT_EXEC` is invalid

- Utilities/build-script-helper.py
Some platforms require the normal, versioned triple to be supplied for the target flag, as Swift modules use this versioned triple as a subdirectory. If the unversioned triple is used instead, the standard library won't be found on these platforms.
Instead, use the unversioned triple only on Darwin. This also should be a noop on Linux. This behavior matches apple/swift-package-manager#3576 and apple/swift-tools-support-core#229 which contain additional context.
> Use the versioned triple outside of Darwin.

- Package.swift
This makes sure that dependencies of Swift Compiler Driver built with SwiftPM and coming from the Swift project use `release/5.8` branch.
> 5.8: set `relatedDependenciesBranch` to 5.8 in `Package.swift`

- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
This is a warning that's currently caused by `priors` using a `var` binding:
```swift
IncrementalCompilation/IncrementalDependencyAndInputSetup.swift:281:17: warning: variable 'priors' was never mutated; consider changing to 'let' constant
guard var priors = computeGraphAndInputsInvalidatedByExternals() else {
~~~ ^
let
```
> IncrementalDependencyAndInputSetup.swift: fix mutability warning

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This will result in the driver passing down '-clang-target' flag to the frontend, which will then ensure that all downstream module (Swift and Clang) compilation compiler sub-invocations are consistent with respect to the target triple used by their underlying instances of Clang. Resulting in all Clang module dependencies being built against the main module's target triple.
> Enable '-clang-target' by-default

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1250
----------------------------------
This will result in the driver passing down '-clang-target' flag to the frontend, which will then ensure that all downstream module (Swift and Clang) compilation compiler sub-invocations are consistent with respect to the target triple used by their underlying instances of Clang. Resulting in all Clang module dependencies being built against the main module's target triple.
> [5.8] Enable '-clang-target' by-default

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1251
Testing whether this change regressed source compatibility.
> Revert "[5.8] Enable '-clang-target' by-default"

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Of the "_SwiftConcurrencyShims" module.
> Adjust tests to Swift compiler's new implicit dependency import

- Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
Second attempt to land https://github.com/apple/swift-driver/pull/1252 after being reverted in https://github.com/apple/swift-driver/pull/1257
--------------------------------------------------
> Use libSwiftScan to query supported compiler flags in-process

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Driver/WindowsExtensions.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Alongside lookup of executable tools, the toolchain is now responsible for looking up the driver's compiler support and dependency scanning library.
It also adds an environment variable override 'SWIFT_DRIVER_SWIFTSCAN_LIB' for clients to specify a specific path to this shared library that they would like to be used instead of the default.
> [Dependency Scanning] Move computation of the path for libSwiftScan to the toolchain

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Driver/WindowsExtensions.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1253
Tentative as it may be causing failures in main CI:
https://ci.swift.org/job/swift-PR-macos/5676/console
> Revert "[Dependency Scanning] Move computation of the path for libSwiftScan to the toolchain"

- Sources/swift-build-sdk-interfaces/main.swift
As `AbsolutePath.init(_:)` is deprecated, we should use throwing `AbsolutePath.init(validating:)` instead to fix the warnings.
> swift-build-sdk-interfaces: fix deprecated AbsolutePath.init

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/Inputs/ExplicitModuleDependencyBuildInputs.swift
The driver library's client may supply information about the current module's dependencies, incl. whether or not they are frameworks. With the dependency scanner no longer re-using source module information from a prior scan (https://github.com/apple/swift/pull/63201), such modules will be reported as prebuilt binary dependencies.
Moreover, add a check to avoid resolving the main module's source module information with a binary dependency, covering an edge case of a module having a dependency with the same name.
> [Explicit Modules] Use external dependency info to determine if discovered binary dependenceis are frameworks.

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/JobExecutorTests.swift
Now that we use the proper linker driver (`clang`), we no longer need to handle the explicit standard library linking.  Delegate this to the linker driver which will properly link to libSystem instead.  This simplifies some of the logic and further harmonises the beahviour across the various platforms.
> SwiftDriver: avoid `-lSystem` on Darwin

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
We were relying on the implicit import of the `DiagnosticsEngine` extension to emit the diagnostics.  Explicitly inline the casting to avoid the dependency.
> SwiftDriver: remove implicit dependency on TSCUtility

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
This function was being imported through `TSCUtility`.  Replace the 3 uses of the function with an alternative to allow us to cleave the dependency.
> SwiftDriver: remove use of `spm_chomp`

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/swift-driver/main.swift
Replace use of `Diagnostic.fatalError` with a
`SwiftDriver.Diagnostics.errorsEmitted` type which removes the final reference to `TSCUtility` in the actual shipping code.  References within the test suite may remain for now.
> Remove last trace of `TSCUtility`

- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
The C-String to Swift-String conversion would corrupt the path on Windows, where the path separator would get dropped.  This would result in the inability to use the driver due to the failure to load the standard library as the SDK would not be consulted.
Directly convert the raw buffer to a `Data` for the foreign representation.  Note that this also makes the code clearer as we explicitly see the copying as opposed to the use of the deprecated `String(bytesNoCopy:length:encoding:freeWhenDone:)` function.
Thanks to @artemcm for the help with this!
> SwiftDriver: avoid using `toSwiftString` for target info

- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift
Present a diagnostic for the failure rather than invoking `fatalError`. This ensures that the user sees a proper diagnostic for the failure and also enables the test suite to run to completion in case of an error.
> SwiftDriver: avoid use of `fatalError` in the driver

- Utilities/build-script-helper.py
Remove the reference to `libTSCLibc.dylib` as the module is now static and will not be present on the file system as a dylib as it is compacted into TSCBasic.
> Utilities: update build-script-helper.py

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/SwiftOptionsTests/OptionParsingTests.swift
Add -package-name to driver
Add packageName to ModuleOutputInfo
Add package name validation and diagnostics
If package name is empty or invalid, fall back to module name
Resolves rdar://105119573.
> Add -package-name to driver

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Pass through options for macros, especially compiler plugin search
paths. Add a default search path into `lib/swift/host/plugins`.
Driver side of rdar://105095761
> Add support for macro frontend options 

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Pass down an optimization level to the Clang linker invocation

- Utilities/build-script-helper.py
The libllbuild library has been converted into a static product and interalised into libllbuildSwift.  This avoids the distribution issues here.  Remove the library from the install set.
> Utilities: adjust install rules for apple/swift-llbuild#852

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
In the case this argument is passed explicitly and invalid, it was previous ignored and fell back to 'main' even in cases where you might not want that like compiling object files. It doesn't seem necessary to allow invalid cases like this through regardless of what object type is being built.
> Be more strict about invalid -module-name arguments

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
- Sources/SwiftDriver/Utilities/Triple+Platforms.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Equivalent to https://github.com/apple/swift/pull/63662
--------------------------------------------------
Darwin no longer uses arclite and it's no longer distributed in the macOS SDKs.
This leaves the options '-link-objc-runtime' and '-no-link-objc-runtime' in place, but strips out all the logic that actually used them.
Part of: rdar://105406972
> Remove support for linking arclite

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
- Sources/SwiftDriver/Utilities/Triple+Platforms.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1295
----------------------------------
It appears this flag was load-bearing for some LLDB tests and the original PR caused a regression. We need to fix these tests to pass the required linker flags.
> Revert "Remove support for linking arclite"

- Sources/swift-help/main.swift
This help should include top-level commands–these should be treated as sub-commands of `swift package`.
rdar://104603198
> Remove `package-collection` and `package-registry` from top-level command help

- Sources/SwiftOptions/Options.swift
> [Options] Update Options.swift

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Compiler flags added in: https://github.com/apple/swift/pull/63975
Driver portion of rdar://105982120
> Add Swift compilation flags to enable Clang's validate-per-build-session module behavior

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
Catch thrown exceptions and fallback to the previous mechanism of shelling out a `swift-frontend -print-target-info` and `swift-frontend -emit-supported-features` tasks. We are seeing spurious failures here and this will help potential users while we investigate the root cause.
Workaround for rdar://105559904
> Attempt to recover from in-process Target Info and Supported Features query failures.

- Sources/SwiftOptions/Options.swift
Regenerate the swift options from the C++ driver to pick up changes for the new Windows options that are being introduced to control the SDK and Visual C++ tools that we use.
> SwiftOptions: regenerate the swift options

- Utilities/build-script-helper.py
This is to support building the swift-driver with -sanitize=address when the Swift build preset specifies enable-asan. Without this option and with enable-asan in picture the entire Swift build fails due to ASAN initialization failure in swift-driver.
rdar://104661463
> Add --enable-asan option in swift-driver

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Add handling for the newly minted Windows options:
- `-windows-sdk-root`
- `-windows-sdk-version`
- `-visualc-tools-root`
- `-visualc-tools-version`
Add some tests to ensure that we handle the flags properly.
> driver: honour new Windows options

- Sources/SwiftDriverExecution/SwiftDriverExecutor.swift
This header contained outdated file name.
> NFC: Fix comment header in SwiftDriverExecutor.swift

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1274
-------------------------
> [5.9][Explicit Modules] Have `-clang-target` on Darwin platforms set to the SDK version by-default

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Unless we are building a static library, we need to propagate `-fsanitizer=` flag to the clang linker driver, otherwise sanitizers libraries will not be found at link-time.
Resolves rdar://107733898
> Propagate sanitizer arguments to the clang-linker-driver invocations for dynamic libraries

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of: https://github.com/apple/swift-driver/pull/1325
------------------------------
Unless we are building a static library, we need to propagate `-fsanitizer=` flag to the clang linker driver, otherwise sanitizers libraries will not be found at link-time.
Resolves rdar://107733898
> [5.9] Propagate sanitizer arguments to the clang-linker-driver invocations for dynamic libraries

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
🍒 Cherry-pick of https://github.com/apple/swift-driver/pull/1319
------------------------------------------------
In the `InterModuleDependencyOracle`, which may be shared across different instances of the `Driver`, all dependency scanning queries are executed synchronously on a shared dispatch queue. This is no longer necessary with the scanner guarding its own shared state as of https://github.com/apple/swift/pull/64615.
> [5.9][🍒][Dependency Scanning] Remove coarse-grained synchronization on all dependency scan queries

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
In the `InterModuleDependencyOracle`, which may be shared across different instances of the `Driver`, all dependency scanning queries are executed synchronously on a shared dispatch queue. This is no longer necessary with the scanner guarding its own shared state as of https://github.com/apple/swift/pull/64615.
> [Dependency Scanning] Remove coarse-grained synchronization on all dependency scan queries

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/LinkJob.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
GCC toolchains are useful when cross-compiling to Linux with a given gcc toolchain. The gcc toolchain contains tools for linking, libraries for linking against, and the headers that map to those libraries.
This patch adds a `-gcc-toolchain` flag to the driver so that Swift can pass that information down to both the clang importer and clang linker appropriately.
I went with the double-dash, equals format passed to clang because maskray keeps poking at the clang flags and that format is the only one that goes all of the way back (to 2013). I'm also passing the path down directly instead of reinterpreting them as an absolute path. The driver seems to use the `-working-directory` path to resolve most of these instead of the current working directory path, which I believe is inconsistent with …
> Add `-gcc-toolchain` flag to swift-driver

- Sources/SwiftOptions/Options.swift
- Sources/makeOptions/makeOptions.cpp
Updating makeOptions to include note that options.swift is generated so it should not be edited by hand.
Adding a note to the file so that folks are reminded not to edit it by hand.
> Add generated file note to Options.swift

- Utilities/build-script-helper.py
~This is needed for all platforms that don't have multi-architecture libraries like Darwin. Also, add the new architecture-specific rpath to the resulting swift-driver and make it possible to cross-compile this repo for non-Darwin platforms on Darwin.~
~The driver changes are the Swift translation of the Driver-specific changes of apple/swift#63782.~
~Resolves apple swift#63645~
This replaces all but one prior check of the host system instead, plus removed
unnecessary regex checking.
> Support building this repo for more platforms, by checking the build triple

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
We have moved towards a build model where the output of the dependency scanner is the canonical collection of modules that must be built. The driver's logic to generate potentially multiple examples of a given Clang dependency, with different command sets, as required per Swift client module in the build graph, is no longer valid - even module output paths are no longer determined by the driver. Remaining logic that is removed in this PR may result in mistakenly producing duplicate jobs for the same Clang PCM build job.
> [Explicit Module Builds] Remove logic for Swift-client-specific Clang module dependency jobs

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
Cherry-pick of #1332
------------------------------ 
We have moved towards a build model where the output of the dependency scanner is the canonical collection of modules that must be built. The driver's logic to generate potentially multiple examples of a given Clang dependency, with different command sets, as required per Swift client module in the build graph, is no longer valid - even module output paths are no longer determined by the driver. Remaining logic that is removed in this PR may result in mistakenly producing duplicate jobs for the same Clang PCM build job.
Change affects explicit module builds only and does not have any impact on implicit build code-path.
> [5.9 🍒][Explicit Module Builds] Remove logic for Swift-client-specific Clang module dependency jobs

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/DriverExtensions.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1335
--------------------------------------
Otherwise, if unquoted paths contain spaces, such paths will become treated as separate strings when we formulate a C string array to pass down to libSwiftScan API entry-points.
Resolves rdar://106712169
> [5.9 🍒] Always quote path arguments when resolving command-lines for libSwiftScan queries

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/DriverExtensions.swift
Otherwise, if unquoted paths contain spaces, such paths will become treated as separate strings when we formulate a C string array to pass down to libSwiftScan API entry-points.
Resolves rdar://106712169
> Always quote path arguments when resolving command-lines for libSwiftScan queries

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/TripleTests.swift
- When compiling for os none for apple, we should perfer using a Darwin toolchain (maybe a misnomer now) instead of a generic UNIX toolchain. This results in the driver selecting relevant tools for apple platforms, such as using ld64 over gold, etc.
> Use DarwinToolchain for apple-none targets

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/DriverExtensions.swift
> [Macros] Set -external-plugin-path when the toolchain is not Xcode

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/DriverExtensions.swift
Cherry-pick #1320 into `release/5.9`
**Explanation**: https://github.com/apple/swift/pull/64376 implemented "plugin server". This change is a corresponding change in `swift-driver` that utilize the plugin-server when the current `swiftc` is not in the Xcode.
**Scope**: Frontend options in macOS environment.
**Risk**: low
**Testing**: Added a regression test case
**Issues**: rdar://108525615
**Reviewer**: Artem Chickin (@artemcm)
> [5.9][Macros] Set -external-plugin-path when the toolchain is not Xcode

- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Sources/SwiftDriver/Utilities/System.swift
Particularly, we have a special utility to quote paths on Windows, where the approach of adding `'` prefix and postfix is not valid.
> Use system-appropriate method when quoting path arguments on command-lines

- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Doing so means downstream code is likely to error or crash, because it expects Swift source (or SIL) inputs. 
Resolves rdar://108057797
> Do not attempt to create compilation jobs when no Swift source files are specified as inputs

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Otherwise, if the first argument is anything else (e.g. an object file) we will use it as a key and the compiler won't be too happy about that.
Resolves rdar://108741675
> In WMO, make sure the dummy "primary" compilation input is a Swift source file

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1346. It's causing failures in CI that are breaking PR testing on Swift `main`. See, e.g., https://ci.swift.org/job/oss-swift-incremental-RA-macos/2773/.
> Revert "In WMO, make sure the dummy "primary" compilation input is a Swift source file"

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
This is to walkaround rdar://108769167
> Avoid quoting paths for dependencies scanning jobs

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
(Cherry-pick from PR: https://github.com/apple/swift-driver/pull/1351)
Explanation: We recently added a change to always add quotes for path arguments. For some reason, the dependency scanning invocation used by prebuilt module cache job doesn't like this change, leading to failures when querying module dependency information. This is a simple change to opt-out adding quotes for dependency scanning jobs.
Scope: Swift prebuilt module cache
Risk: Low.
> [5.9🍒] Avoid quoting paths for dependencies scanning jobs.

- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Command lines generated for `libSwiftScan` (either for actual dependency scanning queries, or for target-info queries) do not go through the shell, and are instead tokenized at the entry-points (inside `libSwiftScan`). In order for them to be correctly tokenized, we must ensure that all the various file paths are escaped in case they contain whitespace characters, to ensure they get treated as a whole path, rather than multiple strings.
The driver previously relied on a separate mechanism to do this for libSwiftScan command lines, by getting the `ArgsResolver` to always escape `.path` arguments. This turned out to be insufficient, because it happens to miss a whole class of paths specified on the command-line that the driver cannot/doesn't recognize as paths: arguments forwarded to tools, …
> [Dependency Scanning] Unify path-escaping handling using TSC's spm_shellEscaped

- Utilities/build-script-helper.py
`distutils` was deprecated in Python 3.10 and will be removed in Python 3.12. We should not depend on it and this import looks unused anyway.
> build-script-helper.py: remove unused `distutils` import

- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1354
--------------------------------------------------
Command lines generated for libSwiftScan (either for actual dependency scanning queries, or for target-info queries) do not go through the shell, and are instead tokenized at the entry-points (inside libSwiftScan). In order for them to be correclty tokenized, we must ensure that all the various filepaths are escaped in case they contain whitespace characters, to ensure they get treated as a whole path, rather than multiple strings.
The driver previously relied on a separate mechanism to do this for libSwiftScan command lines, by getting the 'ArgsResolver' to always escape '.path' arguments. This turned out to be insufficient, because it happens to miss a whole class of paths …
> [5.9 🍒][Dependency Scanning] Unify path-escaping handling using TSC's `spm_shellEscaped`

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick #1356 into `release/5.9`
**Explanation**: Detecting if `-external-plugin-path` should be added or not is not reliable in "integrated driver" mode. In such cases the user should manually add them. This change just disable adding `-external-plugin-path` if `Driver.integratedDriver` is true.
**Scope**: Frontend arguments
**Risk**: Low. This just disabled a newly added functionality depending on the condition
**Testing**: Added a regression test case to verify `-external-plugin-path` is added automatically if the flag is on.
**Issue**: rdar://109060298
**Reviewer**: Artem Chikin (@artemcm )
> [5.9] Disable adding '-external-plugin-path' in integrated driver mode

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Disable adding '-external-plugin-path' in integrated driver mode

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/DriverExtensions.swift
Revert #1320 and #1356 . Doing this in Driver was not a good idea.
> Revert "[Macros] Set -external-plugin-path when the toolchain is not Xcode"

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/DriverExtensions.swift
release/5.9 version of #1359 
**Explanation**: We concluded deriving `-external-plugin-path` in Driver was not a good idea. Revert related commits
**Scope**: Compiler arguments
**Risk**: Low. Just reverting.
**Test**: Existing test cases passed
**Issues**: rdar://109108758
**Reviewers**: Artem Chikin (@artemcm), Owen Voorhees (@owenv)
> [5.9] Revert "[Macros] Set -external-plugin-path when the toolchain is not Xcode"

- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The CompatibilityPacks shim doesn't install any override hooks; it just exports a pair of symbols. We don't want to link the shim if we're not using the symbols.
This is part of https://github.com/apple/swift/pull/65884.
> Add support for compatibility shims that we don't want to -force-load

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick https://github.com/apple/swift-driver/pull/1347 and https://github.com/apple/swift-driver/pull/1350
---------------------------------------------------
• **Release**: Swift 5.9
• **Explanation**: Invoking the driver (`swiftc`) in WMO mode with a collection of object file inputs crashes the driver. The expectation is that, in the absence of `.swift` inputs, the driver will simply invoke the linker to produce a binary of a desired kind. Instead, the driver crashes. 
• **Scope of Issue**: Command-line `swiftc` users who wish to use it to link stuff, or `swiftc` command-line generators who might do the same, e.g. CMake.
• **Origination**: A long-standing driver bug (even affects the legacy C++ driver...)
• **Risk**: Risk of this change is very low. It ensures the driver carefully …
> [5.9 🍒] Fixes to WMO invocations without `.swift` input files

- Package.swift
We no longer support Swift 5.5 and older versions of macOS with SwiftPM, makes sense to bring Swift Driver requirements in line with that.
> Update requirements in `Package.swift` to match SwiftPM

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
Instead of assuming such dependencies are contained in the 'directDependencies' field of the module info, support querying them from a details of a textual module.
Adds support for dependency scanner changes added in:
https://github.com/apple/swift/pull/66031
> [Dependency Scanning] Add support for Swift Overlay dependencies as a separate dependency details field

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftOptions/Options.swift
- Sources/makeOptions/makeOptions.cpp
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Adds support for '-explain-module-dependency <MODULE_NAME>', which causes the driver to run a dependency scan, and find all dependency paths that cause the main module to depend, directly or transitively, on a given module dependency.
> Add option `-explain-module-dependency` to explain a given direct or transitive module dependency

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Frontend allows unicode chars in package-name. This PR follows the same rule in the driver for consistency.
Resolves rdar://110021211
> Allow unicode chars in package-name in driver

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Description: Allow unicode chars in package-name in driver.
Frontend already allows them but the same change was not made in
driver. This PR fixes that for consistency.
Risk: Low. Frontend already allows unicode chars.
Original PR: https://github.com/apple/swift-driver/pull/1367
Reivewers: @artemcm
Testing: Modified an existing test to allow unicode chars in package-name
Resolves: rdar://110021211
> [5.9] Allow unicode chars in package-name in driver

- Sources/SwiftDriver/IncrementalCompilation/Bitcode/Bitcode.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/BitcodeElement.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/Bits.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/Bitstream.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/BitstreamVisitor.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/BitstreamWriter.swift
- Sources/SwiftDriver/IncrementalCompilation/Bitcode/BlockInfo.swift
We do not vend the bitcode reading as an API that others may use.  Mark this as `internal` as the interfaces are used strictly within the `IncrementalCompilation` module.  If we need, we can extend in the further to use `@package` visibility.
> SwiftDriver: mark bitcode interfaces as `internal`

- Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
This upstream change, llvm/llvm-project@a68ccba, broke looking for ASan on Android, so fix it up.
I didn't bother with a test here as [it won't run without the Android sanitizers being installed](https://github.com/apple/swift-driver/blob/f66dd67ce2d0a5950befb3234004277afa866d75/Tests/SwiftDriverTests/SwiftDriverTests.swift#L2528), and this gets the sanitizer tests from the compiler validation suite working on Android anyway.
> Android: look in lib/linux/ for the LLVM sanitizers instead

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/SerializableModuleArtifacts.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
When we encounter a pre-built Swift binary module dependency (without an interface file), such module may have been built with a bridging header, which must still be present and is referenced by the binary .swiftmodule as either a .h or, more-likely, a pre-built .pch in a fully-explicit build.
Clients must be able to know about such header dependencies in order to be able to import this binary module, because this binary module may be referencing types brought in via its bridging header. The build-system client (swift-driver) will then ensure these header dependencies are fed as inputs to all requiring compilation tasks.
This adds support to the driver to query such header dependencies and feed them as inputs to all requiring compilation tasks.
Companion change to …
> [Explicit Module Builds] Add support for header dependencies of binary Swift module dependencies

- Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Remove unused runtime library path on non-Darwin platforms

- Sources/SwiftDriver/Utilities/Triple.swift
> Triple.swift: fix typos in local and private names

- Sources/swift-help/main.swift
Most just run `swift repl` here, but also reference the possibility of passing Swift Frontend arguments.
rdar://109411493
> Add `repl` to swift-help topics

- Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherrypick of #1374
__Explanation:__ As detailed in the linked issue, the compiler currently looks in `/sdk/usr/lib/swift/` if an `-sdk` is explicitly specified, which may be needed for Darwin platforms, but is unused on non-Darwin.
__Scope:__ Only affects an unused library path on non-Darwin platforns
__Issue:__ apple/swift#63416
__Risk:__ low, as nobody appears to use it
__Testing:__ Passed all CI on trunk
__Reviewer:__ @artemcm
> [5.9] Remove unused runtime library path on non-Darwin platforms

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftOptions/Options.swift
- Sources/makeOptions/makeOptions.cpp
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1365 and https://github.com/apple/swift-driver/pull/1363
-----------------------------------------------------------------
**• Release:** Swift 5.9
**• Explanation:** Cherry-picks of a handful of changes to the dependency scanner, in order to facilitate early experimental adoption of explicit module loading in release compilers. Also cherry-picks the new `-explain-dependency` option, which is purely an opt-in feature and does not affect existing code paths. 
**• Scope of Issue:** This issue impacts only users who opt-in to Explicit Module Builds with the driver's -experimental-explicit-module-build.
**• Origination:** Development of Explicit Module loading
**• Risk:** The risk of this change is low, affected code-paths are not …
> [5.9 🍒] Miscellaneous Dependency Scanner and Explicit Modules Improvements

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
When JSONEncoder puts `mainModuleName` in the end of the JSON dictionary, it does not have `,` in the end. Remove the trailing `,` to avoid such failures.
> Fix a non-deterministic failure in testPrintingExplicitDependencyGraph

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Utilities/Triple.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This error diagnostic doesn't make sense when linking on Linux with Musl, which allows fully statically linked executables.
> Driver: allow static executables when using Musl

- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
With the timeline of the module cache being tied to the current run of the test suite. To try and avoid possible conflicts with stale cached modules.
> Set Explicit Incremental Module Build tests to use own module cache

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- TestInputs/SDKChecks/MacOSX10.15.sdk/SDKSettings.json
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> [Explicit Modules] Handle re-mapped platform versions when specifying SDK-aligned `-clang-target` on Darwin platforms

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- TestInputs/SDKChecks/MacOSX10.15.sdk/SDKSettings.json
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1394
--------------------------------------------
**• Release**: 5.9
**• Explanation**: https://github.com/apple/swift-driver/pull/1322 introduced functionality to the driver where `-clang-target` for all Clang module dependencies is set to the target SDK deployment target on Darwin platforms. The original implementation missed the case of targeting platforms with an SDK-specified OS version re-map, causing incorrect versions to be used in those cases, in Explicit Module Builds.
**• Reviewed by**: @xymus 
**• Scope of Issue**: Explicitly-built module dependencies of builds targeting platforms with a version remap (e.g. MacCatalyst) use incorrect/unexpected target OS versions for Clang module dependencies. 
**• Risk**: Low. This …
> [5.9 🍒][Explicit Modules] Handle re-mapped platform versions when specifying SDK-aligned `-clang-target` on Darwin platforms

- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
As a user when you're changing between versions of these files there's nothing you could do to avoid invalidation so this warning feel superfluous
> Downgrade priors version mismatch warning

- Sources/SwiftDriver/CMakeLists.txt
As of https://github.com/jpsim/Yams/pull/343 and Yams 5.0.0, CYaml is now a private static lib, and we no longer have to link it.
I think we also have to fix this in `release/5.9` and `main`? Do we need separate PRs for those?
> Don't try to link private CYaml in CMake

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/SerializableModuleArtifacts.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Cherry-pick of 
https://github.com/apple/swift-driver/pull/1375
--------------------------------------------------------------------
**• Release**: 5.9
**• Explanation**: When we encounter a pre-built Swift binary module dependency (without an interface file), such module may have been built with a bridging header, which must still be present and is referenced by the binary `.swiftmodule` as either a `.h` or, more-likely, a pre-built `.pch` in a fully-explicit build.
Clients must be able to know about such header dependencies in order to be able to import this binary module, because this binary module may be referencing types brought in via its bridging header. The build-system client (`swift-driver`) will then ensure these header dependencies are fed as inputs to all requiring …
> [5.9 🍒][Explicit Module Builds] Add support for header dependencies of binary Swift module dependencies

- Sources/swift-help/main.swift
Windows relies on the suffix for differentiating files.  The use of `.exe` as the executable suffix is nearly universal on Windows.  Ensure that we use that when targeting Windows, repairing the use of certain subcommands, e.g. `swift help build`.
Fixes: #1404
> swift-help: use the executable suffix on Windows

- Sources/SwiftOptions/Options.swift
Update for https://github.com/apple/swift/pull/67834
rdar://113646544
> Update Options.swift for '-load-plugin-executable' update

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Clang dependency scanning produces scanner PCMs which we may want to live in a different filesystem location than the main build module cache.
Resolves rdar://113222853
> [Dependency Scanning] Add option to specify a separate Clang Dependency scanner module cache.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftOptions/Option.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Follow up to https://github.com/apple/swift-driver/pull/1419.
Resolves rdar://114203755
> Pass -experimental-lazy-typecheck to -emit-module jobs

- Sources/SwiftDriver/Utilities/Triple+Platforms.swift
> Fix comment typo in `Triple+Platforms.swift`

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/MergeModuleJob.swift
The code for doing so was duplicated in three separate job implementations.
> NFC: Consolidate the code for adding symbol graph related options to a job

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
Adjust the driver to include the additional library paths that the driver may want to use.  We would previously only add a single path which worked due to internal ordering assumptions that held up.  This makes the driver more resilient to changes to the target info.
> Jobs: support multiple lookup paths

- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
For Windows host, the on-disk CAS is not yet enabled in libSwiftScan yet (due to the lack of support for Windows path in cached file system abstraction), so report caching is not supported on windows hosts.
> [Caching] Fix caching tests on windows hosts

- Sources/makeOptions/makeOptions.cpp
Generate correct `Options.swift` from new option tablegen output format after https://reviews.llvm.org/D157029.
> [Options] Fix makeOptions after upstream Option TableGen change

- Tests/SwiftDriverTests/SwiftDriverTests.swift
It isn't clear where this was meant to be added in:
https://github.com/apple/swift-driver/blob/b20217113c306addda98b10fcb0783cd469453bd/Sources/SwiftDriver/Jobs/GenericUnixToolchain%2BLinkerSupport.swift#L55
> Disable '-static' flag check on the executable against MUSL test

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This PR introduces an `--ld-path` option, which is forwarded to the Clang linker-driver option with the same name. This change is required to support the `toolset.linker.path` option in [SE-0387](https://github.com/apple/swift-evolution/blob/main/proposals/0387-cross-compilation-destinations.md). 
Upstream: https://github.com/apple/swift/pull/67956.
Downstream: https://github.com/apple/swift-package-manager/pull/6719.
> Forward --ld-path to linker driver

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The test suite is currently entirely broken on Windows (awaiting @cachemeifyoucan to fix apple/swift-driver#1431).  This speculatively changes the driver to alter the search paths to match apple/swift#68322).
> SwiftDriver: speculative changes to support Windows macros

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/IncrementalBuildPerformanceTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Step 1 to fix https://github.com/apple/swift-driver/issues/1431
* Remove unnecessary `try!`: if in the throwable context, just use `try`. There are two remaining in `concurrentPerform` that would be good to be removed in the future, the rest are in setup/generic tests, that are probably file.
* Fix a nil unwrap when using `--parallel`
> Improve swift-driver test cases to avoid fatal crash

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
Add support for pluginCAS by adopting the new SwiftScan CAS creation APIs. The old CAS creation API is deprecated, and will be removed once all users are updated.
> [Caching] Support pluginCAS in swiftDriver

- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This is a version of apple/swift#30465 for the new driver.
Since shared objects are classified as `.object`, they end up getting passed to the autolink-extract job.
For ELF platforms, this is unnecessary, since the autolink entries are not in the final shared object, so the autolink-extract process will not find any entries.
Additionally, in ELF platforms, `.so` files can actually be linker scripts (text files) with instructions for the actual linker, which the autolink-extract job will not understand and will fail.
For those two reasons, modify the autolink-extract inputs to skip over objects in ELF platforms that have the `.so` extension.
> [ELF] Don't pass ELF shared objects to autolink-extract

- Sources/SwiftOptions/OptionParsing.swift
- Sources/SwiftOptions/ParsedOptions.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Fix handling of the '--' argument followed by inputs for the immediate compilation mode ('swift')

- Package.swift
> Update dependencies to track `release/5.10`

- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The vast majority of other options on Swift Driver already use a single dash.
> Make `--ld-path` option consistently use single dash

- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of #1441.
The vast majority of other options on Swift Driver already use a single dash.
> [5.10] Make `--ld-path` option consistently use single dash

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Add a couple of conveniences to `SwiftDriverTests` to reduce the boilerplate necessary to write tests that query planned jobs.
> Add test conveniences to SwiftDriverTests

- Package.resolved
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift
- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/IncrementalCompilation/DependencyGraphDotFileWriter.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift
- Sources/swift-build-sdk-interfaces/main.swift
- Tests/SwiftDriverTests/APIDigesterTests.swift
- Tests/SwiftDriverTests/CrossModuleIncrementalBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Tests/SwiftDriverTests/JobExecutorTests.swift
- Tests/SwiftDriverTests/NonincrementalCompilationTests.swift
- Tests/SwiftDriverTests/ParsableMessageTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/SwiftDriverTests/SwiftDriverToolingInterfaceTests.swift
`<<<` operator has been deprecated in TSC, as it mostly duplicates string interpolation, and the latter should be used instead in most cases where `<<<` was used previously. Additionally, `<<<` can't be introduced to scope with a qualified import (which is the case for any operator).
> Replace deprecated uses of `<<<` with `send`

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
Fixes `Initialization of immutable value 'pathModuleInfo' was never used; consider replacing with assignment to '_' or removing it` warning in `FirstWaveComputer.swift`.
The function's body of which result is unused looks to be free of side-effects, so removing this call should in turn have no effect.
> [NFC] Remove unused constant in `FirstWaveComputer.swift`

- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
After merging https://github.com/apple/swift-driver/pull/1444 there are still a few uses of `<<<` left, which should be cleaned up. This fixes remaining deprecation warnings caused by the use of `<<<`.
> Replace remaining uses of `<<<` operator with `.send`

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The Clang linker driver spells this as `--ld-path` so we can't forward the argument wholesale anymore, since as of #1441 we spell it `-ld-path` in the Swift Driver.
> Fix forwarding of `-ld-path` to Clang

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of d8b48e573f9544427c227e005aaaed62584bf15d
-----
Updates the plugin paths for Windows, where the plugins are in `bin` rather than `lib/swift/host/plugins`.
> [5.9.1] Enable macros for Windows in 5.9.1

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This option and its argument, when specified on the driver command line, should be passed through to jobs that emit modules and have access to the whole module.
Resolves rdar://116538520
> Introduce -emit-api-descriptor-path option

- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Also, remove the `isFrontendArgSupported` check for `-experimental-lazy-typecheck` to simplify testing. There's no need to query whether the frontend supports the flags for this feature since `-experimental-lazy-typecheck` would only be specified on the driver command line explicitly.
Resolves rdar://115731361.
> Add -experimental-skip-non-exportable-decls to lazy typechecking emit module jobs

- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry picks of https://github.com/apple/swift-driver/pull/1465/ and https://github.com/apple/swift-driver/pull/1419.
Resolves rdar://115731361.
> [5.10] Add -experimental-skip-non-exportable-decls to lazy typechecking emit module jobs

- Utilities/build-script-helper.py
The latest trunk snapshot toolchain shows five executables built by SwiftPM that incorrectly have this runpath, three from this repo:
```
> readelf -d swift-DEVELOPMENT-SNAPSHOT-2023-10-10-a-ubuntu20.04/usr/bin/*|ag "File:|runpath"|ag "ORIGIN[^/]" -B1
File: swift-DEVELOPMENT-SNAPSHOT-2023-10-10-a-ubuntu20.04/usr/bin/docc
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../lib/swift/linux]
File: swift-DEVELOPMENT-SNAPSHOT-2023-10-10-a-ubuntu20.04/usr/bin/sourcekit-lsp
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../lib/swift/linux]
File: swift-DEVELOPMENT-SNAPSHOT-2023-10-10-a-ubuntu20.04/usr/bin/swift-build-sdk-interfaces
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../lib/swift/linux]
File: …
```
> [Build Script Helper] Use new SwiftPM flag to remove `$ORIGIN` from installed ELF executable runpaths

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1447.
The Clang linker driver spells this as `--ld-path` so we can't forward the argument wholesale anymore, since we spell it `-ld-path`.
(cherry picked from commit https://github.com/apple/swift-driver/commit/9a357eea6edcd9ab071b2dc379eb838997084e5b)
> [5.10] Fix forwarding of `-ld-path`

- Sources/SwiftDriver/Driver/DebugInfo.swift
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This mirrors a similar change in the swift repository.
> Make the DWARF version configurable.

- Sources/SwiftDriver/Driver/DebugInfo.swift
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1467
> Revert "Make the DWARF version configurable."

- Utilities/build-script-helper.py
Cherrypick of #1462
__Explanation:__ Without this flag, `swift-driver` and the other installed executables look in `usr/bin/` first for shared libraries, but there are none in that executable directory.
__Scope:__ installed executables' runpaths
__Issue:__ none
__Risk:__ none, there were no shared libraries there
__Testing:__ SwiftPM merged using this flag into trunk and 5.10 last week, no problems with `swift-package` itself so far.
__Reviewer:__ @artemcm
> [5.10][Build Script Helper] Use new SwiftPM flag to remove `$ORIGIN` from installed ELF executable runpaths

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
`experimentalFeatures` -> `experimentalFeatures`.
Also fixed uses of deprecated `RelativePath` initializer.
> Fix typos and warnings in `SwiftDriver` module and its tests

- Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This is needed for apple/swift#69564, which enables building the early swift driver and running tests from the compiler validation suite with it for the first time on the linux CI. Looking at those test failures, I noticed that the Swift toolchain wrongly runs `autolink-extract` on linux when simply compiling object files, which is obviously unused:
```
> ./swift-DEVELOPMENT-SNAPSHOT-2023-10-30-a-ubuntu20.04/usr/bin/swiftc -c swift/test/Interpreter/hello_toplevel.swift -v
Swift version 5.11-dev (LLVM e22c96610989bdb, Swift bd372c2d6861ce3)
Target: x86_64-unknown-linux-gnu
/home/foo/swift-DEVELOPMENT-SNAPSHOT-2023-10-30-a-ubuntu20.04/usr/bin/swift-frontend -frontend -c -primary-file swift/test/Interpreter/hello_toplevel.swift -target x86_64-unknown-linux-gnu -disable-objc-interop …
```
> Don't add an autolink-extract job unless actually linking ELF/Wasm objects, matching the original C++ driver

- Utilities/build-script-helper.py
A 5.8 swift-driver does not pass along the `--sanitize` flag to the Clang linker (rdar://107733898). Add this workaround to allow building an ASAN swift-driver with a 5.8 toolchain. This is the swift-driver equivalent to https://github.com/apple/swift/pull/64993.
> Add workaround for 5.8 host swift-driver bug

- README.md
- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/CMakeLists.txt
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/GeneratePCHJob.swift
- Sources/SwiftDriver/Jobs/GeneratePCMJob.swift
- Sources/SwiftDriver/Jobs/Job.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Jobs/VerifyModuleInterfaceJob.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/SwiftScan/SwiftScanCAS.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Sources/SwiftDriver/Utilities/VirtualPath.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
Teach swift-driver to use newly added functions in swift-frontend and libSwiftScan.
> [SwiftDriver] PathRemapping and Cache Replay Support

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
When handling invocations with many input kinds, it is important that the Swift compiler is passed a supplementary output filemap that maps the first `.swift` input to the expected outputs. It is already just a convention that we use the first input for a WMO compilation task. In cases where we use the first input which happens to not be a `.swift` input (e.g. a `.o` input), the Swift compiler fails to map it to expected output kinds of Swift compilation.
Resolves rdar://115577783
> Ensure supplementary output file maps associate Swift Source inputs with expected outputs in WMO

- README.md
- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/CMakeLists.txt
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/GeneratePCHJob.swift
- Sources/SwiftDriver/Jobs/GeneratePCMJob.swift
- Sources/SwiftDriver/Jobs/Job.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Jobs/VerifyModuleInterfaceJob.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/SwiftScan/SwiftScanCAS.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Sources/SwiftDriver/Utilities/VirtualPath.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
Retry add swift caching support.
> Add support for swift caching with path remapping and builtin cache replay

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/SwiftDriver/Jobs/VerifyModuleInterfaceJob.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Support package interface generation.
Generate .package.swiftinterface if `-package-name` is passed.
Add package interface to Module Verification step.
Support `-experimental-package-interface-load` for frontend.
Downgrade typecheck interface error for package.swiftinterface.
Resolves rdar://118469253
> Support package interface gen and verification in driver

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
Cherry-pick #1490 into release/5.10
* **Explanation**: Update Options.swift for newly introduced `-disable-sandbox` and forward the option to `swift-frontend`.
* **Scope**: Frontend options
* **Risk**: Low. The change is localized, and straightforward
* **Testing**: Current test suite cases
* **Issues**: rdar://118419424
* **Reviewer**: Artem Chikin (@artemcm)
> [5.10] Update Options.swift for '-disable-sandbox' 

- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Do not perform dependency scanning when no source inputs are specified

- Package.swift
The llbuild executable is not a dependency of this library.
Looks like I missed removing this when I submitted the similar apple/swift-llbuild#891 for llbuild itself. The issue is that [this breaks cross-compiling this repo for Android armv7, because of some issue with compiling the llbuild executable](https://github.com/finagolfin/termux-packages/actions/runs/6805683976/job/18505666700#step:5:25532), but that executable is not a real dependency in the first place.
@neonichu, please review.
> Revert 'Add missing dependency (#1414)'

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/SwiftScan/SwiftScanCAS.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
Add/adjust APIs from swift-driver for build system integration.
> [Caching] SwiftDriver Caching API refinement for build system

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
When using swift caching, `-Xcc` should not be appended to compilation commmands because dependency scanner returns the cc1 command needed to create clang importer. But `-Xcc` options were accidentally dropped from scan-dependencies command, causing them to be ignored.
rdar://119391228
> [SwiftCaching] Don't drop `-Xcc` during dependency scanning

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Follow up to https://github.com/apple/swift-driver/pull/1500.
The `-dwarf-version` frontend option is still relatively new and in some build configurations, a newer driver may be used with an older frontend that does not understand the argument.
> Only specify -dwarf-version if the frontend supports it

- CMakeLists.txt
We can now vendor the dependencies allowing us to build a separate copy of the dependencies when building the package if it is not provided for. This enables building the package standalone for debugging in scenarios where SPM is unable to build the package (e.g. due to incorrect linking).
> build: support building swift-driver outside of the toolchain

- Tests/SwiftDriverTests/CachingBuildTests.swift
Update cache path remap test to be correctly guarded by remapping because if toolchain doesn't support caching, the remap will be automatically disabled and remap will not happen.
> [Test] Remap test should be guarded by caching feature

- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Fixes: https://github.com/apple/swift-driver/issues/1507
> Disable CachingBuildTests on windows

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Recent changes seem to have regressed the test suite on Windows due to the construction of the `ByteString` from the `String`.  Repair this to allow us to test on Windows again.
> tests: repair the test suite on Windows

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Correct the spelling for the argument for the `-debug-info-format`.  We were incorrectly emitting the enum name instead of the value, which would break the build when CodeView was enabled.
> SwiftDriver: repair the generation of CodeView debug info

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Utilities/Sanitizer.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
new sanitiers stable ABI in compiler-rt.
Compiler-rt recently introduced a stable ABI for sanitizers. This patch adds a flag to pass this flag to swift-frontend during compilation and clang at link time to link against the new stable ABI.
NOTE: this was https://github.com/apple/swift-driver/pull/1495 , but Usama is out till after the new year break, so I need to take over and apply feedback from there
rdar://118997873
> [Sanitizer] Add new flag -sanitize-stable-abi flag to link against the

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This reverts commit 3615d0645bc2a32f8cf8b48bb4fc1c0226b60f39.
rdar://117027065
> Revert "[Driver] For immediate mode prefer using the default SDK over the `SDKROOT` variable"

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
These options already aren't passed to the linker when linking statically, we shouldn't pass them in embedded mode either, where everything is linked statically too.
I've been able to reproduce this bug with `wasm32-none-none-wasm` triples, but this should fix possible issues for other embedded triples too.
> Don't pass `-rpath` and `-lswiftCore` in embedded mode

- Sources/SwiftDriver/Utilities/Triple.swift
- Tests/SwiftDriverTests/TripleTests.swift
This architecture is available in [LLVM's `Triple` implementation](https://github.com/llvm/llvm-project/blob/a01b58aef0e42fb1b52e358adf4c56678a884d37/llvm/include/llvm/TargetParser/Triple.h#L62C55-L63C51) and has [an experimental LLVM backend](https://m680x0.github.io/doc/build-from-source) available in upstream LLVM sources. It would be great to have this triple variation supported in the driver, as this architecture is relatively popular in retrocomputing enthusiast circles. It was used in Amiga, Atari ST, Sega Genesis, and of course Apple Lisa and Apple Macintosh. It is supported by Qemu and multiple Linux distributions, including Debian.
> Add `m68k` to `Triple.swift`

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/SwiftScan/SwiftScanCAS.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/TestUtilities/DriverExtensions.swift
If the oracle has been used to create a CAS for the path, reuse the CAS if it is asked to create the same CAS again. This not only save the work of creating the CAS, but also avoid a potential problem that the CAS closing synchronization doesn't work across threads in the same process due to its uses of file lock.
> [CAS] Don't create the same CAS multiple times from the same Oracle

- Sources/SwiftDriver/Utilities/Triple.swift
With retroactive conformances triggering warnings in Swift 5.11, it makes more sense to declare `Decodable` on the original declaration instead of adding it retroactively in modules where `Triple.Arch` is used.
> [NFC] Add `Decodable` conformance to `Triple.Arch`

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
When building for embedded the link phase invocations would contain `@/path/to/swift` which is a directory and not a valid link list. This corrects that logic to appropriately avoid that link file path.
> [Embedded] correct link paths when building for embedded to avoid stray response file paths

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
By catching the relevant errors as thrown from the `InterModuleDependencyOracle` and ensuring diagnostics are emitted before re-throwing them.
> [Dependency Scanning] Upon scan failure, ensure scanner diagnostics are emitted

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The flag `-no-verify-emitted-module-interface` tells the driver to skip verifying the swiftinterfaces emitted by the compiler. Let's pass it down to the frontend as well and so it can write it down in the skipped swiftinterface. This will help understand them from the reader side.
rdar://120445669
> Pass down the -no-verify-emitted-module-interface flag to the frontend

- Sources/swift-driver/main.swift
- Tests/SwiftDriverTests/IntegrationTests.swift
With the swift-driver executable becoming the default target of `swift` and `swiftc` symlinks, we need to allow for the prior mechanism afforded by this flag.
Companion to:
https://github.com/apple/swift/pull/69834
> Add fallback to auxiliary legacy driver executable on '--disallow-use-new-driver'

- Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherrypick of #1479
__Explanation:__ This driver has long run `autolink-extract` even when it wasn't linking, which the old C++ driver didn't. Get the two matched up.
__Scope:__ Compilation jobs that don't link don't need autolink
__Issue:__ none
__Risk:__ none, this was superfluous
__Testing:__ Tested this on trunk with the newly enabled early swift driver tests on the linux CI, no problem.
__Reviewer:__ @artemcm
> [5.10] Don't add an autolink-extract job unless actually linking ELF/Wasm objects, matching the original C++ driver

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
These files exist outside the task execution graph and are not produced by any of the tasks involved, so we rely on trusting they are present. This is crucial because these paths may be pre-VFS-remap paths which means that the driver (not-VFS-aware) may not have access to their "external" path and thus unable to verify their actual existence.
> [Explicit Module Builds] Do not specify Clang dependency `module.modulemap` files as task inputs

- Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift
Static "ar"chivers not prefixed with "llvm-" rarely support WebAssembly object file formats, and the legacy driver uses "llvm-ar", so it would be better to keep the consistency.
This unblocks the use of swift-driver for WebAssembly target.
> Prefer `llvm-ar` over `ar` on WebAssembly

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/GeneratePCHJob.swift
- Sources/SwiftDriver/Jobs/GeneratePCMJob.swift
- Sources/SwiftDriver/Jobs/VerifyModuleInterfaceJob.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/SwiftScan/SwiftScanCAS.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
Using the new APIs from libSwiftScan for cache key computation. The new API doesn't require swift-driver and scanner to have the same file system view for the path of the input files, which eliminates one failure point.
rdar://119517627
> [Caching] Adopt new APIs from libSwiftScan for key computation

- Tests/SwiftDriverTests/SwiftDriverTests.swift
testSanitizeStableAbi fails on Linux. The SanitizeStableAbi for now only makes sense
on Apple OSes, so limiting the test to those
rdar://121121682
> Only run testSanitizeStableAbi on Apple platforms

- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
After reading a prior intermodule dependency graph in an incremental explicit module build, the driver loops over each module in the graph to check if it is up to date. The check which is intended to skip the main (Swift) module was skipping a clang module with the same name as well, if it existed. If this clang module was the only one to be updated in an incremental compile, we wouldn't regenerate its pcm, and compilation would later fail since it wasn't up to date.
rdar://121352768
> Fix explicit modules incremental build failure when only the clang module of a mixed-source module requires rebuild

- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
In order to get better error message on the build system, make DependencyScanningError conform to LocalizedError and return descriptive `errorDescription` for build system to display.
> Make DependencyScanningError conform to LocalizedError

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Issue a warning and disable compile job caching when explicit module is not enabled. This prevents swift-driver attempting to planning a caching build using implicit build, which will result into either a build system crash or bad swift-frontend invocations.
rdar://121206439
> [Caching] Issue a warning when caching build without explicit module

- Sources/SwiftDriverExecution/MultiJobExecutor.swift
We already have a way to say "a subprocess failed", use it. Fixes rdar://121627384.
> When terminating because a subprocess failed, don't print `error: fatalError`

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Currently when linking with `swiftc` for `-unknown-none-` triples, it attempts to link `swiftrt.o` runtime file, which is currently not needed and is not present for these triples. We should avoid linking it in these cases.
> Embedded: don't link `swiftrt.o` for bare metal

- Sources/SwiftDriver/Jobs/Toolchain+InterpreterSupport.swift
Add DYLD_FRAMEWORK_PATH=/System/Library/Frameworks to the environment when constructing swift-frontend invocations for the interpreter so that dlopen can find autolinked frameworks.
Resolves #68785.
> For scripts, use DYLD_FRAMEWORK/LIBRARY_PATH to find frameworks / runtimes.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Execution/DriverExecutor.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/swift-build-sdk-interfaces/main.swift
For possible clients to have access to the full module dependnecies info.
> [Explicit Module Builds] Add an instance of `InterModuleDependencyGraph` to the DriverExecutorWorkload

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Add APIs for SwiftDriver library users to directly load/check the libSwiftScan directly before calling into its function.
* Add APIs to query Driver for libSwiftScan location
* Make `verifyOrCreateScannerInstance` to be public APIs to load or check the libSwiftScan.
* Update `verifyOrCreateScannerInstance` to be more ergonomic to use. The function only returns true if the given path to libSwiftScan does not exist while most of the time caller actually errors out in those cases. Make throwing error the default behavior and caller can check for file existance before calling the function to perserve old behavior.
> [SwiftScan] Add APIs to load/check libSwiftScan directly

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Cache input files and command-line argument additions describing main module explicit module dependencies to each individual job. Instead of re-computing them for each compile task, which includes serializing a whole new `.json` file with the inputs.
> [Explicit Module Builds] Cache explicit dependency additions to main module command-lines

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The `-Xlinker` values should be passed to Clang with `-Xlinker` but it was not done for WebAssembly. This patch fixes it by factoring out the common logic for processing `-Xlinker` and `-Xclang-linker` options and using it in all toolchains.
> Fix wrong -Xlinker propagation to Clang with WebAssembly

- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Just port a missing part from legacy driver:  https://github.com/apple/swift/blob/387156ae1127983afdc4325ebedbb35d72997f34/lib/Driver/WebAssemblyToolChains.cpp#L190-L193
> Port `--global-base` option for WebAssembly from legacy driver

- Sources/SwiftDriver/Driver/Driver.swift
When a bridging header is present but `-disable-bridging-pch` is used, the resulting build is not fully using explicit module build which swift caching is relied on. Emit a warning and disable caching in this case.
> [Caching] Disable caching when -disable-bridging-pch is used

- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The second argument is often treated specially as a mode specifier for tools. This is particularly important for Windows where `-lib` or `/lib` passed to `link` or `ld.lld-link` will change the linker to the librarian. This argument may not be sunk into the response file as it is not treated as the mode specifier then. Special case the first two arguments to ensure that the mode switch parameter is always passed for any tools.
> Execution: special case the first two arguments in RSP mode

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
Fix a typo in pluginCAS creation to use the plugin path from the correct option. Also do not eagerly trying to look for a pluginCAS if not requested.
> [CAS] Fix pluginCAS initialization

- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Jobs/VerifyModuleInterfaceJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Verify the emitted modules interfaces automatically unless opted out by the `-no-verify-emitted-module-interface` flag or a mention of the module by name on the blocklist. Blocklisted modules are noted by a remark and can still be verified by locally setting `-verify-emitted-module-interface` or defining the env var `ENABLE_DEFAULT_INTERFACE_VERIFIER`.
> Verify emitted module interfaces by default and introduce blocklist

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
Fix a bug that can cause scanner args to be dropped from the main module build command.
> [Caching] Fix scanner args were dropped when resolveMainModuleDependencies were called multiple times

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The flag `-no-verify-emitted-module-interface` may still rejected by older frontends, make sure the local frontend accepts it before passing down the flag.
rdar://123345345
> Only pass down the `-no-verify-emitted-module-interface` flag if the frontend accepts it

- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This change makes the clang linker driver for Wasm targets respect the `-tools-directory` option. This is necessary to use linker tools from Swift SDK toolset.
> Passthrough `-tools-directory` as `-B` to clang linker for Wasm target

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Adopts new API that produces per-scan diagnostics for each query of a dependency graph or an import set
Driver part of https://github.com/apple/swift/pull/71907
> [Dependency Scanning] Add and use API for per-query diagnostic gathering

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
Refine unsupportedCachingConfiguration to be a DependencyScanningError because:
* It can only be found during dependency scanning that some dependency requirement for caching is not satisfied.
* DependencyScanningError is a LocalizedError that can help build system to better displayed the error.
rdar://123654299
> [Caching] Move unsupportedCachingConfiguration to be scanning error

- Utilities/build-script-helper.py
This will hopefully fix the following error that has been causing the https://ci.swift.org/job/oss-swift-RA-linux-ubuntu-18_04-long-test/ pipeline to fail for a few days:
```
UnicodeEncodeError: 'ascii' codec can't encode character '\u2502' in position 100311: ordinal not in range(128)
```
Resolves rdar://123809082
> Set `stdout` and `stderr` encodings to UTF-8 in `build-script-helper.py`

- Utilities/build-script-helper.py
An alternative attempt to https://github.com/apple/swift-driver/pull/1554. Some systems still use Python 3.6 where `reconfigure` is not available.
rdar://123809082
> Avoid ascii/utf encoding errors on some systems

- Tests/SwiftDriverTests/SwiftDriverTests.swift
The index was incorrectly `2` for non-Darwin targets. Windows does not have the autolink extract phase which results in a off-by-one index. Use the test helper to exclude the auto-link-extract job to support Linux and Windows similarly.
> Tests: repair test for Windows

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
SwiftDriver should compute `-file-compilation-dir` when debug info is used. This can avoid `swift-frontend` to compute its own compilation directory, which can cause `swift-frontend` to generate different code with the same command if current working directory changed.
> Compute and append -file-compilation-dir when -g options are used

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
A follow-up to #1557 that when caching is enabled and using the scanner prefix mapping option to canonicalize the path, make sure the path passed via `-file-compilation-dir` is remapped.
> [Caching] Remap the path in `-file-compilation-dir` if needed

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Utilities/Triple+Platforms.swift
- Sources/SwiftDriver/Utilities/Triple.swift
The Swift driver needs to understand the new triple and needs to know the platform name to which that corresponds.
rdar://123442522
> Update driver for fully static Linux.

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
Update swift-driver to support directly instantiate clang importer in all jobs with cc1 flags. In the new mode, swift dependency scanner will return all the cc1 flags to the actual compilation doesn't need to run clang driver again. In this mode, swift-driver should avoid forwarding Xcc command-line options since those are expected to be clang driver args, not cc1 args.
> [ExplicitModule] Support direct cc1 flag for all explicit module build job

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Teach swift driver to use a deterministic path for compiled PCH output. Also when dependency scanner is updated to return a module scanning or PCH hash from the scanning result, it will add that to the code path to have an unique PCH file path for the specific compilation.
> [BridgingHeader] Provide a deterministic unique pch file path

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
We are evaluating doing eager module loading in: https://github.com/apple/swift/pull/72471
> [ExplicitModuleBuilds][NFC] Remove lazy module loading check in explicit module tests

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick https://github.com/apple/swift-driver/pull/1573 into `release/6.0`
* **Explanation**: Apple SDK plugins are placed under '{}.platform/Developer/usr' directories, not in the SDK directory. Adding nonexisting paths can be confusing.
* **Scope**: Frontend arguments for Darwin platforms
* **Risk**: Low. The paths were never used and non-exisitent
* **Testing**: Updated regression test cases
* **Issues**: rdar://121451763
* **Reviewer**: Doug Gregor (@DougGregor)
> [6.0] Stop adding '-external-plugin-path' to SDK directories

- CMakeLists.txt
- Sources/CMakeLists.txt
- Sources/makeOptions/CMakeLists.txt
Introduce the ability to build `makeOption` via CMake if desired. This requires passing additional parameters -
`-D LLVM_DIR=... -D Clang_DIR=... -D Swift_DIR=...` to the CMake invocation to allow us to find the required include paths.
> build: add the ability to build tools with CMake

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/SerializableModuleArtifacts.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
When passing in '-explicit-swift-module-map-file', specify which Clang modules are dependencies of textual headers of the main module and binary Swift module dependencies. This relies on a new entry-point in 'libSwiftScan': 'swiftscan_swift_binary_detail_get_header_dependency_module_dependencies'. The compiler will then use this information to determine which Clang modules require an explicit '-fmodule-map-file' ClangImporter input.
Companion to the compiler's: https://github.com/apple/swift/pull/72668
> [Explicit Module Builds] Specify which Clang module dependencies are bridging header dependencies

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/SerializableModuleArtifacts.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
**Explanation:**
This PR is a collection of Explicit Module Build improvements and fixes:
- https://github.com/apple/swift-driver/pull/1571:
When passing in `-explicit-swift-module-map-file`, specify which Clang modules are dependencies of textual headers of the main module and binary Swift module dependencies. This relies on a new entry-point in `libSwiftScan`: `swiftscan_swift_binary_detail_get_header_dependency_module_dependencies`. The compiler will then use this information to determine which Clang modules require an explicit `-fmodule-map-file` ClangImporter input.
- https://github.com/apple/swift-driver/pull/1565:
Covers the case where not all paths were printed with `-explain-module-dependency`.
**Risk:** Low. Code-paths disabled by-default and the changes are meant to improve …
> [6.0🍒][Explicit Module Builds][SwiftDrver] Cherry-pick Explicit Module Loading fixes and improvements

- Sources/SwiftDriver/Utilities/Triple.swift
- Tests/SwiftDriverTests/TripleTests.swift
This reflects corresponding architecture component handling in LLVM: https://github.com/apple/llvm-project/blob/c7d5769e8229c589f9de3d5a88e36ffbfec164fa/llvm/lib/TargetParser/Triple.cpp#L572.
> Implement basic `xtensa` architecture triple parsing

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Explanation: SwiftDriver changes needed for swift caching support
Original PR: https://github.com/apple/swift-driver/pull/1567 https://github.com/apple/swift-driver/pull/1550
Risk: Low. Mostly only affects swift caching experimental feature.
Testing: Unit tests
> [6.0][Caching] SwiftDriver changes for caching support

- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Fix all the tests that expect building module from interface even when the binary module is up-to-date after the swift scanner behavior change.
> Support for binary module validation in scanner

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Utilities/Triple+Platforms.swift
- Sources/SwiftDriver/Utilities/Triple.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Companion change to https://github.com/apple/swift/pull/72834
> Introduce visionOS Platform

- Sources/SwiftDriver/Utilities/Triple+Platforms.swift
- Sources/SwiftDriver/Utilities/Triple.swift
This fixes concurrency warnings when building with Swift 6.
> Mark `Triple` and its nested types as `Sendable`

- Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
Heap --showInternalFragmentation shows that we are loosing 14 bytes to padding in Node instances.
Class: 'Node' [instance size 104, allocation size 112] - Swift, ARC {
...
}
16:  keyAndFingerprint;
<< 7 alignment bytes >>
64:  definitionLocation;
88:  isTraced;
<< 7 alignment bytes >>
96:  cachedHash;
}
Moving isTraced up here will push Node instance allocations to the next quanta (96)
> Decrease the number of padding bytes in the Node Struct so it fits a lower quanta

- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Explanation:
Fix test failures on swift-6.0 branch due to missing a cherry-pick from test fixes that should come with swift compiler changes. The swift 6.0 test passes because sometimes the swift-driver test failure doesn't return error status and can return success for PR testing.
Original PR: https://github.com/apple/swift-driver/pull/1563
Risk: Low. Only test update
Testing: UnitTest
Reviewed By: @artemcm
> [6.0][Tests] Support for binary module validation in scanner

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Utilities/Triple+Platforms.swift
- Sources/SwiftDriver/Utilities/Triple.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1577
------------------------
**Explanation**: This change introduces a new compilation target platform to the Swift compiler - visionOS.
Companion change to https://github.com/apple/swift/pull/73062
**Risk**: Low, additional code-paths should have little effect on compilation for existing platforms.
**Testing**: Automated tests added to the compiler test suite. Existing tests adjusted for the new platform.
**Reviewed By**: @CodaFi
> [6.0 🍒] Introduce VisionOS Platform

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
Remove the CASError that prevents creating two different CAS at the same CAS path. This allows build system to create compatible CAS at the same location even the configuration is slightly different.
> [Caching] Remove the error for creating multiple CAS at same location

- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The following invocation should schedule an emit-module-separately job for src.swift and include other.dylib in the link job.
```
swiftc src.swift other.dylib -emit-library -emit-module
```
rdar://127238278
> Schedule an emit-module-separately job even if an input is not compilable

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
For example, when using a `swift.org` toolchain, which contains the stdlib in the resource directory, we should use toolchain's `SwiftMacros` plugin instead of the platform's one.
> Prefer toolchain's plugins to SDK plugins if the toolchain has stdlib

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
**Description**:  For example, when using a swift.org toolchain, which contains the stdlib in the resource directory, we should use toolchain's SwiftMacros plugin instead of the platform's one. This is necessary because `@TaskLocal` now have become macros, and other projects within swift project must be using it (and thus be able to find the macro).
**Scope/Impact**: 
**Risk:** Low
**Testing**: CI testing and @rintaro manually verified
**Reviewed by**: @ktoso (making cherry-pick on behalf of @rintaro who did the PR)
**Original PR:** https://github.com/apple/swift-driver/pull/1590
> [6.0] Prefer toolchain's plugins to SDK plugins if the toolchain has stdlib 

- Sources/SwiftDriver/SwiftScan/SwiftScanCAS.swift
Do not resume with returning after resume with throwing when there is an error returned from CAS service.
> [CAS] Fix task continuation misuse when CAS error happens

- Sources/SwiftDriver/SwiftScan/SwiftScanCAS.swift
Explanation: Fix a crash due to misuse continuation when error happens
Scope: This fixes a bug that can cause crashes when error happens when enable remote caching for swift compilation
Original PR: https://github.com/apple/swift-driver/pull/1591
Issue: rdar://127452621
Risk: Low. Only affects compilation caching and when some kind of error happens from CAS
Reviewer: @benlangmuir
> [6.0][CAS] Fix task continuation misuse when CAS error happens

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Not all generic-"unix" environments have the Gold linker available to them, and in some cases, the vendor of the toolchain may provide their own linker. In these cases, the driver should be internally consistent with the toolchain that it is shipped with.
Now that we have the clang-linker, we can lean on the linker selection in the clang-linker to determine a default linker. If the clang-linker, and thus, the swift compiler driver, are part of a specific toolchain, that clang-linker should be built for that platform with the appropriate linker defaults set. If someone overrides the linker with `-use-ld`, we should still honour that, but should otherwise be consistent with the appropriate toolchain linker.
This will enable building and linking on AmazonLinux 2023 without requiring folks to …
> Update Generic Unix linker selection

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1545
We're hitting issues where the driver is picking up BFD instead of Gold and mislinking:
```
error: link command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld: /home/build-user/build/buildbot_linux/libdispatch-linux-x86_64/src/swift/CMakeFiles/swiftDispatch.dir/Block.swift.o: relocation R_X86_64_PC32 against protected symbol `$s8Dispatch0A13WorkItemFlagsVSYAAMc' can not be used when making a shared object
/usr/bin/ld: final link failed: bad value
```
Telling the built clang to use gold did not work so I'll need to figure out which clang the driver is trying to use here: https://github.com/apple/swift/pull/73463
> Revert "Update Generic Unix linker selection"

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Fix parsed name of the newly-added `SDKPlatformKind` to use raw toolchain name

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1598
-----------------------------------------
**Explanation**: This change fixes the enum used to represent platform kind to correctly detect the VisionOS SDK platform by using its toolchain name string as the raw value.
**Risk**: Low. The change seems to only affect code-paths used by the `swift-generate-sdk-interfaces` tool and will not affect other platforms.
**Testing**: Automated test added to the compiler test suite.
Resolves rdar://127704084
> [6.0🍒] Fix parsed name of the newly-added `SDKPlatformKind` to use raw toolchain name

- Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
These warnings are not actionable by the user. Instead issue a remark, so as to avoid having these messages being raised as issues in build logs.
> Do not warn on failure to in-process query target info or supported features

- Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1597
------------------------------
**Explanation**: These warnings are not actionable by the user. Instead issue a remark, so as to avoid having these messages being raised as issues in build logs.
**Risk**: None. Replaces an existing warning with a remark
**Reviewed by**: @owenv
> [6.0🍒] Do not warn on failure to in-process query target info or supported features

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
There are two situations when emiting modules are not correctly handled when swift caching is enabled:
* When only `-emit-module` task is requested from driver, in this case, we are contructing a `CompileJob` but only generating module output. SwiftDriver still expects all swift inputs will have a cache key even only the first file is generating outputs and has a cache key.
* When using `-experimental-emit-module-separately`, then swift-driver needs to construct a `EmitModuleJob`, which wasn't taught the concept of caching and not producing any cache key.
rdar://127768967
> [Caching] Handle emit module job correctly for swift caching

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
Explanation: Fix cache key mis-match between swift-frontend and swift-driver that can cause caching inconsistency when only emit module job is scheduled by swift-driver.
Scope: Fixes issue that build system can wrongly think cache miss when it is actually cache hit, or misidentify certain job as not cacheable and always run the compilation.
Issue: rdar://127768967
Original PR: https://github.com/apple/swift-driver/pull/1602
Testing: unit test
Reviewer: @artemcm @xymus
> [6.0][Caching] Handle emit module job correctly for swift caching

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
> Fallback on `swift-frontend -scan-dependencies ...` fallback path in case `libSwiftScan` shared library cannot be loaded.

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Adds valid arguments to -sanitize-coverage: `pc-table` and `inline-8bit-counter`. 
As is, you cannot set all default fuzzer options directly using -sanitize-coverage. Because of this you can use default fuzzer sanitize-coverage args, or a limited number coverage options. 
This PR adds options to allow `pc-table` and `inline-8bit-counter` as valid args. These are default fuzzer options -- and will allow customizing sanitizer-coverage in variations of fuzzer defaults. (i.e. w/o `pc-table` enabled).
In upstream clang the option -fno-sanitize-coverage exists to disable various coverage options. Swift currently does not have a convention of using excluding args for sanitizer flags. This aims to limit the need for a new flag by inclusively setting desired coverage up to current fuzzer defaults. …
> Add additional valid args to sanitize-coverage flag

- Sources/SwiftDriver/Jobs/CommandLineArguments.swift
- Sources/SwiftOptions/Option.swift
- Sources/SwiftOptions/OptionParsing.swift
- Sources/SwiftOptions/OptionTable.swift
- Sources/SwiftOptions/Options.swift
- Sources/SwiftOptions/ParsedOptions.swift
- Sources/makeOptions/makeOptions.cpp
- Tests/SwiftOptionsTests/OptionParsingTests.swift
Teach SwiftOption to handle MultiArg options, including generating Options from Options.td, etc. Even the only MultiArg option in swift is a NoDriver option, still teach the OptionTable to parse such options to future proof the implementation.
> [Option] Support MultiArg options

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1601
-----------------------------------
**Explanation**: On failure to load `libSwiftScan` when Explicitly Built Modules are enabled, attempt to run a dependency scan by invoking `swift-frontend -scan-dependencies ...` on the shell and parsing out the JSON output. 
**Risk**: Low. This change affects a code-path that is followed only in the event that the Swift toolchain is not configured with a correctly (as-expected) placed libSwiftScan or the event that there is a code-signing difference between the client process and the libSwiftScan it attempts to load. Previously, in these cases we encountered a hard failure. Now, we will try a best-effort fallback path attempt. Default code-path remains unaffected.
**Testing**: Test added to …
> [6.0🍒] Fallback on `swift-frontend -scan-dependencies ...` fallback path in case `libSwiftScan` shared library cannot be loaded.

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/swift-driver/main.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Adopt new libSwiftScan API to get source location for each emitted diagnostic: buffer identifier, line number, column number.
This change uses functionality added in: https://github.com/apple/swift/pull/73600
> [Explicit Module Builds] Get source locations from the dependency scanner and emit diagnostics with them

- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
'+' isn't allowed in environment variable names so it's impossible to set the Clang++ executable at the moment. Replace `+` with `X` so that we can set `SWIFT_DRIVER_CLANGXX_EXEC` to set the clang++ executable.
Fixes: rdar://128007218
> Allow setting the clang++ environment variable

- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The following invocation should schedule an emit-module-separately job for src.swift and include other.dylib in the link job. This fixes an issue that would make the compiler instead schedule a deprecated merge-module job.
```
swiftc src.swift other.dylib -emit-library -emit-module
```
Risk: Low, not many clients use this path and emit-module-separately is more reliable than merge-module.
Scope: Projects calling the driver as an executable from cmake.
Reviewed by @artemcm 
Cherry-pick of #1588
Resolves rdar://127238278
> [6.0] Schedule an emit-module-separately job even if an input is not compilable

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Adds valid arguments to -sanitize-coverage: pc-table and inline-8bit-counter.
As is, you cannot set all default fuzzer options directly using -sanitize-coverage. Because of this you can use default fuzzer sanitize-coverage args, or a limited number coverage options.
This PR adds options to allow pc-table and inline-8bit-counter as valid args. These are default fuzzer options -- and will allow customizing sanitizer-coverage in variations of fuzzer defaults. (i.e. w/o pc-table enabled).
In upstream clang the option -fno-sanitize-coverage exists to disable various coverage options. Swift currently does not have a convention of using excluding args for sanitizer flags. This aims to limit the need for a new flag by inclusively setting desired coverage up to current fuzzer defaults. …
> Adds valid arguments to -sanitize-coverage: pc-table and inline-8bit-counter.

- Sources/SwiftDriver/Jobs/CommandLineArguments.swift
- Sources/SwiftOptions/Option.swift
- Sources/SwiftOptions/OptionParsing.swift
- Sources/SwiftOptions/OptionTable.swift
- Sources/SwiftOptions/Options.swift
- Sources/SwiftOptions/ParsedOptions.swift
- Sources/makeOptions/makeOptions.cpp
- Tests/SwiftOptionsTests/OptionParsingTests.swift
Explanation: Add MultiArg support in swift-driver in preparation for landing https://github.com/apple/swift/pull/73601
Scope: This supports generating Options.swift from swift after add new arguments with MultiArg.
Original PR: https://github.com/apple/swift-driver/pull/1609
Reviewer: @owenv @artemcm 
Test: UnitTest
> [6.0][Option] Support MultiArg options

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts apple/swift-driver#1596
Alright ready to re-land this. The issue was that, during the build, the just-built Swift driver would choose the clang from the system instead of the just-built clang that was configured to use `gold` or `lld`. The system clang was configured to use the gnu bfd linker instead of gold or lld. BFD has a known issue with our use of protected symbols and would fail during the Dispatch build with the following error:
> error: link command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld: /home/build-user/build/buildbot_linux/libdispatch-linux-x86_64/src/swift/CMakeFiles/swiftDispatch.dir/Block.swift.o: relocation R_X86_64_PC32 against protected symbol `$s8Dispatch0A13WorkItemFlagsVSYAAMc' can not be used when making a shared object
> /usr/bin/ld: …
> Revert "Revert "Update Generic Unix linker selection""

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The SDKSettings.json file is only used for Darwin platforms, so we should not emit a warning about it being missing for non-Darwin platforms.
> Suppress warning about missing SDKSettings.json for non-Darwin platforms

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
Pass through `-compiler-assertions` to the compiler to enable run-time-switchable assertions
> Pass through `-compiler-assertions` to the compiler

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
Update the graph traversal so that we never need to visit a node more than once.
> Improve performance of precompiled module invalidation in incremental builds

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
Explanation: Simplify the explicit precompiled module invalidation algorithm for incremental builds so that it only visits each module in the graph once, avoiding a slowdown in the worst case where all/most modules in the graph are invalidated
Risk: Low. The changes are narrow in scope and covered by existing tests in the incremental build suite.
Testing: Existing incremental build correctness tests
Original PR: https://github.com/apple/swift-driver/pull/1626
> [6.0] Improve performance of precompiled module invalidation in incremental builds

- Package.swift
Cherrypick of #1481
__Explanation:__ The llbuild executable is not a dependency of this library.
__Scope:__ Removes wrongly added llbuild dependency
__Issue:__ None
__Risk:__ low, as less code is built after this
__Testing:__ Passed all CI on trunk
__Reviewer:__ @artemcm
> [5.10] Revert 'Add missing dependency (#1414)'

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/LinkJob.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Adopt new libSwiftScan API to query link libraries for each module dependency
- Introduce '-explicit-auto-linking' to turn explicit dependency link library information into flags passed directly to the linker invocation
> [Explicit Module Builds] Adopt dependency scanner Link Libraries support

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
For example consider the following module graph:
```mermaid
graph LR;
test-->J;
J-->G;
```
Where on an incremental build we detect that although `G` binary module product is *newer* than its textual source, said binary module product is also *newer* than a prior binary module product of `J`. Which means that although each of the modules is up-to-date with respect to its own textual source inputs, `J`'s module dependency's binary input has been updated elsewhere and `J` needs to be re-built. 
Resolves rdar://129225956
> [Explicit Module Builds][Incremental Builds] Re-compile module dependencies whose dependencies are up-to-date themselves but are themselves newer

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
Due to C API renaming, swift-driver failed to record the bridging header path from a binary swift module dependencies. Fix the issue by supporting both old and new C APIs for querying bridging header path.
rdar://129703095
> [SwiftScan] Fix headerDependencies in SwiftPrebuiltExternalModuleDetails

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1628
------------------------------------------------------
**Explanation**: For example consider the following module graph:
```mermaid
graph LR;
test-->J;
J-->G;
```
Where on an incremental build we detect that although `G` binary module product is *newer* than its textual source, said binary module product is also *newer* than a prior binary module product of `J`. Which means that although each of the modules is up-to-date with respect to its own textual source inputs, `J`'s module dependency's binary input has been updated elsewhere and `J` needs to be re-built. 
**Risk**: Low. This change adds to incremental explicitly-built module re-build filtering logic to also check timestamps of module dependency outputs of a given module …
> [6.0 🍒][Explicit Module Builds][Incremental Builds] Re-compile module dependencies whose dependencies are up-to-date themselves but are newer

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
Explanation: Fix a bug in swift-driver that after a C API rename, the bridging header path can no longer be queried from dependency graph returned from scanner and always be empty.
Scope: This affects builds that depends on the information that is missing now.
Issue: rdar://129703095
Original PR: https://github.com/apple/swift-driver/pull/1633
Risk: Low. The fix supports both version of C API.
Test: UnitTest
>  [6.0 🍒][SwiftScan] Fix headerDependencies in SwiftPrebuiltExternalModuleDetails

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The default debug info format for newer versions of Darwin is DWARF 5.
https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes
rdar://110925733
> Bump the DWARF version number to 5 on Darwin.

- Sources/SwiftDriver/Utilities/Triple+Platforms.swift
NFC change to switch statement to avoid previously handled case warning.
> Fix spurious warning

- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Including the full hash of the job can lead to unnecessary duplication of the file, inhibiting job deduplication
- Use a stable hash to ensure the response file name does not change from one process execution to the next
> Response files should be named using the hash of the command line arguments only

- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Explanation:
Including the full hash of the job can lead to unnecessary duplication of the file, inhibiting job deduplication
Use a stable hash to ensure the response file name does not change from one process execution to the next
Risk: Low. This PR only impacts the naming convention for response files.
Testing: New unit test
Original PR: https://github.com/apple/swift-driver/pull/1636
Reviewer: @nkcsgexi @cachemeifyoucan
> [6.0] Response files should be named using the hash of the command line arguments only

- Sources/swift-build-sdk-interfaces/main.swift
Explanation: When building modules for an SDK, we need to ignore any existing prebuilt modules to avoid building a partial prebuilt module cache. Make sure we do ignore them by passing down an intentionally-bogus path for the existing prebuilt module cache.
Scope: Prebuilt module cache generation logic only, very narrow.
Risk: Very low due to narrow scope.
Testing: Passes current test suite.
Main PR: https://github.com/swiftlang/swift-driver/pull/1649
Issue: rdar://131183526
> Ignore prebuilt module cache when building the prebuilt module cache

- Sources/swift-build-sdk-interfaces/main.swift
Since https://github.com/swiftlang/swift/pull/72291 landed, this tool has been in a state where it can accidentally pick up existing prebuilt deps instead of generating new ones from-scratch (`.swiftinterface`).
> [PrebuiltModuleGen] Ensure the dependency scanner always ignores existing prebuilt modules

- Sources/swift-build-sdk-interfaces/main.swift
- **Explanation:** As an unintended consequence of https://github.com/swiftlang/swift/pull/72291, this tool has now started to occasionally pick up binary modules from a prebuilt cache, instead of always building new ones from their textual interface. This change uses the new control to force the tool to always build modules from interface when one is available. 
- **Scope:** This change affects the `swift-build-sdk-interfaces` tool and forces it to always rebuild modules from interface, instead of potentially being able to pick-up a prebuilt existing binary module.
- **Risk:** Low. This change is purely additive to force the dependency scanner to the expected behavior for this tool when the underlying compiler supports it.
- **Original PR:** …
> [6.0 🍒][PrebuiltModuleGen] Ensure the dependency scanner always ignores existing prebuilt modules

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
As of https://github.com/swiftlang/swift/pull/72067, we instead serialize `.h` inputs directly into binary `.swiftmodule` files, because their clients may not be able to use the dependnecies' corresponding `.pch` files due to a compilation context mismatch. The clients of such binary modules then consume the serialized `.h` files directly, and compile them, implicitly, using explicit module dependencies collected during scan of such header files.
Resolves rdar://131261765
> [Explicit Module Builds] Remove dead/incorrect code for handling header inputs of binary module dependencies

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- **Explanation:** As of https://github.com/swiftlang/swift/pull/72067, we serialize (bridging) `.h` inputs directly into binary `.swiftmodule` files, because their clients may not be able to use the binary module's corresponding `.pch` files due to a compilation context mismatch. The clients of such binary modules then consume the serialized `.h` files directly, and compile them, implicitly, using explicit module dependencies collected during scan of such header files. This change removes leftover code that relied on a prior, incorrect, assumption that we pass on binary dependencies' PCH inputs to their clients. 
- **Scope:** This affects Explicit Module Builds where source client being compiled depends on a binary-only `.swiftmodule` dependency which was built with a bridging header.
- …
> [6.0 🍒][Explicit Module Builds] Remove dead/incorrect code for handling header inputs of binary module dependencies

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Profiling currently relies on the ability to emit duplicate weak symbols across translation units and having the linker coalesce them. Unfortunately `link.exe` does not support this, so require `lld-link` and pass `-lld-allow-duplicate-weak` when `-profile-generate` is passed. We ought to be able to remove this once coverage is changed to not rely on duplicate weak symbols, rdar://131295678 is tracking that.
rdar://129337999
> Pass `-lld-allow-duplicate-weak` for coverage on Windows

- Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift
- Sources/SwiftDriver/SwiftScan/Loader.swift
- Sources/SwiftDriver/Utilities/DateAdditions.swift
- Sources/SwiftDriver/Utilities/System.swift
- Sources/swift-build-sdk-interfaces/main.swift
- Sources/swift-driver/main.swift
Also, fix build error because [`strsignal()` always returns `_Nonnull` in the latest Android NDK 26](https://android.googlesource.com/platform/bionic/+/02c4ef4d78d77da7b7974c46cfa20a8f9aaa56d4/libc/include/string.h#134).
This new overlay was recently added in swiftlang/swift#72161 and swiftlang/swift#72634. I've been building it with this patch on my daily Android CI since then, finagolfin/swift-android-sdk#151, and natively on Android too.
@artemcm, should be an easy review.
> Import new Android overlay or Bionic module

- Tests/SwiftDriverTests/CachingBuildTests.swift
Instead of throwing a failure, a scan may return a hollow result carrying diagnostic error payload
> [Test Only] Make `CachingBuildTests.testDependencyScanning` be adaptable to scanner diagnostic revisions

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
*6.0 cherry-pick of #1655*
- Explanation: Avoids a linker error when building with coverage enabled by using `lld-link` and passing `-lld-allow-duplicate-weak`
- Scope: Affects linking on Windows
- Issue: rdar://129337999
- Risk: Low, the fix is fairly straightforward
- Testing: Added tests to test suite
- Reviewer: Saleem Abdulrasool
> [6.0] Pass `-lld-allow-duplicate-weak` for coverage on Windows

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- Sources/SwiftOptions/Options.swift
The intent here is to permit the Windows/macOS style cross-compilation for Android. This involves passing `-sdk` with the path to the "Swift SDK" which overlays the system's native SDK (NDK). The `ANDROID_NDK_ROOT` is a well-defined environment variable (setup by the SDK installer as well as a general expectation for Android development) that identifies the root of the installation of the NDK. This allows us to locate the native SDK root (`--sysroot`) for driving the linker driver amongst other paths.
> SwiftDriver: initial work to properly handle android cross-compilation

- Tests/SwiftDriverTests/CachingBuildTests.swift
- **Explanation:** Adapt the test to changing compiler-side infrastructure which may no longer cause the driver to throw an exception on the kind of failure this test is meant to test. Make it handle both new and existing behavior.
- **Scope:** Test-only change.
- **Risk:** None. Test-only change.
- **Original PR:** https://github.com/swiftlang/swift-driver/pull/1658
- **Reviewed By:** @cachemeifyoucan
> [6.0 🍒][Test Only] Make `CachingBuildTests.testDependencyScanning` be adaptable to scanner diagnostic revisions

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Pass the `-enable-cmo-everything` flag down to frontend jobs and suppress `-enable-default-cmo` when we do, just like with `-cross-module-optimization`.
Additional drive-by fixes:
- Bring `Options.swift` up-to-date.
- Pass the new `-warn-soft-deprecated` flag through to frontend jobs.
Resolves rdar://128401284.
> Pass `-enable-cmo-everything` to frontend jobs

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This allows modes like -index-file to work the same way they do when not using embedded Swift
> Allow enabling embedded Swift without WMO when not generating SIL

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This allows modes like -index-file to work the same way they do when not using embedded Swift
Explanation: Allow compiler modes which don't emit SIL to build embedded Swift without WMO, to facilitate indexing
Scope: Only affects embedded Swift
Risk: Low - makes an existing check more permissive
Original PR: https://github.com/swiftlang/swift-driver/pull/1513
Reviewed By: @artemcm
> [6.0] Allow enabling embedded Swift without WMO when not generating SIL

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This PR reinstates https://github.com/swiftlang/swift-driver/pull/1560, after it was reverted in https://github.com/swiftlang/swift-driver/pull/1662. 
The revert happened because of a unit test failure in the `SwiftDriverTests.SwiftDriverTests testRelativeResourceDir` test. This PR fixes this test failure by ensuring that SDKROOT is reset before the test is run, and creates a sibling test that reflects the new behavior.
> Reinstate: SwiftDriver: initial work to properly handle android cross-compilation

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Match the legacy driver and add `-module-abi-name` as a common frontend option.
> Pass through `-module-abi-name` to frontend

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
Instead of conservatively assuming them to be new/updated in order to invalidate their dependents. This behavior is no longer necessary since the implementation of https://github.com/swiftlang/swift-driver/pull/1628 (adce1337b5dba9610401e932d1dcf28a0bf114e6) which will ensure that if a binary module dependnecy is newer than any of its dependents they will get invalidated and re-built.
> [Incremental Builds][Explicit Module Builds] Treat Binary-only Swift module dependencies as up-to-date

- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
When the requested output is `-emit-module` and also using `-experimental-emit-module-separately`, do not schedule compileJob for each individual source files since all outputs already satisfied by the separately emit module job. The compileJob will only produce unnecessary outputs like per-file modules and slow down the build.
rdar://84979778
> Don't plan compileJob if emitModule is all that is needed in a separate job

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
After ffbae26 landed, it is now safe to enable this behavior for all Explicit Module Builds.
> [Dependency Scanning] Enable scanner-side up-to-date binary module validation on supporting compilers

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
The former will now simply print the first discovered path to the specified dependency module. While the latter will preserve prior behavior of finding *all possible paths* to the specified module.
> [Explicit Module Builds] Simplify `-explain-module-dependency` behavior and introduce `-explain-module-dependency-detailed`

- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/swift-build-sdk-interfaces/main.swift
Generating prebuilt modules for critical modules is important because missing them has a bigger impact on the overall build time. This change adds a report of generated modules when the job finishes and fails the prebuilt module job if some selected critical modules were missing.
rdar://132094476
> PrebuiltModuleGen: fail prebuilt module generation job when critical modules failed to build

- Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift
- Sources/SwiftDriver/SwiftScan/Loader.swift
- Sources/SwiftDriver/Utilities/DateAdditions.swift
- Sources/SwiftDriver/Utilities/System.swift
- Sources/swift-build-sdk-interfaces/main.swift
- Sources/swift-driver/main.swift
__Explanation:__ Now that this new overlay was merged into the 6.0 compiler too in swiftlang/swift#74758, this adds the overlay to the six files that currently `import Glibc` in this repo and fixes a build error because `strsignal()` always returns `_Nonnull` in the latest Android NDK 26.
__Scope:__ Add imports and a build fix on Android only
__Issue:__ None
__Original PR:__ #1647
__Risk:__ None
__Testing:__ Passed all CI on trunk, plus now builds with the new Android overlay on my daily Android CI, finagolfin/swift-android-sdk#156
__Reviewer:__ @compnerd
@artemcm, easy review.
> [6.0] Import new Android overlay or Bionic module

- Package.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/ToolingInterface/ToolingUtil.swift
- Tests/SwiftDriverTests/SwiftDriverToolingInterfaceTests.swift
- Tests/ToolingTestShim/CMakeLists.txt
- Tests/ToolingTestShim/CToolingTestShimImpl.c
- Tests/ToolingTestShim/include/module.modulemap
- Tests/ToolingTestShim/include/tooling_shim.h
This will enable non-Swift clients to query this utility as an alternative to the legacy C++ driver's equivalent.
> Add a C (`@_cdecl`) API for the driver's `getSingleFrontendInvocationFromDriverArguments`

- Sources/swift-driver/main.swift
Cherry-pick of https://github.com/apple/swift-driver/pull/1583
-------------------------------------------------------
**Explanation**: As per https://github.com/apple/swift/issues/70932, when swift-driver is installed via a symlink, it is not able to correctly resolve adjacent tool binaries by following their corresponding symlinks. This is a regression from the old, legacy C++ driver. This change fixes this behavior by having the driver resolve its own path if it is a symlink, first. 
**Risk**: Low. Cases where the added code takes effect were previously not working. 
**Testing**: Expected behavior validated manually by implementor and issue originator (on `main`)
Resolves https://github.com/apple/swift/issues/70932
> [6.0🍒] Resolve main executable symlink when looking up driver-adjacent subcommand binaries

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This addresses a missing component of the initial Android support. When the user specifies `-sysroot`, that should always be given precedence as it is explicitly specified by the user. The `ANDROID_NDK_ROOT` environment variable is set by the Android NDK and is used as a _default_ value in the scenario that the user does not specify the `-sysroot` option. This makes Android both behave more like the Windows platform and also ensures that the user has full control over the behaviour of the toolchain.
Take the opportunity to refactor some of the code to extract the Android NDK specific helpers into an uninhabited enum and provide some behavioural test cases.
> SwiftDriver: forward `-sysroot` provided by the user

- Sources/makeOptions/makeOptions.cpp
As in most LLVM updates, `OPTION` has been modified. Update `makeOptions.cpp` to take this into account.
> Add new parameters to OPTION macro

- Tests/SwiftDriverTests/SwiftDriverTests.swift
The Darwin toolchain is incomplete, missing `swift-autolink-extract`. Add a workaround for the missing tool to allow the tests to pass. This then uncovers another issue with ASi builds where the prebuilt NDK is only available on x86_64 hosts. While we could loosen the NDK lookup, we do still occassionally use some of the tools, so for now lets limit the test to x86_64.
Fixes: #1682
> Tests: adjust tests for Darwin

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
A bunch of profiler tests in the compiler validation suite were recently enabled on non-Darwin platforms by swiftlang/swift#75572 and then failed natively on Android because they couldn't find this profiler library, which this pull fixed. This is [the same change I used to find the sanitizer libraries for Android a couple years ago](https://github.com/swiftlang/swift-driver/pull/720/files#diff-b2b6d2b2cf451a616f869ff28282d9fb3bbf966edeb03abfa7c47f12b6851377R109).
> Android: add the right suffix for the compiler-rt profiler library

- Sources/SwiftOptions/Options.swift
The updated `Options.swift` file was generated with https://github.com/swiftlang/swift/pull/75564 to include changes in PR to `Options.td` file.
The `language-mode` compiler option was accepted as part of [SE-0441](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0441-formalize-language-mode-terminology.md).
> Update Options.swift with SE-0441 language-mode option

- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Do not always hard-code a macOS triple and pass in explicit stdlib paths to the driver invocations
> [6.0 🍒] Fix CachingBuildTests: testSeparateModuleJob & testModuleOnlyJob

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This change is a counterpart of https://github.com/swiftlang/swift/pull/76280.
> [cxx-interop] Remove `-experimental-cxx-stdlib` flag

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This commit adds support for the warning treating option group, including the following options: -warnings-as-errors, -no-warnings-as-errors, -warning-as-error, and -no-warning-as-error. 
Options in this group are now preserved as-is. It is forbidden to reorder or drop any of them. 
These changes reflect the modifications made to the frontend in https://github.com/swiftlang/swift/pull/74466.
> [Diagnostics] Support for all the flags of the warning treating group

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Some clients still have unversioned prebuilt modules, but SwiftDriver assumed that the versioned path would always exist for macOS (at least for the purposes of passing it when compiling for Mac Catalyst).
This change duplicates some logic from the Swift frontend to check for the existence of the versioned macOS prebuilt modules directory before passing it, optionally stripping off trailing `.0` version components.
This addresses <rdar://problem/136047054>.
> Only pass a versioned prebuilt-modules for Mac Catalyst if it exists.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Execution/DriverExecutor.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Sources/SwiftDriver/SwiftScan/Loader.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/ToolingInterface/ToolingUtil.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/DriverExtensions.swift
- Tests/ToolingTestShim/CToolingTestShimImpl.c
- The driver now holds a reference to the `swiftScanLibInstance` which is shared with the `interModuleDependencyOracle`, but is also used for target info and supported compiler feature queries. This means a single `SwiftScan` instance is shared across all uses in a given driver instance.
- Allow SwiftScan to be instantiated *without* a path to an external `libSwiftScan.dylib`, which will cause it to `dlopen` with a `NULL` argument, and expect the scanner symbols to be found in the image that the driver code is a part of. This is useful for when compiler-based tooling (SourceKit) links the driver directly and uses its C API.
> Allow for non-external lookup of libSwiftScan symbols and centralize the scanning instance use in the driver.

- Tests/SwiftDriverTests/SwiftDriverTests.swift
This test was disabled temporarily in 2021, but the linked radar was closed in 2021 as unreproducible. 
Seems to be passing reliably now on macos-arm64 platform and can be re-enabled.
> Re-enable testVerboseImmediateMode for macos-arm64.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Execution/DriverExecutor.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Sources/SwiftDriver/SwiftScan/Loader.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/ToolingInterface/ToolingUtil.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/DriverExtensions.swift
- Tests/ToolingTestShim/CToolingTestShimImpl.c
Reverts swiftlang/swift-driver#1696
Caused unexpected CI failures.
> Revert "Allow for non-external lookup of libSwiftScan symbols and centralize the scanning instance use in the driver."

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Some clients still have unversioned prebuilt modules, but SwiftDriver assumed that the versioned path would always exist for macOS (at least for the purposes of passing it when compiling for Mac Catalyst).
This change duplicates some logic from the Swift frontend to check for the existence of the versioned macOS prebuilt modules directory before passing it, optionally stripping off trailing `.0` version components.
This change also updates the driver so that it passes a prebuilt modules directory relative to the resource directory rather than relative to the compiler binary, also matching the Swift frontend's behavior.
This addresses <rdar://problem/136047054>.
(cherry picked from commit b1573ef55119629057a57591916ff4d6d7d5af9e)
> [6.0] Only pass a versioned prebuilt-modules for Mac Catalyst if it exists.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Add a new filetype for this mode option: "Raw LLVM IR". When the mode option is emit-irgen, the new filetype will be the output kind; conversely when determining the mode option to use, if the output kind is the new filetype, the mode option will be emit-irgen.
rdar://135437693
> [Driver] Pass -emit-irgen thru to frontend.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Execution/DriverExecutor.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Sources/SwiftDriver/SwiftScan/Loader.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftDriver/ToolingInterface/ToolingUtil.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/DriverExtensions.swift
- Tests/ToolingTestShim/CToolingTestShimImpl.c
>- The driver now holds a reference to the 'swiftScanLibInstance' which is shared with the 'interModuleDependencyOracle', but is also used for target info and supported compiler feature queries. This means a single SwiftScan instance is shared across all uses in a given driver instance.
>- Allow SwiftScan to be instantiated *without* a path to an external 'libSwiftScan.dylib', which will cause it to 'dlopen' with a NULL argument, and expect the scanner symbols to be found in the image that the driver code is a part of. This is useful for when compiler-based tooling (SourceKit) links the driver directly and uses its C API.
Added a deprecation for the prior version of `verifyOrCreateScannerInstance`.
> Re-land: Allow for non-external lookup of libSwiftScan symbols and centralize the scanning instance use in the driver.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This is a partial revert of https://github.com/swiftlang/swift-driver/commit/a9f35bc15f68d4ae0cd3949afa6c78e1a3df8f80
When remotely building and sharing Swift artifacts it is important to maintain
relative paths to avoid serializing any paths that will not be valid on different
machines. Change the logic back to the previous model, and the one used
in the old swift driver, where paths are made absolute only when a 
`-working-directory` flag is passed.
> Only make input paths absolute when -working-directory is passed

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
When providing relative SDK paths to the swift-driver, the path should be
passed directly to the frontend as a relative path. This is necessary to
support remotely building Swift objects that are shared across machines
without serializing invalid absolute paths.
> Maintain relative SDK paths with no -working-directory flag

- Tests/SwiftDriverTests/SwiftDriverTests.swift
We don't support plain musl for now, so don't bother trying to do a static linking test for it.
rdar://138021505
> [Tests] Remove test of static linking against musl.

- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Sources/SwiftDriver/Jobs/LinkJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
https://github.com/swiftlang/swift-driver/pull/1000 switched to use POSIX-style response files but swift-frontend expects Windows-style response files on Windows.
Switch back to generating Windows-style response files on Windows and pass `--rsp-quoting=windows` to `clang` to tell it to pass the response file in Windows mode.
Alternatives considered:
- Have a separate response file generation logic for clang and Swift: This seems like a continuous source of bugs if you always need to think about which response file format you want, especially if the behavior is not intuitive (`clang.exe` expecting POSIX-style response files)
- Instead of parsing `--rsp-quoting=windows` on Windows, use `clang-cl.exe`, which also causes response files to be parsed in Windows-style: I think it’s better to be …
> Output a Windows-style response file for swift-frontend and clang

- Sources/SwiftOptions/Option.swift
- Sources/SwiftOptions/Options.swift
- Sources/makeOptions/makeOptions.cpp
This is the companion of https://github.com/swiftlang/swift/pull/76872.
I've reused the `SwiftIndentOption` constant, which was removed by https://github.com/swiftlang/swift/pull/76577 (but Options.swift was never updated here to remove it).
> Update options to include the new `SwiftSynthesizeInterfaceOption` flag.

- Sources/SwiftOptions/Options.swift
Sync up Options.swift with Options.td from swift's main branch by using `makeOptions` script.
> [SwiftOptions] Add missing options based on Options.inc from swift@main

- Sources/SwiftOptions/Options.swift
This option was introduced by https://github.com/swiftlang/swift/pull/77216
> [SwiftOptions] Add `-interface-compiler-version` frontend option

- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
We added support for `-profile-generate` in the latest LLVM (https://github.com/swiftlang/llvm-project/pull/9418), but it is explicitly banned for WebAssembly targets now. Unlock the feature by adding the necessary runtime library to the link command line as well as other platforms.
> Unlock `-profile-generate` for WebAssembly targets

- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-picking: https://github.com/apple/swift-driver/pull/1605
> '+' isn't allowed in environment variable names so it's impossible to set the Clang++ executable at the moment. Replace + with X so that we can set `SWIFT_DRIVER_CLANGXX_EXEC` to set the clang++ executable.
> 
> Fixes: rdar://128007218
Explanation: Replaces `+` with `X` in the toolchain while doing tool lookup from an environment variable because `+` is not allowed in valid environment variable names. This prevents us from telling the driver where to look for the clang++ binary.
Risk: Low. Only affects projects that set the `SWIFT_DRIVER_CLANGXX_EXEC` environment variable. Since that doesn't do anything today, that would be a silly thing to do. Otherwise, projects cannot currently set `SWIFT_DRIVER_CLANG++_EXEC` because …
> 🍒[Swift 6.0] Allow overriding clang++ with an environment variable

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-Picking https://github.com/apple/swift-driver/pull/1545 back to Swift 6.0
Not all generic-"unix" environments have the Gold linker available to them, and in some cases, the vendor of the toolchain may provide their own linker. In these cases, the driver should be internally consistent with the toolchain that it is shipped with.
Now that we have the clang-linker, we can lean on the linker selection in the clang-linker to determine a default linker. If the clang-linker, and thus, the swift compiler driver, are part of a specific toolchain, that clang-linker should be built for that platform with the appropriate linker defaults set. If someone overrides the linker with -use-ld, we should still honour that, but should otherwise be consistent with the appropriate toolchain linker.
This …
> 🍒[Swift 6.0]: Update Generic Unix linker selection

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Fixing the number of dashes
Cherry-pick of: da265aebaf04fb10506220a741de66af3ff3e143
> [🍒 Swift-6.0.x] fuse-ld only takes one dash

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The driver currently has logic to infer the location of the platform based on the conventional layout of SDKs within platforms. However, that doesn't work well when SDKs have been built up in other places.
Introduce support for a second convention, that the PLATFORM_DIR environment variable can specify the path to the platform. When present, also add external plugin paths pointing into that platform.
Fixes rdar://138370421.
> [Darwin] Add external plugin paths into platform specified by PLATFORM_DIR

- Sources/SwiftOptions/Options.swift
This is a companion to https://github.com/swiftlang/swift/pull/77574.
> Update Options.swift with additional flags supported by `swift-synthesize-interface`.

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Utilities/Diagnostics.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Synchronize `Options.swift` with https://github.com/swiftlang/swift/pull/77662 and update the driver to pass all feature related flags down to the frontend together, preserving the order the flags were specified.
> Add support for `-disable-upcoming-feature` and `-disable-experimental-feature`

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- TestInputs/ExplicitModuleBuilds/Swift/G.swiftinterface
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
The driver does not have the capability to rebuild them, so there is no point to invalidating these dependency nodes. Crucially, if these dependencies are newer than some other dependency between the source module and it, it will still cause invalidation of dependencies which can and must be re-built.
This change fixes the remaining case left by the initial attempt at this in https://github.com/swiftlang/swift-driver/pull/1674.
> [Explicit Module Builds][Incremental Builds] Treat binary Swift module explicit dependencies as always up-to-date

- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The `.autolink` files were being included in static archives and they were silently ignored by wasm-ld linker but they started emitting warnings for archive members that are neither object files nor bitcode files[^1]. This change filters out `.autolink` files from the list of inputs to the static linker job to avoid the warnings.
[^1]: https://github.com/llvm/llvm-project/commit/bcc9b9d80c61ea6521215e9826281041a3f73b05
> Exclude `.autolink` files from static linking on WebAssembly

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
With an escape hatch of `-always-rebuild-module-dependencies` (https://github.com/swiftlang/swift/pull/77717). This change makes it so the driver is always going to produce a build plan which contains only explicit module pre-compile tasks for modules which are not already up-to-date with respect to all of their inputs.
This means that the driver will skip up-to-date module tasks even when `-incremental` is not specified. This is more in line with prior behavior when using Implicit Module builds and results in a better user experience when compiling code with `swiftc` on the command-line. For example, consequtive invocations of `swiftc test.swift -o test.out` should not have to re-build module dependencies of `test.swift` each time.
Swift's `-incremental` is a heavy-weight set of …
> [Explicit Module Builds] Always filter out up-to-date module dependencies from execution

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Apart from `swift-5.9`, the `-cxx-interoperability-flag` compiler flag might take other values, such as `swift-6`, `default`, or `upcoming-swift`.
This teaches Swift Driver to properly handle any of those values.
> [cxx-interop] Handle different interop compat versions

- Tests/SwiftDriverTests/SwiftDriverTests.swift
`swift-autolink-extract` is not available on macOS and thus the toolchain creation fails. Add a mock placeholder to allow us to run the tests on Darwin.
> SwiftDriverTests: repair the tests on Darwin

- Sources/swift-driver/main.swift
Use `URL` to compute the new executable name. This is important to ensure that we correctly strip the executable suffix and re-apply it in the proper location if applicable. Without this change, on Windows, the fallback path would generate `swiftc.exe-legacy-driver` rather than `swiftc-legacy-driver.exe` for the basename of the C++ driver.
> swift-driver: correct the legacy driver path construction

- Sources/swift-driver/main.swift
Revert https://github.com/swiftlang/swift-driver/pull/1741 because it is causing compiler PR testing to fail.
> Revert "swift-driver: correct the legacy driver path construction"

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
When computing the resource directory for the Swift registrar, we need to add a couple of components that we had missed. Correct the path computation so that we can find the object file properly. This was detected while running the test suite with the early swift driver on Windows where `-resource-dir` is explicitly passed.
> SwiftDriver: adjust handling of `-resource-dir` parameter

- Sources/swift-driver/main.swift
Reverts swiftlang/swift-driver#1744
> Revert "Revert "swift-driver: correct the legacy driver path construction""

- Sources/SwiftDriver/Jobs/EmitSupportedFeaturesJob.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
When building the compiler toolchain, there is currently a race condition which makes it so that the 'libSwiftScan.dylib' is not ready by the time the driver is used to begin compilation of the Swift standard library. For now, disable in-process queries altogether.
On 'main', this is resolved with https://github.com/swiftlang/swift/pull/77606, which seems to be a challenge to backport to 6.0.
> [6.0] Disable in-process target-info and supported-features queries using `libSwiftScan`

- Tests/SwiftDriverTests/CachingBuildTests.swift
Use different module cache path for swift caching tests. This allows:
* ModuleCache in temporary directory to be cleaned up later
* Avoid conflicting PCM outputs that can cause driver to make the wrong assumption if PCMs are up-to-date or not.
> [Tests] Overwrite module cache path for swift caching tests

- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Remove a number of cases where we would print the command line or using `-v` on commands which are being executed which results in a significant amount of output in the test run.
> Tests: remove some debugging code

- Sources/swift-driver/main.swift
`swift-driver` tries to invoke `swiftc-legacy-driver.` (trailing dot) on non-Windows platforms when legacy driver is requested since https://github.com/swiftlang/swift-driver/pull/1746
This is because `URL.pathExtension` returns an empty string if the URL does not have an extension but `URL.appendPathExtension` appends a period before the extension even if given an empty string. Thus `url.deletingPathExtension().appendingPathExtension(url.pathExtension)` will not be equal to `url` if `url` does not have an extension.
> Fix the legacy driver path construction on non-Windows platforms

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
For rdar://135443278
This makes the flags available in the new driver. It also infers an extra flag for the frontend that matches how `clang` works.
> swift-driver: Driver support for SamplePGO

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/Helpers/XCTestExtensions.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Introduce a `XCTAssertCommandLineContains` and
`XCTAssertJobInvocationMatches` to validate the invocation of the tools. This helper checks that the command line matches the template and in the case of a failure will print both the actual command line template and the expectation so that it is easier to diagnose the failures.
Take the opportunity to clean up some of the job type checks, converting them from `XCTAssertTrue` to `XCTAssertEquals` to ensure that the values are printed.
Perform a partial pass to adopt this new helper in a large set of the SwiftDriverTests. This is a mostly mechanical change, though there are a few places where the tests are actually changed semantically slightly. Those changes are limited to a stronger assertion about the ordering of arguments which was not …
> Tests: introduce and partially adopt a command line test helper

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Rewrite some of the LLD requirement checking code to be simpler to follow. Adjust the C++ interop checking code to be less verbose. Rely on the clang driver to properly select the flags for the profiling runtime.
> Windows: simplify the linker invocation for Windows

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Reverts swiftlang/swift-driver#1754
This PR is causing build failures, reverting for now.
https://ci.swift.org/job/swift-PR-Linux/18898/
```
/home/build-user/swift-driver/Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift:58:25: error: expected initial value after '='
let bUseLLD: Bool = switch parsedOptions.getLastArgument(.useLd)?.asSingle {
^
```
> Revert "Windows: simplify the linker invocation for Windows"

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This further reduces the use of `-v` in the commands to avoid extraneous messages when running the test suite. This makes it easier to identify failures when iterating on the full suite.
> Tests: disable verbosity in the tests

- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This reverts commit 2b853979a6046cc31a201db6778c88a2c205ad26.
Add a compatibility path for Swift <6.0. This is required to allow bootstrapping the early swift driver in CI.
> Reapply "Windows: simplify the linker invocation for Windows"

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Various changes to clean up the test suite implementation.
- Adopt `XCTAssertJobInvocationMatches` in more test cases
- Replace use of `XCTAssert(... == ...)` in favour of `XCTAssertEqual`
- Replace use of `XCTAssertTrue(!...)` in favour of `XCTAssertFalse`
- Some stylistic compression of `... ; return`
- Coddle braces as per Swift style
- Adopt `XCTUnwrap` in a number of test cases
The majority of this change is intended to reduce the LoC and ease debugging by allowing the test failure to indicate what the expectation vs computed values are. Additionally, it makes the test suite run to completion in more cases by removing forced unwraps.
> Tests: various changes to clean up the swift-driver test suite (NFC)

- Sources/swift-build-sdk-interfaces/main.swift
- Sources/swift-driver/main.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
- Tests/TestUtilities/DriverExtensions.swift
The new `ProcessEnvironmentBlock` allows for better handling of the environment block on Windows. This cleans up some of the warnings emitted when building. A more thorough replacement requires changing the APIs to replace usage in the `SwiftDriver.init` method.
> Update some uses of `ProcessEnv.vars` to `ProcessEnv.block`

- Sources/SwiftDriver/Jobs/ModuleWrapJob.swift
- Sources/SwiftDriver/Jobs/Planning.swift
With `-emit-module`, the output type computed is the swiftmodule. This output is subsequently wrapped by the module wrap job which will embed the swift module into an object file. This would trigger the assertion previously. Clean up some of the planning code associated with this in tandem.
> Jobs: adjust swift module wrapping job (NFC)

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Invoking `swiftc` without any inputs is expected to fail (as is being tested by this test case!). Remove the invalid cases which were likely added for debugging.
> Tests: remove some invalid tests

- Sources/SwiftDriver/Toolchains/Toolchain.swift
We would previously not honour this flag on Windows as the layout of the toolchain is different on Windows from the other platforms. The computed path needing to be different bifurcated the implementation. Hoist a path for override handling into the shared path.
> SwiftDriver: honour `SWIFT_DRIVER_SWIFTSCAN_LIB` on Windows

- Tests/SwiftDriverTests/APIDigesterTests.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
- Tests/SwiftDriverTests/JobExecutorTests.swift
- Tests/SwiftDriverTests/ParsableMessageTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Another round of cleanups in the test suite to help ease diagnostics.
- Reduce verbosity in the driver execution
- Prefer `XCTSkipIf` to avoid warnings about unexecuted code
- Silence mutation related warning
- Remove defaulted argument in `Driver` construction to avoid deprecation warnings
- Prefer `XCTAssertEqual` over `XCTAssert` and `XCTAssertTrue` of equality expressions
- Cleanup some bleeding whitespace
- Compress multiline statements returning `()` to single line
> Tests: further cleanups

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
We would previously form an in-place job on Windows which would then terminate the tests. Explicitly use an output file map which generates a build record which prevents the in-place job.
> Tests: avoid forming an in-place driver job

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
Currently, swift-driver emits an error when trying to importing a swift binary module that has a bridging header when swift caching is enabled. This turns out to be a very common configuration that we need to support.
It turns out most of the time, allowing the compilation to continue will result in a successful compilation. Even though in rare occasions where multiple bridging headers from the dependencies are involved with overlapping content, the compilation is going to fail with confusing error message, we will address that in swift compiler instead.
Thus the current error message is removed to allow more supported projects.
> Remove error for invalid swift caching configuration

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
`Options.swift` has been regenerated so as to include `load-pass-plugin` option as well.
Frontend implementation at https://github.com/apple/swift/pull/68985.
> Add support for `load-pass-plugin` option

- Sources/SwiftDriver/Driver/OutputFileMap.swift
- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Simplify the encoding of output file maps and remove a yams dependency we don't need in this part of the driver
> Consistently use JSON when encoding output file maps

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- **Explanation**:  Currently, swift-driver emits an error when trying to importing a swift binary module that has a bridging header when swift caching is enabled. This turns out to be a very common configuration that we need to support. It turns out most of the time, allowing the compilation to continue will result in a successful compilation. Even though in rare occasions where multiple bridging headers from the dependencies are involved with overlapping content, the compilation is going to fail with confusing error message, we will address that in swift compiler instead.
- **Scope**: Thus the current error message is removed to allow more supported projects.
- **Issues**: rdar://142709084
- **Original PRs**: https://github.com/swiftlang/swift-driver/pull/1775
- **Risk**: Low. Removing …
> [6.1]Remove error for invalid swift caching configuration

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/TripleTests.swift
On platforms where the triple includes the os version, in this case `x86_64-unknown-freebsd14.2`,
the swift-driver is trying to link against various clang rt libraries in `clang/lib/freebsd14.2`, but the actual
clang convention is to have the libraries installed in `clang/lib/freebsd` instead, see [clang/lib/Driver/ToolChain.cpp#L686](https://github.com/swiftlang/llvm-project/blob/985636ed916ef54e2df74f9d72fc20656b11c094/clang/lib/Driver/ToolChain.cpp#L686).
Although the right solution is probably to implement `getOSLibName` in `swift-driver`; we can just use
`osNameUnversioned` for now as the only special case where `getOSLibName != osNameUnversioned`
is for `Solaris`, which is not yet supported.
> libclang_rt.profile*.a search path should use osNameUnversioned

- CMakeLists.txt
- Package.resolved
- Package.swift
- README.md
- Sources/SwiftDriver/CMakeLists.txt
- Utilities/build-script-helper.py
Now that old-style incremental build records are obsolete, this dependency is unused and we no longer need to build it as part of the driver
> Remove now-unused yaml parser dependency

- Sources/SwiftOptions/Options.swift
We need to do this to remove references to implicit backtracing import, but it also looks like there are some other options that haven't been picked up yet.
rdar://143310410
> [Options] Update options.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/APIDigesterJobs.swift
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/EmitModuleJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/MergeModuleJob.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This patch teaches the driver how to emit the supplementary outputs for a module build for the target-variant.
These supplementary outputs are:
- Swift module
- Swift module documentation
- Swift module source information
- Swift interface
- Swift private interface
- Swift package interface
- JSON API description
- JSON ABI description
This means that the driver can emit all of the relevant outputs for a build in a single invocation without needing to be called twice with the same arguments, with one to emit the zippered object and target supplemental outputs, and again for the target-variant outputs.
Patch to add new flags: https://github.com/swiftlang/swift/pull/78336
rdar://141582282
> Emit supplemental outputs for the target variant

- Tests/SwiftDriverTests/SwiftDriverTests.swift
`"` is an invalid filesystem character, you may not use this in a file name. Replace the character with `'`. This repairs the test suite on Windows.
> SwiftDriverTests: repair the tests on Windows

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Windows is now generating and packaging a SDKSettings.json which reduces the warnings here to match that of the other platforms. This adjusts the expectations accordingly.
> SwiftDriverTests: adjust the windows expectations

- CMakeLists.txt
We should do a singular call to `FetchContent_MakeAvailable` as per the documentation. Heed this advice which also allows us to reduce the scope of the overridden variables. Once we migrate to a new enough CMake minimum (3.25), we should be able to replace that with a `block` scope to avoid the push/pop manual adjustment.
> build: tweak `FetchContent` usage to follow best practices

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- TestInputs/ExplicitModuleBuilds/Swift/O.swiftinterface
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
For swift caching build, swift-frontend only reads from CAS for inputs for full build reproducibility. In this case, if the CAS is removed, we need to treat the modules as missing from CAS and rebuild them, even if the version on disk appears to pass the up-to-date check.
rdar://135718227
> [Caching] Invalidate built module if missing from CAS

- Sources/SwiftDriver/SwiftScan/Loader.swift
- Sources/SwiftDriver/Utilities/DateAdditions.swift
- Sources/swift-build-sdk-interfaces/main.swift
- Sources/swift-driver/main.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Easier than listing every Apple platform and keeping that list updated.
> Consistently use canImport(Darwin) throughout the codebase

- Sources/SwiftDriver/Driver/Driver.swift
Silence `warning: code after 'return' will never be executed`
> [NFC] Remove a redundant return statement

- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
BTI enforcement is mandatory, which means if PAC and BTI instructions are not emitted, then the compiled binary gets killed with SIGILL. The platform default compiler achieves enabling PAC and BTI by embedding the relevant enabled Clang compilation option flags into the local platform toolchain, which affects C/C++ code generation.
For bootstrapping purposes, we need to make this change in the legacy C++ driver in swiftlang/swift#78394; this is the equivalent change for the new driver.
It's not quite clear whether the flags need to be introduced in BackendJob.swift as well as FrontendJobHelpers.swift; just in case, add them in both locations.
> Enable PACBTI on OpenBSD/arm64.

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/GeneratePCHJob.swift
Do not assert if libSwiftScan is not initialized when querying PCH generation feature. If libSwiftScan is not initialized, then the feature is not available so just return false for not available.
rdar://141554457
> [GeneratePCH] Don't assert when libSwiftScan is not initialized

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The option itself was added by it wasn't piped through.
Resolves: https://github.com/swiftlang/swift/issues/77192
Resolves: rdar://143965800
> Add support for `-disable-dynamic-actor-isolation`

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Execution/DriverExecutor.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalDependencyAndInputSetup.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftOptions/Options.swift
- Sources/swift-build-sdk-interfaces/main.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
For Explicit Module Builds, have the driver configure the dependency scanner invocation to serialize its internal scanner cache state after a scan, and attempt to deserialize a prior build's scanner cache state, and validate its contents for an incremental re-scan.
Using functionality implemented in: https://github.com/swiftlang/swift/pull/78962
> [Incremental Builds][Explicit Module Builds] Switch to using incremental dependency scanning

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of #1722.
* **Explanation:** Allows users to pass `-dump-ast-format` to the new driver.
* **Main Branch PR:** https://github.com/swiftlang/swift-driver/pull/1722
* **Risk: Very Low**
* **Reviewed By:** @artemcm
* **Testing:** Added new tests to the test suite.
> 🍒 [6.1] Pass the `-dump-ast-format` flag down to the frontend.

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Only the Apple-platforms support dsymutil and building/linking with the swiftmodule, therefore, this test only applies to running on macOS where we have dsymutil. I've also cleaned up the test a bit to make it a bit clearer what the goals were.
We're trying to verify that the contents of the filelist passed into the link job contains only the expected object file and does not include the swiftmodule file.
Fixes: rdar://144378596
> Skip testLinkFilelistWithDebugInfo off of macOS

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/VerifyModuleInterfaceJob.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Teach swift driver to handle bridging header chaining and pass the correct arguments to swift-frontend.
> [BridgingHeader] Support automatic bridging header chaining

- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/Helpers/AssertDiagnostics.swift
And fix 'testTraceDependency' where we can have two possibilities for the emitted note.
> [Test] Allow for diagnostic verifier to expect an alternative diagnostic

- Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
> Darwin: fix target variant flag when building zippered libraries

- Sources/SwiftDriver/Jobs/AutolinkExtractJob.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This driver job has no effect (all autolinking sections are empty when building in this mode) and is actually prone to failure when Wasm reference types are used:
```
error: autolink-extract command failed with exit code 1 (use -v to see invocation)
.build/wasm32-unknown-none-wasm/release/externref.build/externref.c.o' (invalid data relocation: table)
```
> Exclude `swift-autolink-extractor` no-op job for embedded Wasm

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Pass `-auto-bridging-header-chaining` to all planned jobs. The module importing job relies on the flag to know not to import bridging header from binary modules because they are available chained in PCH file.
> [BridgingHeader] Pass bridging header chaining flag for all jobs

- Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
ASAN, UBSAN are available on Windows while TSAN is not. The toolchain has started building the runtimes and will be distributing them with the toolchain builds. This change enables the support in the driver for the santizers on Windows.
> SwiftDriver: enable `-sanitize=` on Windows selectively

- Tests/SwiftDriverTests/SwiftDriverTests.swift
These seem to be causing a regression on Linux somehow. Restore the original `#if os(macOS)` check around the region, but retain some of the enabled tests which are passing.
> Tests: reduce enabled tests on Linux

- Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Even after https://github.com/swiftlang/swift-driver/pull/1814, https://github.com/swiftlang/swift-driver/pull/1804 is still breaking Linux CI so revert it for now.
> Revert #1804

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This makes two changes:
1. Use the new flag on all Unix platforms, as in the original frontend pull where it was introduced, swiftlang/swift#72352.
2. When compiling for Android and `ANDROID_NDK_ROOT` is unset, fall back to the `-sdk` as the sysroot when linking.
I'm primarily concerned with 2., as it got `swift-crypto` cross-compiling again with my trunk Android SDK bundle, but I went ahead and updated 1. also, when I looked into how that new `-sysroot` flag was introduced in that linked compiler frontend pull.
I tested this pull on linux x86_64 locally and saw no test regressions.
@compnerd, I'd like to expand this pull to get rid of `AndroidNDK.getDefaultSysrootPath(in:)` altogether, if you aren't using it anymore. Please review, since you added all this `-sysroot` code for [your new …
> [Unix] Use the new `-sysroot` flag for all non-Darwin Unix platforms, not just Android

- Tests/SwiftDriverTests/CachingBuildTests.swift
When running swift-driver test suite with an older compiler that doesn't support bridging header chaining, the second part of the bridging header caching test will just be a single job, from which the default executor will run the swift-frontend in-place. This will cause the test suite to early exit regardless of the state of the test suite.
> [Tests] Fix another early termination in tests

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
If we're building a statically linked executable, we should look in `usr/lib/swift_static` for `swiftrt.o`, rather than looking in `usr/lib/swift`.  Not doing this breaks the Static SDK for Linux.
rdar://145549541
> [SDK Support] Make sure to look in `swift_static` rather than just `swift`.

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
__Explanation:__ This makes two changes:
1. Use the new flag on all Unix platforms, as in the original frontend pull where it was introduced, swiftlang/swift#72352.
2. When compiling for Android and `ANDROID_NDK_ROOT` is unset, fall back to the `-sdk` as the sysroot when linking.
I'm primarily concerned with 2., as it got a few packages cross-compiling again with both my trunk and 6.1 Android SDK bundles, but I went ahead and updated 1. also, when I looked into how that new `-sysroot` flag was introduced in that linked compiler frontend pull.
__Scope:__ Only affects Unix platforms and Android
__Issue:__ None
__Original PR:__ #1811
__Risk:__ Very low
__Testing:__ Passed all CI on trunk and appears to fix getting my Android SDK bundle working with this new swift-driver again, because of 2. …
> [Unix] Use the new `-sysroot` flag for all non-Darwin Unix platforms, not just Android (#1811)

- Package.swift
The SWIFTPM_SWBUILD_FRAMEWORK environment variable used in the Package.swift is not indicative of the actual behaviour.
Rename the environment variable to SWIFT_DRIVER_USE_STSC_DYLIB to more clearly indicate the behavioural change when it is set.
> Rename env var with more accurate name

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
When looking at the performance of swift-driver when doing a batch planning for a very large module including thousands of files, the cache key computation is the bottle neck for performance. This PR includes fixes to eliminate some of the inefficiencies in the swift-driver that can cause unnecessary cache key computations. This PR includes:
* Eliminate the redundant batch job forming when using `-enable-batch-mode -incremental`
* Eliminate the cache key computation when constructing the initial jobs which later will turn into batch jobs.
* Make the bridging between swift `[String]` and C `const char **` more efficient for swift scan interfaces.
rdar://145298257
> SwiftDriver performance fixes for swift caching

- Sources/SwiftDriver/Jobs/Planning.swift
This reverts commit 7ba9d485ab44cca5c61cf974679d6fba91feb1ca.
This is breaking swift-build CI, because SwiftDriver now fails to return a build plan to clients when there are 0 mandatory jobs
> Revert "[Planning] Avoid batching compile job twice"

- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
This re-land the change in 7ba9d485ab44cca5c61cf974679d6fba91feb1ca with compatibility fixes and additional tests.
The fix makes sure the skipped jobs are returned in the planning as well for compatibility reasons. Not after this change:
For the build systems that use swift-driver that doesn't support incremental build (swiftpm), asking for an incremental planning will still get the full list of jobs, but the skipped jobs might not be batched. The planned jobs are still complete, but might not be optimally batched.
For the build systems that supports incremental build (swift-build), the build planning is extracted from incremental state directly. But note swift-driver lazily wrapped the compile jobs in Executor so swift-driver can't return an empty list of jobs. Add a test to make sure …
> Re-land [Planning] Avoid batching compile job twice

- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
Embarrassingly, the code failed to query the already-`visited` set when traversing dependencies.
> [Explain Dependency] Fix performance bug in `-explain-module-dependency` implementation

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
The build system has been emitting the output path of generating PCH job in the module level entry in the output file map, while swift-driver is expecting the entry in an entry that accosiated with imported bridging header.
This patch unifies the behavior by picking the implementation of the swift-build, where it is a module level entry. This works better for future when bridging header can be chained, thus creating PCH job even there isn't a imported objc header explicitly provided.
rdar://146395316
> [PCH][OutputFileMap] GeneratePCH output should use single output entry

- Sources/SwiftDriver/ExplicitModuleBuilds/ModuleDependencyScanning.swift
- Sources/SwiftOptions/Options.swift
Added in https://github.com/swiftlang/swift/pull/79818
> [Dependency Scanning] Add support for new flag for placing explicitly-built SDK modules into a separate module cache

- .editorconfig
This ensures formatting with tooling that respects `.editorconfig` is consistent with the established convention in this repository.
> NFC: Create `.editorconfig` to keep formatting consistent

- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
`WebAssemblyToolchain` didn't check for `parsedOptions.isEmbeddedEnabled` when forming `swiftrt.o` and `static-executable-args.lnk` options, and neither of these files exist when building with Embedded Swift for WASI.
> Fix incorrect link job options for embedded WASI

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Add support for `-enable-deterministic-check` after promoting that to a driver flag. This allows running the command twice and comparing the output and make sure they are the same.
> Support driver flag `-enable-deterministic-check`

- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
We have a bunch of Darwin OS version checks, but those really shouldn't apply for Embedded Swift, because the OS version check logic is only for userspace binaries. Embedded Swift is meant for non-userspace firmware and other components, where these OS version numbers are meaningless.
rdar://147439906
> [embedded] Skip checking OS versions of target triples when Embedded Swift is used

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
The test has a longer comment explaining the scenario this addresses, where a change in flags or environment triggers updated PCM hashes when it should have been canonicalized away as the sources don't need to recompile.
rdar://146668157
> Ensure we don't skip precompile jobs if a planned interface verification depends on recompiling modules

- .editorconfig
Small amendment to #1840 
Be explicit about encoding and line endings, and add the extra whitespace-on-empty-lines bit needed for Xcode to behave sensibly.
> Make a few small amendments to editorconfig

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/Planning.swift
Swift Build will use this to access header dependencies for clang modules
> Expose a new public property on the driver to retrieve an InterModuleDependencyGraph

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Always plan the job producing swiftinterface and verifying
swiftinterface together. This make sure the swiftinterface exists on
disk or in CAS when verification job is running.
rdar://147501517
> Plan swiftinterface job and verify interface job together

- Sources/SwiftDriver/ToolingInterface/ToolingUtil.swift
- Tests/SwiftDriverTests/SwiftDriverToolingInterfaceTests.swift
This variant adds a `compilerExecutableDir` parameter which gets passed along to the `Driver` during initialization. This allows callers of `getSingleFrontendInvocationFromDriverArgumentsV4` to set a custom `compilerExecutableDir`, which influences paths passed to the frontend for things like the in-process plugin library.
This addresses <rdar://problem/147692019>.
> Added a new `getSingleFrontendInvocationFromDriverArgumentsV4` function.

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Utilities/StringAdditions.swift
- Tests/SwiftDriverTests/StringAdditionsTests.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This is the companion to the frontend changes for SE-0451 in https://github.com/swiftlang/swift/pull/76636. The first component of a `-module-alias` flag is allowed to be a raw identifier (without the backticks); for example, `-module-alias //some/module:name=ActualModuleName` allows users to write this:
```
import `//some/module:name`
```
The *target* of the alias (the actual module name) must still be a valid Swift identifier, since that corresponds to file system artifacts that need stricter naming conventions.
> Allow module aliases to be raw identifiers.

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState+Extensions.swift
- Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
This fixes a fallout from #1829 that skipped non-compile jobs are not returned from `planBuild()` during incremental build if there are no compile jobs are being schedule from the first place. This can result into an empty list of job being returned, and `swift-build` will treat that as an error.
Now the skipped non-compile jobs are properly tracked and returned.
rdar://147874145
> [Incremental] Track and return skipped non-compile job

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Repurposing this PR for allowing `contains(subsequence:)` checks on any bidirectional collection instead of just arrays. This allows use of this check on array slices among other collections.
This PR was to originally fix an issue in passing the wrong triple to the emit-module job for the variant module. After discussion with Artem, actually fixing this issue will require a fair bit more work.
Also fixed a missing `-Xfrontend` on a test.
> Add `contains(subsequence:)` on any bidirectional sequence instead of just arrays

- Sources/SwiftDriver/SwiftScan/SwiftScanCAS.swift
When makeGlobal failed, it accidentally callbacks the async function twice with the second time being success case.
rdar://147955776
> [CAS] Fix the async error handling for `makeGlobal()`

- Sources/SwiftDriver/Driver/Driver.swift
Tweak the warning message when using -disable-bridging-pch when using together with -cache-compile-job since it can be confusing. The new message should be clear that the automatic resolution from the driver is to ignore -disable-bridging-pch and enable compilation caching.
rdar://148284738
> [SwiftCaching] Tweak warning for disable pch when caching is enabled

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
Fix few remaining paths that are not re-mapped on the command-line when caching/prefix-mapping is enabled.
rdar://147955190
> [Caching] Remap block-list files if needed

- Utilities/build-script-helper.py
Removing the definition of `_GNU_SOURCE` is no longer needed since swiftlang/swift-tools-support-core#500 made sure the right `strerror_r()` is used.
> Android: remove build flags that are no longer needed

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- TestInputs/Dummy.xctoolchain/usr/local/lib/swift/blocklists/block-list1.yml
- TestInputs/Dummy.xctoolchain/usr/local/lib/swift/blocklists/block-list2.yaml
- Tests/SwiftDriverTests/CachingBuildTests.swift
Don't remap block list path from dependency scanning invocation.
This is a regression from #1858
rdar://149015672
> [Caching] Fix a fallout from block list remap

- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/swiftlang/swift-driver/pull/1863.
**Explanation**: Currently, when building packages for WASI with Embedded Swift, libraries such as `libswift_Concurrency.a` and `libswift_ConcurrencyDefaultExecutor.a` are not discoverable and require passing `-Xlinker <swift-sdk-path>/usr/lib/swift/embedded/wasm32-unknown-wasip1` option manually. This path can be inferred by the driver, which simplifies build invocations for users significantly, while the rest of linkage options (`-lswift_Concurrency` etc) can be specified in toolset files.
**Scope**: Limited to Embedded Swift for Wasm.
**Risk**: Low due to limited scope.
**Testing**: Added new automated test cases.
**Issue**: rdar://148820885
**Reviewer**: @kateinoigakukun
> [6.2] Allow linking `_Concurrency` for WASI with Embedded Swift

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/CommonDependencyOperations.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/SwiftDriver/Utilities/DOTModuleDependencyGraphSerializer.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
This is in preparation of dependency scanner turning the `directDependencies` field to contain only actually-directly-imported modules.
> [Explicit Module Builds] Centralize computing *all* dependencies of a given `ModuleInfo` and use throughout

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
On the swift side, we added a new build flavor in swiftlang/swift#80389 to opt-out of BTCFI as a way of working around swiftlang/swift#80059. We communicate this to swift-driver via the frontend with FrontendTargetInfo.
> Detect OpenBSD opt-out of BTCFI.

- README.md
Custom build instructions for Windows have no longer been necessary since the introduction of swift-toolchain-sqlite.
> Remove outdated Windows instructions

- Sources/SwiftDriver/CMakeLists.txt
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/Job.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Jobs/PrintSupportedFeaturesJob.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This makes it possible to use `-print-supported-features` directly
on `swift{c}` and without any extra flags just like `-print-target-info`.
> [Jobs] Add a job for `-print-supported-features`

- Tests/SwiftDriverTests/CachingBuildTests.swift
Remove a check for the exact diagnostics message from the compiler side as it is out of scope for the test and it prohibits improvements to the diagnostics message from the compiler.
> [Tests] Remove a check for compiler side diagnostics

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Jobs/PrintTargetInfoJob.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- **Explanation**:
On the swift side, we added a new build flavor in swiftlang/swift#80389 to opt-out of BTCFI as a way of working around swiftlang/swift#80059. We communicate this to swift-driver via the frontend with FrontendTargetInfo.
This is required in 6.2 to properly parallel the changes made on the swift side, even if builds default to BTCFI disabled.
- **Scope**:
Changes are limited to OpenBSD.
- **Issues**:
See swiftlang/swift#80059 and the OpenBSD port issue in swiftlang/swift#78437
- **Original PRs**:
swiftlang/swift-driver#1857
- **Risk**:
Minimal, since changes are scoped only to OpenBSD.
- **Testing**:
CI has ran on the original prs. OpenBSD nobtcfi-flavored builds require this change.
- **Reviewers**:
@DougGregor
> [6.2][cherrypick] Detect OpenBSD opt-out of BTCFI.

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Adopts new Swift dependency scanner API to query only directly-imported module dependencies for the module being scanned
> [Explicit Module Builds] Adopt new direct-import field for Swift source modules

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Cherry-pick of https://github.com/swiftlang/swift-driver/pull/1877
------------------------------------
Explanation:Adopts new Swift dependency scanner API to query only directly-imported module dependencies for the module being scanned. This API, for the main source module, provides info on which dependencies are directly imported into the user program, explicitly ('import' statement) or implicitly (e.g. stdlib). This list does not include Swift overlay dependencies, cross-import dependencies, bridging header dependencies.
Scope: Does not affect existing clients, provides a new API.
Risk: Low, this is a purely additive API change which should not affect existing clients.
Testing: Added a test to the driver test suite.
Issue: rdar://146697570
> [6.2 🍒][Explicit Module Builds] Adopt new direct-import field for Swift source modules

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Re-land https://github.com/swiftlang/swift-driver/pull/1886 with a test fix
----------------------------------
**Explanation**: Adopts new Swift dependency scanner API to query only directly-imported module dependencies for the module being scanned. This API, for the main source module, provides info on which dependencies are directly imported into the user program, explicitly ('import' statement) or implicitly (e.g. stdlib). This list does not include Swift overlay dependencies, cross-import dependencies, bridging header dependencies.
**Scope**: Does not affect existing clients, provides a new API.
**Risk**: Low, this is a purely additive API change which should not affect existing clients.
**Testing**: Added a test to the driver test suite.
**Issue**: rdar://146697570
> Revert Revert [6.2 🍒][Explicit Module Builds] Adopt new direct-import field for Swift source modules

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Re-land https://github.com/swiftlang/swift-driver/pull/1877 with a test fix
-------------------------------------
Adopts new Swift dependency scanner API to query only directly-imported module dependencies for the module being scanned
> Revert Revert [Explicit Module Builds] Adopt new direct-import field for Swift source modules

- Sources/SwiftDriver/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift
- Sources/SwiftDriver/Toolchains/DarwinToolchain.swift
- Sources/SwiftDriver/Toolchains/GenericUnixToolchain.swift
- Sources/SwiftDriver/Toolchains/Toolchain.swift
- Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift
- Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- This way we can adopt a feature of a specific platform's linker separately from the others.
- Adopt `-possible_l*` and `-possible_framework *` flags on Darwin platforms.
> [Explicit Module Builds] Move generation of explicit auto-link flags to a toolchain-specific method

- Tests/SwiftDriverTests/CachingBuildTests.swift
- **Explanation**: Remove a check that on the diagnostic message that is on the swift compiler side, that should out of scope of the test.
- **Scope**: To enable future cherry-picks of the swift compiler change that update the message.
- **Issues**: N/A
- **Original PRs**:https://github.com/swiftlang/swift-driver/pull/1882
- **Risk**:Low. Test Only change. 
- **Testing**: N/A
- **Reviewers**: @artemcm
> [6.2][Test-Only] Remove a check for compiler side diagnostics

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Jobs/WebAssemblyToolchain+LinkerSupport.swift
- Sources/SwiftDriver/Toolchains/WebAssemblyToolchain.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
We are adding support for sanitizers on WASI targets. This commit adds driver support by unblocking hard-coded checks and forwarding sanitizer flags to clang linker driver.
> Add WASI as a supported target for ASan

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
OpenBSD spells the common 64-bit x86 architecture as amd64, while LLVM defaults it to x86_64. A while back we tried to stick with the amd64 spelling, but this was difficult to make the change properly and consistently. A while back we decided to just stick with LLVM spellings, but there are a few minor cases missing.
This change is necessary for properly finding swiftrt.o.
> Use LLVM-default spellings for amd64 on OpenBSD.

- Sources/SwiftDriver/CMakeLists.txt
- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/Job.swift
- Sources/SwiftDriver/Jobs/Planning.swift
- Sources/SwiftDriver/Jobs/PrintSupportedFeaturesJob.swift
- Sources/SwiftDriver/Utilities/FileType.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/swiftlang/swift-driver/pull/1880
---
- Explanation:
This makes it possible to use `-print-supported-features` directly on `swift{c}` and without any extra flags just like `-print-target-info`.
- Main Branch PR:  https://github.com/swiftlang/swift-driver/pull/1880
- Risk: Very Low (Adds a new job that is only available with new `-print-supported-features` compiler option).
- Reviewed By: @artemcm 
- Resolves: rdar://148124973
- Testing: Added new tests to the suite.
> [6.2][Jobs] Add a job for -print-supported-features

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
It otherwise results in a warning from the Clang linker driver.
Resolves rdar://143793051
> Do not add redundant `-pie` when building static executables on Linux platforms

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Cherry-pick of https://github.com/swiftlang/swift-driver/pull/1903
--------------------------------
- **Explanation**: The combination of `-static` which gets passed to the linker driver when `-static-executable` is specified, in combination with `-pie` results in a `warning: argument unused during compilation` diagnostic. 
- **Scope**: Executable compilation on Linux platforms
- **Risk**: Low, simply removes an option which currently gets unused on this code path.
- **Testing**: Added a test to the driver test suite.
- **Original PR**: https://github.com/swiftlang/swift-driver/pull/1903
- **Reviewed By**: @cachemeifyoucan 
- **Issue**: rdar://143793051
> [6.2 🍒] Do not add redundant `-pie` when building static executables on Linux platforms

- Sources/SwiftDriver/Jobs/GenericUnixToolchain+LinkerSupport.swift
- **Explanation**:
OpenBSD spells the common 64-bit x86 architecture as amd64, while LLVM defaults it to x86_64. A while back we tried to stick with the amd64 spelling, but this was difficult to make the change properly and consistently. A while back we decided to just stick with LLVM spellings, but there are a few minor cases missing.
This change is necessary for properly finding swiftrt.o.
- **Scope**:
Changes are intended to affect OpenBSD only.
- **Issues**:
See OpenBSD port issue in #78437
- **Original PRs**:
#1876 
- **Risk**:
Minimal, as changes are intended to affect only OpenBSD.
- **Testing**:
Original change has passed CI.
- **Reviewers**:
@DougGregor
> [6.2][cherrypick] Use LLVM-default spellings for amd64 on OpenBSD.

- Sources/swift-help/main.swift
The Swift driver only emitted color on xterm-256color terminals. screen-256color terminals also have the ability to output colors so we can colorize the output there too.
Also fixing the build deprecation warning on `ProcessEnv.vars`.
> Color output on screen256 color terminals

- Utilities/build-script-helper.py
The build_os in build-script includes the platform version number from the target triple. The runtimes are installed to a location that does not include the version number, resulting in the swift-driver failing to launch due to not finding libswiftCore. Fixing the rpath to avoid requiring folks to manually specify the correct location through environment variables.
> FreeBSD: Fix rpath to swift runtimes

- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
Cherry-picking: https://github.com/swiftlang/swift-driver/pull/1910
Explanation: Without this change, the build log of a failing prebuilt module generation job doesn't contain the stack trace if the underlying compiler invocation crashed, adding extra process for triaging the failure. This change teaches the tool to emit crash trace to the build log.
Scope: Swift prebuilt module generation.
Risk: None. This is to add more diagnostics to an already-failing task
Testing: Tested locally that build logs are now with failing compiler invocations
Issue: rdar://152342109
Reviewer: @artemredkin
> [6.2] PrebuiltModuleGen: print entire compiler invocation for failed module generation job

- Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/IncrementalCompilationTests.swift
This change was originally landed in https://github.com/swiftlang/swift-driver/pull/1905 and reverted in https://github.com/swiftlang/swift-driver/pull/1916 due to an intermittently-failing test it caused. This is a re-application of the original change with an added test fix. The `testExplicitModuleBuildDoesNotSkipPrecompiledModulesWhenOnlyVerificationIsInvalidated` was a bit too fast with the new module up-to-date checking after the inputs got generated, for the granularity of `stat` calls on Linux, so this change adds a wait to this test. 
Resolves rdar://151626629
> Re-land [Incremental Builds] Separately check whether we can skip 'emit-module' on an incremental module-only build

- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
SwiftPM will compute a hash of the arguments passed to `swift build`, `swift test`, etc to determine if a full rebuild is necessary. Currently, it doesn't take in to account whether `.doesNotAffectIncrementalBuild` is set on swift compiler options and so any time any compiler option changes it will perform a full rebuild.
Expose the function that swift-driver uses to compute the argument hash which takes in to account `.doesNotAffectIncrementalBuild` so that SwiftPM can leverage it to reduce unnecessary rebuilds.
In order to keep `BuildRecordInfo` hidden behind `_spi` the function was moved out to the standalone `BuildRecordArguments` struct.
> Expose `BuildRecordInfo.computeHash`

- Sources/CSwiftScan/include/swiftscan_header.h
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyGraph.swift
- Sources/SwiftDriver/ExplicitModuleBuilds/InterModuleDependencies/InterModuleDependencyOracle.swift
- Sources/SwiftDriver/SwiftScan/DependencyGraphBuilder.swift
- Sources/SwiftDriver/SwiftScan/SwiftScan.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Adding support and API for functionality added in: https://github.com/swiftlang/swift/pull/82169
> [Explicit Module Builds] Add support for libSwiftScan API to query source import details

- Sources/SwiftDriver/Jobs/APIDigesterJobs.swift
swift-api-digester doesn't support the -isystem clang flag like it does the -iframework one. Use -I for now.
rdar://153664788
> [ABIChecking] swift-api-digester doesn't support -isystem

- CMakeLists.txt
Update the pinned version of swift-argument-parser in the CMakeLists.txt. This fully migrates the package over to the new swift-argument-parser release.
> build: update the pinned version of swift-argument-parser

- Sources/SwiftDriver/IncrementalCompilation/BuildRecordInfo.swift
SwiftPM will compute a hash of the arguments passed to `swift build`, `swift test`, etc to determine if a full rebuild is necessary. Currently, it doesn't take in to account whether
`.doesNotAffectIncrementalBuild` is set on swift compiler options and so any time any compiler option changes it will perform a full rebuild.
Expose the function that swift-driver uses to compute the argument hash which takes in to account `.doesNotAffectIncrementalBuild` so that SwiftPM can leverage it to reduce unnecessary rebuilds.
In order to keep `BuildRecordInfo` hidden behind `_spi` the function was moved out to the standalone `BuildRecordArguments` struct.
Original PR: https://github.com/swiftlang/swift-driver/pull/1922
> [6.2] Expose `BuildRecordInfo.computeHash`

- Sources/SwiftDriver/Execution/ArgsResolver.swift
Switch over to using `FileSystem.writeFileContents(_ path:, bytes:, atomically:)`. Otherwise we may encounter a race when multiple driver invocations attempt to write a response file for an identical task, such as a shared module dependency pre-compilation job.
> Perform response file write atomically

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
b0a01d3a283f6aa63ac64d0aa5af3d0cc8b64fc7 accidentally broke this by restricting these flags to never get passed when EBM is enabled, as opposed to ensuring they get passed on non-EBM and dependency scanning tasks.
Resolves rdar://154326377
> [Explicit Module Builds] Ensure that plugin paths are specified to the dependency scanning invocation

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
Fix a regression that `in-process-plugin-server-path` is accidentally dropped in explicit module build.
rdar://154780122
> [Macro] Do not drop `in-process-plugin-server-path` option

- Sources/SwiftDriver/Jobs/APIDigesterJobs.swift
swift-api-digester supports the Swift -Fsystem and -Isystem flags, switch to those.
rdar://152747553
> [ABIChecking] Use -Isystem and -Fsystem for swift-api-digester

- Tests/SwiftDriverTests/CachingBuildTests.swift
After rewriting the scanning service, oracle can get a race condition when CAS configuration is changed in between builds. It causes clang dependency scanning using a wrong CAS when scanning after some other thread updated the CAS location.
Fix the occasional race condition by not sharing the orcale between all the tests sicne this is not a valid real world configuration. In the future, we should teach clang scanner not to hold a global CAS instance so service can be shared when switching CAS locations in a racy way.
rdar://154592458
> [Tests] Do not share underlying Oracle for caching tests

- CMakeLists.txt
- Sources/SwiftDriverExecution/CMakeLists.txt
- Sources/SwiftDriverExecution/llbuild.swift
The module directly imports libllbuild, and while the dependency _should_ be available due to the dependency on `llbuildSwift`, this ensures that we do not rely on ordering but rather the explicit dependency is codified into the build graph.
> SwiftDriverExecution: add explicit dependency on libllbuild

- Sources/SwiftDriver/ToolingInterface/ToolingUtil.swift
... to avoid adding driver path to arguments
The path to the driver is passed down already and it would be added to the arguments by `getSingleFrontendInvocationFromDriverArgumentsV5`.
> [ToolingInterface] Fix `getSingleFrontendInvocationFromDriverArgumentsV3`

- Sources/SwiftDriver/Driver/Driver.swift
- Sources/SwiftDriver/Driver/ToolExecutionDelegate.swift
- Sources/SwiftDriver/Execution/DriverExecutor.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
- Sources/SwiftDriverExecution/MultiJobExecutor.swift
- Sources/SwiftOptions/Options.swift
- Tests/SwiftDriverTests/JobExecutorTests.swift
When swift compiler crashed with swift caching enabled, create a crash reproducer automatically.
> Add swift crash producer support

- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Sources/SwiftDriverExecution/MultiJobExecutor.swift
- Tests/SwiftDriverTests/CachingBuildTests.swift
Add some improvements to crash reproducer:
* Allow environmental variable `SWIFT_CRASH_DIAGNOSTICS_DIR` to specify where the reproducer is written to.
* Add a testcase for generation reproducer since we can direct reproducer into a directory that can be cleared after testcase
* Do use parseable output when producing reproducer (to avoid polluting the stdout where build system might except build commands)
> CrashReproducer generation improvements

- Sources/SwiftDriverExecution/CMakeLists.txt
In the cmake build, the lilbrary to link was specified as `libllbuild`, which caused the build to pass `-llibllbuild` to the linker, instead of `-lllbuild`.
> [Build] Fix linking of llbuild

- Sources/SwiftDriver/Driver/Driver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
TSAN, ASAN, MemSAN, and UBSAN all work on FreeBSD. Fixing the driver to allow enabling sanitizers on FreeBSD.
> FreeBSD: Allow enabling sanitizers on FreeBSD

- Sources/SwiftDriver/Jobs/PrebuiltModulesJob.swift
This prevents issues that we can find same module in multiple different locations.
rdar://158615938
> PrebuiltModuleGen: dedupe prebuilt module jobs

- Sources/makeOptions/CMakeLists.txt
- Sources/makeOptions/makeOptions.cpp
Adjust the code to work with both stable/20240723 and stable/21.x after https://github.com/llvm/llvm-project/pull/119198. This saves us from having to cut and qualify a rebranch branch for swift-driver.
> makeOptions: Fix CMake build for stable/21.x rebranch

- Sources/SwiftDriverExecution/MultiJobExecutor.swift
Execution of the `MultiJobExecutor` throws a
`Driver.ErrorDiagnostics.emitted` if the job was not successful, ie. it assume any errors were already emitted. Make sure to emit an error in all paths of `ExecuteJobRule.executeJob` so that failures aren't hidden.
> Always diagnose failures in job execution

- Tests/SwiftDriverTests/SwiftDriverTests.swift
Amazon Linux 2023 includes a dsymutil in its LLVM package, which is installed on our builders (checking separately if that is actually required). The intent of this test seems to be mostly to make sure we are able to find all tools when allowing fallbacks, so update it to just check for that.
> Update `testExecutableFallbackPath` to pass on all platforms

- Tests/SwiftDriverTests/CachingBuildTests.swift
- Tests/SwiftDriverTests/ExplicitModuleBuildTests.swift
- Tests/SwiftDriverTests/SwiftDriverToolingInterfaceTests.swift
https://github.com/swiftlang/swift/pull/84244 introduces the requirement that `swift-frontend` jobs emitting a swiftinterface must explicitly specify either `-language-mode` or `-swift-version` to avoid mis-compilation of the interface. Add the necessary arguments to various tests that form their own `swift-frontend` invocations.
> Specify `-swift-version` in tests that emit swiftinterfaces

- Sources/SwiftDriver/Jobs/CompileJob.swift
- Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
This allows us to index multiple files in a single frontend invocation during background indexing, allowing us to share common work like module loading.
One thing that I’m not sure about is that in the previously existing single file indexing mode, we were adding `-o <module-name>.indexData` to the frontend invocation and I couldn’t figure out what that’s needed for. With the multi-file indexing mode we add that argument for every single file to index, eg. in my test case we have `-o main.indexData -o main.indexData`. As far as I can tell this does no harm but it’s worth considering during review.
> Allow multiple files to be indexed in a single invocation using the `-index-file` driver mode

- Package.swift
* Update swift-llbuild and swift-tools-support-core to track the release/6.2.1 branch.
> Closes #1969 - Update 6.2.1 branch dependant package versions

- Sources/SwiftDriver/Execution/ArgsResolver.swift
- Tests/SwiftDriverTests/SwiftDriverTests.swift
Using the content hash in the response file name caused us to require using the atomic FS write API, due to a possibility that concurrently-running driver processes may encounter a need to build a common, shared module dependency with an identical command-line recipe. In such a scenario there was a possibility of a race in writing out the response file for this command. 
We have since seen challenges with the current atomic FS write APIs and this PR is an alternative approach to tackling this problem. Instead of using the content hash, we will use UUID to ensure that we do not have races when multiple drivers are creating a response file for an identical command. In addition, we add an API for build system clients so that they can directly examine the pre-response-file-creation command …
> Use UUID for response file names and add 'resolveArgumentList' API which contains original command-line if a response file is used
